// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forum.sql

package coredb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countForumPostComments = `-- name: CountForumPostComments :one
SELECT count(*) FROM core.forum_comments WHERE post_id = $1
`

func (q *Queries) CountForumPostComments(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPostComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countForumPosts = `-- name: CountForumPosts :one
SELECT count(*) FROM core.forum_posts p
WHERE ($1::text IS NULL OR p.channel = $1::text)
  AND ($2::text IS NULL OR p.game_ids @> ARRAY[$2::text])
  AND ($3::text     IS NULL OR p.tags     @> ARRAY[$3::text])
  AND ($4::uuid IS NULL OR p.author_id = $4::uuid)
`

type CountForumPostsParams struct {
	Channel  *string
	GameID   *string
	Tag      *string
	AuthorID *uuid.UUID
}

func (q *Queries) CountForumPosts(ctx context.Context, arg CountForumPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPosts,
		arg.Channel,
		arg.GameID,
		arg.Tag,
		arg.AuthorID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForumComment = `-- name: CreateForumComment :one
WITH allocated AS (
    UPDATE core.forum_posts
    SET next_comment_no = next_comment_no + 1
    WHERE id = $2
    RETURNING next_comment_no - 1 AS comment_no
)
INSERT INTO core.forum_comments (id, post_id, parent_id, author_id, body, comment_no)
SELECT $1, $2, NULL, $3,
       $4, allocated.comment_no
FROM allocated
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at
`

type CreateForumCommentParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

// Creates a top-level comment and allocates its floor number in one statement.
//
// The number comes from a counter on the post, not from max(comment_no) + 1:
// deleting the highest comment must not hand its number to the next one. The
// UPDATE takes a row lock on the post, which serialises comment creation for
// that thread and nothing else, and because both halves are one statement a
// failed insert rolls the counter back rather than burning a number.
func (q *Queries) CreateForumComment(ctx context.Context, arg CreateForumCommentParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, createForumComment,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
	)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const createForumPost = `-- name: CreateForumPost :one
INSERT INTO core.forum_posts (id, author_id, channel, title, body, topic, game_ids, tags)
VALUES ($1, $2, $3, $4, $5, $8, $6, $7)
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at
`

type CreateForumPostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
	Channel  string
	Title    string
	Body     string
	GameIDs  []string
	Tags     []string
	Topic    *string
}

func (q *Queries) CreateForumPost(ctx context.Context, arg CreateForumPostParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, createForumPost,
		arg.ID,
		arg.AuthorID,
		arg.Channel,
		arg.Title,
		arg.Body,
		arg.GameIDs,
		arg.Tags,
		arg.Topic,
	)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const createForumReply = `-- name: CreateForumReply :one
INSERT INTO core.forum_comments (id, post_id, parent_id, author_id, body, comment_no)
VALUES ($1, $2, $3, $4, $5, NULL)
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at
`

type CreateForumReplyParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	ParentID *uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

// Creates a reply. No floor number is allocated: only top-level comments are
// numbered, and the schema refuses a comment_no on a row that has a parent.
//
// The composite foreign key refuses this outright if parent_id names a reply
// rather than a top-level comment, which is what keeps the thread two levels deep.
func (q *Queries) CreateForumReply(ctx context.Context, arg CreateForumReplyParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, createForumReply,
		arg.ID,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
	)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteForumComment = `-- name: DeleteForumComment :execrows
DELETE FROM core.forum_comments WHERE id = $1
`

func (q *Queries) DeleteForumComment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForumComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForumPost = `-- name: DeleteForumPost :execrows
DELETE FROM core.forum_posts WHERE id = $1
`

func (q *Queries) DeleteForumPost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForumPost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getForumCommentByID = `-- name: GetForumCommentByID :one
SELECT id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at FROM core.forum_comments WHERE id = $1
`

func (q *Queries) GetForumCommentByID(ctx context.Context, id uuid.UUID) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, getForumCommentByID, id)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getForumPostByID = `-- name: GetForumPostByID :one
SELECT id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at FROM core.forum_posts WHERE id = $1
`

func (q *Queries) GetForumPostByID(ctx context.Context, id uuid.UUID) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, getForumPostByID, id)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getForumPostByNo = `-- name: GetForumPostByNo :one
SELECT id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at FROM core.forum_posts WHERE post_no = $1
`

func (q *Queries) GetForumPostByNo(ctx context.Context, postNo int64) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, getForumPostByNo, postNo)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listForumComments = `-- name: ListForumComments :many
SELECT c.id, c.post_id, c.parent_id, c.author_id, c.body, c.comment_no, c.depth, c.parent_depth, c.created_at, c.updated_at, c.edited_at
FROM core.forum_comments c
LEFT JOIN core.forum_comments parent ON parent.id = c.parent_id
WHERE c.post_id = $1
ORDER BY COALESCE(c.comment_no, parent.comment_no), c.depth, c.created_at, c.id
`

// A thread's comments in one response: floors in order, each reply directly after
// the floor it belongs to. Ordering by the floor number of the comment or of its
// parent keeps a reply adjacent to its parent without a second query.
func (q *Queries) ListForumComments(ctx context.Context, postID uuid.UUID) ([]CoreForumComment, error) {
	rows, err := q.db.Query(ctx, listForumComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreForumComment{}
	for rows.Next() {
		var i CoreForumComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.CommentNo,
			&i.Depth,
			&i.ParentDepth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPosts = `-- name: ListForumPosts :many
SELECT
    p.id, p.post_no, p.author_id, p.channel, p.title, p.body, p.topic, p.game_ids, p.tags, p.next_comment_no, p.created_at, p.updated_at, p.edited_at,
    (SELECT count(*) FROM core.forum_comments c WHERE c.post_id = p.id) AS comment_count
FROM core.forum_posts p
WHERE ($1::text IS NULL OR p.channel = $1::text)
  AND ($2::text IS NULL OR p.game_ids @> ARRAY[$2::text])
  AND ($3::text     IS NULL OR p.tags     @> ARRAY[$3::text])
  AND ($4::uuid IS NULL OR p.author_id = $4::uuid)
ORDER BY p.created_at DESC, p.id
LIMIT $6 OFFSET $5
`

type ListForumPostsParams struct {
	Channel      *string
	GameID       *string
	Tag          *string
	AuthorID     *uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListForumPostsRow struct {
	ID            uuid.UUID
	PostNo        int64
	AuthorID      uuid.UUID
	Channel       string
	Title         string
	Body          string
	Topic         *string
	GameIDs       []string
	Tags          []string
	NextCommentNo int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EditedAt      pgtype.Timestamptz
	CommentCount  int64
}

// Feed listing, with every filter optional.
//
// The comment count is a lateral subquery rather than a stored counter: it is
// correct by construction, and a counter column can replace it behind the DTO if
// the feed ever gets slow.
func (q *Queries) ListForumPosts(ctx context.Context, arg ListForumPostsParams) ([]ListForumPostsRow, error) {
	rows, err := q.db.Query(ctx, listForumPosts,
		arg.Channel,
		arg.GameID,
		arg.Tag,
		arg.AuthorID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumPostsRow{}
	for rows.Next() {
		var i ListForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostNo,
			&i.AuthorID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.Topic,
			&i.GameIDs,
			&i.Tags,
			&i.NextCommentNo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForumComment = `-- name: UpdateForumComment :one
UPDATE core.forum_comments SET body = $2, edited_at = now()
WHERE id = $1
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at
`

type UpdateForumCommentParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateForumComment(ctx context.Context, arg UpdateForumCommentParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, updateForumComment, arg.ID, arg.Body)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}

const updateForumPost = `-- name: UpdateForumPost :one
UPDATE core.forum_posts SET
    title     = COALESCE($1, title),
    body      = COALESCE($2, body),
    topic     = CASE WHEN $3::boolean
                     THEN $4::text ELSE topic END,
    game_ids  = COALESCE($5::text[], game_ids),
    tags      = COALESCE($6::text[], tags),
    edited_at = now()
WHERE id = $7
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at
`

type UpdateForumPostParams struct {
	Title    *string
	Body     *string
	SetTopic bool
	Topic    *string
	GameIDs  []string
	Tags     []string
	ID       uuid.UUID
}

// Partial edit, following the convention of UpdateUser: a NULL argument means
// "leave unchanged". edited_at is stamped unconditionally, because reaching this
// statement at all means an author changed something.
func (q *Queries) UpdateForumPost(ctx context.Context, arg UpdateForumPostParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, updateForumPost,
		arg.Title,
		arg.Body,
		arg.SetTopic,
		arg.Topic,
		arg.GameIDs,
		arg.Tags,
		arg.ID,
	)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
	)
	return i, err
}
