// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forum.sql

package coredb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countForumPostComments = `-- name: CountForumPostComments :one
SELECT count(*) FROM core.forum_comments WHERE post_id = $1 AND hidden_at IS NULL
`

func (q *Queries) CountForumPostComments(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPostComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countForumPosts = `-- name: CountForumPosts :one
SELECT count(*) FROM core.forum_posts p
WHERE p.hidden_at IS NULL
  AND ($1::text IS NULL OR p.channel = $1::text)
  AND ($2::text IS NULL OR p.game_ids @> ARRAY[$2::text])
  AND ($3::text     IS NULL OR p.tags     @> ARRAY[$3::text])
  AND ($4::uuid IS NULL OR p.author_id = $4::uuid)
  AND ($5::uuid IS NULL OR p.author_id IN (
      SELECT f.followee_id FROM core.user_follows f
      WHERE f.follower_id = $5::uuid))
  AND ($6::boolean IS NULL
       OR (p.featured_at IS NOT NULL) = $6::boolean)
  AND ($7::text IS NULL
       OR lower(p.title || ' ' || p.body) LIKE '%' || lower($7::text) || '%' ESCAPE '\')
`

type CountForumPostsParams struct {
	Channel    *string
	GameID     *string
	Tag        *string
	AuthorID   *uuid.UUID
	FollowedBy *uuid.UUID
	Featured   *bool
	Query      *string
}

// The predicates must stay identical to ListForumPosts, or the pager offers pages the
// feed will not return. Sorting is absent on purpose: it cannot change a count.
func (q *Queries) CountForumPosts(ctx context.Context, arg CountForumPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPosts,
		arg.Channel,
		arg.GameID,
		arg.Tag,
		arg.AuthorID,
		arg.FollowedBy,
		arg.Featured,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForumComment = `-- name: CreateForumComment :one
WITH allocated AS (
    UPDATE core.forum_posts
    SET next_comment_no = next_comment_no + 1
    WHERE id = $2
    RETURNING next_comment_no - 1 AS comment_no
)
INSERT INTO core.forum_comments (id, post_id, parent_id, author_id, body, comment_no)
SELECT $1, $2, NULL, $3,
       $4, allocated.comment_no
FROM allocated
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at, hidden_at, hidden_by, hidden_reason
`

type CreateForumCommentParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

// Creates a top-level comment and allocates its floor number in one statement.
//
// The number comes from a counter on the post, not from max(comment_no) + 1:
// deleting the highest comment must not hand its number to the next one. The
// UPDATE takes a row lock on the post, which serialises comment creation for
// that thread and nothing else, and because both halves are one statement a
// failed insert rolls the counter back rather than burning a number.
func (q *Queries) CreateForumComment(ctx context.Context, arg CreateForumCommentParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, createForumComment,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
	)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const createForumPost = `-- name: CreateForumPost :one
INSERT INTO core.forum_posts (id, author_id, channel, title, body, topic, game_ids, tags)
VALUES ($1, $2, $3, $4, $5, $8, $6, $7)
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason
`

type CreateForumPostParams struct {
	ID       uuid.UUID
	AuthorID uuid.UUID
	Channel  string
	Title    string
	Body     string
	GameIDs  []string
	Tags     []string
	Topic    *string
}

func (q *Queries) CreateForumPost(ctx context.Context, arg CreateForumPostParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, createForumPost,
		arg.ID,
		arg.AuthorID,
		arg.Channel,
		arg.Title,
		arg.Body,
		arg.GameIDs,
		arg.Tags,
		arg.Topic,
	)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const createForumReply = `-- name: CreateForumReply :one
INSERT INTO core.forum_comments (id, post_id, parent_id, author_id, body, comment_no)
VALUES ($1, $2, $3, $4, $5, NULL)
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at, hidden_at, hidden_by, hidden_reason
`

type CreateForumReplyParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	ParentID *uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

// Creates a reply. No floor number is allocated: only top-level comments are
// numbered, and the schema refuses a comment_no on a row that has a parent.
//
// The composite foreign key refuses this outright if parent_id names a reply
// rather than a top-level comment, which is what keeps the thread two levels deep.
func (q *Queries) CreateForumReply(ctx context.Context, arg CreateForumReplyParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, createForumReply,
		arg.ID,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
	)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const deleteForumComment = `-- name: DeleteForumComment :execrows
DELETE FROM core.forum_comments WHERE id = $1
`

func (q *Queries) DeleteForumComment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForumComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForumPost = `-- name: DeleteForumPost :execrows
DELETE FROM core.forum_posts WHERE id = $1
`

func (q *Queries) DeleteForumPost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForumPost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forumPostReactions = `-- name: ForumPostReactions :one
SELECT
    (SELECT count(*) FROM core.forum_comments c
        WHERE c.post_id = $1 AND c.hidden_at IS NULL) AS comment_count,
    (SELECT count(*) FROM core.forum_post_likes l
        WHERE l.post_id = $1) AS like_count,
    (SELECT count(*) FROM core.forum_post_bookmarks b
        WHERE b.post_id = $1) AS bookmark_count,
    EXISTS (
        SELECT 1 FROM core.forum_post_likes l
        WHERE l.post_id = $1 AND l.user_id = $2::uuid
    ) AS liked,
    EXISTS (
        SELECT 1 FROM core.forum_post_bookmarks b
        WHERE b.post_id = $1 AND b.user_id = $2::uuid
    ) AS bookmarked
`

type ForumPostReactionsParams struct {
	PostID   uuid.UUID
	ViewerID *uuid.UUID
}

type ForumPostReactionsRow struct {
	CommentCount  int64
	LikeCount     int64
	BookmarkCount int64
	Liked         bool
	Bookmarked    bool
}

// Everything a single post's DTO needs beyond its own row, in one round trip rather
// than one query per counter.
func (q *Queries) ForumPostReactions(ctx context.Context, arg ForumPostReactionsParams) (ForumPostReactionsRow, error) {
	row := q.db.QueryRow(ctx, forumPostReactions, arg.PostID, arg.ViewerID)
	var i ForumPostReactionsRow
	err := row.Scan(
		&i.CommentCount,
		&i.LikeCount,
		&i.BookmarkCount,
		&i.Liked,
		&i.Bookmarked,
	)
	return i, err
}

const getForumCommentByID = `-- name: GetForumCommentByID :one
SELECT id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at, hidden_at, hidden_by, hidden_reason FROM core.forum_comments WHERE id = $1
`

func (q *Queries) GetForumCommentByID(ctx context.Context, id uuid.UUID) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, getForumCommentByID, id)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const getForumPostByID = `-- name: GetForumPostByID :one
SELECT id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason FROM core.forum_posts WHERE id = $1
`

func (q *Queries) GetForumPostByID(ctx context.Context, id uuid.UUID) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, getForumPostByID, id)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const getForumPostByNo = `-- name: GetForumPostByNo :one
SELECT id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason FROM core.forum_posts WHERE post_no = $1
`

func (q *Queries) GetForumPostByNo(ctx context.Context, postNo int64) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, getForumPostByNo, postNo)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const listForumComments = `-- name: ListForumComments :many
SELECT
    c.id, c.post_id, c.parent_id, c.author_id, c.body, c.comment_no, c.depth, c.parent_depth, c.created_at, c.updated_at, c.edited_at, c.hidden_at, c.hidden_by, c.hidden_reason,
    (SELECT count(*) FROM core.forum_comment_likes l WHERE l.comment_id = c.id) AS like_count,
    EXISTS (
        SELECT 1 FROM core.forum_comment_likes l
        WHERE l.comment_id = c.id AND l.user_id = $1::uuid
    ) AS liked
FROM core.forum_comments c
LEFT JOIN core.forum_comments parent ON parent.id = c.parent_id
WHERE c.post_id = $2 AND c.hidden_at IS NULL
ORDER BY COALESCE(c.comment_no, parent.comment_no), c.depth, c.created_at, c.id
LIMIT $4 OFFSET $3
`

type ListForumCommentsParams struct {
	ViewerID     *uuid.UUID
	PostID       uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListForumCommentsRow struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	ParentID     *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CommentNo    *int64
	Depth        int16
	ParentDepth  *int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     pgtype.Timestamptz
	HiddenAt     pgtype.Timestamptz
	HiddenBy     *uuid.UUID
	HiddenReason *string
	LikeCount    int64
	Liked        bool
}

// A page of a thread's comments: floors in order, each reply directly after the
// floor it belongs to. Ordering by the floor number of the comment or of its
// parent keeps a reply adjacent to its parent without a second query.
//
// Bounded, unlike an earlier version. This endpoint is public and unauthenticated,
// so a thread with ten thousand long comments would otherwise let anyone ask the
// server to build a response of hundreds of megabytes.
// The parent join is for ordering only and deliberately does not exclude a hidden
// parent: a reply is its own author's words, so hiding the comment above it must not
// take it down, and the parent's floor number is still what the reply sorts under.
func (q *Queries) ListForumComments(ctx context.Context, arg ListForumCommentsParams) ([]ListForumCommentsRow, error) {
	rows, err := q.db.Query(ctx, listForumComments,
		arg.ViewerID,
		arg.PostID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumCommentsRow{}
	for rows.Next() {
		var i ListForumCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.CommentNo,
			&i.Depth,
			&i.ParentDepth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.HiddenAt,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.LikeCount,
			&i.Liked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPosts = `-- name: ListForumPosts :many
SELECT
    p.id, p.post_no, p.author_id, p.channel, p.title, p.body, p.topic, p.game_ids, p.tags, p.next_comment_no, p.created_at, p.updated_at, p.edited_at, p.featured_at, p.featured_by, p.hidden_at, p.hidden_by, p.hidden_reason,
    (SELECT count(*) FROM core.forum_comments c WHERE c.post_id = p.id AND c.hidden_at IS NULL) AS comment_count,
    (SELECT count(*) FROM core.forum_post_likes l WHERE l.post_id = p.id) AS like_count,
    (SELECT count(*) FROM core.forum_post_bookmarks b WHERE b.post_id = p.id) AS bookmark_count,
    EXISTS (
        SELECT 1 FROM core.forum_post_likes l
        WHERE l.post_id = p.id AND l.user_id = $1::uuid
    ) AS liked,
    EXISTS (
        SELECT 1 FROM core.forum_post_bookmarks b
        WHERE b.post_id = p.id AND b.user_id = $1::uuid
    ) AS bookmarked
FROM core.forum_posts p
WHERE p.hidden_at IS NULL
  AND ($2::text IS NULL OR p.channel = $2::text)
  AND ($3::text IS NULL OR p.game_ids @> ARRAY[$3::text])
  AND ($4::text     IS NULL OR p.tags     @> ARRAY[$4::text])
  AND ($5::uuid IS NULL OR p.author_id = $5::uuid)
  -- The "following only" feed. IN rather than a join, so a post is not duplicated
  -- and the predicate composes with every other filter.
  AND ($6::uuid IS NULL OR p.author_id IN (
      SELECT f.followee_id FROM core.user_follows f
      WHERE f.follower_id = $6::uuid))
  AND ($7::boolean IS NULL
       OR (p.featured_at IS NOT NULL) = $7::boolean)
  -- The expression matches forum_posts_search_idx exactly, which is what lets a
  -- substring query use the trigram index instead of scanning every body.
  AND ($8::text IS NULL
       OR lower(p.title || ' ' || p.body) LIKE '%' || lower($8::text) || '%' ESCAPE '\')
ORDER BY
    -- One statement rather than three, so every filter above is written once. A CASE
    -- per sort collapses to NULL for the orders not chosen, and NULLS LAST keeps those
    -- from dominating; ` + "`" + `created_at DESC, id` + "`" + ` is both the default order and the
    -- tie-break that makes paging deterministic under the other two.
    CASE WHEN $9::text = 'top' THEN
        (SELECT count(*) FROM core.forum_post_likes l WHERE l.post_id = p.id)
    END DESC NULLS LAST,
    -- Engagement decayed by age. Comments weigh double: writing one costs more than
    -- tapping a heart, so it is the stronger signal that a thread is alive. The +2 and
    -- the 1.5 exponent are a starting shape, not a tuned result -- recorded as such
    -- because a ranking formula invites being mistaken for one.
    CASE WHEN $9::text = 'hot' THEN
        ((SELECT count(*) FROM core.forum_post_likes l WHERE l.post_id = p.id)
         + 2 * (SELECT count(*) FROM core.forum_comments c WHERE c.post_id = p.id AND c.hidden_at IS NULL) + 1)
        / power(extract(epoch FROM (now() - p.created_at)) / 3600.0 + 2, 1.5)
    END DESC NULLS LAST,
    p.created_at DESC, p.id
LIMIT $11 OFFSET $10
`

type ListForumPostsParams struct {
	ViewerID     *uuid.UUID
	Channel      *string
	GameID       *string
	Tag          *string
	AuthorID     *uuid.UUID
	FollowedBy   *uuid.UUID
	Featured     *bool
	Query        *string
	Sort         string
	ResultOffset int32
	ResultLimit  int32
}

type ListForumPostsRow struct {
	ID            uuid.UUID
	PostNo        int64
	AuthorID      uuid.UUID
	Channel       string
	Title         string
	Body          string
	Topic         *string
	GameIDs       []string
	Tags          []string
	NextCommentNo int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EditedAt      pgtype.Timestamptz
	FeaturedAt    pgtype.Timestamptz
	FeaturedBy    *uuid.UUID
	HiddenAt      pgtype.Timestamptz
	HiddenBy      *uuid.UUID
	HiddenReason  *string
	CommentCount  int64
	LikeCount     int64
	BookmarkCount int64
	Liked         bool
	Bookmarked    bool
}

// Feed listing, with every filter optional.
//
// The comment count is a lateral subquery rather than a stored counter: it is
// correct by construction, and a counter column can replace it behind the DTO if
// the feed ever gets slow.
// The viewer's own state (`liked`, `bookmarked`) needs no NULL guard: when no viewer
// is supplied, `user_id = NULL` is never true, so EXISTS is false and an anonymous
// reader sees the same shape with both flags off. That keeps clients from needing a
// branch for signed-out reads.
func (q *Queries) ListForumPosts(ctx context.Context, arg ListForumPostsParams) ([]ListForumPostsRow, error) {
	rows, err := q.db.Query(ctx, listForumPosts,
		arg.ViewerID,
		arg.Channel,
		arg.GameID,
		arg.Tag,
		arg.AuthorID,
		arg.FollowedBy,
		arg.Featured,
		arg.Query,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForumPostsRow{}
	for rows.Next() {
		var i ListForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostNo,
			&i.AuthorID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.Topic,
			&i.GameIDs,
			&i.Tags,
			&i.NextCommentNo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.FeaturedAt,
			&i.FeaturedBy,
			&i.HiddenAt,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.CommentCount,
			&i.LikeCount,
			&i.BookmarkCount,
			&i.Liked,
			&i.Bookmarked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setForumPostFeatured = `-- name: SetForumPostFeatured :one
UPDATE core.forum_posts SET
    featured_at = CASE WHEN $1::boolean THEN now() ELSE NULL END,
    featured_by = CASE WHEN $1::boolean THEN $2::uuid ELSE NULL END
WHERE id = $3
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason
`

type SetForumPostFeaturedParams struct {
	Featured bool
	ActorID  *uuid.UUID
	ID       uuid.UUID
}

// Both columns move together, which the forum_posts_featured_together constraint
// requires: a featured post always records who featured it.
func (q *Queries) SetForumPostFeatured(ctx context.Context, arg SetForumPostFeaturedParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, setForumPostFeatured, arg.Featured, arg.ActorID, arg.ID)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const updateForumComment = `-- name: UpdateForumComment :one
UPDATE core.forum_comments SET body = $2, edited_at = now()
WHERE id = $1
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at, hidden_at, hidden_by, hidden_reason
`

type UpdateForumCommentParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateForumComment(ctx context.Context, arg UpdateForumCommentParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, updateForumComment, arg.ID, arg.Body)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const updateForumPost = `-- name: UpdateForumPost :one
UPDATE core.forum_posts SET
    title     = COALESCE($1, title),
    body      = COALESCE($2, body),
    topic     = CASE WHEN $3::boolean
                     THEN $4::text ELSE topic END,
    game_ids  = COALESCE($5::text[], game_ids),
    tags      = COALESCE($6::text[], tags),
    edited_at = now()
WHERE id = $7
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason
`

type UpdateForumPostParams struct {
	Title    *string
	Body     *string
	SetTopic bool
	Topic    *string
	GameIDs  []string
	Tags     []string
	ID       uuid.UUID
}

// Partial edit, following the convention of UpdateUser: a NULL argument means
// "leave unchanged". edited_at is stamped unconditionally, because reaching this
// statement at all means an author changed something.
func (q *Queries) UpdateForumPost(ctx context.Context, arg UpdateForumPostParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, updateForumPost,
		arg.Title,
		arg.Body,
		arg.SetTopic,
		arg.Topic,
		arg.GameIDs,
		arg.Tags,
		arg.ID,
	)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}
