// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package coredb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countHiddenForumComments = `-- name: CountHiddenForumComments :one
SELECT count(*) FROM core.forum_comments c
JOIN core.forum_posts p ON p.id = c.post_id
WHERE c.hidden_at IS NOT NULL
  AND ($1::text[] IS NULL OR p.game_ids && $1::text[])
`

func (q *Queries) CountHiddenForumComments(ctx context.Context, games []string) (int64, error) {
	row := q.db.QueryRow(ctx, countHiddenForumComments, games)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHiddenForumPosts = `-- name: CountHiddenForumPosts :one
SELECT count(*) FROM core.forum_posts
WHERE hidden_at IS NOT NULL
  AND ($1::text[] IS NULL OR game_ids && $1::text[])
`

func (q *Queries) CountHiddenForumPosts(ctx context.Context, games []string) (int64, error) {
	row := q.db.QueryRow(ctx, countHiddenForumPosts, games)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenForumReports = `-- name: CountOpenForumReports :one
SELECT count(*) FROM core.forum_reports r
LEFT JOIN core.forum_posts p    ON p.id = r.post_id
LEFT JOIN core.forum_comments c ON c.id = r.comment_id
LEFT JOIN core.forum_posts cp   ON cp.id = c.post_id
WHERE r.state = 'open'
  AND ($1::text[] IS NULL
       OR COALESCE(p.game_ids, cp.game_ids) && $1::text[])
`

func (q *Queries) CountOpenForumReports(ctx context.Context, games []string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenForumReports, games)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForumReport = `-- name: CreateForumReport :one
INSERT INTO core.forum_reports (id, reporter_id, post_id, comment_id, reason, detail)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (reporter_id, post_id, comment_id) DO UPDATE SET
    reason = excluded.reason,
    detail = excluded.detail,
    state = 'open',
    handled_by = NULL,
    handled_at = NULL
RETURNING id, reporter_id, post_id, comment_id, reason, detail, state, handled_by, handled_at, created_at
`

type CreateForumReportParams struct {
	ID         uuid.UUID
	ReporterID uuid.UUID
	PostID     *uuid.UUID
	CommentID  *uuid.UUID
	Reason     string
	Detail     *string
}

// Re-reporting the same target is not an error and does not create a second row: the
// reporter has already said this once, and a duplicate would only pad the queue.
// Re-reporting something already handled reopens it, because a second complaint about
// content a moderator let stand is new information.
func (q *Queries) CreateForumReport(ctx context.Context, arg CreateForumReportParams) (CoreForumReport, error) {
	row := q.db.QueryRow(ctx, createForumReport,
		arg.ID,
		arg.ReporterID,
		arg.PostID,
		arg.CommentID,
		arg.Reason,
		arg.Detail,
	)
	var i CoreForumReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.CommentID,
		&i.Reason,
		&i.Detail,
		&i.State,
		&i.HandledBy,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getForumReport = `-- name: GetForumReport :one
SELECT id, reporter_id, post_id, comment_id, reason, detail, state, handled_by, handled_at, created_at FROM core.forum_reports WHERE id = $1
`

func (q *Queries) GetForumReport(ctx context.Context, id uuid.UUID) (CoreForumReport, error) {
	row := q.db.QueryRow(ctx, getForumReport, id)
	var i CoreForumReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.CommentID,
		&i.Reason,
		&i.Detail,
		&i.State,
		&i.HandledBy,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listHiddenForumComments = `-- name: ListHiddenForumComments :many
SELECT c.id, c.post_id, c.parent_id, c.author_id, c.body, c.comment_no, c.depth, c.parent_depth, c.created_at, c.updated_at, c.edited_at, c.hidden_at, c.hidden_by, c.hidden_reason, p.post_no FROM core.forum_comments c
JOIN core.forum_posts p ON p.id = c.post_id
WHERE c.hidden_at IS NOT NULL
  AND ($1::text[] IS NULL OR p.game_ids && $1::text[])
ORDER BY c.hidden_at DESC, c.id
LIMIT $3 OFFSET $2
`

type ListHiddenForumCommentsParams struct {
	Games        []string
	ResultOffset int32
	ResultLimit  int32
}

type ListHiddenForumCommentsRow struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	ParentID     *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CommentNo    *int64
	Depth        int16
	ParentDepth  *int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     pgtype.Timestamptz
	HiddenAt     pgtype.Timestamptz
	HiddenBy     *uuid.UUID
	HiddenReason *string
	PostNo       int64
}

// The counterpart to ListHiddenForumPosts. Without it a hidden comment can be restored
// only by someone who already knows its id, which makes hiding one effectively permanent.
// Scoped by the games of the post the comment belongs to, since a comment carries none.
func (q *Queries) ListHiddenForumComments(ctx context.Context, arg ListHiddenForumCommentsParams) ([]ListHiddenForumCommentsRow, error) {
	rows, err := q.db.Query(ctx, listHiddenForumComments, arg.Games, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHiddenForumCommentsRow{}
	for rows.Next() {
		var i ListHiddenForumCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.CommentNo,
			&i.Depth,
			&i.ParentDepth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.HiddenAt,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.PostNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenForumPosts = `-- name: ListHiddenForumPosts :many
SELECT id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason, video_url FROM core.forum_posts
WHERE hidden_at IS NOT NULL
  AND ($1::text[] IS NULL OR game_ids && $1::text[])
ORDER BY hidden_at DESC, id
LIMIT $3 OFFSET $2
`

type ListHiddenForumPostsParams struct {
	Games        []string
	ResultOffset int32
	ResultLimit  int32
}

// What a moderator can see that a reader cannot.
func (q *Queries) ListHiddenForumPosts(ctx context.Context, arg ListHiddenForumPostsParams) ([]CoreForumPost, error) {
	rows, err := q.db.Query(ctx, listHiddenForumPosts, arg.Games, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreForumPost{}
	for rows.Next() {
		var i CoreForumPost
		if err := rows.Scan(
			&i.ID,
			&i.PostNo,
			&i.AuthorID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.Topic,
			&i.GameIDs,
			&i.Tags,
			&i.NextCommentNo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.FeaturedAt,
			&i.FeaturedBy,
			&i.HiddenAt,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.VideoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenForumReports = `-- name: ListOpenForumReports :many
SELECT r.id, r.reporter_id, r.post_id, r.comment_id, r.reason, r.detail, r.state, r.handled_by, r.handled_at, r.created_at FROM core.forum_reports r
LEFT JOIN core.forum_posts p        ON p.id = r.post_id
LEFT JOIN core.forum_comments c     ON c.id = r.comment_id
LEFT JOIN core.forum_posts cp       ON cp.id = c.post_id
WHERE r.state = 'open'
  AND ($1::text[] IS NULL
       OR COALESCE(p.game_ids, cp.game_ids) && $1::text[])
ORDER BY r.created_at, r.id
LIMIT $3 OFFSET $2
`

type ListOpenForumReportsParams struct {
	Games        []string
	ResultOffset int32
	ResultLimit  int32
}

// Oldest first: the complaint that has waited longest is the one to answer.
//
// Scoped by game when a game's moderator asks, through the tags on the reported post
// or on the post the reported comment belongs to. A site administrator passes no
// scope and sees everything.
func (q *Queries) ListOpenForumReports(ctx context.Context, arg ListOpenForumReportsParams) ([]CoreForumReport, error) {
	rows, err := q.db.Query(ctx, listOpenForumReports, arg.Games, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreForumReport{}
	for rows.Next() {
		var i CoreForumReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.PostID,
			&i.CommentID,
			&i.Reason,
			&i.Detail,
			&i.State,
			&i.HandledBy,
			&i.HandledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveForumReport = `-- name: ResolveForumReport :one
UPDATE core.forum_reports SET
    state = $1,
    handled_by = $2::uuid,
    handled_at = now()
WHERE id = $3 AND state = 'open'
RETURNING id, reporter_id, post_id, comment_id, reason, detail, state, handled_by, handled_at, created_at
`

type ResolveForumReportParams struct {
	State     string
	HandledBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ResolveForumReport(ctx context.Context, arg ResolveForumReportParams) (CoreForumReport, error) {
	row := q.db.QueryRow(ctx, resolveForumReport, arg.State, arg.HandledBy, arg.ID)
	var i CoreForumReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.CommentID,
		&i.Reason,
		&i.Detail,
		&i.State,
		&i.HandledBy,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}

const setForumCommentHidden = `-- name: SetForumCommentHidden :one
UPDATE core.forum_comments SET
    hidden_at     = CASE WHEN $1::boolean THEN now() ELSE NULL END,
    hidden_by     = CASE WHEN $1::boolean THEN $2::uuid ELSE NULL END,
    hidden_reason = CASE WHEN $1::boolean THEN $3::text ELSE NULL END
WHERE id = $4
RETURNING id, post_id, parent_id, author_id, body, comment_no, depth, parent_depth, created_at, updated_at, edited_at, hidden_at, hidden_by, hidden_reason
`

type SetForumCommentHiddenParams struct {
	Hidden  bool
	ActorID *uuid.UUID
	Reason  *string
	ID      uuid.UUID
}

func (q *Queries) SetForumCommentHidden(ctx context.Context, arg SetForumCommentHiddenParams) (CoreForumComment, error) {
	row := q.db.QueryRow(ctx, setForumCommentHidden,
		arg.Hidden,
		arg.ActorID,
		arg.Reason,
		arg.ID,
	)
	var i CoreForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.CommentNo,
		&i.Depth,
		&i.ParentDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
	)
	return i, err
}

const setForumPostHidden = `-- name: SetForumPostHidden :one

UPDATE core.forum_posts SET
    hidden_at     = CASE WHEN $1::boolean THEN now() ELSE NULL END,
    hidden_by     = CASE WHEN $1::boolean THEN $2::uuid ELSE NULL END,
    hidden_reason = CASE WHEN $1::boolean THEN $3::text ELSE NULL END
WHERE id = $4
RETURNING id, post_no, author_id, channel, title, body, topic, game_ids, tags, next_comment_no, created_at, updated_at, edited_at, featured_at, featured_by, hidden_at, hidden_by, hidden_reason, video_url
`

type SetForumPostHiddenParams struct {
	Hidden  bool
	ActorID *uuid.UUID
	Reason  *string
	ID      uuid.UUID
}

// Moderation. Hiding is reversible and attributed; reports are an audit trail.
// All three columns move together, which forum_posts_hidden_together requires.
func (q *Queries) SetForumPostHidden(ctx context.Context, arg SetForumPostHiddenParams) (CoreForumPost, error) {
	row := q.db.QueryRow(ctx, setForumPostHidden,
		arg.Hidden,
		arg.ActorID,
		arg.Reason,
		arg.ID,
	)
	var i CoreForumPost
	err := row.Scan(
		&i.ID,
		&i.PostNo,
		&i.AuthorID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.Topic,
		&i.GameIDs,
		&i.Tags,
		&i.NextCommentNo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.FeaturedAt,
		&i.FeaturedBy,
		&i.HiddenAt,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.VideoUrl,
	)
	return i, err
}
