// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coredb

import (
	"time"

	"github.com/google/uuid"
)

type CoreUser struct {
	ID             uuid.UUID
	Name           string
	Email          string
	HashedPassword string
	IsActive       bool
	IsSuperuser    bool
	IsVerified     bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UID            int64
	SpecialUID     *int32
	AvatarKey      *string
}
