// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package coredb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreForumComment struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	ParentID     *uuid.UUID
	AuthorID     uuid.UUID
	Body         string
	CommentNo    *int64
	Depth        int16
	ParentDepth  *int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EditedAt     pgtype.Timestamptz
	HiddenAt     pgtype.Timestamptz
	HiddenBy     *uuid.UUID
	HiddenReason *string
}

type CoreForumCommentLike struct {
	CommentID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type CoreForumPost struct {
	ID            uuid.UUID
	PostNo        int64
	AuthorID      uuid.UUID
	Channel       string
	Title         string
	Body          string
	Topic         *string
	GameIDs       []string
	Tags          []string
	NextCommentNo int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EditedAt      pgtype.Timestamptz
	FeaturedAt    pgtype.Timestamptz
	FeaturedBy    *uuid.UUID
	HiddenAt      pgtype.Timestamptz
	HiddenBy      *uuid.UUID
	HiddenReason  *string
}

type CoreForumPostBookmark struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type CoreForumPostImage struct {
	PostID    uuid.UUID
	Position  int16
	ObjectKey string
	Width     int32
	Height    int32
	CreatedAt time.Time
}

type CoreForumPostLike struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type CoreForumReport struct {
	ID         uuid.UUID
	ReporterID uuid.UUID
	PostID     *uuid.UUID
	CommentID  *uuid.UUID
	Reason     string
	Detail     *string
	State      string
	HandledBy  *uuid.UUID
	HandledAt  pgtype.Timestamptz
	CreatedAt  time.Time
}

type CoreNotification struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	Kind        string
	ActorID     *uuid.UUID
	PostID      *uuid.UUID
	CommentID   *uuid.UUID
	Body        *string
	ReadAt      pgtype.Timestamptz
	CreatedAt   time.Time
}

type CoreNotificationPreference struct {
	UserID      uuid.UUID
	Reply       bool
	Mention     bool
	PostLike    bool
	CommentLike bool
	Follow      bool
	System      bool
	UpdatedAt   time.Time
}

type CoreRoleGrant struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Role      string
	Game      string
	GrantedBy *uuid.UUID
	CreatedAt time.Time
}

type CoreUser struct {
	ID             uuid.UUID
	Name           string
	Email          string
	HashedPassword string
	IsActive       bool
	IsSuperuser    bool
	IsVerified     bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UID            int64
	SpecialUID     *int32
	AvatarKey      *string
}

type CoreUserFollow struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	CreatedAt  time.Time
}

type CoreUserPrivacy struct {
	UserID             uuid.UUID
	ProfileVisibility  string
	PostsVisibility    string
	ActivityVisibility string
	UpdatedAt          time.Time
}
