// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM core.notifications
WHERE recipient_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
`

type CountNotificationsParams struct {
	RecipientID uuid.UUID
	UnreadOnly  bool
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, arg.RecipientID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM core.notifications WHERE recipient_id = $1 AND read_at IS NULL
`

// Answered by notifications_unread_idx, so the badge does not scan the inbox.
func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO core.notifications (id, recipient_id, kind, actor_id, post_id, comment_id, body)
SELECT $1, $2, $3,
       $4::uuid, $5::uuid,
       $6::uuid, $7::text
WHERE COALESCE((
    SELECT CASE $3
        WHEN 'reply'        THEN p.reply
        WHEN 'mention'      THEN p.mention
        WHEN 'post_like'    THEN p.post_like
        WHEN 'comment_like' THEN p.comment_like
        WHEN 'follow'       THEN p.follow
        WHEN 'system'       THEN p.system
    END
    FROM core.notification_preferences p
    WHERE p.user_id = $2
), true)
AND $4::uuid IS DISTINCT FROM $2
`

type CreateNotificationParams struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	Kind        string
	ActorID     *uuid.UUID
	PostID      *uuid.UUID
	CommentID   *uuid.UUID
	Body        *string
}

// Gated on the recipient's preference for this kind, in the statement rather than in Go:
// the check and the insert are then one round trip and cannot race a preference change.
// An absent preferences row means every default, which COALESCE supplies.
// The self-notification constraint would reject this anyway; skipping it here keeps a
// like on your own post from failing the request that caused it.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.RecipientID,
		arg.Kind,
		arg.ActorID,
		arg.PostID,
		arg.CommentID,
		arg.Body,
	)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT
    COALESCE(p.reply,        true) AS reply,
    COALESCE(p.mention,      true) AS mention,
    COALESCE(p.post_like,    true) AS post_like,
    COALESCE(p.comment_like, true) AS comment_like,
    COALESCE(p.follow,       true) AS follow,
    COALESCE(p.system,       true) AS system
FROM core.users u
LEFT JOIN core.notification_preferences p ON p.user_id = u.id
WHERE u.id = $1
`

type GetNotificationPreferencesRow struct {
	Reply       bool
	Mention     bool
	PostLike    bool
	CommentLike bool
	Follow      bool
	System      bool
}

func (q *Queries) GetNotificationPreferences(ctx context.Context, id uuid.UUID) (GetNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, id)
	var i GetNotificationPreferencesRow
	err := row.Scan(
		&i.Reply,
		&i.Mention,
		&i.PostLike,
		&i.CommentLike,
		&i.Follow,
		&i.System,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_id, kind, actor_id, post_id, comment_id, body, read_at, created_at FROM core.notifications
WHERE recipient_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	RecipientID  uuid.UUID
	UnreadOnly   bool
	ResultOffset int32
	ResultLimit  int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]CoreNotification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.RecipientID,
		arg.UnreadOnly,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreNotification{}
	for rows.Next() {
		var i CoreNotification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.ActorID,
			&i.PostID,
			&i.CommentID,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE core.notifications SET read_at = now()
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE core.notifications SET read_at = now()
WHERE id = $1 AND recipient_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
}

// Scoped by recipient as well as id, so one account cannot mark another's as read by
// guessing a uuid.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNotificationPreferences = `-- name: SetNotificationPreferences :one
INSERT INTO core.notification_preferences (user_id, reply, mention, post_like, comment_like, follow, system)
VALUES (
    $1,
    COALESCE($2, true),
    COALESCE($3, true),
    COALESCE($4, true),
    COALESCE($5, true),
    COALESCE($6, true),
    COALESCE($7, true)
)
ON CONFLICT (user_id) DO UPDATE SET
    reply        = COALESCE($2,        core.notification_preferences.reply),
    mention      = COALESCE($3,      core.notification_preferences.mention),
    post_like    = COALESCE($4,    core.notification_preferences.post_like),
    comment_like = COALESCE($5, core.notification_preferences.comment_like),
    follow       = COALESCE($6,       core.notification_preferences.follow),
    system       = COALESCE($7,       core.notification_preferences.system)
RETURNING reply, mention, post_like, comment_like, follow, system
`

type SetNotificationPreferencesParams struct {
	UserID      uuid.UUID
	Reply       interface{}
	Mention     interface{}
	PostLike    interface{}
	CommentLike interface{}
	Follow      interface{}
	System      interface{}
}

type SetNotificationPreferencesRow struct {
	Reply       bool
	Mention     bool
	PostLike    bool
	CommentLike bool
	Follow      bool
	System      bool
}

func (q *Queries) SetNotificationPreferences(ctx context.Context, arg SetNotificationPreferencesParams) (SetNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, setNotificationPreferences,
		arg.UserID,
		arg.Reply,
		arg.Mention,
		arg.PostLike,
		arg.CommentLike,
		arg.Follow,
		arg.System,
	)
	var i SetNotificationPreferencesRow
	err := row.Scan(
		&i.Reply,
		&i.Mention,
		&i.PostLike,
		&i.CommentLike,
		&i.Follow,
		&i.System,
	)
	return i, err
}
