// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postimages.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const attachForumPostImage = `-- name: AttachForumPostImage :one
INSERT INTO core.forum_post_images (post_id, position, object_key, width, height)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (post_id, position) DO UPDATE SET
    object_key = excluded.object_key,
    width      = excluded.width,
    height     = excluded.height
RETURNING post_id, position, object_key, width, height, created_at
`

type AttachForumPostImageParams struct {
	PostID    uuid.UUID
	Position  int16
	ObjectKey string
	Width     int32
	Height    int32
}

// Re-attaching at the same position replaces it, so a client correcting one slot does not
// have to detach first and does not leave a gap if the second call never arrives.
func (q *Queries) AttachForumPostImage(ctx context.Context, arg AttachForumPostImageParams) (CoreForumPostImage, error) {
	row := q.db.QueryRow(ctx, attachForumPostImage,
		arg.PostID,
		arg.Position,
		arg.ObjectKey,
		arg.Width,
		arg.Height,
	)
	var i CoreForumPostImage
	err := row.Scan(
		&i.PostID,
		&i.Position,
		&i.ObjectKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const countForumPostImages = `-- name: CountForumPostImages :one
SELECT count(*) FROM core.forum_post_images WHERE post_id = $1
`

func (q *Queries) CountForumPostImages(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countForumPostImages, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const detachForumPostImage = `-- name: DetachForumPostImage :execrows
DELETE FROM core.forum_post_images WHERE post_id = $1 AND position = $2
`

type DetachForumPostImageParams struct {
	PostID   uuid.UUID
	Position int16
}

func (q *Queries) DetachForumPostImage(ctx context.Context, arg DetachForumPostImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachForumPostImage, arg.PostID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listForumPostImages = `-- name: ListForumPostImages :many
SELECT post_id, position, object_key, width, height, created_at FROM core.forum_post_images WHERE post_id = $1 ORDER BY position
`

func (q *Queries) ListForumPostImages(ctx context.Context, postID uuid.UUID) ([]CoreForumPostImage, error) {
	rows, err := q.db.Query(ctx, listForumPostImages, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreForumPostImage{}
	for rows.Next() {
		var i CoreForumPostImage
		if err := rows.Scan(
			&i.PostID,
			&i.Position,
			&i.ObjectKey,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPostImagesForPosts = `-- name: ListForumPostImagesForPosts :many
SELECT post_id, position, object_key, width, height, created_at FROM core.forum_post_images
WHERE post_id = ANY ($1::uuid[])
ORDER BY post_id, position
`

// One query for a page of posts rather than one per post, matching how a page of authors
// is loaded.
func (q *Queries) ListForumPostImagesForPosts(ctx context.Context, postIds []uuid.UUID) ([]CoreForumPostImage, error) {
	rows, err := q.db.Query(ctx, listForumPostImagesForPosts, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreForumPostImage{}
	for rows.Next() {
		var i CoreForumPostImage
		if err := rows.Scan(
			&i.PostID,
			&i.Position,
			&i.ObjectKey,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
