// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const getUserPrivacy = `-- name: GetUserPrivacy :one
SELECT
    COALESCE(p.profile_visibility,  'public') AS profile_visibility,
    COALESCE(p.posts_visibility,    'public') AS posts_visibility,
    COALESCE(p.activity_visibility, 'public') AS activity_visibility
FROM core.users u
LEFT JOIN core.user_privacy p ON p.user_id = u.id
WHERE u.id = $1
`

type GetUserPrivacyRow struct {
	ProfileVisibility  string
	PostsVisibility    string
	ActivityVisibility string
}

// COALESCE rather than a required row: an account that has never touched its settings
// has no row, and everything defaults to public.
func (q *Queries) GetUserPrivacy(ctx context.Context, id uuid.UUID) (GetUserPrivacyRow, error) {
	row := q.db.QueryRow(ctx, getUserPrivacy, id)
	var i GetUserPrivacyRow
	err := row.Scan(&i.ProfileVisibility, &i.PostsVisibility, &i.ActivityVisibility)
	return i, err
}

const setUserPrivacy = `-- name: SetUserPrivacy :one
INSERT INTO core.user_privacy (user_id, profile_visibility, posts_visibility, activity_visibility)
VALUES (
    $1,
    COALESCE($2,  'public'),
    COALESCE($3,    'public'),
    COALESCE($4, 'public')
)
ON CONFLICT (user_id) DO UPDATE SET
    profile_visibility  = COALESCE($2,  core.user_privacy.profile_visibility),
    posts_visibility    = COALESCE($3,    core.user_privacy.posts_visibility),
    activity_visibility = COALESCE($4, core.user_privacy.activity_visibility)
RETURNING profile_visibility, posts_visibility, activity_visibility
`

type SetUserPrivacyParams struct {
	UserID             uuid.UUID
	ProfileVisibility  interface{}
	PostsVisibility    interface{}
	ActivityVisibility interface{}
}

type SetUserPrivacyRow struct {
	ProfileVisibility  string
	PostsVisibility    string
	ActivityVisibility string
}

// Upsert, so the first change creates the row and later ones update it. A NULL argument
// leaves that setting alone, matching how UpdateUser treats a partial edit.
func (q *Queries) SetUserPrivacy(ctx context.Context, arg SetUserPrivacyParams) (SetUserPrivacyRow, error) {
	row := q.db.QueryRow(ctx, setUserPrivacy,
		arg.UserID,
		arg.ProfileVisibility,
		arg.PostsVisibility,
		arg.ActivityVisibility,
	)
	var i SetUserPrivacyRow
	err := row.Scan(&i.ProfileVisibility, &i.PostsVisibility, &i.ActivityVisibility)
	return i, err
}
