// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const bookmarkForumPost = `-- name: BookmarkForumPost :exec
INSERT INTO core.forum_post_bookmarks (post_id, user_id) VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type BookmarkForumPostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) BookmarkForumPost(ctx context.Context, arg BookmarkForumPostParams) error {
	_, err := q.db.Exec(ctx, bookmarkForumPost, arg.PostID, arg.UserID)
	return err
}

const forumCommentReactions = `-- name: ForumCommentReactions :one
SELECT
    (SELECT count(*) FROM core.forum_comment_likes l
        WHERE l.comment_id = $1) AS like_count,
    EXISTS (
        SELECT 1 FROM core.forum_comment_likes l
        WHERE l.comment_id = $1 AND l.user_id = $2::uuid
    ) AS liked
`

type ForumCommentReactionsParams struct {
	CommentID uuid.UUID
	ViewerID  *uuid.UUID
}

type ForumCommentReactionsRow struct {
	LikeCount int64
	Liked     bool
}

// One comment's like state, for the responses that return a single comment rather
// than a page of them.
func (q *Queries) ForumCommentReactions(ctx context.Context, arg ForumCommentReactionsParams) (ForumCommentReactionsRow, error) {
	row := q.db.QueryRow(ctx, forumCommentReactions, arg.CommentID, arg.ViewerID)
	var i ForumCommentReactionsRow
	err := row.Scan(&i.LikeCount, &i.Liked)
	return i, err
}

const likeForumComment = `-- name: LikeForumComment :exec
INSERT INTO core.forum_comment_likes (comment_id, user_id) VALUES ($1, $2)
ON CONFLICT (comment_id, user_id) DO NOTHING
`

type LikeForumCommentParams struct {
	CommentID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) LikeForumComment(ctx context.Context, arg LikeForumCommentParams) error {
	_, err := q.db.Exec(ctx, likeForumComment, arg.CommentID, arg.UserID)
	return err
}

const likeForumPost = `-- name: LikeForumPost :exec

INSERT INTO core.forum_post_likes (post_id, user_id) VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type LikeForumPostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

// Reactions. Every write is idempotent, because the client is asking for an end
// state: liking a post twice must mean the same as liking it once, so a double tap
// or a retried request is not an error anyone has to interpret.
func (q *Queries) LikeForumPost(ctx context.Context, arg LikeForumPostParams) error {
	_, err := q.db.Exec(ctx, likeForumPost, arg.PostID, arg.UserID)
	return err
}

const unbookmarkForumPost = `-- name: UnbookmarkForumPost :exec
DELETE FROM core.forum_post_bookmarks WHERE post_id = $1 AND user_id = $2
`

type UnbookmarkForumPostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnbookmarkForumPost(ctx context.Context, arg UnbookmarkForumPostParams) error {
	_, err := q.db.Exec(ctx, unbookmarkForumPost, arg.PostID, arg.UserID)
	return err
}

const unlikeForumComment = `-- name: UnlikeForumComment :exec
DELETE FROM core.forum_comment_likes WHERE comment_id = $1 AND user_id = $2
`

type UnlikeForumCommentParams struct {
	CommentID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UnlikeForumComment(ctx context.Context, arg UnlikeForumCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeForumComment, arg.CommentID, arg.UserID)
	return err
}

const unlikeForumPost = `-- name: UnlikeForumPost :exec
DELETE FROM core.forum_post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikeForumPostParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnlikeForumPost(ctx context.Context, arg UnlikeForumPostParams) error {
	_, err := q.db.Exec(ctx, unlikeForumPost, arg.PostID, arg.UserID)
	return err
}
