// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const grantRole = `-- name: GrantRole :one
INSERT INTO core.role_grants (id, user_id, role, game, granted_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, role, game) DO UPDATE SET role = core.role_grants.role
RETURNING id, user_id, role, game, granted_by, created_at
`

type GrantRoleParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Role      string
	Game      string
	GrantedBy *uuid.UUID
}

// Idempotent: granting a role someone already holds returns the existing grant
// rather than failing, so a double-click is not an error the client has to
// interpret. DO UPDATE rather than DO NOTHING because DO NOTHING returns no row,
// which would make the handler unable to answer with the grant.
func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (CoreRoleGrant, error) {
	row := q.db.QueryRow(ctx, grantRole,
		arg.ID,
		arg.UserID,
		arg.Role,
		arg.Game,
		arg.GrantedBy,
	)
	var i CoreRoleGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Game,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRoleGrantsForGame = `-- name: ListRoleGrantsForGame :many
SELECT id, user_id, role, game, granted_by, created_at FROM core.role_grants
WHERE game = $1
ORDER BY CASE role WHEN 'game_admin' THEN 0 ELSE 1 END, created_at, id
`

// The public cabin query: who staffs this game. Administrators before moderators,
// then oldest grant first, so the ordering is stable and reads as a hierarchy.
func (q *Queries) ListRoleGrantsForGame(ctx context.Context, game string) ([]CoreRoleGrant, error) {
	rows, err := q.db.Query(ctx, listRoleGrantsForGame, game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRoleGrant{}
	for rows.Next() {
		var i CoreRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Game,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleGrantsForUser = `-- name: ListRoleGrantsForUser :many
SELECT id, user_id, role, game, granted_by, created_at FROM core.role_grants
WHERE user_id = $1
ORDER BY game, role
`

func (q *Queries) ListRoleGrantsForUser(ctx context.Context, userID uuid.UUID) ([]CoreRoleGrant, error) {
	rows, err := q.db.Query(ctx, listRoleGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRoleGrant{}
	for rows.Next() {
		var i CoreRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Game,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleGrantsForUserInGame = `-- name: ListRoleGrantsForUserInGame :many
SELECT id, user_id, role, game, granted_by, created_at FROM core.role_grants
WHERE user_id = $1 AND game = $2
`

type ListRoleGrantsForUserInGameParams struct {
	UserID uuid.UUID
	Game   string
}

// The authorization query. Narrow on purpose: it answers "what may this account do
// in this game" without loading grants for games the request has nothing to do with.
func (q *Queries) ListRoleGrantsForUserInGame(ctx context.Context, arg ListRoleGrantsForUserInGameParams) ([]CoreRoleGrant, error) {
	rows, err := q.db.Query(ctx, listRoleGrantsForUserInGame, arg.UserID, arg.Game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRoleGrant{}
	for rows.Next() {
		var i CoreRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Game,
			&i.GrantedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :execrows
DELETE FROM core.role_grants
WHERE user_id = $1 AND role = $2 AND game = $3
`

type RevokeRoleParams struct {
	UserID uuid.UUID
	Role   string
	Game   string
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.Role, arg.Game)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
