// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package coredb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT count(*) FROM core.user_follows WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT count(*) FROM core.user_follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :exec

INSERT INTO core.user_follows (follower_id, followee_id) VALUES ($1, $2)
ON CONFLICT (follower_id, followee_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

// The follow graph. Writes are idempotent for the same reason reactions are: the
// caller is stating an end state, so a retry or a double tap must not be an error.
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM core.user_follows
    WHERE follower_id = $1::uuid AND followee_id = $2
)
`

type IsFollowingParams struct {
	FollowerID *uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT follower_id, created_at FROM core.user_follows
WHERE followee_id = $1
ORDER BY created_at DESC, follower_id
LIMIT $3 OFFSET $2
`

type ListFollowersParams struct {
	FolloweeID   uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListFollowersRow struct {
	FollowerID uuid.UUID
	CreatedAt  time.Time
}

// Newest first: a follower list is read to see who arrived, not alphabetically.
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FolloweeID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(&i.FollowerID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT followee_id, created_at FROM core.user_follows
WHERE follower_id = $1
ORDER BY created_at DESC, followee_id
LIMIT $3 OFFSET $2
`

type ListFollowingParams struct {
	FollowerID   uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListFollowingRow struct {
	FolloweeID uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(&i.FolloweeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM core.user_follows WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
