// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const countOtherActiveSuperusers = `-- name: CountOtherActiveSuperusers :one
SELECT count(*) FROM core.users
WHERE is_superuser AND is_active AND id <> $1
`

// Counts administrators who could still sign in if the given account stopped
// being one. Used to refuse the change that would leave the site with none.
func (q *Queries) CountOtherActiveSuperusers(ctx context.Context, excluding uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveSuperusers, excluding)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM core.users
WHERE (
        ($1::text IS NULL AND $2::text IS NULL)
     OR ($1::text  IS NOT NULL AND name  ILIKE '%' || $1::text  || '%')
     OR ($2::text IS NOT NULL AND email ILIKE '%' || $2::text || '%')
)
`

type CountUsersParams struct {
	Name  *string
	Email *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Name, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO core.users (id, name, email, hashed_password, is_active, is_superuser, is_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key
`

type CreateUserParams struct {
	ID             uuid.UUID
	Name           string
	Email          string
	HashedPassword string
	IsActive       bool
	IsSuperuser    bool
	IsVerified     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.IsActive,
		arg.IsSuperuser,
		arg.IsVerified,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const getUserByAnyUID = `-- name: GetUserByAnyUID :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users WHERE uid = $1 OR special_uid = $1
`

// Resolves either kind of account number in one round trip.
//
// No discriminator is needed because the two ranges cannot overlap: uid is
// checked >= 10000 and special_uid <= 9999, so a given number can only ever
// match one column. Both columns are uniquely indexed, and the planner answers
// this with a BitmapOr over the two indexes rather than a scan.
func (q *Queries) GetUserByAnyUID(ctx context.Context, uid int64) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByAnyUID, uid)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const getUserIDsByNames = `-- name: GetUserIDsByNames :many
SELECT id, name FROM core.users
WHERE name = ANY ($1::text[]) AND is_active
`

type GetUserIDsByNamesRow struct {
	ID   uuid.UUID
	Name string
}

// Resolves a batch of display names at once, for mentions. One round trip rather than one
// per name: a body may legitimately name several people, and an abusive one names
// thousands, so the cost must not scale with what the author typed.
// Inactive accounts are omitted, matching every other name and uid lookup.
func (q *Queries) GetUserIDsByNames(ctx context.Context, names []string) ([]GetUserIDsByNamesRow, error) {
	rows, err := q.db.Query(ctx, getUserIDsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserIDsByNamesRow{}
	for rows.Next() {
		var i GetUserIDsByNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users WHERE id = ANY($1::uuid[])
`

// Batch lookup for rendering authors on a page of forum posts, so a feed costs
// one query for its authors instead of one per row.
func (q *Queries) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]CoreUser, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.HashedPassword,
			&i.IsActive,
			&i.IsSuperuser,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UID,
			&i.SpecialUID,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminMembership = `-- name: LockAdminMembership :exec
SELECT pg_advisory_xact_lock(hashtext('core.users.admin_membership'))
`

// Serialises every change to the set of usable administrators. Held for the
// duration of the transaction, so a check and the update it authorises cannot
// interleave with another such pair. Without it two concurrent deactivations
// each observe the other as the remaining administrator and both succeed.
func (q *Queries) LockAdminMembership(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdminMembership)
	return err
}

const searchUsers = `-- name: SearchUsers :many

SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key FROM core.users
WHERE (
        ($1::text IS NULL AND $2::text IS NULL)
     OR ($1::text  IS NOT NULL AND name  ILIKE '%' || $1::text  || '%')
     OR ($2::text IS NOT NULL AND email ILIKE '%' || $2::text || '%')
)
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type SearchUsersParams struct {
	Name         *string
	Email        *string
	ResultOffset int32
	ResultLimit  int32
}

// Accounts are never deleted, only deactivated: the row is the author of its
// comments and contributions, so removing it would cascade that work away or
// orphan it. Deactivation goes through UpdateUser's is_active flag. No delete
// query exists here on purpose — the capability is absent rather than merely
// unused.
// Search preserves the Python endpoint's OR semantics: with both filters set a
// user matching either one is returned, and with neither set every user is.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]CoreUser, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Name,
		arg.Email,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.HashedPassword,
			&i.IsActive,
			&i.IsSuperuser,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UID,
			&i.SpecialUID,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE core.users SET avatar_key = $1
WHERE id = $2
RETURNING id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key
`

type SetUserAvatarParams struct {
	AvatarKey *string
	ID        uuid.UUID
}

// Setting and clearing an avatar are the same statement: a key assigns one, NULL
// removes it. Unlike special_uid this needs no "leave unchanged" state, because
// nothing edits an avatar as a side effect of another change.
func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, setUserAvatar, arg.AvatarKey, arg.ID)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}

const superuserExists = `-- name: SuperuserExists :one
SELECT EXISTS (SELECT 1 FROM core.users WHERE is_superuser)
`

func (q *Queries) SuperuserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, superuserExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE core.users SET
    name            = COALESCE($1, name),
    email           = COALESCE($2, email),
    hashed_password = COALESCE($3, hashed_password),
    is_active       = COALESCE($4, is_active),
    is_superuser    = COALESCE($5, is_superuser),
    is_verified     = COALESCE($6, is_verified),
    special_uid     = CASE WHEN $7::boolean
                           THEN $8::integer
                           ELSE special_uid END
WHERE id = $9
RETURNING id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at, uid, special_uid, avatar_key
`

type UpdateUserParams struct {
	Name           *string
	Email          *string
	HashedPassword *string
	IsActive       *bool
	IsSuperuser    *bool
	IsVerified     *bool
	SetSpecialUID  bool
	SpecialUID     *int32
	ID             uuid.UUID
}

// The COALESCE idiom cannot express clearing a column, because it reads NULL as
// "leave unchanged". special_uid is the one column that must be clearable, so it
// takes an explicit set_special_uid flag: false leaves the current value alone,
// true writes special_uid through verbatim -- including NULL, which revokes.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.IsActive,
		arg.IsSuperuser,
		arg.IsVerified,
		arg.SetSpecialUID,
		arg.SpecialUID,
		arg.ID,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UID,
		&i.SpecialUID,
		&i.AvatarKey,
	)
	return i, err
}
