// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package coredb

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM core.users
WHERE (
        ($1::text IS NULL AND $2::text IS NULL)
     OR ($1::text  IS NOT NULL AND name  ILIKE '%' || $1::text  || '%')
     OR ($2::text IS NOT NULL AND email ILIKE '%' || $2::text || '%')
)
`

type CountUsersParams struct {
	Name  *string
	Email *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Name, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO core.users (id, name, email, hashed_password, is_active, is_superuser, is_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Name           string
	Email          string
	HashedPassword string
	IsActive       bool
	IsSuperuser    bool
	IsVerified     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.IsActive,
		arg.IsSuperuser,
		arg.IsVerified,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM core.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at FROM core.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at FROM core.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at FROM core.users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at FROM core.users
WHERE (
        ($1::text IS NULL AND $2::text IS NULL)
     OR ($1::text  IS NOT NULL AND name  ILIKE '%' || $1::text  || '%')
     OR ($2::text IS NOT NULL AND email ILIKE '%' || $2::text || '%')
)
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type SearchUsersParams struct {
	Name         *string
	Email        *string
	ResultOffset int32
	ResultLimit  int32
}

// Search preserves the Python endpoint's OR semantics: with both filters set a
// user matching either one is returned, and with neither set every user is.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]CoreUser, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Name,
		arg.Email,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUser{}
	for rows.Next() {
		var i CoreUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.HashedPassword,
			&i.IsActive,
			&i.IsSuperuser,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const superuserExists = `-- name: SuperuserExists :one
SELECT EXISTS (SELECT 1 FROM core.users WHERE is_superuser)
`

func (q *Queries) SuperuserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, superuserExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE core.users SET
    name            = COALESCE($1, name),
    email           = COALESCE($2, email),
    hashed_password = COALESCE($3, hashed_password),
    is_active       = COALESCE($4, is_active),
    is_superuser    = COALESCE($5, is_superuser),
    is_verified     = COALESCE($6, is_verified)
WHERE id = $7
RETURNING id, name, email, hashed_password, is_active, is_superuser, is_verified, created_at, updated_at
`

type UpdateUserParams struct {
	Name           *string
	Email          *string
	HashedPassword *string
	IsActive       *bool
	IsSuperuser    *bool
	IsVerified     *bool
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.IsActive,
		arg.IsSuperuser,
		arg.IsVerified,
		arg.ID,
	)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.IsActive,
		&i.IsSuperuser,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
