import type { Language } from './i18n'

// Breeding-calculator strings, merged into the `translation` namespace under a
// `breeding` key (see i18n.ts). Kept separate from the map strings to keep both
// tables readable.
export interface BreedingStrings {
  navMap: string
  navBreeding: string
  title: string
  parentA: string
  parentB: string
  child: string
  anyPal: string
  searchPal: string
  noPalFound: string
  combinations: string
  clear: string
  showingSpecial: string
  unique: string
  favorite: string
  more: string
  /** Label for a Pal's CombiRank (shown in the Paldeck breeding section). */
  breedingPower: string
  /** Pager button labels (Paldeck breeding section). */
  prevPage: string
  nextPage: string
}

export const BREEDING_STRINGS: Record<Language, BreedingStrings> = {
  'en-US': {
    navMap: 'Map',
    navBreeding: 'Breeding',
    title: 'Breeding Calculator',
    parentA: 'Parent A',
    parentB: 'Parent B',
    child: 'Child',
    anyPal: 'Any Pal',
    searchPal: 'Search Pals…',
    noPalFound: 'No Pal found.',
    combinations: '{{count}} combinations',
    clear: 'Clear',
    showingSpecial: 'Unique recipes — pick a Pal to calculate every pairing',
    unique: 'Unique',
    favorite: 'Favorite',
    more: '+{{count}} more — pick a parent to narrow',
    breedingPower: 'Breeding Power',
    prevPage: 'Previous page',
    nextPage: 'Next page',
  },
  'de-DE': {
    navMap: 'Karte',
    navBreeding: 'Zucht',
    title: 'Zucht-Rechner',
    parentA: 'Elternteil A',
    parentB: 'Elternteil B',
    child: 'Nachkomme',
    anyPal: 'Beliebiges Pal',
    searchPal: 'Pals suchen…',
    noPalFound: 'Kein Pal gefunden.',
    combinations: '{{count}} Kombinationen',
    clear: 'Zurücksetzen',
    showingSpecial: 'Einzigartige Rezepte — wähle ein Pal, um jede Paarung zu berechnen',
    unique: 'Einzigartig',
    favorite: 'Favorit',
    more: '+{{count}} weitere — Elternteil wählen zum Eingrenzen',
    breedingPower: 'Zuchtstärke',
    prevPage: 'Vorherige Seite',
    nextPage: 'Nächste Seite',
  },
  'es-ES': {
    navMap: 'Mapa',
    navBreeding: 'Crianza',
    title: 'Calculadora de crianza',
    parentA: 'Progenitor A',
    parentB: 'Progenitor B',
    child: 'Cría',
    anyPal: 'Cualquier Pal',
    searchPal: 'Buscar Pals…',
    noPalFound: 'No se encontró ningún Pal.',
    combinations: '{{count}} combinaciones',
    clear: 'Limpiar',
    showingSpecial: 'Recetas únicas — elige un Pal para calcular cualquier cruce',
    unique: 'Único',
    favorite: 'Favorito',
    more: '+{{count}} más — elige un progenitor para acotar',
    breedingPower: 'Poder de crianza',
    prevPage: 'Página anterior',
    nextPage: 'Página siguiente',
  },
  'es-MX': {
    navMap: 'Mapa',
    navBreeding: 'Crianza',
    title: 'Calculadora de crianza',
    parentA: 'Progenitor A',
    parentB: 'Progenitor B',
    child: 'Cría',
    anyPal: 'Cualquier Pal',
    searchPal: 'Buscar Pals…',
    noPalFound: 'No se encontró ningún Pal.',
    combinations: '{{count}} combinaciones',
    clear: 'Limpiar',
    showingSpecial: 'Recetas únicas — elige un Pal para calcular cualquier cruce',
    unique: 'Único',
    favorite: 'Favorito',
    more: '+{{count}} más — elige un progenitor para acotar',
    breedingPower: 'Poder de crianza',
    prevPage: 'Página anterior',
    nextPage: 'Página siguiente',
  },
  'fr-FR': {
    navMap: 'Carte',
    navBreeding: 'Élevage',
    title: "Calculateur d'élevage",
    parentA: 'Parent A',
    parentB: 'Parent B',
    child: 'Enfant',
    anyPal: "N'importe quel Pal",
    searchPal: 'Rechercher des Pals…',
    noPalFound: 'Aucun Pal trouvé.',
    combinations: '{{count}} combinaisons',
    clear: 'Effacer',
    showingSpecial: 'Recettes uniques — choisissez un Pal pour calculer chaque croisement',
    unique: 'Unique',
    favorite: 'Favori',
    more: '+{{count}} de plus — choisissez un parent pour affiner',
    breedingPower: "Puissance d'élevage",
    prevPage: 'Page précédente',
    nextPage: 'Page suivante',
  },
  'id-ID': {
    navMap: 'Peta',
    navBreeding: 'Ternak',
    title: 'Kalkulator Ternak',
    parentA: 'Induk A',
    parentB: 'Induk B',
    child: 'Anak',
    anyPal: 'Pal apa saja',
    searchPal: 'Cari Pal…',
    noPalFound: 'Pal tidak ditemukan.',
    combinations: '{{count}} kombinasi',
    clear: 'Hapus',
    showingSpecial: 'Resep unik — pilih Pal untuk menghitung setiap perkawinan',
    unique: 'Unik',
    favorite: 'Favorit',
    more: '+{{count}} lagi — pilih induk untuk mempersempit',
    breedingPower: 'Kekuatan Ternak',
    prevPage: 'Halaman sebelumnya',
    nextPage: 'Halaman berikutnya',
  },
  'it-IT': {
    navMap: 'Mappa',
    navBreeding: 'Allevamento',
    title: 'Calcolatore di allevamento',
    parentA: 'Genitore A',
    parentB: 'Genitore B',
    child: 'Cucciolo',
    anyPal: 'Qualsiasi Pal',
    searchPal: 'Cerca Pal…',
    noPalFound: 'Nessun Pal trovato.',
    combinations: '{{count}} combinazioni',
    clear: 'Cancella',
    showingSpecial: 'Ricette uniche — scegli un Pal per calcolare ogni accoppiamento',
    unique: 'Unico',
    favorite: 'Preferito',
    more: '+{{count}} altre — scegli un genitore per restringere',
    breedingPower: 'Potenza di allevamento',
    prevPage: 'Pagina precedente',
    nextPage: 'Pagina successiva',
  },
  'ja-JP': {
    navMap: 'マップ',
    navBreeding: '交配',
    title: '交配計算機',
    parentA: '親 A',
    parentB: '親 B',
    child: '子',
    anyPal: 'すべてのパル',
    searchPal: 'パルを検索…',
    noPalFound: 'パルが見つかりません。',
    combinations: '{{count}} 通りの組み合わせ',
    clear: 'クリア',
    showingSpecial: '固有レシピ — パルを選ぶとすべての組み合わせを計算します',
    unique: '固有',
    favorite: 'お気に入り',
    more: '他 {{count}} 件 — 親を選ぶと絞り込めます',
    breedingPower: '交配ランク',
    prevPage: '前のページ',
    nextPage: '次のページ',
  },
  'ko-KR': {
    navMap: '지도',
    navBreeding: '교배',
    title: '교배 계산기',
    parentA: '부모 A',
    parentB: '부모 B',
    child: '자식',
    anyPal: '모든 팰',
    searchPal: '팰 검색…',
    noPalFound: '팰을 찾을 수 없습니다.',
    combinations: '조합 {{count}}개',
    clear: '초기화',
    showingSpecial: '고유 레시피 — 팰을 선택하면 모든 조합을 계산합니다',
    unique: '고유',
    favorite: '즐겨찾기',
    more: '+{{count}}개 더 — 부모를 선택해 좁히세요',
    breedingPower: '교배 랭크',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
  },
  'pl-PL': {
    navMap: 'Mapa',
    navBreeding: 'Hodowla',
    title: 'Kalkulator hodowli',
    parentA: 'Rodzic A',
    parentB: 'Rodzic B',
    child: 'Potomek',
    anyPal: 'Dowolny Pal',
    searchPal: 'Szukaj Pali…',
    noPalFound: 'Nie znaleziono Pala.',
    combinations: 'Kombinacje: {{count}}',
    clear: 'Wyczyść',
    showingSpecial: 'Receptury unikatowe — wybierz Pala, aby obliczyć każdą parę',
    unique: 'Unikat',
    favorite: 'Ulubione',
    more: '+{{count}} więcej — wybierz rodzica, aby zawęzić',
    breedingPower: 'Moc hodowlana',
    prevPage: 'Poprzednia strona',
    nextPage: 'Następna strona',
  },
  'pt-BR': {
    navMap: 'Mapa',
    navBreeding: 'Reprodução',
    title: 'Calculadora de reprodução',
    parentA: 'Progenitor A',
    parentB: 'Progenitor B',
    child: 'Filhote',
    anyPal: 'Qualquer Pal',
    searchPal: 'Buscar Pals…',
    noPalFound: 'Nenhum Pal encontrado.',
    combinations: '{{count}} combinações',
    clear: 'Limpar',
    showingSpecial: 'Receitas únicas — escolha um Pal para calcular qualquer cruzamento',
    unique: 'Único',
    favorite: 'Favorito',
    more: '+{{count}} mais — escolha um progenitor para refinar',
    breedingPower: 'Poder de reprodução',
    prevPage: 'Página anterior',
    nextPage: 'Próxima página',
  },
  'ru-RU': {
    navMap: 'Карта',
    navBreeding: 'Разведение',
    title: 'Калькулятор разведения',
    parentA: 'Родитель A',
    parentB: 'Родитель B',
    child: 'Потомок',
    anyPal: 'Любой пал',
    searchPal: 'Поиск палов…',
    noPalFound: 'Пал не найден.',
    combinations: 'Комбинаций: {{count}}',
    clear: 'Сбросить',
    showingSpecial: 'Уникальные рецепты — выберите пала, чтобы рассчитать любую пару',
    unique: 'Уникальный',
    favorite: 'Избранное',
    more: 'Ещё {{count}} — выберите родителя для сужения',
    breedingPower: 'Сила разведения',
    prevPage: 'Предыдущая страница',
    nextPage: 'Следующая страница',
  },
  'th-TH': {
    navMap: 'แผนที่',
    navBreeding: 'การผสมพันธุ์',
    title: 'เครื่องคำนวณการผสมพันธุ์',
    parentA: 'พ่อแม่ A',
    parentB: 'พ่อแม่ B',
    child: 'ลูก',
    anyPal: 'Pal ใดก็ได้',
    searchPal: 'ค้นหา Pal…',
    noPalFound: 'ไม่พบ Pal',
    combinations: '{{count}} ชุดผสม',
    clear: 'ล้าง',
    showingSpecial: 'สูตรยูนีค — เลือก Pal เพื่อคำนวณทุกการผสม',
    unique: 'ยูนีค',
    favorite: 'รายการโปรด',
    more: 'อีก {{count}} รายการ — เลือกพ่อแม่เพื่อจำกัดผล',
    breedingPower: 'พลังการผสมพันธุ์',
    prevPage: 'หน้าก่อนหน้า',
    nextPage: 'หน้าถัดไป',
  },
  'tr-TR': {
    navMap: 'Harita',
    navBreeding: 'Üretme',
    title: 'Üretme Hesaplayıcı',
    parentA: 'Ebeveyn A',
    parentB: 'Ebeveyn B',
    child: 'Yavru',
    anyPal: 'Herhangi bir Pal',
    searchPal: 'Pal ara…',
    noPalFound: 'Pal bulunamadı.',
    combinations: '{{count}} kombinasyon',
    clear: 'Temizle',
    showingSpecial: 'Benzersiz tarifler — her eşleşmeyi hesaplamak için bir Pal seç',
    unique: 'Benzersiz',
    favorite: 'Favori',
    more: '+{{count}} tane daha — daraltmak için bir ebeveyn seç',
    breedingPower: 'Üretme Gücü',
    prevPage: 'Önceki sayfa',
    nextPage: 'Sonraki sayfa',
  },
  'vi-VN': {
    navMap: 'Bản đồ',
    navBreeding: 'Nhân giống',
    title: 'Công cụ tính nhân giống',
    parentA: 'Bố mẹ A',
    parentB: 'Bố mẹ B',
    child: 'Con',
    anyPal: 'Pal bất kỳ',
    searchPal: 'Tìm Pal…',
    noPalFound: 'Không tìm thấy Pal.',
    combinations: '{{count}} tổ hợp',
    clear: 'Xóa',
    showingSpecial: 'Công thức độc nhất — chọn một Pal để tính mọi cặp ghép',
    unique: 'Độc nhất',
    favorite: 'Yêu thích',
    more: '+{{count}} nữa — chọn bố mẹ để thu hẹp',
    breedingPower: 'Sức nhân giống',
    prevPage: 'Trang trước',
    nextPage: 'Trang sau',
  },
  'zh-CN': {
    navMap: '地图',
    navBreeding: '配种',
    title: '配种计算器',
    parentA: '父母 A',
    parentB: '父母 B',
    child: '子代',
    anyPal: '任意帕鲁',
    searchPal: '搜索帕鲁…',
    noPalFound: '未找到帕鲁。',
    combinations: '{{count}} 种组合',
    clear: '清除',
    showingSpecial: '独有配方 — 选择帕鲁以计算任意配对',
    unique: '独有',
    favorite: '收藏',
    more: '还有 {{count}} 条 — 选择父母以缩小范围',
    breedingPower: '配种能力',
    prevPage: '上一页',
    nextPage: '下一页',
  },
  'zh-TW': {
    navMap: '地圖',
    navBreeding: '配種',
    title: '配種計算器',
    parentA: '父母 A',
    parentB: '父母 B',
    child: '子代',
    anyPal: '任意帕魯',
    searchPal: '搜尋帕魯…',
    noPalFound: '未找到帕魯。',
    combinations: '{{count}} 種組合',
    clear: '清除',
    showingSpecial: '獨有配方 — 選擇帕魯以計算任意配對',
    unique: '獨有',
    favorite: '收藏',
    more: '還有 {{count}} 筆 — 選擇父母以縮小範圍',
    breedingPower: '配種能力',
    prevPage: '上一頁',
    nextPage: '下一頁',
  },
}
