import type { Language } from './i18n'

// Item / building / technology encyclopedia UI chrome, merged into the
// `translation` namespace under `item` / `building` / `tech` keys (see i18n.ts).
// Data-driven labels (item / building / tech names, descriptions) come from the
// locale data files; this table only holds the encyclopedias' own UI chrome.
export interface CatalogStrings {
  loading: string
  item: {
    title: string
    /** Singular kind label for the hover-card tag pill ("Item"). */
    tag: string
    searchPlaceholder: string
    count: string
    notFound: string
    backToList: string
    viewInEncyclopedia: string
    all: string
    section: {
      description: string
      properties: string
      craft: string
      obtain: string
      usedIn: string
    }
    type: string
    rarity: string
    sortId: string
    rank: string
    weight: string
    price: string
    stack: string
    element: string
    work: string
    craftedAt: string
    unlockItem: string
    handcraft: string
    droppedBy: string
    bossDrop: string
    fromTech: string
    usedInItems: string
    usedInBuildings: string
    food: { satiety: string; health: string; sanity: string; concentration: string }
    equip: {
      attack: string
      defense: string
      hp: string
      shield: string
      magicAttack: string
      magicDefense: string
      durability: string
      magazine: string
    }
  }
  building: {
    title: string
    /** Singular kind label for the hover-card tag pill ("Building"). */
    tag: string
    searchPlaceholder: string
    count: string
    notFound: string
    backToList: string
    viewInEncyclopedia: string
    all: string
    section: { description: string; materials: string; crafts: string; info: string }
    id: string
    type: string
    level: string
    energy: string
    work: string
    fromTech: string
  }
  tech: {
    title: string
    level: string
    boss: string
    cost: string
    unlockBy: string
    reqCapture: string
    reqDefeat: string
    reqUnlock: string
    reqResearch: string
    unlocksItems: string
    unlocksBuildings: string
    empty: string
    normalTitle: string
    ancientTitle: string
    typeItem: string
    typeStructure: string
    searchPlaceholder: string
    count: string
  }
}

export const CATALOG_STRINGS: Record<Language, CatalogStrings> = {
  'en-US': {
    loading: 'Loading…',
    item: {
      title: 'Items',
      tag: 'Item',
      searchPlaceholder: 'Search items…',
      count: '{{count}} items',
      notFound: 'No item found for "{{id}}".',
      backToList: 'Back to Items',
      viewInEncyclopedia: 'View item →',
      all: 'All',
      section: { description: 'Description', properties: 'Properties', craft: 'How to craft', obtain: 'How to obtain', usedIn: 'Used in' },
      type: 'Type',
      rarity: 'Rarity',
      sortId: 'Sort ID',
      rank: 'Rank',
      weight: 'Weight',
      price: 'Price',
      stack: 'Max stack',
      element: 'Element',
      work: 'Work',
      unlockItem: 'Requires blueprint',
      craftedAt: 'Crafted at',
      handcraft: 'Can be handcrafted',
      droppedBy: 'Dropped by',
      bossDrop: 'Boss',
      fromTech: 'Unlocked by technology',
      usedInItems: 'Ingredient in',
      usedInBuildings: 'Used to build',
      food: { satiety: 'Satiety', health: 'Health', sanity: 'Sanity', concentration: 'Concentration' },
      equip: { attack: 'Attack', defense: 'Defense', hp: 'HP', shield: 'Shield', magicAttack: 'Magic Attack', magicDefense: 'Magic Defense', durability: 'Durability', magazine: 'Magazine' },
    },
    building: {
      id: 'ID',
      title: 'Buildings',
      tag: 'Building',
      searchPlaceholder: 'Search buildings…',
      count: '{{count}} buildings',
      notFound: 'No building found for "{{id}}".',
      backToList: 'Back to Buildings',
      viewInEncyclopedia: 'View building →',
      all: 'All',
      section: { description: 'Description', materials: 'Build materials', crafts: 'Craftable items', info: 'Properties' },
      type: 'Type',
      level: 'Level',
      energy: 'Energy',
      work: 'Work',
      fromTech: 'Unlocked by technology',
    },
    tech: {
      title: 'Technology',
      level: 'Level {{level}}',
      boss: 'Boss',
      cost: '{{count}} pts',
      unlockBy: 'Unlocked by',
      reqCapture: 'Capture',
      reqDefeat: 'Clear',
      reqUnlock: 'Unlock',
      reqResearch: 'Research',
      unlocksItems: 'Items',
      unlocksBuildings: 'Buildings',
      empty: 'No technologies at this level.',
      normalTitle: 'Technology',
      ancientTitle: 'Ancient Technology',
      typeItem: 'Item',
      typeStructure: 'Structure',
      searchPlaceholder: 'Search technologies…',
      count: '{{count}} technologies',
    },
  },
  'de-DE': {
    loading: 'Wird geladen…',
    item: {
      title: 'Gegenstände',
      tag: 'Gegenstand',
      searchPlaceholder: 'Gegenstände suchen…',
      count: '{{count}} Gegenstände',
      notFound: 'Kein Gegenstand für „{{id}}" gefunden.',
      backToList: 'Zurück zu Gegenständen',
      viewInEncyclopedia: 'Gegenstand ansehen →',
      all: 'Alle',
      section: { description: 'Beschreibung', properties: 'Eigenschaften', craft: 'Herstellung', obtain: 'Beschaffung', usedIn: 'Verwendet in' },
      type: 'Typ',
      rarity: 'Seltenheit',
      sortId: 'Sortier-ID',
      rank: 'Rang',
      weight: 'Gewicht',
      price: 'Preis',
      stack: 'Max. Stapel',
      element: 'Element',
      work: 'Arbeit',
      unlockItem: 'Benötigt Bauplan',
      craftedAt: 'Hergestellt an',
      handcraft: 'Handwerklich herstellbar',
      droppedBy: 'Fallen gelassen von',
      bossDrop: 'Boss',
      fromTech: 'Durch Technologie freigeschaltet',
      usedInItems: 'Zutat für',
      usedInBuildings: 'Zum Bauen von',
      food: { satiety: 'Sättigung', health: 'Gesundheit', sanity: 'Verstand', concentration: 'Konzentration' },
      equip: { attack: 'Angriff', defense: 'Verteidigung', hp: 'LP', shield: 'Schild', magicAttack: 'Magieangriff', magicDefense: 'Magieabwehr', durability: 'Haltbarkeit', magazine: 'Magazin' },
    },
    building: {
      id: 'ID',
      title: 'Gebäude',
      tag: 'Gebäude',
      searchPlaceholder: 'Gebäude suchen…',
      count: '{{count}} Gebäude',
      notFound: 'Kein Gebäude für „{{id}}" gefunden.',
      backToList: 'Zurück zu Gebäuden',
      viewInEncyclopedia: 'Gebäude ansehen →',
      all: 'Alle',
      section: { description: 'Beschreibung', materials: 'Baumaterialien', crafts: 'Herstellbare Gegenstände', info: 'Eigenschaften' },
      type: 'Typ',
      level: 'Stufe',
      energy: 'Energie',
      work: 'Arbeit',
      fromTech: 'Durch Technologie freigeschaltet',
    },
    tech: {
      title: 'Technologie',
      level: 'Stufe {{level}}',
      boss: 'Boss',
      cost: '{{count}} Pkt.',
      unlockBy: 'Freischaltung durch',
      reqCapture: 'Fangen',
      reqDefeat: 'Bezwingen',
      reqUnlock: 'Freischalten',
      reqResearch: 'Erforschen',
      unlocksItems: 'Gegenstände',
      unlocksBuildings: 'Gebäude',
      empty: 'Keine Technologien auf dieser Stufe.',
      normalTitle: 'Technologie',
      ancientTitle: 'Antike Technologie',
      typeItem: 'Gegenstand',
      typeStructure: 'Struktur',
      searchPlaceholder: 'Technologien suchen…',
      count: '{{count}} Technologien',
    },
  },
  'es-ES': {
    loading: 'Cargando…',
    item: {
      title: 'Objetos',
      tag: 'Objeto',
      searchPlaceholder: 'Buscar objetos…',
      count: '{{count}} objetos',
      notFound: 'No se encontró ningún objeto para "{{id}}".',
      backToList: 'Volver a objetos',
      viewInEncyclopedia: 'Ver objeto →',
      all: 'Todos',
      section: { description: 'Descripción', properties: 'Propiedades', craft: 'Cómo fabricar', obtain: 'Cómo obtener', usedIn: 'Usado en' },
      type: 'Tipo',
      rarity: 'Rareza',
      sortId: 'ID de orden',
      rank: 'Rango',
      weight: 'Peso',
      price: 'Precio',
      stack: 'Pila máx.',
      element: 'Elemento',
      work: 'Trabajo',
      unlockItem: 'Requiere plano',
      craftedAt: 'Se fabrica en',
      handcraft: 'Se puede fabricar a mano',
      droppedBy: 'Soltado por',
      bossDrop: 'Jefe',
      fromTech: 'Desbloqueado por tecnología',
      usedInItems: 'Ingrediente de',
      usedInBuildings: 'Se usa para construir',
      food: { satiety: 'Saciedad', health: 'Salud', sanity: 'Cordura', concentration: 'Concentración' },
      equip: { attack: 'Ataque', defense: 'Defensa', hp: 'PS', shield: 'Escudo', magicAttack: 'Ataque mágico', magicDefense: 'Defensa mágica', durability: 'Durabilidad', magazine: 'Cargador' },
    },
    building: {
      id: 'ID',
      title: 'Construcciones',
      tag: 'Construcción',
      searchPlaceholder: 'Buscar construcciones…',
      count: '{{count}} construcciones',
      notFound: 'No se encontró ninguna construcción para "{{id}}".',
      backToList: 'Volver a construcciones',
      viewInEncyclopedia: 'Ver construcción →',
      all: 'Todas',
      section: { description: 'Descripción', materials: 'Materiales de construcción', crafts: 'Objetos fabricables', info: 'Propiedades' },
      type: 'Tipo',
      level: 'Nivel',
      energy: 'Energía',
      work: 'Trabajo',
      fromTech: 'Desbloqueado por tecnología',
    },
    tech: {
      title: 'Tecnología',
      level: 'Nivel {{level}}',
      boss: 'Jefe',
      cost: '{{count}} pts',
      unlockBy: 'Se desbloquea al',
      reqCapture: 'Capturar',
      reqDefeat: 'Conquistar',
      reqUnlock: 'Desbloquear',
      reqResearch: 'Investigar',
      unlocksItems: 'Objetos',
      unlocksBuildings: 'Construcciones',
      empty: 'No hay tecnologías en este nivel.',
      normalTitle: 'Tecnología',
      ancientTitle: 'Tecnología antigua',
      typeItem: 'Objeto',
      typeStructure: 'Estructura',
      searchPlaceholder: 'Buscar tecnologías…',
      count: '{{count}} tecnologías',
    },
  },
  'es-MX': {
    loading: 'Cargando…',
    item: {
      title: 'Objetos',
      tag: 'Objeto',
      searchPlaceholder: 'Buscar objetos…',
      count: '{{count}} objetos',
      notFound: 'No se encontró ningún objeto para "{{id}}".',
      backToList: 'Volver a objetos',
      viewInEncyclopedia: 'Ver objeto →',
      all: 'Todos',
      section: { description: 'Descripción', properties: 'Propiedades', craft: 'Cómo fabricar', obtain: 'Cómo obtener', usedIn: 'Usado en' },
      type: 'Tipo',
      rarity: 'Rareza',
      sortId: 'ID de orden',
      rank: 'Rango',
      weight: 'Peso',
      price: 'Precio',
      stack: 'Pila máx.',
      element: 'Elemento',
      work: 'Trabajo',
      unlockItem: 'Requiere plano',
      craftedAt: 'Se fabrica en',
      handcraft: 'Se puede fabricar a mano',
      droppedBy: 'Soltado por',
      bossDrop: 'Jefe',
      fromTech: 'Desbloqueado por tecnología',
      usedInItems: 'Ingrediente de',
      usedInBuildings: 'Se usa para construir',
      food: { satiety: 'Saciedad', health: 'Salud', sanity: 'Cordura', concentration: 'Concentración' },
      equip: { attack: 'Ataque', defense: 'Defensa', hp: 'PS', shield: 'Escudo', magicAttack: 'Ataque mágico', magicDefense: 'Defensa mágica', durability: 'Durabilidad', magazine: 'Cargador' },
    },
    building: {
      id: 'ID',
      title: 'Construcciones',
      tag: 'Construcción',
      searchPlaceholder: 'Buscar construcciones…',
      count: '{{count}} construcciones',
      notFound: 'No se encontró ninguna construcción para "{{id}}".',
      backToList: 'Volver a construcciones',
      viewInEncyclopedia: 'Ver construcción →',
      all: 'Todas',
      section: { description: 'Descripción', materials: 'Materiales de construcción', crafts: 'Objetos fabricables', info: 'Propiedades' },
      type: 'Tipo',
      level: 'Nivel',
      energy: 'Energía',
      work: 'Trabajo',
      fromTech: 'Desbloqueado por tecnología',
    },
    tech: {
      title: 'Tecnología',
      level: 'Nivel {{level}}',
      boss: 'Jefe',
      cost: '{{count}} pts',
      unlockBy: 'Se desbloquea al',
      reqCapture: 'Capturar',
      reqDefeat: 'Conquistar',
      reqUnlock: 'Desbloquear',
      reqResearch: 'Investigar',
      unlocksItems: 'Objetos',
      unlocksBuildings: 'Construcciones',
      empty: 'No hay tecnologías en este nivel.',
      normalTitle: 'Tecnología',
      ancientTitle: 'Tecnología antigua',
      typeItem: 'Objeto',
      typeStructure: 'Estructura',
      searchPlaceholder: 'Buscar tecnologías…',
      count: '{{count}} tecnologías',
    },
  },
  'fr-FR': {
    loading: 'Chargement…',
    item: {
      title: 'Objets',
      tag: 'Objet',
      searchPlaceholder: 'Rechercher des objets…',
      count: '{{count}} objets',
      notFound: 'Aucun objet trouvé pour « {{id}} ».',
      backToList: 'Retour aux objets',
      viewInEncyclopedia: "Voir l'objet →",
      all: 'Tous',
      section: { description: 'Description', properties: 'Propriétés', craft: 'Comment fabriquer', obtain: 'Comment obtenir', usedIn: 'Utilisé dans' },
      type: 'Type',
      rarity: 'Rareté',
      sortId: 'ID de tri',
      rank: 'Rang',
      weight: 'Poids',
      price: 'Prix',
      stack: 'Pile max.',
      element: 'Élément',
      work: 'Travail',
      unlockItem: 'Nécessite un plan',
      craftedAt: 'Fabriqué à',
      handcraft: 'Fabricable à la main',
      droppedBy: 'Lâché par',
      bossDrop: 'Boss',
      fromTech: 'Débloqué par technologie',
      usedInItems: 'Ingrédient de',
      usedInBuildings: 'Sert à construire',
      food: { satiety: 'Satiété', health: 'Santé', sanity: 'Santé mentale', concentration: 'Concentration' },
      equip: { attack: 'Attaque', defense: 'Défense', hp: 'PV', shield: 'Bouclier', magicAttack: 'Attaque magique', magicDefense: 'Défense magique', durability: 'Durabilité', magazine: 'Chargeur' },
    },
    building: {
      id: 'ID',
      title: 'Bâtiments',
      tag: 'Bâtiment',
      searchPlaceholder: 'Rechercher des bâtiments…',
      count: '{{count}} bâtiments',
      notFound: 'Aucun bâtiment trouvé pour « {{id}} ».',
      backToList: 'Retour aux bâtiments',
      viewInEncyclopedia: 'Voir le bâtiment →',
      all: 'Tous',
      section: { description: 'Description', materials: 'Matériaux de construction', crafts: 'Objets fabricables', info: 'Propriétés' },
      type: 'Type',
      level: 'Niveau',
      energy: 'Énergie',
      work: 'Travail',
      fromTech: 'Débloqué par technologie',
    },
    tech: {
      title: 'Technologie',
      level: 'Niveau {{level}}',
      boss: 'Boss',
      cost: '{{count}} pts',
      unlockBy: 'Débloqué par',
      reqCapture: 'Capturer',
      reqDefeat: 'Conquérir',
      reqUnlock: 'Débloquer',
      reqResearch: 'Rechercher',
      unlocksItems: 'Objets',
      unlocksBuildings: 'Bâtiments',
      empty: 'Aucune technologie à ce niveau.',
      normalTitle: 'Technologie',
      ancientTitle: 'Technologie ancienne',
      typeItem: 'Objet',
      typeStructure: 'Structure',
      searchPlaceholder: 'Rechercher des technologies…',
      count: '{{count}} technologies',
    },
  },
  'id-ID': {
    loading: 'Memuat…',
    item: {
      title: 'Item',
      tag: 'Item',
      searchPlaceholder: 'Cari item…',
      count: '{{count}} item',
      notFound: 'Tidak ada item untuk "{{id}}".',
      backToList: 'Kembali ke Item',
      viewInEncyclopedia: 'Lihat item →',
      all: 'Semua',
      section: { description: 'Deskripsi', properties: 'Properti', craft: 'Cara membuat', obtain: 'Cara mendapatkan', usedIn: 'Digunakan dalam' },
      type: 'Tipe',
      rarity: 'Kelangkaan',
      sortId: 'ID urutan',
      rank: 'Peringkat',
      weight: 'Berat',
      price: 'Harga',
      stack: 'Tumpukan maks.',
      element: 'Elemen',
      work: 'Kerja',
      unlockItem: 'Membutuhkan blueprint',
      craftedAt: 'Dibuat di',
      handcraft: 'Bisa dibuat dengan tangan',
      droppedBy: 'Dijatuhkan oleh',
      bossDrop: 'Bos',
      fromTech: 'Dibuka oleh teknologi',
      usedInItems: 'Bahan untuk',
      usedInBuildings: 'Untuk membangun',
      food: { satiety: 'Kekenyangan', health: 'Kesehatan', sanity: 'Kewarasan', concentration: 'Konsentrasi' },
      equip: { attack: 'Serangan', defense: 'Pertahanan', hp: 'HP', shield: 'Perisai', magicAttack: 'Serangan Sihir', magicDefense: 'Pertahanan Sihir', durability: 'Daya Tahan', magazine: 'Magasin' },
    },
    building: {
      id: 'ID',
      title: 'Bangunan',
      tag: 'Bangunan',
      searchPlaceholder: 'Cari bangunan…',
      count: '{{count}} bangunan',
      notFound: 'Tidak ada bangunan untuk "{{id}}".',
      backToList: 'Kembali ke Bangunan',
      viewInEncyclopedia: 'Lihat bangunan →',
      all: 'Semua',
      section: { description: 'Deskripsi', materials: 'Bahan bangunan', crafts: 'Item yang dapat dibuat', info: 'Properti' },
      type: 'Tipe',
      level: 'Level',
      energy: 'Energi',
      work: 'Kerja',
      fromTech: 'Dibuka oleh teknologi',
    },
    tech: {
      title: 'Teknologi',
      level: 'Level {{level}}',
      boss: 'Bos',
      cost: '{{count}} poin',
      unlockBy: 'Dibuka dengan',
      reqCapture: 'Tangkap',
      reqDefeat: 'Taklukkan',
      reqUnlock: 'Buka',
      reqResearch: 'Teliti',
      unlocksItems: 'Item',
      unlocksBuildings: 'Bangunan',
      empty: 'Tidak ada teknologi di level ini.',
      normalTitle: 'Teknologi',
      ancientTitle: 'Teknologi Kuno',
      typeItem: 'Item',
      typeStructure: 'Struktur',
      searchPlaceholder: 'Cari teknologi…',
      count: '{{count}} teknologi',
    },
  },
  'it-IT': {
    loading: 'Caricamento…',
    item: {
      title: 'Oggetti',
      tag: 'Oggetto',
      searchPlaceholder: 'Cerca oggetti…',
      count: '{{count}} oggetti',
      notFound: 'Nessun oggetto trovato per "{{id}}".',
      backToList: 'Torna agli oggetti',
      viewInEncyclopedia: "Vedi l'oggetto →",
      all: 'Tutti',
      section: { description: 'Descrizione', properties: 'Proprietà', craft: 'Come fabbricare', obtain: 'Come ottenere', usedIn: 'Usato in' },
      type: 'Tipo',
      rarity: 'Rarità',
      sortId: 'ID ordine',
      rank: 'Grado',
      weight: 'Peso',
      price: 'Prezzo',
      stack: 'Pila max',
      element: 'Elemento',
      work: 'Lavoro',
      unlockItem: 'Richiede progetto',
      craftedAt: 'Fabbricato in',
      handcraft: 'Fabbricabile a mano',
      droppedBy: 'Rilasciato da',
      bossDrop: 'Boss',
      fromTech: 'Sbloccato dalla tecnologia',
      usedInItems: 'Ingrediente di',
      usedInBuildings: 'Usato per costruire',
      food: { satiety: 'Sazietà', health: 'Salute', sanity: 'Sanità mentale', concentration: 'Concentrazione' },
      equip: { attack: 'Attacco', defense: 'Difesa', hp: 'PS', shield: 'Scudo', magicAttack: 'Attacco magico', magicDefense: 'Difesa magica', durability: 'Durabilità', magazine: 'Caricatore' },
    },
    building: {
      id: 'ID',
      title: 'Costruzioni',
      tag: 'Costruzione',
      searchPlaceholder: 'Cerca costruzioni…',
      count: '{{count}} costruzioni',
      notFound: 'Nessuna costruzione trovata per "{{id}}".',
      backToList: 'Torna alle costruzioni',
      viewInEncyclopedia: 'Vedi la costruzione →',
      all: 'Tutte',
      section: { description: 'Descrizione', materials: 'Materiali di costruzione', crafts: 'Oggetti fabbricabili', info: 'Proprietà' },
      type: 'Tipo',
      level: 'Livello',
      energy: 'Energia',
      work: 'Lavoro',
      fromTech: 'Sbloccato dalla tecnologia',
    },
    tech: {
      title: 'Tecnologia',
      level: 'Livello {{level}}',
      boss: 'Boss',
      cost: '{{count}} pt',
      unlockBy: 'Sbloccato con',
      reqCapture: 'Cattura',
      reqDefeat: 'Conquista',
      reqUnlock: 'Sblocca',
      reqResearch: 'Ricerca',
      unlocksItems: 'Oggetti',
      unlocksBuildings: 'Costruzioni',
      empty: 'Nessuna tecnologia a questo livello.',
      normalTitle: 'Tecnologia',
      ancientTitle: 'Tecnologia antica',
      typeItem: 'Oggetto',
      typeStructure: 'Struttura',
      searchPlaceholder: 'Cerca tecnologie…',
      count: '{{count}} tecnologie',
    },
  },
  'ja-JP': {
    loading: '読み込み中…',
    item: {
      title: 'アイテム',
      tag: 'アイテム',
      searchPlaceholder: 'アイテムを検索…',
      count: '{{count}} 個',
      notFound: '「{{id}}」のアイテムが見つかりません。',
      backToList: 'アイテム一覧に戻る',
      viewInEncyclopedia: 'アイテムを見る →',
      all: 'すべて',
      section: { description: '説明', properties: '基本情報', craft: '作成方法', obtain: '入手方法', usedIn: '使用先' },
      type: '種類',
      rarity: 'レア度',
      sortId: '並び順ID',
      rank: 'ランク',
      weight: '重量',
      price: '価格',
      stack: '最大スタック',
      element: '属性',
      work: '作業',
      unlockItem: '設計図が必要',
      craftedAt: '製作施設',
      handcraft: '手作業で作成可能',
      droppedBy: 'ドロップ元',
      bossDrop: 'ボス',
      fromTech: 'テクノロジーで解放',
      usedInItems: '材料になるレシピ',
      usedInBuildings: '建築に使用',
      food: { satiety: '満腹度', health: 'HP', sanity: 'SAN値', concentration: '集中力' },
      equip: { attack: '攻撃', defense: '防御', hp: 'HP', shield: 'シールド', magicAttack: '魔法攻撃', magicDefense: '魔法防御', durability: '耐久度', magazine: '装弾数' },
    },
    building: {
      id: 'ID',
      title: '建築物',
      tag: '建築物',
      searchPlaceholder: '建築物を検索…',
      count: '{{count}} 個',
      notFound: '「{{id}}」の建築物が見つかりません。',
      backToList: '建築物一覧に戻る',
      viewInEncyclopedia: '建築物を見る →',
      all: 'すべて',
      section: { description: '説明', materials: '建築素材', crafts: '作成できるアイテム', info: '基本情報' },
      type: '種類',
      level: 'レベル',
      energy: 'エネルギー',
      work: '作業',
      fromTech: 'テクノロジーで解放',
    },
    tech: {
      title: 'テクノロジー',
      level: 'レベル {{level}}',
      boss: 'ボス',
      cost: '{{count}} pt',
      unlockBy: '解放条件',
      reqCapture: '捕獲',
      reqDefeat: '攻略',
      reqUnlock: '解放',
      reqResearch: '研究',
      unlocksItems: 'アイテム',
      unlocksBuildings: '建築物',
      empty: 'このレベルのテクノロジーはありません。',
      normalTitle: 'テクノロジー',
      ancientTitle: '古代テクノロジー',
      typeItem: 'アイテム',
      typeStructure: '建築',
      searchPlaceholder: 'テクノロジーを検索…',
      count: '{{count}}件のテクノロジー',
    },
  },
  'ko-KR': {
    loading: '불러오는 중…',
    item: {
      title: '아이템',
      tag: '아이템',
      searchPlaceholder: '아이템 검색…',
      count: '{{count}}개',
      notFound: '"{{id}}"에 해당하는 아이템을 찾을 수 없습니다.',
      backToList: '아이템 목록으로',
      viewInEncyclopedia: '아이템 보기 →',
      all: '전체',
      section: { description: '설명', properties: '속성', craft: '제작 방법', obtain: '획득 방법', usedIn: '사용처' },
      type: '종류',
      rarity: '희귀도',
      sortId: '정렬 ID',
      rank: '랭크',
      weight: '무게',
      price: '가격',
      stack: '최대 중첩',
      element: '속성',
      work: '작업',
      unlockItem: '설계도 필요',
      craftedAt: '제작 시설',
      handcraft: '수작업 제작 가능',
      droppedBy: '드롭 대상',
      bossDrop: '보스',
      fromTech: '기술로 해금',
      usedInItems: '재료로 쓰이는 레시피',
      usedInBuildings: '건축에 사용',
      food: { satiety: '포만감', health: 'HP', sanity: 'SAN', concentration: '집중력' },
      equip: { attack: '공격', defense: '방어', hp: 'HP', shield: '실드', magicAttack: '마법 공격', magicDefense: '마법 방어', durability: '내구도', magazine: '탄창' },
    },
    building: {
      id: 'ID',
      title: '건축물',
      tag: '건축물',
      searchPlaceholder: '건축물 검색…',
      count: '{{count}}개',
      notFound: '"{{id}}"에 해당하는 건축물을 찾을 수 없습니다.',
      backToList: '건축물 목록으로',
      viewInEncyclopedia: '건축물 보기 →',
      all: '전체',
      section: { description: '설명', materials: '건축 재료', crafts: '제작 가능한 아이템', info: '속성' },
      type: '종류',
      level: '레벨',
      energy: '에너지',
      work: '작업',
      fromTech: '기술로 해금',
    },
    tech: {
      title: '기술',
      level: '레벨 {{level}}',
      boss: '보스',
      cost: '{{count}} pt',
      unlockBy: '해금 조건',
      reqCapture: '포획',
      reqDefeat: '공략',
      reqUnlock: '해금',
      reqResearch: '연구',
      unlocksItems: '아이템',
      unlocksBuildings: '건축물',
      empty: '이 레벨의 기술이 없습니다.',
      normalTitle: '기술',
      ancientTitle: '고대 기술',
      typeItem: '아이템',
      typeStructure: '건축',
      searchPlaceholder: '기술 검색…',
      count: '기술 {{count}}개',
    },
  },
  'pl-PL': {
    loading: 'Wczytywanie…',
    item: {
      title: 'Przedmioty',
      tag: 'Przedmiot',
      searchPlaceholder: 'Szukaj przedmiotów…',
      count: 'Przedmioty: {{count}}',
      notFound: 'Nie znaleziono przedmiotu dla „{{id}}".',
      backToList: 'Powrót do przedmiotów',
      viewInEncyclopedia: 'Zobacz przedmiot →',
      all: 'Wszystkie',
      section: { description: 'Opis', properties: 'Właściwości', craft: 'Jak wytworzyć', obtain: 'Jak zdobyć', usedIn: 'Używany w' },
      type: 'Typ',
      rarity: 'Rzadkość',
      sortId: 'ID sortowania',
      rank: 'Ranga',
      weight: 'Waga',
      price: 'Cena',
      stack: 'Maks. stos',
      element: 'Żywioł',
      work: 'Praca',
      unlockItem: 'Wymaga schematu',
      craftedAt: 'Wytwarzane w',
      handcraft: 'Można wytworzyć ręcznie',
      droppedBy: 'Upuszczany przez',
      bossDrop: 'Boss',
      fromTech: 'Odblokowany przez technologię',
      usedInItems: 'Składnik w',
      usedInBuildings: 'Używany do budowy',
      food: { satiety: 'Sytość', health: 'Zdrowie', sanity: 'Poczytalność', concentration: 'Koncentracja' },
      equip: { attack: 'Atak', defense: 'Obrona', hp: 'PŻ', shield: 'Tarcza', magicAttack: 'Atak magiczny', magicDefense: 'Obrona magiczna', durability: 'Wytrzymałość', magazine: 'Magazynek' },
    },
    building: {
      id: 'ID',
      title: 'Budynki',
      tag: 'Budynek',
      searchPlaceholder: 'Szukaj budynków…',
      count: 'Budynki: {{count}}',
      notFound: 'Nie znaleziono budynku dla „{{id}}".',
      backToList: 'Powrót do budynków',
      viewInEncyclopedia: 'Zobacz budynek →',
      all: 'Wszystkie',
      section: { description: 'Opis', materials: 'Materiały budowlane', crafts: 'Przedmioty do wytworzenia', info: 'Właściwości' },
      type: 'Typ',
      level: 'Poziom',
      energy: 'Energia',
      work: 'Praca',
      fromTech: 'Odblokowany przez technologię',
    },
    tech: {
      title: 'Technologia',
      level: 'Poziom {{level}}',
      boss: 'Boss',
      cost: '{{count}} pkt',
      unlockBy: 'Odblokowywane przez',
      reqCapture: 'Złap',
      reqDefeat: 'Zdobądź',
      reqUnlock: 'Odblokuj',
      reqResearch: 'Zbadaj',
      unlocksItems: 'Przedmioty',
      unlocksBuildings: 'Budynki',
      empty: 'Brak technologii na tym poziomie.',
      normalTitle: 'Technologia',
      ancientTitle: 'Starożytna technologia',
      typeItem: 'Przedmiot',
      typeStructure: 'Konstrukcja',
      searchPlaceholder: 'Szukaj technologii…',
      count: 'Technologie: {{count}}',
    },
  },
  'pt-BR': {
    loading: 'Carregando…',
    item: {
      title: 'Itens',
      tag: 'Item',
      searchPlaceholder: 'Buscar itens…',
      count: '{{count}} itens',
      notFound: 'Nenhum item encontrado para "{{id}}".',
      backToList: 'Voltar aos itens',
      viewInEncyclopedia: 'Ver item →',
      all: 'Todos',
      section: { description: 'Descrição', properties: 'Propriedades', craft: 'Como fabricar', obtain: 'Como obter', usedIn: 'Usado em' },
      type: 'Tipo',
      rarity: 'Raridade',
      sortId: 'ID de ordenação',
      rank: 'Classe',
      weight: 'Peso',
      price: 'Preço',
      stack: 'Pilha máx.',
      element: 'Elemento',
      work: 'Trabalho',
      unlockItem: 'Requer projeto',
      craftedAt: 'Fabricado em',
      handcraft: 'Pode ser fabricado à mão',
      droppedBy: 'Solto por',
      bossDrop: 'Chefe',
      fromTech: 'Desbloqueado por tecnologia',
      usedInItems: 'Ingrediente de',
      usedInBuildings: 'Usado para construir',
      food: { satiety: 'Saciedade', health: 'Saúde', sanity: 'Sanidade', concentration: 'Concentração' },
      equip: { attack: 'Ataque', defense: 'Defesa', hp: 'PV', shield: 'Escudo', magicAttack: 'Ataque mágico', magicDefense: 'Defesa mágica', durability: 'Durabilidade', magazine: 'Carregador' },
    },
    building: {
      id: 'ID',
      title: 'Construções',
      tag: 'Construção',
      searchPlaceholder: 'Buscar construções…',
      count: '{{count}} construções',
      notFound: 'Nenhuma construção encontrada para "{{id}}".',
      backToList: 'Voltar às construções',
      viewInEncyclopedia: 'Ver construção →',
      all: 'Todas',
      section: { description: 'Descrição', materials: 'Materiais de construção', crafts: 'Itens fabricáveis', info: 'Propriedades' },
      type: 'Tipo',
      level: 'Nível',
      energy: 'Energia',
      work: 'Trabalho',
      fromTech: 'Desbloqueado por tecnologia',
    },
    tech: {
      title: 'Tecnologia',
      level: 'Nível {{level}}',
      boss: 'Chefe',
      cost: '{{count}} pts',
      unlockBy: 'Desbloqueado por',
      reqCapture: 'Capturar',
      reqDefeat: 'Conquistar',
      reqUnlock: 'Desbloquear',
      reqResearch: 'Pesquisar',
      unlocksItems: 'Itens',
      unlocksBuildings: 'Construções',
      empty: 'Nenhuma tecnologia neste nível.',
      normalTitle: 'Tecnologia',
      ancientTitle: 'Tecnologia antiga',
      typeItem: 'Item',
      typeStructure: 'Estrutura',
      searchPlaceholder: 'Buscar tecnologias…',
      count: '{{count}} tecnologias',
    },
  },
  'ru-RU': {
    loading: 'Загрузка…',
    item: {
      title: 'Предметы',
      tag: 'Предмет',
      searchPlaceholder: 'Поиск предметов…',
      count: 'Предметов: {{count}}',
      notFound: 'Предмет по запросу «{{id}}» не найден.',
      backToList: 'Назад к предметам',
      viewInEncyclopedia: 'Открыть предмет →',
      all: 'Все',
      section: { description: 'Описание', properties: 'Свойства', craft: 'Как создать', obtain: 'Как получить', usedIn: 'Используется в' },
      type: 'Тип',
      rarity: 'Редкость',
      sortId: 'ID сортировки',
      rank: 'Ранг',
      weight: 'Вес',
      price: 'Цена',
      stack: 'Макс. стопка',
      element: 'Стихия',
      work: 'Работа',
      unlockItem: 'Требуется чертёж',
      craftedAt: 'Изготавливается в',
      handcraft: 'Можно создать вручную',
      droppedBy: 'Выпадает с',
      bossDrop: 'Босс',
      fromTech: 'Открывается технологией',
      usedInItems: 'Ингредиент для',
      usedInBuildings: 'Используется для постройки',
      food: { satiety: 'Сытость', health: 'Здоровье', sanity: 'Рассудок', concentration: 'Концентрация' },
      equip: { attack: 'Атака', defense: 'Защита', hp: 'ОЗ', shield: 'Щит', magicAttack: 'Магическая атака', magicDefense: 'Магическая защита', durability: 'Прочность', magazine: 'Магазин' },
    },
    building: {
      id: 'ID',
      title: 'Постройки',
      tag: 'Постройка',
      searchPlaceholder: 'Поиск построек…',
      count: 'Построек: {{count}}',
      notFound: 'Постройка по запросу «{{id}}» не найдена.',
      backToList: 'Назад к постройкам',
      viewInEncyclopedia: 'Открыть постройку →',
      all: 'Все',
      section: { description: 'Описание', materials: 'Материалы для постройки', crafts: 'Создаваемые предметы', info: 'Свойства' },
      type: 'Тип',
      level: 'Уровень',
      energy: 'Энергия',
      work: 'Работа',
      fromTech: 'Открывается технологией',
    },
    tech: {
      title: 'Технологии',
      level: 'Уровень {{level}}',
      boss: 'Босс',
      cost: '{{count}} очк.',
      unlockBy: 'Условие разблокировки',
      reqCapture: 'Поймать',
      reqDefeat: 'Пройти',
      reqUnlock: 'Разблокировать',
      reqResearch: 'Исследовать',
      unlocksItems: 'Предметы',
      unlocksBuildings: 'Постройки',
      empty: 'На этом уровне нет технологий.',
      normalTitle: 'Технологии',
      ancientTitle: 'Древние технологии',
      typeItem: 'Предмет',
      typeStructure: 'Постройка',
      searchPlaceholder: 'Поиск технологий…',
      count: 'Технологий: {{count}}',
    },
  },
  'th-TH': {
    loading: 'กำลังโหลด…',
    item: {
      title: 'ไอเทม',
      tag: 'ไอเทม',
      searchPlaceholder: 'ค้นหาไอเทม…',
      count: '{{count}} รายการ',
      notFound: 'ไม่พบไอเทมสำหรับ "{{id}}"',
      backToList: 'กลับไปที่ไอเทม',
      viewInEncyclopedia: 'ดูไอเทม →',
      all: 'ทั้งหมด',
      section: { description: 'คำอธิบาย', properties: 'คุณสมบัติ', craft: 'วิธีสร้าง', obtain: 'วิธีได้รับ', usedIn: 'ใช้ใน' },
      type: 'ประเภท',
      rarity: 'ความหายาก',
      sortId: 'ลำดับการจัดเรียง',
      rank: 'ระดับ',
      weight: 'น้ำหนัก',
      price: 'ราคา',
      stack: 'สแตกสูงสุด',
      element: 'ธาตุ',
      work: 'งาน',
      unlockItem: 'ต้องมีพิมพ์เขียว',
      craftedAt: 'ผลิตที่',
      handcraft: 'สร้างด้วยมือได้',
      droppedBy: 'ดรอปจาก',
      bossDrop: 'บอส',
      fromTech: 'ปลดล็อกด้วยเทคโนโลยี',
      usedInItems: 'ส่วนผสมของ',
      usedInBuildings: 'ใช้ก่อสร้าง',
      food: { satiety: 'ความอิ่ม', health: 'พลังชีวิต', sanity: 'สติ', concentration: 'สมาธิ' },
      equip: { attack: 'โจมตี', defense: 'ป้องกัน', hp: 'HP', shield: 'โล่', magicAttack: 'โจมตีเวท', magicDefense: 'ป้องกันเวท', durability: 'ความทนทาน', magazine: 'แม็กกาซีน' },
    },
    building: {
      id: 'ID',
      title: 'สิ่งก่อสร้าง',
      tag: 'สิ่งก่อสร้าง',
      searchPlaceholder: 'ค้นหาสิ่งก่อสร้าง…',
      count: '{{count}} รายการ',
      notFound: 'ไม่พบสิ่งก่อสร้างสำหรับ "{{id}}"',
      backToList: 'กลับไปที่สิ่งก่อสร้าง',
      viewInEncyclopedia: 'ดูสิ่งก่อสร้าง →',
      all: 'ทั้งหมด',
      section: { description: 'คำอธิบาย', materials: 'วัสดุก่อสร้าง', crafts: 'ไอเทมที่สร้างได้', info: 'คุณสมบัติ' },
      type: 'ประเภท',
      level: 'เลเวล',
      energy: 'พลังงาน',
      work: 'งาน',
      fromTech: 'ปลดล็อกด้วยเทคโนโลยี',
    },
    tech: {
      title: 'เทคโนโลยี',
      level: 'เลเวล {{level}}',
      boss: 'บอส',
      cost: '{{count}} แต้ม',
      unlockBy: 'ปลดล็อกโดย',
      reqCapture: 'จับ',
      reqDefeat: 'พิชิต',
      reqUnlock: 'ปลดล็อก',
      reqResearch: 'วิจัย',
      unlocksItems: 'ไอเทม',
      unlocksBuildings: 'สิ่งก่อสร้าง',
      empty: 'ไม่มีเทคโนโลยีในเลเวลนี้',
      normalTitle: 'เทคโนโลยี',
      ancientTitle: 'เทคโนโลยีโบราณ',
      typeItem: 'ไอเทม',
      typeStructure: 'สิ่งก่อสร้าง',
      searchPlaceholder: 'ค้นหาเทคโนโลยี…',
      count: 'เทคโนโลยี {{count}} รายการ',
    },
  },
  'tr-TR': {
    loading: 'Yükleniyor…',
    item: {
      title: 'Eşyalar',
      tag: 'Eşya',
      searchPlaceholder: 'Eşya ara…',
      count: '{{count}} eşya',
      notFound: '"{{id}}" için eşya bulunamadı.',
      backToList: 'Eşyalara dön',
      viewInEncyclopedia: 'Eşyayı görüntüle →',
      all: 'Tümü',
      section: { description: 'Açıklama', properties: 'Özellikler', craft: 'Nasıl üretilir', obtain: 'Nasıl elde edilir', usedIn: 'Kullanıldığı yer' },
      type: 'Tür',
      rarity: 'Nadirlik',
      sortId: 'Sıralama kimliği',
      rank: 'Rütbe',
      weight: 'Ağırlık',
      price: 'Fiyat',
      stack: 'Maks. yığın',
      element: 'Element',
      work: 'İş',
      unlockItem: 'Şablon gerekir',
      craftedAt: 'Şurada üretilir',
      handcraft: 'Elle üretilebilir',
      droppedBy: 'Düşüren',
      bossDrop: 'Boss',
      fromTech: 'Teknolojiyle açılır',
      usedInItems: 'Şu tarifin malzemesi',
      usedInBuildings: 'İnşaatta kullanılır',
      food: { satiety: 'Tokluk', health: 'Sağlık', sanity: 'Akıl sağlığı', concentration: 'Konsantrasyon' },
      equip: { attack: 'Saldırı', defense: 'Savunma', hp: 'CP', shield: 'Kalkan', magicAttack: 'Büyü Saldırısı', magicDefense: 'Büyü Savunması', durability: 'Dayanıklılık', magazine: 'Şarjör' },
    },
    building: {
      id: 'ID',
      title: 'Yapılar',
      tag: 'Yapı',
      searchPlaceholder: 'Yapı ara…',
      count: '{{count}} yapı',
      notFound: '"{{id}}" için yapı bulunamadı.',
      backToList: 'Yapılara dön',
      viewInEncyclopedia: 'Yapıyı görüntüle →',
      all: 'Tümü',
      section: { description: 'Açıklama', materials: 'İnşaat malzemeleri', crafts: 'Üretilebilir eşyalar', info: 'Özellikler' },
      type: 'Tür',
      level: 'Seviye',
      energy: 'Enerji',
      work: 'İş',
      fromTech: 'Teknolojiyle açılır',
    },
    tech: {
      title: 'Teknoloji',
      level: 'Seviye {{level}}',
      boss: 'Boss',
      cost: '{{count}} puan',
      unlockBy: 'Kilit açma koşulu',
      reqCapture: 'Yakala',
      reqDefeat: 'Fethet',
      reqUnlock: 'Kilidini aç',
      reqResearch: 'Araştır',
      unlocksItems: 'Eşyalar',
      unlocksBuildings: 'Yapılar',
      empty: 'Bu seviyede teknoloji yok.',
      normalTitle: 'Teknoloji',
      ancientTitle: 'Antik Teknoloji',
      typeItem: 'Eşya',
      typeStructure: 'Yapı',
      searchPlaceholder: 'Teknoloji ara…',
      count: '{{count}} teknoloji',
    },
  },
  'vi-VN': {
    loading: 'Đang tải…',
    item: {
      title: 'Vật phẩm',
      tag: 'Vật phẩm',
      searchPlaceholder: 'Tìm vật phẩm…',
      count: '{{count}} vật phẩm',
      notFound: 'Không tìm thấy vật phẩm cho "{{id}}".',
      backToList: 'Quay lại vật phẩm',
      viewInEncyclopedia: 'Xem vật phẩm →',
      all: 'Tất cả',
      section: { description: 'Mô tả', properties: 'Thuộc tính', craft: 'Cách chế tạo', obtain: 'Cách nhận', usedIn: 'Dùng trong' },
      type: 'Loại',
      rarity: 'Độ hiếm',
      sortId: 'ID sắp xếp',
      rank: 'Bậc',
      weight: 'Trọng lượng',
      price: 'Giá',
      stack: 'Xếp chồng tối đa',
      element: 'Hệ',
      work: 'Công việc',
      unlockItem: 'Cần bản thiết kế',
      craftedAt: 'Chế tạo tại',
      handcraft: 'Có thể chế tạo thủ công',
      droppedBy: 'Rơi từ',
      bossDrop: 'Boss',
      fromTech: 'Mở khóa bằng công nghệ',
      usedInItems: 'Nguyên liệu của',
      usedInBuildings: 'Dùng để xây',
      food: { satiety: 'Độ no', health: 'Sức khỏe', sanity: 'Tinh thần', concentration: 'Tập trung' },
      equip: { attack: 'Tấn công', defense: 'Phòng thủ', hp: 'HP', shield: 'Khiên', magicAttack: 'Tấn công phép', magicDefense: 'Phòng thủ phép', durability: 'Độ bền', magazine: 'Băng đạn' },
    },
    building: {
      id: 'ID',
      title: 'Công trình',
      tag: 'Công trình',
      searchPlaceholder: 'Tìm công trình…',
      count: '{{count}} công trình',
      notFound: 'Không tìm thấy công trình cho "{{id}}".',
      backToList: 'Quay lại công trình',
      viewInEncyclopedia: 'Xem công trình →',
      all: 'Tất cả',
      section: { description: 'Mô tả', materials: 'Vật liệu xây dựng', crafts: 'Vật phẩm có thể chế tạo', info: 'Thuộc tính' },
      type: 'Loại',
      level: 'Cấp',
      energy: 'Năng lượng',
      work: 'Công việc',
      fromTech: 'Mở khóa bằng công nghệ',
    },
    tech: {
      title: 'Công nghệ',
      level: 'Cấp {{level}}',
      boss: 'Trùm',
      cost: '{{count}} điểm',
      unlockBy: 'Mở khóa bằng',
      reqCapture: 'Bắt',
      reqDefeat: 'Chinh phục',
      reqUnlock: 'Mở khóa',
      reqResearch: 'Nghiên cứu',
      unlocksItems: 'Vật phẩm',
      unlocksBuildings: 'Công trình',
      empty: 'Không có công nghệ ở cấp này.',
      normalTitle: 'Công nghệ',
      ancientTitle: 'Công nghệ cổ đại',
      typeItem: 'Vật phẩm',
      typeStructure: 'Công trình',
      searchPlaceholder: 'Tìm công nghệ…',
      count: '{{count}} công nghệ',
    },
  },
  'zh-CN': {
    loading: '加载中…',
    item: {
      title: '道具',
      tag: '道具',
      searchPlaceholder: '搜索道具…',
      count: '{{count}} 个道具',
      notFound: '未找到道具「{{id}}」。',
      backToList: '返回道具列表',
      viewInEncyclopedia: '查看道具 →',
      all: '全部',
      section: { description: '描述', properties: '属性', craft: '制作方法', obtain: '获取方式', usedIn: '用途' },
      type: '类型',
      rarity: '稀有度',
      sortId: '排序 ID',
      rank: '等级',
      weight: '重量',
      price: '价格',
      stack: '最大堆叠',
      element: '属性',
      work: '工作',
      unlockItem: '需要图纸',
      craftedAt: '制作设施',
      handcraft: '可手工制作',
      droppedBy: '掉落来源',
      bossDrop: 'BOSS',
      fromTech: '通过科技解锁',
      usedInItems: '用作材料',
      usedInBuildings: '用于建造',
      food: { satiety: '饱腹度', health: '生命值', sanity: '理智', concentration: '专注度' },
      equip: { attack: '攻击', defense: '防御', hp: '生命值', shield: '护盾', magicAttack: '魔法攻击', magicDefense: '魔法防御', durability: '耐久度', magazine: '弹匣' },
    },
    building: {
      id: 'ID',
      title: '建筑',
      tag: '建筑',
      searchPlaceholder: '搜索建筑…',
      count: '{{count}} 个建筑',
      notFound: '未找到建筑「{{id}}」。',
      backToList: '返回建筑列表',
      viewInEncyclopedia: '查看建筑 →',
      all: '全部',
      section: { description: '描述', materials: '建造材料', crafts: '可制作物品', info: '属性' },
      type: '类型',
      level: '等级',
      energy: '能源',
      work: '工作',
      fromTech: '通过科技解锁',
    },
    tech: {
      title: '科技',
      level: '{{level}} 级',
      boss: 'Boss',
      cost: '{{count}} 点',
      unlockBy: '解锁条件',
      reqCapture: '捕获',
      reqDefeat: '攻克',
      reqUnlock: '解锁',
      reqResearch: '研究',
      unlocksItems: '道具',
      unlocksBuildings: '建筑',
      empty: '该等级没有科技。',
      normalTitle: '科技',
      ancientTitle: '古代科技',
      typeItem: '道具',
      typeStructure: '建筑',
      searchPlaceholder: '通过名字搜索',
      count: '{{count}} 项科技',
    },
  },
  'zh-TW': {
    loading: '載入中…',
    item: {
      title: '道具',
      tag: '道具',
      searchPlaceholder: '搜尋道具…',
      count: '{{count}} 個道具',
      notFound: '未找到道具「{{id}}」。',
      backToList: '返回道具列表',
      viewInEncyclopedia: '查看道具 →',
      all: '全部',
      section: { description: '描述', properties: '屬性', craft: '製作方法', obtain: '取得方式', usedIn: '用途' },
      type: '類型',
      rarity: '稀有度',
      sortId: '排序 ID',
      rank: '等級',
      weight: '重量',
      price: '價格',
      stack: '最大堆疊',
      element: '屬性',
      work: '工作',
      unlockItem: '需要圖紙',
      craftedAt: '製作設施',
      handcraft: '可手工製作',
      droppedBy: '掉落來源',
      bossDrop: 'BOSS',
      fromTech: '透過科技解鎖',
      usedInItems: '用作材料',
      usedInBuildings: '用於建造',
      food: { satiety: '飽腹度', health: '生命值', sanity: '理智', concentration: '專注度' },
      equip: { attack: '攻擊', defense: '防禦', hp: '生命值', shield: '護盾', magicAttack: '魔法攻擊', magicDefense: '魔法防禦', durability: '耐久度', magazine: '彈匣' },
    },
    building: {
      id: 'ID',
      title: '建築',
      tag: '建築',
      searchPlaceholder: '搜尋建築…',
      count: '{{count}} 個建築',
      notFound: '未找到建築「{{id}}」。',
      backToList: '返回建築列表',
      viewInEncyclopedia: '查看建築 →',
      all: '全部',
      section: { description: '描述', materials: '建造材料', crafts: '可製作物品', info: '屬性' },
      type: '類型',
      level: '等級',
      energy: '能源',
      work: '工作',
      fromTech: '透過科技解鎖',
    },
    tech: {
      title: '科技',
      level: '{{level}} 級',
      boss: 'Boss',
      cost: '{{count}} 點',
      unlockBy: '解鎖條件',
      reqCapture: '捕獲',
      reqDefeat: '攻克',
      reqUnlock: '解鎖',
      reqResearch: '研究',
      unlocksItems: '道具',
      unlocksBuildings: '建築',
      empty: '該等級沒有科技。',
      normalTitle: '科技',
      ancientTitle: '古代科技',
      typeItem: '道具',
      typeStructure: '建築',
      searchPlaceholder: '透過名稱搜尋',
      count: '{{count}} 項科技',
    },
  },
}

// English-only category labels for the item TypeA and building TypeA enums.
// Game L10N doesn't cleanly cover these enum values; fallback is the raw enum
// string (stripped of any `EPal…::` prefix by the caller).
export const ITEM_TYPE_LABELS: Record<string, string> = {
  Blueprint: 'Blueprint',
  Essential: 'Essential',
  Consume: 'Consumable',
  Material: 'Material',
  Weapon: 'Weapon',
  Armor: 'Armor',
  Food: 'Food',
  Accessory: 'Accessory',
  Ammo: 'Ammo',
  SpecialWeapon: 'Special Weapon',
  CaptureItemModifier: 'Sphere Module',
  Glider: 'Glider',
  Money: 'Money',
  MonsterEquipWeapon: 'Pal Gear',
  Ingredient: 'Ingredient',
  Seed: 'Seed',
  Blood: 'Blood',
  PalEgg: 'Pal Egg',
  Sphere: 'Pal Sphere',
  Medicine: 'Medicine',
}

export const BUILDING_TYPE_LABELS: Record<string, string> = {
  Furniture: 'Furniture',
  Foundation: 'Foundation',
  Product: 'Production',
  Storage: 'Storage',
  Infrastructure: 'Infrastructure',
  Pal: 'Pal',
  Light: 'Lighting',
  Defense: 'Defense',
  Other: 'Other',
  Food: 'Food',
  Medical: 'Medical',
  Dimension: 'Dimension',
  Amenity: 'Amenity',
  Environment: 'Environment',
}
