import type { Language } from './i18n'

// Dungeon loot page UI chrome, merged into the `translation` namespace under
// the `dungeon` key (see i18n.ts). Dungeon / item / pal names come from the
// locale data files; this table only holds the page's own labels.
export interface DungeonStrings {
  title: string
  /** "EXP bonus ×{{rate}}" badge on each dungeon card. */
  expBonus: string
  boss: string
  /** Alpha mini-boss pool encountered midway through a run. */
  midBoss: string
  enemies: string
  /** Multi-floor dungeon spawn pool: "Floor {{n}}". */
  floor: string
  /** Interior fishing-spot pal pool. */
  fishing: string
  chestLoot: string
  techChest: string
  bossRewards: string
  /** Independent lottery slot header: "Roll {{n}} · {{pct}}%". */
  roll: string
  /** Locked-chest tier badge: "Chest tier {{n}}". */
  chestTier: string
  /** Slot-mechanics footnote under each loot table. */
  lootNote: string
  /** Reward-pool entry kinds. */
  kind: {
    chest: string
    junk: string
    egg: string
    cage: string
    pal: string
    skillFruit: string
    lotus: string
    mushroom: string
    object: string
  }
  /** Reward tiers (dungeon difficulty variants). */
  tier: { easy: string; medium: string; hard: string; bonus: string }
  /** Stat-lotus flavors (PickupItem_Lotus_<Stat>). */
  lotusStat: { workspeed: string; attack: string; hp: string; stamina: string; weight: string }
  /** Expandable pool summary: "{{count}} possible pals". */
  poolCount: string
  /** Item detail page: "Found in dungeons" obtain row. */
  foundIn: string
  /** Map popup link on dungeon portal markers. */
  viewLoot: string
  /** Detail page: enemy pools section title. */
  encounters: string
  /** Detail page: entrance-map section title, with count. */
  entrances: string
  /** Detail page: top-drops strip title. */
  notableDrops: string
  backToList: string
  /** Detail page: unknown-id message. */
  notFound: string
  /** Entrance widget corner link to the full map. */
  viewOnMap: string
  /** Prev/next dungeon header links (aria-labels). */
  prevDungeon: string
  nextDungeon: string
  /** Boss-reward chest that reuses the interior chest lottery (dedup line). */
  sameAsChest: string
  /** Interior layout gallery + per-layout spawn-point map. */
  layout: {
    title: string
    /** Card label / page heading: "Layout {{variant}}". */
    name: string
    /** Rotation disclaimer: the game picks one of {{count}} interiors. */
    note: string
    /** Boss-reward spawn points by pool quality (object-style names — these
     *  spawn a chest/egg/cage roll from the tier's pool after the boss dies;
     *  the difficulty-flavored tier ids stay on the loot tables). */
    rewardEasy: string
    rewardMedium: string
    rewardHard: string
    /** The guaranteed permanent-stat-item chest (Hard03). */
    elixirChest: string
    chests: string
    exit: string
    bossDoor: string
    humans: string
    stone: string
    coal: string
    copper: string
    sulfur: string
    quartz: string
    crystal: string
    notFound: string
    backToDungeon: string
  }
}

export const DUNGEON_STRINGS: Record<Language, DungeonStrings> = {
  'en-US': {
    title: 'Dungeons',
    expBonus: 'EXP bonus ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Mid-boss',
    enemies: 'Enemies',
    floor: 'Floor {{n}}',
    fishing: 'Fishing',
    chestLoot: 'Chest loot',
    techChest: 'Technology chest',
    bossRewards: 'Boss room rewards',
    roll: 'Roll {{n}} · {{pct}}%',
    chestTier: 'Chest tier {{n}}',
    lootNote: 'Each roll happens independently at the shown chance; percentages inside a roll share it.',
    kind: { chest: 'Treasure chest', junk: 'Scrap pile', egg: 'Pal egg', cage: 'Caged pal', pal: 'Mimic ambush', skillFruit: 'Skill fruit tree', lotus: 'Stat flower', mushroom: 'Mushroom', object: 'Object' },
    tier: { easy: 'Easy', medium: 'Medium', hard: 'Hard', bonus: 'Bonus · Elixir chest' },
    lotusStat: { workspeed: 'Work Speed', attack: 'Attack', hp: 'HP', stamina: 'Stamina', weight: 'Weight' },
    poolCount: '{{count}} possible pals',
    foundIn: 'Found in dungeons',
    viewLoot: 'View dungeon loot',
    encounters: 'Encounters',
    entrances: 'Entrances ({{count}})',
    notableDrops: 'Notable drops',
    backToList: 'Back to dungeons',
    notFound: 'Dungeon {{id}} not found.',
    viewOnMap: 'View on full map',
    prevDungeon: 'Previous dungeon',
    nextDungeon: 'Next dungeon',
    sameAsChest: 'Same items as the dungeon chest loot',
    layout: {
      rewardEasy: 'Boss reward (basic)',
      rewardMedium: 'Boss reward (fine)',
      rewardHard: 'Boss reward (rare)',
      elixirChest: 'Elixir chest',
      title: 'Interior layouts',
      name: 'Layout {{variant}}',
      note: 'The game picks one of {{count}} interior layouts when the dungeon spawns; enemy and chest counts differ per layout.',
      chests: 'Chests',
      exit: 'Exit',
      bossDoor: 'Boss door',
      humans: 'Humans',
      stone: 'Stone',
      coal: 'Coal',
      copper: 'Copper ore',
      sulfur: 'Sulfur',
      quartz: 'Quartz',
      crystal: 'Pal crystal',
      notFound: 'Layout {{id}} not found.',
      backToDungeon: 'Back to {{name}}',
    },
  },
  'de-DE': {
    title: 'Dungeons',
    expBonus: 'EP-Bonus ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Zwischenboss',
    enemies: 'Gegner',
    floor: 'Ebene {{n}}',
    fishing: 'Angeln',
    chestLoot: 'Truhenbeute',
    techChest: 'Technologie-Truhe',
    bossRewards: 'Bossraum-Belohnungen',
    roll: 'Wurf {{n}} · {{pct}} %',
    chestTier: 'Truhenstufe {{n}}',
    lootNote: 'Jeder Wurf erfolgt unabhängig mit der angezeigten Chance; Prozente innerhalb eines Wurfs teilen sie sich.',
    kind: { chest: 'Schatztruhe', junk: 'Schrotthaufen', egg: 'Pal-Ei', cage: 'Eingesperrter Pal', pal: 'Mimic-Hinterhalt', skillFruit: 'Fertigkeitsfrucht-Baum', lotus: 'Statusblume', mushroom: 'Pilz', object: 'Objekt' },
    tier: { easy: 'Leicht', medium: 'Mittel', hard: 'Schwer', bonus: 'Bonus · Elixier-Truhe' },
    lotusStat: { workspeed: 'Arbeitstempo', attack: 'Angriff', hp: 'HP', stamina: 'Ausdauer', weight: 'Gewicht' },
    poolCount: '{{count}} mögliche Pals',
    foundIn: 'In Dungeons zu finden',
    viewLoot: 'Dungeon-Beute ansehen',
    encounters: 'Begegnungen',
    entrances: 'Eingänge ({{count}})',
    notableDrops: 'Nennenswerte Beute',
    backToList: 'Zurück zu den Dungeons',
    notFound: 'Dungeon {{id}} nicht gefunden.',
    viewOnMap: 'Auf der Gesamtkarte ansehen',
    prevDungeon: 'Vorheriger Dungeon',
    nextDungeon: 'Nächster Dungeon',
    sameAsChest: 'Gleiche Gegenstände wie die Truhenbeute',
    layout: {
      rewardEasy: 'Boss-Belohnung (einfach)',
      rewardMedium: 'Boss-Belohnung (gut)',
      rewardHard: 'Boss-Belohnung (selten)',
      elixirChest: 'Elixier-Truhe',
      title: 'Innenlayouts',
      name: 'Layout {{variant}}',
      note: 'Das Spiel wählt beim Erscheinen des Dungeons eines von {{count}} Innenlayouts; Gegner- und Truhenanzahl unterscheiden sich je Layout.',
      chests: 'Truhen',
      exit: 'Ausgang',
      bossDoor: 'Bosstür',
      humans: 'Menschen',
      stone: 'Stein',
      coal: 'Kohle',
      copper: 'Kupfererz',
      sulfur: 'Schwefel',
      quartz: 'Quarz',
      crystal: 'Pal-Kristall',
      notFound: 'Layout {{id}} nicht gefunden.',
      backToDungeon: 'Zurück zu {{name}}',
    },
  },
  'es-ES': {
    title: 'Mazmorras',
    expBonus: 'Bonus de EXP ×{{rate}}',
    boss: 'Jefe',
    midBoss: 'Jefe intermedio',
    enemies: 'Enemigos',
    floor: 'Piso {{n}}',
    fishing: 'Pesca',
    chestLoot: 'Botín de cofres',
    techChest: 'Cofre de tecnología',
    bossRewards: 'Recompensas de la sala del jefe',
    roll: 'Tirada {{n}} · {{pct}} %',
    chestTier: 'Nivel de cofre {{n}}',
    lootNote: 'Cada tirada ocurre de forma independiente con la probabilidad mostrada; los porcentajes dentro de una tirada la comparten.',
    kind: { chest: 'Cofre del tesoro', junk: 'Montón de chatarra', egg: 'Huevo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árbol de frutas de habilidad', lotus: 'Flor de mejora', mushroom: 'Seta', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Media', hard: 'Difícil', bonus: 'Extra · Cofre de elixir' },
    lotusStat: { workspeed: 'Velocidad de trabajo', attack: 'Ataque', hp: 'PS', stamina: 'Resistencia', weight: 'Peso' },
    poolCount: '{{count}} pals posibles',
    foundIn: 'Se encuentra en mazmorras',
    viewLoot: 'Ver botín de la mazmorra',
    encounters: 'Encuentros',
    entrances: 'Entradas ({{count}})',
    notableDrops: 'Botín destacado',
    backToList: 'Volver a mazmorras',
    notFound: 'No se encontró la mazmorra {{id}}.',
    viewOnMap: 'Ver en el mapa completo',
    prevDungeon: 'Mazmorra anterior',
    nextDungeon: 'Mazmorra siguiente',
    sameAsChest: 'Los mismos objetos que el botín de cofres',
    layout: {
      rewardEasy: 'Recompensa del jefe (básica)',
      rewardMedium: 'Recompensa del jefe (buena)',
      rewardHard: 'Recompensa del jefe (rara)',
      elixirChest: 'Cofre de elixir',
      title: 'Distribuciones interiores',
      name: 'Distribución {{variant}}',
      note: 'El juego elige una de {{count}} distribuciones interiores al aparecer la mazmorra; los enemigos y cofres varían según la distribución.',
      chests: 'Cofres',
      exit: 'Salida',
      bossDoor: 'Puerta del jefe',
      humans: 'Humanos',
      stone: 'Piedra',
      coal: 'Carbón',
      copper: 'Mineral de cobre',
      sulfur: 'Azufre',
      quartz: 'Cuarzo',
      crystal: 'Cristal de Pal',
      notFound: 'No se encontró la distribución {{id}}.',
      backToDungeon: 'Volver a {{name}}',
    },
  },
  'es-MX': {
    title: 'Mazmorras',
    expBonus: 'Bono de EXP ×{{rate}}',
    boss: 'Jefe',
    midBoss: 'Jefe intermedio',
    enemies: 'Enemigos',
    floor: 'Piso {{n}}',
    fishing: 'Pesca',
    chestLoot: 'Botín de cofres',
    techChest: 'Cofre de tecnología',
    bossRewards: 'Recompensas de la sala del jefe',
    roll: 'Tirada {{n}} · {{pct}} %',
    chestTier: 'Nivel de cofre {{n}}',
    lootNote: 'Cada tirada ocurre de forma independiente con la probabilidad mostrada; los porcentajes dentro de una tirada la comparten.',
    kind: { chest: 'Cofre del tesoro', junk: 'Montón de chatarra', egg: 'Huevo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árbol de frutas de habilidad', lotus: 'Flor de mejora', mushroom: 'Hongo', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Media', hard: 'Difícil', bonus: 'Extra · Cofre de elixir' },
    lotusStat: { workspeed: 'Velocidad de trabajo', attack: 'Ataque', hp: 'PS', stamina: 'Resistencia', weight: 'Peso' },
    poolCount: '{{count}} pals posibles',
    foundIn: 'Se encuentra en mazmorras',
    viewLoot: 'Ver botín de la mazmorra',
    encounters: 'Encuentros',
    entrances: 'Entradas ({{count}})',
    notableDrops: 'Botín destacado',
    backToList: 'Volver a mazmorras',
    notFound: 'No se encontró la mazmorra {{id}}.',
    viewOnMap: 'Ver en el mapa completo',
    prevDungeon: 'Mazmorra anterior',
    nextDungeon: 'Mazmorra siguiente',
    sameAsChest: 'Los mismos objetos que el botín de cofres',
    layout: {
      rewardEasy: 'Recompensa del jefe (básica)',
      rewardMedium: 'Recompensa del jefe (buena)',
      rewardHard: 'Recompensa del jefe (rara)',
      elixirChest: 'Cofre de elixir',
      title: 'Distribuciones interiores',
      name: 'Distribución {{variant}}',
      note: 'El juego elige una de {{count}} distribuciones interiores al aparecer la mazmorra; los enemigos y cofres varían según la distribución.',
      chests: 'Cofres',
      exit: 'Salida',
      bossDoor: 'Puerta del jefe',
      humans: 'Humanos',
      stone: 'Piedra',
      coal: 'Carbón',
      copper: 'Mineral de cobre',
      sulfur: 'Azufre',
      quartz: 'Cuarzo',
      crystal: 'Cristal de Pal',
      notFound: 'No se encontró la distribución {{id}}.',
      backToDungeon: 'Volver a {{name}}',
    },
  },
  'fr-FR': {
    title: 'Donjons',
    expBonus: 'Bonus d’EXP ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Boss intermédiaire',
    enemies: 'Ennemis',
    floor: 'Étage {{n}}',
    fishing: 'Pêche',
    chestLoot: 'Butin des coffres',
    techChest: 'Coffre technologique',
    bossRewards: 'Récompenses de la salle du boss',
    roll: 'Tirage {{n}} · {{pct}} %',
    chestTier: 'Niveau de coffre {{n}}',
    lootNote: 'Chaque tirage a lieu indépendamment avec la chance indiquée ; les pourcentages d’un même tirage se la partagent.',
    kind: { chest: 'Coffre au trésor', junk: 'Tas de ferraille', egg: 'Œuf de Pal', cage: 'Pal en cage', pal: 'Embuscade mimique', skillFruit: 'Arbre à fruits de compétence', lotus: 'Fleur de statistique', mushroom: 'Champignon', object: 'Objet' },
    tier: { easy: 'Facile', medium: 'Moyen', hard: 'Difficile', bonus: 'Bonus · Coffre à élixir' },
    lotusStat: { workspeed: 'Vitesse de travail', attack: 'Attaque', hp: 'PV', stamina: 'Endurance', weight: 'Poids' },
    poolCount: '{{count}} pals possibles',
    foundIn: 'Trouvé dans les donjons',
    viewLoot: 'Voir le butin du donjon',
    encounters: 'Rencontres',
    entrances: 'Entrées ({{count}})',
    notableDrops: 'Butin notable',
    backToList: 'Retour aux donjons',
    notFound: 'Donjon {{id}} introuvable.',
    viewOnMap: 'Voir sur la carte complète',
    prevDungeon: 'Donjon précédent',
    nextDungeon: 'Donjon suivant',
    sameAsChest: 'Mêmes objets que le butin des coffres',
    layout: {
      rewardEasy: 'Récompense du boss (simple)',
      rewardMedium: 'Récompense du boss (bonne)',
      rewardHard: 'Récompense du boss (rare)',
      elixirChest: 'Coffre à élixir',
      title: 'Agencements intérieurs',
      name: 'Agencement {{variant}}',
      note: 'Le jeu choisit l’un des {{count}} agencements intérieurs à l’apparition du donjon ; ennemis et coffres varient selon l’agencement.',
      chests: 'Coffres',
      exit: 'Sortie',
      bossDoor: 'Porte du boss',
      humans: 'Humains',
      stone: 'Pierre',
      coal: 'Charbon',
      copper: 'Minerai de cuivre',
      sulfur: 'Soufre',
      quartz: 'Quartz',
      crystal: 'Cristal de Pal',
      notFound: 'Agencement {{id}} introuvable.',
      backToDungeon: 'Retour à {{name}}',
    },
  },
  'id-ID': {
    title: 'Dungeon',
    expBonus: 'Bonus EXP ×{{rate}}',
    boss: 'Bos',
    midBoss: 'Bos tengah',
    enemies: 'Musuh',
    floor: 'Lantai {{n}}',
    fishing: 'Memancing',
    chestLoot: 'Isi peti',
    techChest: 'Peti teknologi',
    bossRewards: 'Hadiah ruang bos',
    roll: 'Undian {{n}} · {{pct}}%',
    chestTier: 'Tingkat peti {{n}}',
    lootNote: 'Setiap undian terjadi secara independen dengan peluang yang ditampilkan; persentase dalam satu undian membaginya.',
    kind: { chest: 'Peti harta', junk: 'Tumpukan rongsokan', egg: 'Telur Pal', cage: 'Pal terkurung', pal: 'Penyergapan mimic', skillFruit: 'Pohon buah skill', lotus: 'Bunga status', mushroom: 'Jamur', object: 'Objek' },
    tier: { easy: 'Mudah', medium: 'Sedang', hard: 'Sulit', bonus: 'Bonus · Peti eliksir' },
    lotusStat: { workspeed: 'Kecepatan kerja', attack: 'Serangan', hp: 'HP', stamina: 'Stamina', weight: 'Berat' },
    poolCount: '{{count}} pal yang mungkin',
    foundIn: 'Ditemukan di dungeon',
    viewLoot: 'Lihat loot dungeon',
    encounters: 'Musuh yang muncul',
    entrances: 'Pintu masuk ({{count}})',
    notableDrops: 'Loot penting',
    backToList: 'Kembali ke daftar dungeon',
    notFound: 'Dungeon {{id}} tidak ditemukan.',
    viewOnMap: 'Lihat di peta penuh',
    prevDungeon: 'Dungeon sebelumnya',
    nextDungeon: 'Dungeon berikutnya',
    sameAsChest: 'Item yang sama dengan isi peti dungeon',
    layout: {
      rewardEasy: 'Hadiah bos (dasar)',
      rewardMedium: 'Hadiah bos (bagus)',
      rewardHard: 'Hadiah bos (langka)',
      elixirChest: 'Peti eliksir',
      title: 'Tata letak interior',
      name: 'Tata letak {{variant}}',
      note: 'Game memilih satu dari {{count}} tata letak interior saat dungeon muncul; jumlah musuh dan peti berbeda tiap tata letak.',
      chests: 'Peti',
      exit: 'Keluar',
      bossDoor: 'Pintu bos',
      humans: 'Manusia',
      stone: 'Batu',
      coal: 'Batu bara',
      copper: 'Bijih tembaga',
      sulfur: 'Belerang',
      quartz: 'Kuarsa',
      crystal: 'Kristal Pal',
      notFound: 'Tata letak {{id}} tidak ditemukan.',
      backToDungeon: 'Kembali ke {{name}}',
    },
  },
  'it-IT': {
    title: 'Dungeon',
    expBonus: 'Bonus EXP ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Boss intermedio',
    enemies: 'Nemici',
    floor: 'Piano {{n}}',
    fishing: 'Pesca',
    chestLoot: 'Bottino dei forzieri',
    techChest: 'Forziere tecnologico',
    bossRewards: 'Ricompense della stanza del boss',
    roll: 'Estrazione {{n}} · {{pct}}%',
    chestTier: 'Livello forziere {{n}}',
    lootNote: 'Ogni estrazione avviene in modo indipendente con la probabilità indicata; le percentuali di un’estrazione se la dividono.',
    kind: { chest: 'Forziere del tesoro', junk: 'Mucchio di rottami', egg: 'Uovo di Pal', cage: 'Pal in gabbia', pal: 'Imboscata mimic', skillFruit: 'Albero dei frutti abilità', lotus: 'Fiore di statistica', mushroom: 'Fungo', object: 'Oggetto' },
    tier: { easy: 'Facile', medium: 'Media', hard: 'Difficile', bonus: 'Bonus · Forziere degli elisir' },
    lotusStat: { workspeed: 'Velocità di lavoro', attack: 'Attacco', hp: 'PS', stamina: 'Resistenza', weight: 'Peso' },
    poolCount: '{{count}} pal possibili',
    foundIn: 'Si trova nei dungeon',
    viewLoot: 'Vedi bottino del dungeon',
    encounters: 'Incontri',
    entrances: 'Ingressi ({{count}})',
    notableDrops: 'Bottino degno di nota',
    backToList: 'Torna ai dungeon',
    notFound: 'Dungeon {{id}} non trovato.',
    viewOnMap: 'Vedi sulla mappa completa',
    prevDungeon: 'Dungeon precedente',
    nextDungeon: 'Dungeon successivo',
    sameAsChest: 'Stessi oggetti del bottino dei forzieri',
    layout: {
      rewardEasy: 'Ricompensa del boss (base)',
      rewardMedium: 'Ricompensa del boss (buona)',
      rewardHard: 'Ricompensa del boss (rara)',
      elixirChest: 'Forziere degli elisir',
      title: 'Planimetrie interne',
      name: 'Planimetria {{variant}}',
      note: 'Il gioco sceglie una delle {{count}} planimetrie interne alla comparsa del dungeon; nemici e forzieri variano per planimetria.',
      chests: 'Forzieri',
      exit: 'Uscita',
      bossDoor: 'Porta del boss',
      humans: 'Umani',
      stone: 'Pietra',
      coal: 'Carbone',
      copper: 'Minerale di rame',
      sulfur: 'Zolfo',
      quartz: 'Quarzo',
      crystal: 'Cristallo di Pal',
      notFound: 'Planimetria {{id}} non trovata.',
      backToDungeon: 'Torna a {{name}}',
    },
  },
  'ja-JP': {
    title: 'ダンジョン',
    expBonus: '経験値ボーナス ×{{rate}}',
    boss: 'ボス',
    midBoss: '中ボス',
    enemies: '出現する敵',
    floor: '第{{n}}層',
    fishing: '釣り',
    chestLoot: '宝箱の中身',
    techChest: '技術書の宝箱',
    bossRewards: 'ボス部屋の報酬',
    roll: '抽選 {{n}} · {{pct}}%',
    chestTier: '宝箱ランク {{n}}',
    lootNote: '各抽選は表示された確率で独立して行われ、抽選内の割合はそれを分け合います。',
    kind: { chest: '宝箱', junk: 'ガラクタの山', egg: 'パルの卵', cage: '檻の中のパル', pal: 'ミミック', skillFruit: 'スキルフルーツの木', lotus: 'ステータスの花', mushroom: 'キノコ', object: 'オブジェクト' },
    tier: { easy: '易しい', medium: '普通', hard: '難しい', bonus: 'ボーナス · 秘薬の宝箱' },
    lotusStat: { workspeed: '作業速度', attack: '攻撃', hp: 'HP', stamina: 'スタミナ', weight: '重量' },
    poolCount: '出現候補 {{count}} 体',
    foundIn: '入手できるダンジョン',
    viewLoot: 'ダンジョンの戦利品を見る',
    encounters: '出現する敵とボス',
    entrances: '入口（{{count}}か所）',
    notableDrops: '注目のドロップ',
    backToList: 'ダンジョン一覧へ戻る',
    notFound: 'ダンジョン {{id}} が見つかりません。',
    viewOnMap: '全体マップで見る',
    prevDungeon: '前のダンジョン',
    nextDungeon: '次のダンジョン',
    sameAsChest: '宝箱の中身と同じアイテム',
    layout: {
      rewardEasy: 'ボス報酬（初級）',
      rewardMedium: 'ボス報酬（中級）',
      rewardHard: 'ボス報酬（上級）',
      elixirChest: '秘薬の宝箱',
      title: '内部レイアウト',
      name: 'レイアウト {{variant}}',
      note: 'ダンジョン出現時に{{count}}種類の内部レイアウトから1つが選ばれます。敵や宝箱の数はレイアウトごとに異なります。',
      chests: '宝箱',
      exit: '出口',
      bossDoor: 'ボス部屋の扉',
      humans: '人間',
      stone: '石',
      coal: '石炭',
      copper: '銅鉱石',
      sulfur: '硫黄',
      quartz: '水晶',
      crystal: 'パルクリスタル',
      notFound: 'レイアウト {{id}} が見つかりません。',
      backToDungeon: '{{name}} へ戻る',
    },
  },
  'ko-KR': {
    title: '던전',
    expBonus: '경험치 보너스 ×{{rate}}',
    boss: '보스',
    midBoss: '중간 보스',
    enemies: '등장 몬스터',
    floor: '{{n}}층',
    fishing: '낚시',
    chestLoot: '상자 전리품',
    techChest: '기술서 상자',
    bossRewards: '보스 방 보상',
    roll: '추첨 {{n}} · {{pct}}%',
    chestTier: '상자 등급 {{n}}',
    lootNote: '각 추첨은 표시된 확률로 독립적으로 진행되며, 추첨 내 비율은 이를 나눠 가집니다.',
    kind: { chest: '보물 상자', junk: '고철 더미', egg: '팰 알', cage: '갇힌 팰', pal: '미믹 기습', skillFruit: '스킬 프루트 나무', lotus: '스탯 꽃', mushroom: '버섯', object: '오브젝트' },
    tier: { easy: '쉬움', medium: '보통', hard: '어려움', bonus: '보너스 · 비약 상자' },
    lotusStat: { workspeed: '작업 속도', attack: '공격', hp: 'HP', stamina: '기력', weight: '무게' },
    poolCount: '가능한 팰 {{count}}종',
    foundIn: '획득 가능한 던전',
    viewLoot: '던전 전리품 보기',
    encounters: '등장 몬스터와 보스',
    entrances: '입구 ({{count}}곳)',
    notableDrops: '주목할 전리품',
    backToList: '던전 목록으로 돌아가기',
    notFound: '던전 {{id}}을(를) 찾을 수 없습니다.',
    viewOnMap: '전체 지도에서 보기',
    prevDungeon: '이전 던전',
    nextDungeon: '다음 던전',
    sameAsChest: '상자 전리품과 동일한 아이템',
    layout: {
      rewardEasy: '보스 보상 (초급)',
      rewardMedium: '보스 보상 (중급)',
      rewardHard: '보스 보상 (고급)',
      elixirChest: '비약 상자',
      title: '내부 레이아웃',
      name: '레이아웃 {{variant}}',
      note: '던전이 생성될 때 {{count}}가지 내부 레이아웃 중 하나가 선택됩니다. 레이아웃마다 적과 상자 수가 다릅니다.',
      chests: '상자',
      exit: '출구',
      bossDoor: '보스 방 문',
      humans: '인간',
      stone: '돌',
      coal: '석탄',
      copper: '구리 광석',
      sulfur: '유황',
      quartz: '석영',
      crystal: '팰 크리스탈',
      notFound: '레이아웃 {{id}}을(를) 찾을 수 없습니다.',
      backToDungeon: '{{name}}(으)로 돌아가기',
    },
  },
  'pl-PL': {
    title: 'Lochy',
    expBonus: 'Premia EXP ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Miniboss',
    enemies: 'Wrogowie',
    floor: 'Poziom {{n}}',
    fishing: 'Wędkowanie',
    chestLoot: 'Łup ze skrzyń',
    techChest: 'Skrzynia technologiczna',
    bossRewards: 'Nagrody z sali bossa',
    roll: 'Losowanie {{n}} · {{pct}}%',
    chestTier: 'Poziom skrzyni {{n}}',
    lootNote: 'Każde losowanie odbywa się niezależnie z podaną szansą; procenty w obrębie losowania dzielą ją między siebie.',
    kind: { chest: 'Skrzynia skarbów', junk: 'Sterta złomu', egg: 'Jajo Pala', cage: 'Pal w klatce', pal: 'Zasadzka mimika', skillFruit: 'Drzewo owoców umiejętności', lotus: 'Kwiat statystyk', mushroom: 'Grzyb', object: 'Obiekt' },
    tier: { easy: 'Łatwy', medium: 'Średni', hard: 'Trudny', bonus: 'Bonus · Skrzynia z eliksirem' },
    lotusStat: { workspeed: 'Tempo pracy', attack: 'Atak', hp: 'PŻ', stamina: 'Wytrzymałość', weight: 'Waga' },
    poolCount: '{{count}} możliwych pali',
    foundIn: 'Występuje w lochach',
    viewLoot: 'Zobacz łupy z lochu',
    encounters: 'Przeciwnicy i bossowie',
    entrances: 'Wejścia ({{count}})',
    notableDrops: 'Godny uwagi łup',
    backToList: 'Powrót do lochów',
    notFound: 'Nie znaleziono lochu {{id}}.',
    viewOnMap: 'Zobacz na pełnej mapie',
    prevDungeon: 'Poprzedni loch',
    nextDungeon: 'Następny loch',
    sameAsChest: 'Te same przedmioty co łup ze skrzyń',
    layout: {
      rewardEasy: 'Nagroda bossa (podstawowa)',
      rewardMedium: 'Nagroda bossa (dobra)',
      rewardHard: 'Nagroda bossa (rzadka)',
      elixirChest: 'Skrzynia z eliksirem',
      title: 'Układy wnętrza',
      name: 'Układ {{variant}}',
      note: 'Gra wybiera jeden z {{count}} układów wnętrza przy pojawieniu się lochu; liczba wrogów i skrzyń różni się w zależności od układu.',
      chests: 'Skrzynie',
      exit: 'Wyjście',
      bossDoor: 'Drzwi bossa',
      humans: 'Ludzie',
      stone: 'Kamień',
      coal: 'Węgiel',
      copper: 'Ruda miedzi',
      sulfur: 'Siarka',
      quartz: 'Kwarc',
      crystal: 'Kryształ Pala',
      notFound: 'Nie znaleziono układu {{id}}.',
      backToDungeon: 'Powrót do {{name}}',
    },
  },
  'pt-BR': {
    title: 'Masmorras',
    expBonus: 'Bônus de EXP ×{{rate}}',
    boss: 'Chefe',
    midBoss: 'Chefe intermediário',
    enemies: 'Inimigos',
    floor: 'Andar {{n}}',
    fishing: 'Pesca',
    chestLoot: 'Saque dos baús',
    techChest: 'Baú de tecnologia',
    bossRewards: 'Recompensas da sala do chefe',
    roll: 'Sorteio {{n}} · {{pct}}%',
    chestTier: 'Nível do baú {{n}}',
    lootNote: 'Cada sorteio acontece de forma independente com a chance mostrada; as porcentagens dentro de um sorteio a compartilham.',
    kind: { chest: 'Baú do tesouro', junk: 'Pilha de sucata', egg: 'Ovo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árvore de frutas de habilidade', lotus: 'Flor de atributo', mushroom: 'Cogumelo', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Média', hard: 'Difícil', bonus: 'Bônus · Baú de elixir' },
    lotusStat: { workspeed: 'Velocidade de trabalho', attack: 'Ataque', hp: 'PV', stamina: 'Vigor', weight: 'Peso' },
    poolCount: '{{count}} pals possíveis',
    foundIn: 'Encontrado em masmorras',
    viewLoot: 'Ver saque da masmorra',
    encounters: 'Encontros',
    entrances: 'Entradas ({{count}})',
    notableDrops: 'Saque notável',
    backToList: 'Voltar às masmorras',
    notFound: 'Masmorra {{id}} não encontrada.',
    viewOnMap: 'Ver no mapa completo',
    prevDungeon: 'Masmorra anterior',
    nextDungeon: 'Próxima masmorra',
    sameAsChest: 'Os mesmos itens do saque dos baús',
    layout: {
      rewardEasy: 'Recompensa do chefe (básica)',
      rewardMedium: 'Recompensa do chefe (boa)',
      rewardHard: 'Recompensa do chefe (rara)',
      elixirChest: 'Baú de elixir',
      title: 'Plantas internas',
      name: 'Planta {{variant}}',
      note: 'O jogo escolhe uma de {{count}} plantas internas quando a masmorra surge; inimigos e baús variam por planta.',
      chests: 'Baús',
      exit: 'Saída',
      bossDoor: 'Porta do chefe',
      humans: 'Humanos',
      stone: 'Pedra',
      coal: 'Carvão',
      copper: 'Minério de cobre',
      sulfur: 'Enxofre',
      quartz: 'Quartzo',
      crystal: 'Cristal de Pal',
      notFound: 'Planta {{id}} não encontrada.',
      backToDungeon: 'Voltar a {{name}}',
    },
  },
  'ru-RU': {
    title: 'Подземелья',
    expBonus: 'Бонус опыта ×{{rate}}',
    boss: 'Босс',
    midBoss: 'Мини-босс',
    enemies: 'Враги',
    floor: 'Этаж {{n}}',
    fishing: 'Рыбалка',
    chestLoot: 'Добыча из сундуков',
    techChest: 'Сундук с технологиями',
    bossRewards: 'Награды комнаты босса',
    roll: 'Бросок {{n}} · {{pct}}%',
    chestTier: 'Уровень сундука {{n}}',
    lootNote: 'Каждый бросок происходит независимо с указанным шансом; проценты внутри броска делят его между собой.',
    kind: { chest: 'Сундук с сокровищами', junk: 'Куча хлама', egg: 'Яйцо пала', cage: 'Пал в клетке', pal: 'Засада мимика', skillFruit: 'Дерево плодов навыков', lotus: 'Цветок характеристик', mushroom: 'Гриб', object: 'Объект' },
    tier: { easy: 'Лёгкий', medium: 'Средний', hard: 'Сложный', bonus: 'Бонус · Сундук с эликсиром' },
    lotusStat: { workspeed: 'Скорость работы', attack: 'Атака', hp: 'ОЗ', stamina: 'Выносливость', weight: 'Вес' },
    poolCount: 'Возможных палов: {{count}}',
    foundIn: 'Встречается в подземельях',
    viewLoot: 'Посмотреть добычу подземелья',
    encounters: 'Противники и боссы',
    entrances: 'Входы ({{count}})',
    notableDrops: 'Примечательная добыча',
    backToList: 'Назад к подземельям',
    notFound: 'Подземелье {{id}} не найдено.',
    viewOnMap: 'Показать на полной карте',
    prevDungeon: 'Предыдущее подземелье',
    nextDungeon: 'Следующее подземелье',
    sameAsChest: 'Те же предметы, что и в добыче из сундуков',
    layout: {
      rewardEasy: 'Награда босса (простая)',
      rewardMedium: 'Награда босса (хорошая)',
      rewardHard: 'Награда босса (редкая)',
      elixirChest: 'Сундук с эликсиром',
      title: 'Внутренние планировки',
      name: 'Планировка {{variant}}',
      note: 'При появлении подземелья игра выбирает одну из {{count}} планировок; количество врагов и сундуков зависит от планировки.',
      chests: 'Сундуки',
      exit: 'Выход',
      bossDoor: 'Дверь босса',
      humans: 'Люди',
      stone: 'Камень',
      coal: 'Уголь',
      copper: 'Медная руда',
      sulfur: 'Сера',
      quartz: 'Кварц',
      crystal: 'Кристалл пала',
      notFound: 'Планировка {{id}} не найдена.',
      backToDungeon: 'Назад к {{name}}',
    },
  },
  'th-TH': {
    title: 'ดันเจี้ยน',
    expBonus: 'โบนัส EXP ×{{rate}}',
    boss: 'บอส',
    midBoss: 'มินิบอส',
    enemies: 'ศัตรู',
    floor: 'ชั้น {{n}}',
    fishing: 'ตกปลา',
    chestLoot: 'ของในหีบสมบัติ',
    techChest: 'หีบตำราเทคโนโลยี',
    bossRewards: 'รางวัลห้องบอส',
    roll: 'สุ่มครั้งที่ {{n}} · {{pct}}%',
    chestTier: 'ระดับหีบ {{n}}',
    lootNote: 'การสุ่มแต่ละครั้งเกิดขึ้นอย่างอิสระตามโอกาสที่แสดง เปอร์เซ็นต์ภายในการสุ่มเดียวกันจะแบ่งโอกาสนั้น',
    kind: { chest: 'หีบสมบัติ', junk: 'กองเศษเหล็ก', egg: 'ไข่พัล', cage: 'พัลในกรง', pal: 'มิมิคซุ่มโจมตี', skillFruit: 'ต้นผลสกิล', lotus: 'ดอกไม้เพิ่มค่าสถานะ', mushroom: 'เห็ด', object: 'วัตถุ' },
    tier: { easy: 'ง่าย', medium: 'ปานกลาง', hard: 'ยาก', bonus: 'โบนัส · หีบยาวิเศษ' },
    lotusStat: { workspeed: 'ความเร็วทำงาน', attack: 'โจมตี', hp: 'HP', stamina: 'ความอึด', weight: 'น้ำหนัก' },
    poolCount: 'พัลที่เป็นไปได้ {{count}} ตัว',
    foundIn: 'พบได้ในดันเจี้ยน',
    viewLoot: 'ดูของรางวัลดันเจี้ยน',
    encounters: 'ศัตรูและบอส',
    entrances: 'ทางเข้า ({{count}})',
    notableDrops: 'ของรางวัลเด่น',
    backToList: 'กลับไปหน้าดันเจี้ยน',
    notFound: 'ไม่พบดันเจี้ยน {{id}}',
    viewOnMap: 'ดูบนแผนที่เต็ม',
    prevDungeon: 'ดันเจี้ยนก่อนหน้า',
    nextDungeon: 'ดันเจี้ยนถัดไป',
    sameAsChest: 'ไอเทมเดียวกับของในหีบสมบัติ',
    layout: {
      rewardEasy: 'รางวัลบอส (พื้นฐาน)',
      rewardMedium: 'รางวัลบอส (ดี)',
      rewardHard: 'รางวัลบอส (หายาก)',
      elixirChest: 'หีบยาวิเศษ',
      title: 'ผังภายใน',
      name: 'ผัง {{variant}}',
      note: 'เกมจะสุ่มเลือกผังภายใน 1 จาก {{count}} แบบเมื่อดันเจี้ยนปรากฏ จำนวนศัตรูและหีบต่างกันในแต่ละผัง',
      chests: 'หีบ',
      exit: 'ทางออก',
      bossDoor: 'ประตูห้องบอส',
      humans: 'มนุษย์',
      stone: 'หิน',
      coal: 'ถ่านหิน',
      copper: 'แร่ทองแดง',
      sulfur: 'กำมะถัน',
      quartz: 'ควอตซ์',
      crystal: 'พัลคริสตัล',
      notFound: 'ไม่พบผัง {{id}}',
      backToDungeon: 'กลับไปที่ {{name}}',
    },
  },
  'tr-TR': {
    title: 'Zindanlar',
    expBonus: 'EXP bonusu ×{{rate}}',
    boss: 'Boss',
    midBoss: 'Ara boss',
    enemies: 'Düşmanlar',
    floor: 'Kat {{n}}',
    fishing: 'Balıkçılık',
    chestLoot: 'Sandık ganimeti',
    techChest: 'Teknoloji sandığı',
    bossRewards: 'Boss odası ödülleri',
    roll: 'Çekiliş {{n}} · %{{pct}}',
    chestTier: 'Sandık seviyesi {{n}}',
    lootNote: 'Her çekiliş gösterilen şansla bağımsız yapılır; bir çekiliş içindeki yüzdeler bu şansı paylaşır.',
    kind: { chest: 'Hazine sandığı', junk: 'Hurda yığını', egg: 'Pal yumurtası', cage: 'Kafesteki Pal', pal: 'Mimik pususu', skillFruit: 'Yetenek meyvesi ağacı', lotus: 'Nitelik çiçeği', mushroom: 'Mantar', object: 'Nesne' },
    tier: { easy: 'Kolay', medium: 'Orta', hard: 'Zor', bonus: 'Bonus · İksir sandığı' },
    lotusStat: { workspeed: 'Çalışma hızı', attack: 'Saldırı', hp: 'HP', stamina: 'Dayanıklılık', weight: 'Ağırlık' },
    poolCount: '{{count}} olası pal',
    foundIn: 'Zindanlarda bulunur',
    viewLoot: 'Zindan ganimetini gör',
    encounters: 'Karşılaşmalar',
    entrances: 'Girişler ({{count}})',
    notableDrops: 'Öne çıkan ganimet',
    backToList: 'Zindan listesine dön',
    notFound: '{{id}} zindanı bulunamadı.',
    viewOnMap: 'Tam haritada gör',
    prevDungeon: 'Önceki zindan',
    nextDungeon: 'Sonraki zindan',
    sameAsChest: 'Sandık ganimetiyle aynı eşyalar',
    layout: {
      rewardEasy: 'Boss ödülü (temel)',
      rewardMedium: 'Boss ödülü (iyi)',
      rewardHard: 'Boss ödülü (nadir)',
      elixirChest: 'İksir sandığı',
      title: 'İç düzenler',
      name: 'Düzen {{variant}}',
      note: 'Zindan belirdiğinde oyun {{count}} iç düzenden birini seçer; düşman ve sandık sayıları düzene göre değişir.',
      chests: 'Sandıklar',
      exit: 'Çıkış',
      bossDoor: 'Boss kapısı',
      humans: 'İnsanlar',
      stone: 'Taş',
      coal: 'Kömür',
      copper: 'Bakır cevheri',
      sulfur: 'Kükürt',
      quartz: 'Kuvars',
      crystal: 'Pal kristali',
      notFound: '{{id}} düzeni bulunamadı.',
      backToDungeon: '{{name}} sayfasına dön',
    },
  },
  'vi-VN': {
    title: 'Hầm ngục',
    expBonus: 'Thưởng EXP ×{{rate}}',
    boss: 'Trùm',
    midBoss: 'Trùm phụ',
    enemies: 'Kẻ địch',
    floor: 'Tầng {{n}}',
    fishing: 'Câu cá',
    chestLoot: 'Chiến lợi phẩm rương',
    techChest: 'Rương sách công nghệ',
    bossRewards: 'Phần thưởng phòng trùm',
    roll: 'Lượt quay {{n}} · {{pct}}%',
    chestTier: 'Cấp rương {{n}}',
    lootNote: 'Mỗi lượt quay diễn ra độc lập với tỉ lệ hiển thị; các phần trăm trong một lượt chia nhau tỉ lệ đó.',
    kind: { chest: 'Rương kho báu', junk: 'Đống phế liệu', egg: 'Trứng Pal', cage: 'Pal bị nhốt', pal: 'Mimic phục kích', skillFruit: 'Cây quả kỹ năng', lotus: 'Hoa chỉ số', mushroom: 'Nấm', object: 'Vật thể' },
    tier: { easy: 'Dễ', medium: 'Trung bình', hard: 'Khó', bonus: 'Thưởng thêm · Rương thuốc quý' },
    lotusStat: { workspeed: 'Tốc độ làm việc', attack: 'Tấn công', hp: 'HP', stamina: 'Thể lực', weight: 'Cân nặng' },
    poolCount: '{{count}} pal có thể xuất hiện',
    foundIn: 'Tìm thấy trong hầm ngục',
    viewLoot: 'Xem chiến lợi phẩm hầm ngục',
    encounters: 'Kẻ địch và trùm',
    entrances: 'Lối vào ({{count}})',
    notableDrops: 'Chiến lợi phẩm đáng chú ý',
    backToList: 'Quay lại danh sách hầm ngục',
    notFound: 'Không tìm thấy hầm ngục {{id}}.',
    viewOnMap: 'Xem trên bản đồ đầy đủ',
    prevDungeon: 'Hầm ngục trước',
    nextDungeon: 'Hầm ngục sau',
    sameAsChest: 'Cùng vật phẩm với chiến lợi phẩm rương',
    layout: {
      rewardEasy: 'Phần thưởng trùm (cơ bản)',
      rewardMedium: 'Phần thưởng trùm (tốt)',
      rewardHard: 'Phần thưởng trùm (hiếm)',
      elixirChest: 'Rương thuốc quý',
      title: 'Bố cục bên trong',
      name: 'Bố cục {{variant}}',
      note: 'Trò chơi chọn một trong {{count}} bố cục bên trong khi hầm ngục xuất hiện; số kẻ địch và rương khác nhau theo bố cục.',
      chests: 'Rương',
      exit: 'Lối ra',
      bossDoor: 'Cửa phòng trùm',
      humans: 'Con người',
      stone: 'Đá',
      coal: 'Than',
      copper: 'Quặng đồng',
      sulfur: 'Lưu huỳnh',
      quartz: 'Thạch anh',
      crystal: 'Tinh thể Pal',
      notFound: 'Không tìm thấy bố cục {{id}}.',
      backToDungeon: 'Quay lại {{name}}',
    },
  },
  'zh-CN': {
    title: '地下城',
    expBonus: '经验加成 ×{{rate}}',
    boss: '头目',
    midBoss: '小头目',
    enemies: '出现的敌人',
    floor: '第 {{n}} 层',
    fishing: '钓鱼',
    chestLoot: '宝箱掉落',
    techChest: '技术书宝箱',
    bossRewards: '头目房间奖励',
    roll: '第 {{n}} 次抽取 · {{pct}}%',
    chestTier: '宝箱等级 {{n}}',
    lootNote: '每次抽取按所示概率独立进行；同一次抽取内的百分比按权重分摊该概率。',
    kind: { chest: '宝箱', junk: '废料堆', egg: '帕鲁蛋', cage: '笼中帕鲁', pal: '宝箱怪伏击', skillFruit: '技能果实树', lotus: '属性之花', mushroom: '蘑菇', object: '物件' },
    tier: { easy: '简单', medium: '普通', hard: '困难', bonus: '额外 · 秘药宝箱' },
    lotusStat: { workspeed: '工作速度', attack: '攻击', hp: '生命', stamina: '耐力', weight: '负重' },
    poolCount: '可能出现 {{count}} 种帕鲁',
    foundIn: '可在以下地下城获得',
    viewLoot: '查看地下城掉落',
    encounters: '敌人与头目',
    entrances: '入口（{{count}} 个）',
    notableDrops: '重点掉落',
    backToList: '返回地下城列表',
    notFound: '未找到地下城 {{id}}。',
    viewOnMap: '在完整地图中查看',
    prevDungeon: '上一个地下城',
    nextDungeon: '下一个地下城',
    sameAsChest: '与宝箱掉落相同的物品',
    layout: {
      rewardEasy: '头目奖励·初级',
      rewardMedium: '头目奖励·中级',
      rewardHard: '头目奖励·高级',
      elixirChest: '秘药宝箱',
      title: '内部布局',
      name: '布局 {{variant}}',
      note: '地下城生成时会从 {{count}} 种内部布局中随机选择一种；每种布局的敌人和宝箱数量不同。',
      chests: '宝箱',
      exit: '出口',
      bossDoor: '头目房间之门',
      humans: '人类',
      stone: '石头',
      coal: '煤炭',
      copper: '铜矿石',
      sulfur: '硫磺',
      quartz: '石英',
      crystal: '帕鲁水晶',
      notFound: '未找到布局 {{id}}。',
      backToDungeon: '返回{{name}}',
    },
  },
  'zh-TW': {
    title: '地下城',
    expBonus: '經驗加成 ×{{rate}}',
    boss: '頭目',
    midBoss: '小頭目',
    enemies: '出現的敵人',
    floor: '第 {{n}} 層',
    fishing: '釣魚',
    chestLoot: '寶箱掉落',
    techChest: '技術書寶箱',
    bossRewards: '頭目房間獎勵',
    roll: '第 {{n}} 次抽取 · {{pct}}%',
    chestTier: '寶箱等級 {{n}}',
    lootNote: '每次抽取依所示機率獨立進行；同一次抽取內的百分比按權重分攤該機率。',
    kind: { chest: '寶箱', junk: '廢料堆', egg: '帕魯蛋', cage: '籠中帕魯', pal: '寶箱怪伏擊', skillFruit: '技能果實樹', lotus: '屬性之花', mushroom: '蘑菇', object: '物件' },
    tier: { easy: '簡單', medium: '普通', hard: '困難', bonus: '額外 · 秘藥寶箱' },
    lotusStat: { workspeed: '工作速度', attack: '攻擊', hp: '生命', stamina: '耐力', weight: '負重' },
    poolCount: '可能出現 {{count}} 種帕魯',
    foundIn: '可在以下地下城獲得',
    viewLoot: '查看地下城掉落',
    encounters: '敵人與頭目',
    entrances: '入口（{{count}} 個）',
    notableDrops: '重點掉落',
    backToList: '返回地下城列表',
    notFound: '未找到地下城 {{id}}。',
    viewOnMap: '在完整地圖中檢視',
    prevDungeon: '上一個地下城',
    nextDungeon: '下一個地下城',
    sameAsChest: '與寶箱掉落相同的物品',
    layout: {
      rewardEasy: '頭目獎勵·初級',
      rewardMedium: '頭目獎勵·中級',
      rewardHard: '頭目獎勵·高級',
      elixirChest: '秘藥寶箱',
      title: '內部布局',
      name: '布局 {{variant}}',
      note: '地下城生成時會從 {{count}} 種內部布局中隨機選擇一種；每種布局的敵人和寶箱數量不同。',
      chests: '寶箱',
      exit: '出口',
      bossDoor: '頭目房間之門',
      humans: '人類',
      stone: '石頭',
      coal: '煤炭',
      copper: '銅礦石',
      sulfur: '硫磺',
      quartz: '石英',
      crystal: '帕魯水晶',
      notFound: '未找到布局 {{id}}。',
      backToDungeon: '返回{{name}}',
    },
  },
}
