import type { Language } from './i18n'

// Dungeon loot page UI chrome, merged into the `translation` namespace under
// the `dungeon` key (see i18n.ts). Dungeon / item / pal names come from the
// locale data files; this table only holds the page's own labels.
export interface DungeonStrings {
  title: string
  /** "EXP bonus ×{{rate}}" badge on each dungeon card. */
  expBonus: string
  boss: string
  enemies: string
  chestLoot: string
  techChest: string
  bossRewards: string
  /** Independent lottery slot header: "Roll {{n}} · {{pct}}%". */
  roll: string
  /** Locked-chest tier badge: "Chest tier {{n}}". */
  chestTier: string
  /** Slot-mechanics footnote under each loot table. */
  lootNote: string
  /** Reward-pool entry kinds. */
  kind: {
    chest: string
    junk: string
    egg: string
    cage: string
    pal: string
    skillFruit: string
    lotus: string
    mushroom: string
    object: string
  }
  /** Reward tiers (dungeon difficulty variants). */
  tier: { easy: string; medium: string; hard: string; bonus: string }
  /** Stat-lotus flavors (PickupItem_Lotus_<Stat>). */
  lotusStat: { workspeed: string; attack: string; hp: string; stamina: string; weight: string }
  /** Expandable pool summary: "{{count}} possible pals". */
  poolCount: string
  /** Item detail page: "Found in dungeons" obtain row. */
  foundIn: string
  /** Map popup link on dungeon portal markers. */
  viewLoot: string
}

export const DUNGEON_STRINGS: Record<Language, DungeonStrings> = {
  'en-US': {
    title: 'Dungeons',
    expBonus: 'EXP bonus ×{{rate}}',
    boss: 'Boss',
    enemies: 'Enemies',
    chestLoot: 'Chest loot',
    techChest: 'Technology chest',
    bossRewards: 'Boss room rewards',
    roll: 'Roll {{n}} · {{pct}}%',
    chestTier: 'Chest tier {{n}}',
    lootNote: 'Each roll happens independently at the shown chance; percentages inside a roll share it.',
    kind: { chest: 'Treasure chest', junk: 'Scrap pile', egg: 'Pal egg', cage: 'Caged pal', pal: 'Mimic ambush', skillFruit: 'Skill fruit tree', lotus: 'Stat flower', mushroom: 'Mushroom', object: 'Object' },
    tier: { easy: 'Easy', medium: 'Medium', hard: 'Hard', bonus: 'Hard · bonus' },
    lotusStat: { workspeed: 'Work Speed', attack: 'Attack', hp: 'HP', stamina: 'Stamina', weight: 'Weight' },
    poolCount: '{{count}} possible pals',
    foundIn: 'Found in dungeons',
    viewLoot: 'View dungeon loot',
  },
  'de-DE': {
    title: 'Dungeons',
    expBonus: 'EP-Bonus ×{{rate}}',
    boss: 'Boss',
    enemies: 'Gegner',
    chestLoot: 'Truhenbeute',
    techChest: 'Technologie-Truhe',
    bossRewards: 'Bossraum-Belohnungen',
    roll: 'Wurf {{n}} · {{pct}} %',
    chestTier: 'Truhenstufe {{n}}',
    lootNote: 'Jeder Wurf erfolgt unabhängig mit der angezeigten Chance; Prozente innerhalb eines Wurfs teilen sie sich.',
    kind: { chest: 'Schatztruhe', junk: 'Schrotthaufen', egg: 'Pal-Ei', cage: 'Eingesperrter Pal', pal: 'Mimic-Hinterhalt', skillFruit: 'Fertigkeitsfrucht-Baum', lotus: 'Statusblume', mushroom: 'Pilz', object: 'Objekt' },
    tier: { easy: 'Leicht', medium: 'Mittel', hard: 'Schwer', bonus: 'Schwer · Bonus' },
    lotusStat: { workspeed: 'Arbeitstempo', attack: 'Angriff', hp: 'HP', stamina: 'Ausdauer', weight: 'Gewicht' },
    poolCount: '{{count}} mögliche Pals',
    foundIn: 'In Dungeons zu finden',
    viewLoot: 'Dungeon-Beute ansehen',
  },
  'es-ES': {
    title: 'Mazmorras',
    expBonus: 'Bonus de EXP ×{{rate}}',
    boss: 'Jefe',
    enemies: 'Enemigos',
    chestLoot: 'Botín de cofres',
    techChest: 'Cofre de tecnología',
    bossRewards: 'Recompensas de la sala del jefe',
    roll: 'Tirada {{n}} · {{pct}} %',
    chestTier: 'Nivel de cofre {{n}}',
    lootNote: 'Cada tirada ocurre de forma independiente con la probabilidad mostrada; los porcentajes dentro de una tirada la comparten.',
    kind: { chest: 'Cofre del tesoro', junk: 'Montón de chatarra', egg: 'Huevo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árbol de frutas de habilidad', lotus: 'Flor de mejora', mushroom: 'Seta', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Media', hard: 'Difícil', bonus: 'Difícil · extra' },
    lotusStat: { workspeed: 'Velocidad de trabajo', attack: 'Ataque', hp: 'PS', stamina: 'Resistencia', weight: 'Peso' },
    poolCount: '{{count}} pals posibles',
    foundIn: 'Se encuentra en mazmorras',
    viewLoot: 'Ver botín de la mazmorra',
  },
  'es-MX': {
    title: 'Mazmorras',
    expBonus: 'Bono de EXP ×{{rate}}',
    boss: 'Jefe',
    enemies: 'Enemigos',
    chestLoot: 'Botín de cofres',
    techChest: 'Cofre de tecnología',
    bossRewards: 'Recompensas de la sala del jefe',
    roll: 'Tirada {{n}} · {{pct}} %',
    chestTier: 'Nivel de cofre {{n}}',
    lootNote: 'Cada tirada ocurre de forma independiente con la probabilidad mostrada; los porcentajes dentro de una tirada la comparten.',
    kind: { chest: 'Cofre del tesoro', junk: 'Montón de chatarra', egg: 'Huevo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árbol de frutas de habilidad', lotus: 'Flor de mejora', mushroom: 'Hongo', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Media', hard: 'Difícil', bonus: 'Difícil · extra' },
    lotusStat: { workspeed: 'Velocidad de trabajo', attack: 'Ataque', hp: 'PS', stamina: 'Resistencia', weight: 'Peso' },
    poolCount: '{{count}} pals posibles',
    foundIn: 'Se encuentra en mazmorras',
    viewLoot: 'Ver botín de la mazmorra',
  },
  'fr-FR': {
    title: 'Donjons',
    expBonus: 'Bonus d’EXP ×{{rate}}',
    boss: 'Boss',
    enemies: 'Ennemis',
    chestLoot: 'Butin des coffres',
    techChest: 'Coffre technologique',
    bossRewards: 'Récompenses de la salle du boss',
    roll: 'Tirage {{n}} · {{pct}} %',
    chestTier: 'Niveau de coffre {{n}}',
    lootNote: 'Chaque tirage a lieu indépendamment avec la chance indiquée ; les pourcentages d’un même tirage se la partagent.',
    kind: { chest: 'Coffre au trésor', junk: 'Tas de ferraille', egg: 'Œuf de Pal', cage: 'Pal en cage', pal: 'Embuscade mimique', skillFruit: 'Arbre à fruits de compétence', lotus: 'Fleur de statistique', mushroom: 'Champignon', object: 'Objet' },
    tier: { easy: 'Facile', medium: 'Moyen', hard: 'Difficile', bonus: 'Difficile · bonus' },
    lotusStat: { workspeed: 'Vitesse de travail', attack: 'Attaque', hp: 'PV', stamina: 'Endurance', weight: 'Poids' },
    poolCount: '{{count}} pals possibles',
    foundIn: 'Trouvé dans les donjons',
    viewLoot: 'Voir le butin du donjon',
  },
  'id-ID': {
    title: 'Dungeon',
    expBonus: 'Bonus EXP ×{{rate}}',
    boss: 'Bos',
    enemies: 'Musuh',
    chestLoot: 'Isi peti',
    techChest: 'Peti teknologi',
    bossRewards: 'Hadiah ruang bos',
    roll: 'Undian {{n}} · {{pct}}%',
    chestTier: 'Tingkat peti {{n}}',
    lootNote: 'Setiap undian terjadi secara independen dengan peluang yang ditampilkan; persentase dalam satu undian membaginya.',
    kind: { chest: 'Peti harta', junk: 'Tumpukan rongsokan', egg: 'Telur Pal', cage: 'Pal terkurung', pal: 'Penyergapan mimic', skillFruit: 'Pohon buah skill', lotus: 'Bunga status', mushroom: 'Jamur', object: 'Objek' },
    tier: { easy: 'Mudah', medium: 'Sedang', hard: 'Sulit', bonus: 'Sulit · bonus' },
    lotusStat: { workspeed: 'Kecepatan kerja', attack: 'Serangan', hp: 'HP', stamina: 'Stamina', weight: 'Berat' },
    poolCount: '{{count}} pal yang mungkin',
    foundIn: 'Ditemukan di dungeon',
    viewLoot: 'Lihat loot dungeon',
  },
  'it-IT': {
    title: 'Dungeon',
    expBonus: 'Bonus EXP ×{{rate}}',
    boss: 'Boss',
    enemies: 'Nemici',
    chestLoot: 'Bottino dei forzieri',
    techChest: 'Forziere tecnologico',
    bossRewards: 'Ricompense della stanza del boss',
    roll: 'Estrazione {{n}} · {{pct}}%',
    chestTier: 'Livello forziere {{n}}',
    lootNote: 'Ogni estrazione avviene in modo indipendente con la probabilità indicata; le percentuali di un’estrazione se la dividono.',
    kind: { chest: 'Forziere del tesoro', junk: 'Mucchio di rottami', egg: 'Uovo di Pal', cage: 'Pal in gabbia', pal: 'Imboscata mimic', skillFruit: 'Albero dei frutti abilità', lotus: 'Fiore di statistica', mushroom: 'Fungo', object: 'Oggetto' },
    tier: { easy: 'Facile', medium: 'Media', hard: 'Difficile', bonus: 'Difficile · bonus' },
    lotusStat: { workspeed: 'Velocità di lavoro', attack: 'Attacco', hp: 'PS', stamina: 'Resistenza', weight: 'Peso' },
    poolCount: '{{count}} pal possibili',
    foundIn: 'Si trova nei dungeon',
    viewLoot: 'Vedi bottino del dungeon',
  },
  'ja-JP': {
    title: 'ダンジョン',
    expBonus: '経験値ボーナス ×{{rate}}',
    boss: 'ボス',
    enemies: '出現する敵',
    chestLoot: '宝箱の中身',
    techChest: '技術書の宝箱',
    bossRewards: 'ボス部屋の報酬',
    roll: '抽選 {{n}} · {{pct}}%',
    chestTier: '宝箱ランク {{n}}',
    lootNote: '各抽選は表示された確率で独立して行われ、抽選内の割合はそれを分け合います。',
    kind: { chest: '宝箱', junk: 'ガラクタの山', egg: 'パルの卵', cage: '檻の中のパル', pal: 'ミミック', skillFruit: 'スキルフルーツの木', lotus: 'ステータスの花', mushroom: 'キノコ', object: 'オブジェクト' },
    tier: { easy: '易しい', medium: '普通', hard: '難しい', bonus: '難しい · ボーナス' },
    lotusStat: { workspeed: '作業速度', attack: '攻撃', hp: 'HP', stamina: 'スタミナ', weight: '重量' },
    poolCount: '出現候補 {{count}} 体',
    foundIn: '入手できるダンジョン',
    viewLoot: 'ダンジョンの戦利品を見る',
  },
  'ko-KR': {
    title: '던전',
    expBonus: '경험치 보너스 ×{{rate}}',
    boss: '보스',
    enemies: '등장 몬스터',
    chestLoot: '상자 전리품',
    techChest: '기술서 상자',
    bossRewards: '보스 방 보상',
    roll: '추첨 {{n}} · {{pct}}%',
    chestTier: '상자 등급 {{n}}',
    lootNote: '각 추첨은 표시된 확률로 독립적으로 진행되며, 추첨 내 비율은 이를 나눠 가집니다.',
    kind: { chest: '보물 상자', junk: '고철 더미', egg: '팰 알', cage: '갇힌 팰', pal: '미믹 기습', skillFruit: '스킬 프루트 나무', lotus: '스탯 꽃', mushroom: '버섯', object: '오브젝트' },
    tier: { easy: '쉬움', medium: '보통', hard: '어려움', bonus: '어려움 · 보너스' },
    lotusStat: { workspeed: '작업 속도', attack: '공격', hp: 'HP', stamina: '기력', weight: '무게' },
    poolCount: '가능한 팰 {{count}}종',
    foundIn: '획득 가능한 던전',
    viewLoot: '던전 전리품 보기',
  },
  'pl-PL': {
    title: 'Lochy',
    expBonus: 'Premia EXP ×{{rate}}',
    boss: 'Boss',
    enemies: 'Wrogowie',
    chestLoot: 'Łup ze skrzyń',
    techChest: 'Skrzynia technologiczna',
    bossRewards: 'Nagrody z sali bossa',
    roll: 'Losowanie {{n}} · {{pct}}%',
    chestTier: 'Poziom skrzyni {{n}}',
    lootNote: 'Każde losowanie odbywa się niezależnie z podaną szansą; procenty w obrębie losowania dzielą ją między siebie.',
    kind: { chest: 'Skrzynia skarbów', junk: 'Sterta złomu', egg: 'Jajo Pala', cage: 'Pal w klatce', pal: 'Zasadzka mimika', skillFruit: 'Drzewo owoców umiejętności', lotus: 'Kwiat statystyk', mushroom: 'Grzyb', object: 'Obiekt' },
    tier: { easy: 'Łatwy', medium: 'Średni', hard: 'Trudny', bonus: 'Trudny · bonus' },
    lotusStat: { workspeed: 'Tempo pracy', attack: 'Atak', hp: 'PŻ', stamina: 'Wytrzymałość', weight: 'Waga' },
    poolCount: '{{count}} możliwych pali',
    foundIn: 'Występuje w lochach',
    viewLoot: 'Zobacz łupy z lochu',
  },
  'pt-BR': {
    title: 'Masmorras',
    expBonus: 'Bônus de EXP ×{{rate}}',
    boss: 'Chefe',
    enemies: 'Inimigos',
    chestLoot: 'Saque dos baús',
    techChest: 'Baú de tecnologia',
    bossRewards: 'Recompensas da sala do chefe',
    roll: 'Sorteio {{n}} · {{pct}}%',
    chestTier: 'Nível do baú {{n}}',
    lootNote: 'Cada sorteio acontece de forma independente com a chance mostrada; as porcentagens dentro de um sorteio a compartilham.',
    kind: { chest: 'Baú do tesouro', junk: 'Pilha de sucata', egg: 'Ovo de Pal', cage: 'Pal enjaulado', pal: 'Emboscada mímica', skillFruit: 'Árvore de frutas de habilidade', lotus: 'Flor de atributo', mushroom: 'Cogumelo', object: 'Objeto' },
    tier: { easy: 'Fácil', medium: 'Média', hard: 'Difícil', bonus: 'Difícil · bônus' },
    lotusStat: { workspeed: 'Velocidade de trabalho', attack: 'Ataque', hp: 'PV', stamina: 'Vigor', weight: 'Peso' },
    poolCount: '{{count}} pals possíveis',
    foundIn: 'Encontrado em masmorras',
    viewLoot: 'Ver saque da masmorra',
  },
  'ru-RU': {
    title: 'Подземелья',
    expBonus: 'Бонус опыта ×{{rate}}',
    boss: 'Босс',
    enemies: 'Враги',
    chestLoot: 'Добыча из сундуков',
    techChest: 'Сундук с технологиями',
    bossRewards: 'Награды комнаты босса',
    roll: 'Бросок {{n}} · {{pct}}%',
    chestTier: 'Уровень сундука {{n}}',
    lootNote: 'Каждый бросок происходит независимо с указанным шансом; проценты внутри броска делят его между собой.',
    kind: { chest: 'Сундук с сокровищами', junk: 'Куча хлама', egg: 'Яйцо пала', cage: 'Пал в клетке', pal: 'Засада мимика', skillFruit: 'Дерево плодов навыков', lotus: 'Цветок характеристик', mushroom: 'Гриб', object: 'Объект' },
    tier: { easy: 'Лёгкий', medium: 'Средний', hard: 'Сложный', bonus: 'Сложный · бонус' },
    lotusStat: { workspeed: 'Скорость работы', attack: 'Атака', hp: 'ОЗ', stamina: 'Выносливость', weight: 'Вес' },
    poolCount: 'Возможных палов: {{count}}',
    foundIn: 'Встречается в подземельях',
    viewLoot: 'Посмотреть добычу подземелья',
  },
  'th-TH': {
    title: 'ดันเจี้ยน',
    expBonus: 'โบนัส EXP ×{{rate}}',
    boss: 'บอส',
    enemies: 'ศัตรู',
    chestLoot: 'ของในหีบสมบัติ',
    techChest: 'หีบตำราเทคโนโลยี',
    bossRewards: 'รางวัลห้องบอส',
    roll: 'สุ่มครั้งที่ {{n}} · {{pct}}%',
    chestTier: 'ระดับหีบ {{n}}',
    lootNote: 'การสุ่มแต่ละครั้งเกิดขึ้นอย่างอิสระตามโอกาสที่แสดง เปอร์เซ็นต์ภายในการสุ่มเดียวกันจะแบ่งโอกาสนั้น',
    kind: { chest: 'หีบสมบัติ', junk: 'กองเศษเหล็ก', egg: 'ไข่พัล', cage: 'พัลในกรง', pal: 'มิมิคซุ่มโจมตี', skillFruit: 'ต้นผลสกิล', lotus: 'ดอกไม้เพิ่มค่าสถานะ', mushroom: 'เห็ด', object: 'วัตถุ' },
    tier: { easy: 'ง่าย', medium: 'ปานกลาง', hard: 'ยาก', bonus: 'ยาก · โบนัส' },
    lotusStat: { workspeed: 'ความเร็วทำงาน', attack: 'โจมตี', hp: 'HP', stamina: 'ความอึด', weight: 'น้ำหนัก' },
    poolCount: 'พัลที่เป็นไปได้ {{count}} ตัว',
    foundIn: 'พบได้ในดันเจี้ยน',
    viewLoot: 'ดูของรางวัลดันเจี้ยน',
  },
  'tr-TR': {
    title: 'Zindanlar',
    expBonus: 'EXP bonusu ×{{rate}}',
    boss: 'Boss',
    enemies: 'Düşmanlar',
    chestLoot: 'Sandık ganimeti',
    techChest: 'Teknoloji sandığı',
    bossRewards: 'Boss odası ödülleri',
    roll: 'Çekiliş {{n}} · %{{pct}}',
    chestTier: 'Sandık seviyesi {{n}}',
    lootNote: 'Her çekiliş gösterilen şansla bağımsız yapılır; bir çekiliş içindeki yüzdeler bu şansı paylaşır.',
    kind: { chest: 'Hazine sandığı', junk: 'Hurda yığını', egg: 'Pal yumurtası', cage: 'Kafesteki Pal', pal: 'Mimik pususu', skillFruit: 'Yetenek meyvesi ağacı', lotus: 'Nitelik çiçeği', mushroom: 'Mantar', object: 'Nesne' },
    tier: { easy: 'Kolay', medium: 'Orta', hard: 'Zor', bonus: 'Zor · bonus' },
    lotusStat: { workspeed: 'Çalışma hızı', attack: 'Saldırı', hp: 'HP', stamina: 'Dayanıklılık', weight: 'Ağırlık' },
    poolCount: '{{count}} olası pal',
    foundIn: 'Zindanlarda bulunur',
    viewLoot: 'Zindan ganimetini gör',
  },
  'vi-VN': {
    title: 'Hầm ngục',
    expBonus: 'Thưởng EXP ×{{rate}}',
    boss: 'Trùm',
    enemies: 'Kẻ địch',
    chestLoot: 'Chiến lợi phẩm rương',
    techChest: 'Rương sách công nghệ',
    bossRewards: 'Phần thưởng phòng trùm',
    roll: 'Lượt quay {{n}} · {{pct}}%',
    chestTier: 'Cấp rương {{n}}',
    lootNote: 'Mỗi lượt quay diễn ra độc lập với tỉ lệ hiển thị; các phần trăm trong một lượt chia nhau tỉ lệ đó.',
    kind: { chest: 'Rương kho báu', junk: 'Đống phế liệu', egg: 'Trứng Pal', cage: 'Pal bị nhốt', pal: 'Mimic phục kích', skillFruit: 'Cây quả kỹ năng', lotus: 'Hoa chỉ số', mushroom: 'Nấm', object: 'Vật thể' },
    tier: { easy: 'Dễ', medium: 'Trung bình', hard: 'Khó', bonus: 'Khó · thưởng' },
    lotusStat: { workspeed: 'Tốc độ làm việc', attack: 'Tấn công', hp: 'HP', stamina: 'Thể lực', weight: 'Cân nặng' },
    poolCount: '{{count}} pal có thể xuất hiện',
    foundIn: 'Tìm thấy trong hầm ngục',
    viewLoot: 'Xem chiến lợi phẩm hầm ngục',
  },
  'zh-CN': {
    title: '地下城',
    expBonus: '经验加成 ×{{rate}}',
    boss: '头目',
    enemies: '出现的敌人',
    chestLoot: '宝箱掉落',
    techChest: '技术书宝箱',
    bossRewards: '头目房间奖励',
    roll: '第 {{n}} 次抽取 · {{pct}}%',
    chestTier: '宝箱等级 {{n}}',
    lootNote: '每次抽取按所示概率独立进行；同一次抽取内的百分比按权重分摊该概率。',
    kind: { chest: '宝箱', junk: '废料堆', egg: '帕鲁蛋', cage: '笼中帕鲁', pal: '宝箱怪伏击', skillFruit: '技能果实树', lotus: '属性之花', mushroom: '蘑菇', object: '物件' },
    tier: { easy: '简单', medium: '普通', hard: '困难', bonus: '困难 · 额外' },
    lotusStat: { workspeed: '工作速度', attack: '攻击', hp: '生命', stamina: '耐力', weight: '负重' },
    poolCount: '可能出现 {{count}} 种帕鲁',
    foundIn: '可在以下地下城获得',
    viewLoot: '查看地下城掉落',
  },
  'zh-TW': {
    title: '地下城',
    expBonus: '經驗加成 ×{{rate}}',
    boss: '頭目',
    enemies: '出現的敵人',
    chestLoot: '寶箱掉落',
    techChest: '技術書寶箱',
    bossRewards: '頭目房間獎勵',
    roll: '第 {{n}} 次抽取 · {{pct}}%',
    chestTier: '寶箱等級 {{n}}',
    lootNote: '每次抽取依所示機率獨立進行；同一次抽取內的百分比按權重分攤該機率。',
    kind: { chest: '寶箱', junk: '廢料堆', egg: '帕魯蛋', cage: '籠中帕魯', pal: '寶箱怪伏擊', skillFruit: '技能果實樹', lotus: '屬性之花', mushroom: '蘑菇', object: '物件' },
    tier: { easy: '簡單', medium: '普通', hard: '困難', bonus: '困難 · 額外' },
    lotusStat: { workspeed: '工作速度', attack: '攻擊', hp: '生命', stamina: '耐力', weight: '負重' },
    poolCount: '可能出現 {{count}} 種帕魯',
    foundIn: '可在以下地下城獲得',
    viewLoot: '查看地下城掉落',
  },
}
