import type { Language } from './i18n'

export type MarkerDetailStrings = {
  close: string
  details: string
  comments: string
  scrollArea: string
  collapseSection: string
  expandSection: string
  description: string
  drops: string
  gallery: string
  galleryDescription: string
  uploadImage: string
  galleryReviewNote: string
  commentCount: string
  popular: string
  latest: string
  like: string
  reply: string
  viewReplies: string
  commentPlaceholder: string
  attachImages: string
  attachmentLimit: string
  removeImage: string
  publish: string
  emptyDetails: string
  emptyComments: string
  guestAuthor: string
  justNow: string
  awaitingReview: string
}

const en: MarkerDetailStrings = {
  close: 'Close marker details', details: 'Details', comments: 'Comments', scrollArea: 'Marker content, scrollable',
  collapseSection: 'Collapse {{title}}', expandSection: 'Show all {{title}}', description: 'Marker description', drops: 'Drops',
  gallery: 'Player images', galleryDescription: 'Help other players identify the terrain and entrance', uploadImage: 'Add image',
  galleryReviewNote: 'Images become public after community review. Up to 3 images.', commentCount: '{{count}} comments', popular: 'Popular', latest: 'Latest',
  like: 'Like', reply: 'Reply', viewReplies: 'View {{count}} replies', commentPlaceholder: 'Share useful information about this marker',
  attachImages: 'Attach images', attachmentLimit: 'Up to 3 images', removeImage: 'Remove image', publish: 'Publish',
  emptyDetails: 'No details yet.', emptyComments: 'No comments yet.',
  guestAuthor: 'Guest', justNow: 'Just now', awaitingReview: 'Awaiting review',
}

export const MARKER_DETAIL_STRINGS: Record<Language, MarkerDetailStrings> = {
  'en-US': en,
  'de-DE': { ...en, close: 'Markerdetails schließen', details: 'Details', comments: 'Kommentare', scrollArea: 'Markerinhalt, scrollbar', collapseSection: '{{title}} einklappen', expandSection: 'Alle {{title}} anzeigen', description: 'Markerbeschreibung', drops: 'Beute', gallery: 'Spielerbilder', galleryDescription: 'Hilf anderen Spielern, Gelände und Eingang zu erkennen', uploadImage: 'Bild hochladen', galleryReviewNote: 'Bilder werden nach der Community-Prüfung veröffentlicht. Bis zu 3 Bilder.', commentCount: '{{count}} Kommentare', popular: 'Beliebt', latest: 'Neueste', like: 'Gefällt mir', reply: 'Antworten', viewReplies: '{{count}} Antworten anzeigen', commentPlaceholder: 'Teile nützliche Informationen zu diesem Marker', attachImages: 'Bilder anhängen', attachmentLimit: 'Bis zu 3 Bilder', publish: 'Veröffentlichen', emptyDetails: 'Noch keine weiteren Details. Füge ein Bild hinzu oder hinterlasse einen nützlichen Kommentar.', emptyComments: 'Noch keine Kommentare. Beginne die Unterhaltung.', guestAuthor: 'Gast', justNow: 'Gerade eben', awaitingReview: 'Wird geprüft' },
  'es-ES': { ...en, close: 'Cerrar detalles del marcador', details: 'Detalles', comments: 'Comentarios', scrollArea: 'Contenido del marcador, desplazable', collapseSection: 'Contraer {{title}}', expandSection: 'Mostrar todo: {{title}}', description: 'Descripción del marcador', drops: 'Botín', gallery: 'Imágenes de jugadores', galleryDescription: 'Ayuda a otros jugadores a identificar el terreno y la entrada', uploadImage: 'Subir imagen', galleryReviewNote: 'Las imágenes se publican tras la revisión de la comunidad. Hasta 3 imágenes.', commentCount: '{{count}} comentarios', popular: 'Popular', latest: 'Recientes', like: 'Me gusta', reply: 'Responder', viewReplies: 'Ver {{count}} respuestas', commentPlaceholder: 'Comparte información útil sobre este marcador', attachImages: 'Adjuntar imágenes', attachmentLimit: 'Hasta 3 imágenes', publish: 'Publicar', emptyDetails: 'Aún no hay más detalles. Añade una imagen o deja un comentario útil.', emptyComments: 'Aún no hay comentarios. Inicia la conversación.', guestAuthor: 'Invitado', justNow: 'Ahora mismo', awaitingReview: 'Pendiente de revisión' },
  'es-MX': { ...en, close: 'Cerrar detalles del marcador', details: 'Detalles', comments: 'Comentarios', scrollArea: 'Contenido del marcador, desplazable', collapseSection: 'Contraer {{title}}', expandSection: 'Mostrar todo: {{title}}', description: 'Descripción del marcador', drops: 'Botín', gallery: 'Imágenes de jugadores', galleryDescription: 'Ayuda a otros jugadores a identificar el terreno y la entrada', uploadImage: 'Subir imagen', galleryReviewNote: 'Las imágenes se publican tras la revisión de la comunidad. Hasta 3 imágenes.', commentCount: '{{count}} comentarios', popular: 'Popular', latest: 'Recientes', like: 'Me gusta', reply: 'Responder', viewReplies: 'Ver {{count}} respuestas', commentPlaceholder: 'Comparte información útil sobre este marcador', attachImages: 'Adjuntar imágenes', attachmentLimit: 'Hasta 3 imágenes', publish: 'Publicar', emptyDetails: 'Aún no hay más detalles. Agrega una imagen o deja un comentario útil.', emptyComments: 'Aún no hay comentarios. Inicia la conversación.', guestAuthor: 'Invitado', justNow: 'Ahora mismo', awaitingReview: 'Pendiente de revisión' },
  'fr-FR': { ...en, close: 'Fermer les détails du marqueur', details: 'Détails', comments: 'Commentaires', scrollArea: 'Contenu du marqueur, défilable', collapseSection: 'Réduire {{title}}', expandSection: 'Afficher tout : {{title}}', description: 'Description du marqueur', drops: 'Butin', gallery: 'Images des joueurs', galleryDescription: 'Aidez les autres joueurs à repérer le terrain et l’entrée', uploadImage: 'Importer une image', galleryReviewNote: 'Les images sont publiées après vérification par la communauté. Jusqu’à 3 images.', commentCount: '{{count}} commentaires', popular: 'Populaires', latest: 'Récents', like: 'J’aime', reply: 'Répondre', viewReplies: 'Voir {{count}} réponses', commentPlaceholder: 'Partagez des informations utiles sur ce marqueur', attachImages: 'Joindre des images', attachmentLimit: 'Jusqu’à 3 images', publish: 'Publier', emptyDetails: 'Aucun détail supplémentaire pour l’instant. Ajoutez une image ou laissez un commentaire utile.', emptyComments: 'Aucun commentaire pour l’instant. Lancez la conversation.', guestAuthor: 'Invité', justNow: 'À l’instant', awaitingReview: 'En attente de vérification' },
  'id-ID': { ...en, close: 'Tutup detail penanda', details: 'Detail', comments: 'Komentar', scrollArea: 'Konten penanda, dapat digulir', collapseSection: 'Tutup {{title}}', expandSection: 'Tampilkan semua {{title}}', description: 'Deskripsi penanda', drops: 'Jarahan', gallery: 'Gambar pemain', galleryDescription: 'Bantu pemain lain mengenali medan dan pintu masuk', uploadImage: 'Unggah gambar', galleryReviewNote: 'Gambar dipublikasikan setelah ditinjau komunitas. Maksimal 3 gambar.', commentCount: '{{count}} komentar', popular: 'Populer', latest: 'Terbaru', like: 'Suka', reply: 'Balas', viewReplies: 'Lihat {{count}} balasan', commentPlaceholder: 'Bagikan informasi bermanfaat tentang penanda ini', attachImages: 'Lampirkan gambar', attachmentLimit: 'Maksimal 3 gambar', publish: 'Terbitkan', emptyDetails: 'Belum ada detail tambahan. Tambahkan gambar atau tinggalkan komentar yang bermanfaat.', emptyComments: 'Belum ada komentar. Mulai percakapan.', guestAuthor: 'Tamu', justNow: 'Baru saja', awaitingReview: 'Menunggu peninjauan' },
  'it-IT': { ...en, close: 'Chiudi dettagli indicatore', details: 'Dettagli', comments: 'Commenti', scrollArea: 'Contenuto dell’indicatore, scorrevole', collapseSection: 'Comprimi {{title}}', expandSection: 'Mostra tutto: {{title}}', description: 'Descrizione indicatore', drops: 'Bottino', gallery: 'Immagini dei giocatori', galleryDescription: 'Aiuta gli altri giocatori a riconoscere il terreno e l’ingresso', uploadImage: 'Carica immagine', galleryReviewNote: 'Le immagini vengono pubblicate dopo la revisione della community. Fino a 3 immagini.', commentCount: '{{count}} commenti', popular: 'Popolari', latest: 'Recenti', like: 'Mi piace', reply: 'Rispondi', viewReplies: 'Mostra {{count}} risposte', commentPlaceholder: 'Condividi informazioni utili su questo indicatore', attachImages: 'Allega immagini', attachmentLimit: 'Fino a 3 immagini', publish: 'Pubblica', emptyDetails: 'Nessun altro dettaglio per ora. Aggiungi un’immagine o lascia un commento utile.', emptyComments: 'Nessun commento per ora. Inizia la conversazione.', guestAuthor: 'Ospite', justNow: 'Adesso', awaitingReview: 'In attesa di revisione' },
  'ja-JP': { ...en, close: 'マーカー詳細を閉じる', details: '詳細', comments: 'コメント', scrollArea: 'マーカーの内容（スクロール可能）', collapseSection: '{{title}}を折りたたむ', expandSection: '{{title}}をすべて表示', description: 'マーカー説明', drops: '討伐ドロップ', gallery: 'プレイヤー画像', galleryDescription: '他のプレイヤーが地形や入口を確認できるように協力しましょう', uploadImage: '画像をアップロード', galleryReviewNote: '画像はコミュニティの審査後に公開されます。最大3枚。', commentCount: 'コメント{{count}}件', popular: '人気', latest: '新着', like: 'いいね', reply: '返信', viewReplies: '返信{{count}}件を表示', commentPlaceholder: 'このマーカーについて役立つ情報を共有しましょう', attachImages: '画像を添付', attachmentLimit: '最大3枚', publish: '投稿', emptyDetails: 'まだ詳細情報がありません。画像を追加するか、役立つコメントを残してください。', emptyComments: 'まだコメントがありません。最初のコメントを投稿しましょう。', guestAuthor: 'ゲスト', justNow: 'たった今', awaitingReview: '審査中' },
  'ko-KR': { ...en, close: '마커 상세 닫기', details: '상세', comments: '댓글', scrollArea: '스크롤 가능한 마커 내용', collapseSection: '{{title}} 접기', expandSection: '{{title}} 모두 보기', description: '마커 설명', drops: '처치 보상', gallery: '플레이어 이미지', galleryDescription: '다른 플레이어가 지형과 입구를 확인하도록 도와주세요', uploadImage: '이미지 업로드', galleryReviewNote: '이미지는 커뮤니티 검토 후 공개됩니다. 최대 3장.', commentCount: '댓글 {{count}}개', popular: '인기', latest: '최신', like: '좋아요', reply: '답글', viewReplies: '답글 {{count}}개 보기', commentPlaceholder: '이 마커에 유용한 정보를 공유하세요', attachImages: '이미지 첨부', attachmentLimit: '최대 3장', publish: '게시', emptyDetails: '아직 추가 정보가 없습니다. 이미지를 추가하거나 유용한 댓글을 남겨 주세요.', emptyComments: '아직 댓글이 없습니다. 첫 댓글을 남겨 보세요.', guestAuthor: '손님', justNow: '방금', awaitingReview: '검토 대기 중' },
  'pl-PL': { ...en, close: 'Zamknij szczegóły znacznika', details: 'Szczegóły', comments: 'Komentarze', scrollArea: 'Treść znacznika, przewijalna', collapseSection: 'Zwiń {{title}}', expandSection: 'Pokaż wszystko: {{title}}', description: 'Opis znacznika', drops: 'Łup', gallery: 'Zdjęcia graczy', galleryDescription: 'Pomóż innym graczom rozpoznać teren i wejście', uploadImage: 'Prześlij zdjęcie', galleryReviewNote: 'Zdjęcia są publikowane po weryfikacji przez społeczność. Maksymalnie 3 zdjęcia.', commentCount: 'Komentarze: {{count}}', popular: 'Popularne', latest: 'Najnowsze', like: 'Lubię', reply: 'Odpowiedz', viewReplies: 'Pokaż {{count}} odpowiedzi', commentPlaceholder: 'Podziel się przydatnymi informacjami o tym znaczniku', attachImages: 'Dołącz zdjęcia', attachmentLimit: 'Maksymalnie 3 zdjęcia', publish: 'Opublikuj', emptyDetails: 'Na razie brak dodatkowych szczegółów. Dodaj zdjęcie lub zostaw przydatny komentarz.', emptyComments: 'Na razie brak komentarzy. Rozpocznij rozmowę.', guestAuthor: 'Gość', justNow: 'Właśnie teraz', awaitingReview: 'Oczekuje na weryfikację' },
  'pt-BR': { ...en, close: 'Fechar detalhes do marcador', details: 'Detalhes', comments: 'Comentários', scrollArea: 'Conteúdo do marcador, rolável', collapseSection: 'Recolher {{title}}', expandSection: 'Mostrar tudo: {{title}}', description: 'Descrição do marcador', drops: 'Itens obtidos', gallery: 'Imagens de jogadores', galleryDescription: 'Ajude outros jogadores a identificar o terreno e a entrada', uploadImage: 'Enviar imagem', galleryReviewNote: 'As imagens ficam públicas após a revisão da comunidade. Até 3 imagens.', commentCount: '{{count}} comentários', popular: 'Populares', latest: 'Recentes', like: 'Curtir', reply: 'Responder', viewReplies: 'Ver {{count}} respostas', commentPlaceholder: 'Compartilhe informações úteis sobre este marcador', attachImages: 'Anexar imagens', attachmentLimit: 'Até 3 imagens', publish: 'Publicar', emptyDetails: 'Ainda não há mais detalhes. Adicione uma imagem ou deixe um comentário útil.', emptyComments: 'Ainda não há comentários. Comece a conversa.', guestAuthor: 'Visitante', justNow: 'Agora mesmo', awaitingReview: 'Aguardando revisão' },
  'ru-RU': { ...en, close: 'Закрыть сведения о метке', details: 'Подробности', comments: 'Комментарии', scrollArea: 'Содержимое метки, с прокруткой', collapseSection: 'Свернуть: {{title}}', expandSection: 'Показать все: {{title}}', description: 'Описание метки', drops: 'Добыча', gallery: 'Снимки игроков', galleryDescription: 'Помогите другим игрокам распознать местность и вход', uploadImage: 'Загрузить изображение', galleryReviewNote: 'Изображения публикуются после проверки сообществом. До 3 изображений.', commentCount: 'Комментариев: {{count}}', popular: 'Популярные', latest: 'Новые', like: 'Нравится', reply: 'Ответить', viewReplies: 'Показать ответы: {{count}}', commentPlaceholder: 'Поделитесь полезной информацией об этой метке', attachImages: 'Прикрепить изображения', attachmentLimit: 'До 3 изображений', publish: 'Опубликовать', emptyDetails: 'Пока нет дополнительных сведений. Добавьте изображение или оставьте полезный комментарий.', emptyComments: 'Пока нет комментариев. Начните обсуждение.', guestAuthor: 'Гость', justNow: 'Только что', awaitingReview: 'Ожидает проверки' },
  'th-TH': { ...en, close: 'ปิดรายละเอียดหมุด', details: 'รายละเอียด', comments: 'ความคิดเห็น', scrollArea: 'เนื้อหาของหมุด เลื่อนได้', collapseSection: 'ย่อ {{title}}', expandSection: 'แสดง {{title}} ทั้งหมด', description: 'คำอธิบายหมุด', drops: 'ไอเทมที่ดรอป', gallery: 'ภาพจากผู้เล่น', galleryDescription: 'ช่วยผู้เล่นคนอื่นสังเกตภูมิประเทศและทางเข้า', uploadImage: 'อัปโหลดภาพ', galleryReviewNote: 'ภาพจะเผยแพร่หลังการตรวจสอบจากชุมชน สูงสุด 3 ภาพ', commentCount: 'ความคิดเห็น {{count}} รายการ', popular: 'ยอดนิยม', latest: 'ล่าสุด', like: 'ถูกใจ', reply: 'ตอบกลับ', viewReplies: 'ดูการตอบกลับ {{count}} รายการ', commentPlaceholder: 'แบ่งปันข้อมูลที่เป็นประโยชน์เกี่ยวกับหมุดนี้', attachImages: 'แนบภาพ', attachmentLimit: 'สูงสุด 3 ภาพ', publish: 'เผยแพร่', emptyDetails: 'ยังไม่มีรายละเอียดเพิ่มเติม เพิ่มภาพหรือฝากความคิดเห็นที่เป็นประโยชน์ได้เลย', emptyComments: 'ยังไม่มีความคิดเห็น มาเริ่มการสนทนากันเลย', guestAuthor: 'ผู้เยี่ยมชม', justNow: 'เมื่อสักครู่', awaitingReview: 'รอการตรวจสอบ' },
  'tr-TR': { ...en, close: 'İşaret ayrıntılarını kapat', details: 'Ayrıntılar', comments: 'Yorumlar', scrollArea: 'İşaret içeriği, kaydırılabilir', collapseSection: '{{title}} bölümünü daralt', expandSection: 'Tüm {{title}} göster', description: 'İşaret açıklaması', drops: 'Düşen eşyalar', gallery: 'Oyuncu görselleri', galleryDescription: 'Diğer oyuncuların araziyi ve girişi tanımasına yardım edin', uploadImage: 'Görsel yükle', galleryReviewNote: 'Görseller topluluk incelemesinden sonra yayınlanır. En fazla 3 görsel.', commentCount: '{{count}} yorum', popular: 'Popüler', latest: 'En yeni', like: 'Beğen', reply: 'Yanıtla', viewReplies: '{{count}} yanıtı görüntüle', commentPlaceholder: 'Bu işaret hakkında faydalı bilgiler paylaşın', attachImages: 'Görsel ekle', attachmentLimit: 'En fazla 3 görsel', publish: 'Yayınla', emptyDetails: 'Henüz başka ayrıntı yok. Bir görsel ekleyin veya faydalı bir yorum bırakın.', emptyComments: 'Henüz yorum yok. Sohbeti başlatın.', guestAuthor: 'Konuk', justNow: 'Az önce', awaitingReview: 'İnceleme bekliyor' },
  'vi-VN': { ...en, close: 'Đóng chi tiết điểm', details: 'Chi tiết', comments: 'Bình luận', scrollArea: 'Nội dung điểm, có thể cuộn', collapseSection: 'Thu gọn {{title}}', expandSection: 'Hiện tất cả {{title}}', description: 'Mô tả điểm', drops: 'Vật phẩm rơi', gallery: 'Ảnh người chơi', galleryDescription: 'Giúp người chơi khác nhận ra địa hình và lối vào', uploadImage: 'Tải ảnh lên', galleryReviewNote: 'Ảnh sẽ công khai sau khi cộng đồng kiểm duyệt. Tối đa 3 ảnh.', commentCount: '{{count}} bình luận', popular: 'Phổ biến', latest: 'Mới nhất', like: 'Thích', reply: 'Trả lời', viewReplies: 'Xem {{count}} trả lời', commentPlaceholder: 'Chia sẻ thông tin hữu ích về điểm này', attachImages: 'Đính kèm ảnh', attachmentLimit: 'Tối đa 3 ảnh', publish: 'Đăng', emptyDetails: 'Chưa có thông tin bổ sung. Hãy thêm ảnh hoặc để lại bình luận hữu ích.', emptyComments: 'Chưa có bình luận. Hãy bắt đầu cuộc trò chuyện.', guestAuthor: 'Khách', justNow: 'Vừa xong', awaitingReview: 'Đang chờ kiểm duyệt' },
  'zh-CN': { ...en, close: '关闭点位详情', details: '详情', comments: '留言', scrollArea: '点位内容，可滚动', collapseSection: '收起{{title}}', expandSection: '展示全部{{title}}', description: '点位说明', drops: '掉落物', gallery: '玩家图片', galleryDescription: '帮助其他玩家确认地形与入口', uploadImage: '添加图片', galleryReviewNote: '图片经社区审核后公开，最多上传 3 张。', commentCount: '{{count}} 条留言', popular: '热门', latest: '最新', like: '点赞', reply: '回复', viewReplies: '查看 {{count}} 条回复', commentPlaceholder: '分享这个点位的实用信息', attachImages: '添加图片', attachmentLimit: '最多 3 张', removeImage: '删除图片', publish: '发布', emptyDetails: '暂无详情', emptyComments: '暂无留言', guestAuthor: '访客', justNow: '刚刚', awaitingReview: '等待审核' },
  'zh-TW': { ...en, close: '關閉點位詳情', details: '詳情', comments: '留言', scrollArea: '點位內容，可捲動', collapseSection: '收起{{title}}', expandSection: '顯示全部{{title}}', description: '點位說明', drops: '掉落物', gallery: '玩家圖片', galleryDescription: '幫助其他玩家確認地形與入口', uploadImage: '加入圖片', galleryReviewNote: '圖片經社群審核後公開，最多上傳 3 張。', commentCount: '{{count}} 則留言', popular: '熱門', latest: '最新', like: '讚', reply: '回覆', viewReplies: '查看 {{count}} 則回覆', commentPlaceholder: '分享這個點位的實用資訊', attachImages: '加入圖片', attachmentLimit: '最多 3 張', removeImage: '刪除圖片', publish: '發佈', emptyDetails: '暫無詳情', emptyComments: '暫無留言', guestAuthor: '訪客', justNow: '剛剛', awaitingReview: '等待審核' },
}
