import type { Language } from './i18n'

// Pal-encyclopedia strings, merged into the `translation` namespace under a
// `pal` key (see i18n.ts). Data-driven labels (element / work / skill / item /
// pal names) come from the locale data files, not here — this table only holds
// the encyclopedia's own UI chrome.
export interface PalStrings {
  title: string
  searchPlaceholder: string
  count: string
  loading: string
  notFound: string
  backToList: string
  viewInEncyclopedia: string
  viewOnMap: string
  noSpawns: string
  breedingOnly: string
  summonOnly: string
  summonMaterials: string
  spawnWild: string
  spawnBoss: string
  /** Short legend label for night-restricted spawn points. */
  nightOnly: string
  /** Popup/map note when a spawn (or all of a pal's spawns) is night-only. */
  nightOnlyNote: string
  lv: string
  skill: string
  power: string
  cooldown: string
  range: string
  type: string
  melee: string
  ranged: string
  genderless: string
  rankScaling: string
  effectTime: string
  cost: string
  toggle: string
  condensation: string
  unlockItem: string
  bredFrom: string
  openBreeding: string
  noBreeding: string
  workBestCaption: string
  condenseTitle: string
  /** Base Stats caption explaining the green "+N" trust-growth suffix
   *  (rendered after a coloured "+N" chip, hence the leading dash). */
  friendshipNote: string
  /** Red level badge on summon materials ({{n}} = required boss level). */
  summonLevel: string
  summonEggPool: string
  firstDefeatReward: string
  unlocksTechNote: string
  enemyScalingNote: string
  /** Enemy-scaling multiplier rows (HP / cooldown reuse stat.hp / cooldown). */
  dmgTaken: string
  dmgDealt: string
  /** Spawn-map legend for the game's Paldeck habitat overlay. */
  habitatLabel: string
  habitatDay: string
  habitatNight: string
  yes: string
  section: {
    description: string
    stats: string
    details: string
    work: string
    partnerSkill: string
    activeSkills: string
    passives: string
    drops: string
    bossDrops: string
    spawns: string
    breeding: string
    dungeons: string
    fishing: string
    unlocksTech: string
    enemyScaling: string
  }
  stat: {
    hp: string
    meleeAttack: string
    shotAttack: string
    defense: string
    support: string
    craftSpeed: string
    stamina: string
    foodAmount: string
    maxFullStomach: string
    captureRate: string
    price: string
    size: string
    rarity: string
    egg: string
    gender: string
    slowWalkSpeed: string
    walkSpeed: string
    runSpeed: string
    rideSprintSpeed: string
    transportSpeed: string
    swimSpeed: string
    predator: string
    expRatio: string
  }
}

export const PAL_STRINGS: Record<Language, PalStrings> = {
  'en-US': {
    title: 'Paldeck',
    searchPlaceholder: 'Search Pals…',
    count: '{{count}} Pals',
    loading: 'Loading…',
    notFound: 'No Pal found for "{{id}}".',
    backToList: 'Back to Paldeck',
    viewInEncyclopedia: 'View in Paldeck →',
    viewOnMap: 'View on full map',
    noSpawns: 'This Pal has no known spawn locations.',
    breedingOnly: 'Not found in the wild — obtainable through breeding.',
    summonOnly: 'Not found in the wild — obtainable by summoning.',
    summonMaterials: 'Summon materials',
    spawnWild: 'Wild',
    spawnBoss: 'Boss',
    nightOnly: 'Night',
    nightOnlyNote: 'Only appears at night.',
    lv: 'Lv',
    skill: 'Skill',
    power: 'Power',
    cooldown: 'Cooldown',
    range: 'Range',
    type: 'Type',
    melee: 'Melee',
    ranged: 'Ranged',
    genderless: 'Genderless',
    rankScaling: 'Rank scaling',
    effectTime: 'Duration',
    cost: 'Activation cost',
    toggle: 'Toggle skill',
    condensation: 'Unlocked and strengthened via condensation (Lv.1–5).',
    unlockItem: 'Unlock Item',
    bredFrom: 'Bred from',
    openBreeding: 'Open breeding calculator →',
    noBreeding: 'No breeding combinations produce this Pal.',
    workBestCaption: '★ Best work suitability — Pal Essence Condenser stars upgrade it first.',
    condenseTitle: 'Pal Essence Condenser upgrades',
    friendshipNote: '— stat gain per friendship (trust) rank, up to rank 10.',
    summonLevel: 'Boss Lv{{n}}',
    summonEggPool: 'Reward pool',
    firstDefeatReward: 'First-defeat reward',
    unlocksTechNote: 'Capturing this Pal unlocks:',
    enemyScalingNote: 'Multipliers applied to the wild alpha / boss form.',
    dmgTaken: 'Damage taken',
    dmgDealt: 'Damage dealt',
    habitatLabel: 'Paldex habitat',
    habitatDay: 'Day',
    habitatNight: 'Night',
    yes: 'Yes',
    section: {
      description: 'Description',
      stats: 'Base Stats',
      details: 'Details',
      work: 'Work Suitability',
      partnerSkill: 'Partner Skill',
      activeSkills: 'Active Skills',
      passives: 'Passive Skills',
      drops: 'Drops',
      bossDrops: 'Boss Drops',
      spawns: 'Spawn Locations',
      breeding: 'Breeding',
      dungeons: 'Found in Dungeons',
      fishing: 'Caught by Fishing',
      unlocksTech: 'Unlocks Technology',
      enemyScaling: 'Enemy Scaling',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Melee Attack',
      shotAttack: 'Attack',
      defense: 'Defense',
      support: 'Support',
      craftSpeed: 'Work Speed',
      stamina: 'Stamina',
      foodAmount: 'Food',
      maxFullStomach: 'Max Hunger',
      captureRate: 'Capture Rate',
      price: 'Gold',
      size: 'Size',
      rarity: 'Rarity',
      egg: 'Egg',
      gender: 'Gender',
      slowWalkSpeed: 'Slow Walk',
      walkSpeed: 'Walk Speed',
      runSpeed: 'Run Speed',
      rideSprintSpeed: 'Ride Sprint',
      transportSpeed: 'Transport Speed',
      swimSpeed: 'Swim Speed',
      predator: 'Predator',
      expRatio: 'EXP yield',
    },
  },
  'de-DE': {
    title: 'Paldex',
    searchPlaceholder: 'Pals suchen…',
    count: '{{count}} Pals',
    loading: 'Wird geladen…',
    notFound: 'Kein Pal für „{{id}}" gefunden.',
    backToList: 'Zurück zur Paldex',
    viewInEncyclopedia: 'In der Paldex ansehen →',
    viewOnMap: 'Auf voller Karte ansehen',
    noSpawns: 'Für dieses Pal sind keine Fundorte bekannt.',
    breedingOnly: 'Kommt nicht in der Wildnis vor – nur durch Zucht erhältlich.',
    summonOnly: 'Kommt nicht in der Wildnis vor – durch Beschwörung erhältlich.',
    summonMaterials: 'Beschwörungsmaterial',
    spawnWild: 'Wild',
    spawnBoss: 'Boss',
    nightOnly: 'Nachts',
    nightOnlyNote: 'Erscheint nur nachts.',
    lv: 'Stufe',
    skill: 'Fähigkeit',
    power: 'Stärke',
    cooldown: 'Abklingzeit',
    range: 'Reichweite',
    type: 'Typ',
    melee: 'Nahkampf',
    ranged: 'Fernkampf',
    genderless: 'Geschlechtslos',
    rankScaling: 'Rang-Skalierung',
    effectTime: 'Dauer',
    cost: 'Aktivierungskosten',
    toggle: 'Umschaltbar',
    condensation: 'Durch Verdichtung freigeschaltet und verstärkt (Stufe 1–5).',
    unlockItem: 'Freischaltobjekt',
    bredFrom: 'Gezüchtet aus',
    openBreeding: 'Zucht-Rechner öffnen →',
    noBreeding: 'Keine Zuchtkombination erzeugt dieses Pal.',
    workBestCaption: '★ Beste Arbeitseignung – die Sterne des Pal-Entsafters verbessern sie zuerst.',
    condenseTitle: 'Pal-Entsafter: Verbesserungen',
    friendshipNote: '– Wertzuwachs pro Zutraulichkeits-Rang, bis Rang 10.',
    summonLevel: 'Boss Stufe {{n}}',
    summonEggPool: 'Belohnungspool',
    firstDefeatReward: 'Belohnung für den ersten Sieg',
    unlocksTechNote: 'Der Fang dieses Pals schaltet frei:',
    enemyScalingNote: 'Multiplikatoren für die wilde Alpha-/Boss-Form.',
    dmgTaken: 'Erlittener Schaden',
    dmgDealt: 'Verursachter Schaden',
    habitatLabel: 'Paldex-Lebensraum',
    habitatDay: 'Tag',
    habitatNight: 'Nacht',
    yes: 'Ja',
    section: {
      description: 'Beschreibung',
      stats: 'Basiswerte',
      details: 'Details',
      work: 'Arbeitseignung',
      partnerSkill: 'Partner-Fähigkeit',
      activeSkills: 'Aktive Fähigkeiten',
      passives: 'Passive Fähigkeiten',
      drops: 'Beute',
      bossDrops: 'Boss-Beute',
      spawns: 'Fundorte',
      breeding: 'Zucht',
      dungeons: 'In Dungeons zu finden',
      fishing: 'Durch Angeln erhältlich',
      unlocksTech: 'Schaltet Technologie frei',
      enemyScaling: 'Gegner-Skalierung',
    },
    stat: {
      hp: 'LP',
      meleeAttack: 'Nahkampfangriff',
      shotAttack: 'Angriff',
      defense: 'Verteidigung',
      support: 'Unterstützung',
      craftSpeed: 'Arbeitstempo',
      stamina: 'Ausdauer',
      foodAmount: 'Nahrung',
      maxFullStomach: 'Max. Sattheit',
      captureRate: 'Fangrate',
      price: 'Gold',
      size: 'Größe',
      rarity: 'Seltenheit',
      egg: 'Ei',
      gender: 'Geschlecht',
      slowWalkSpeed: 'Langsames Gehen',
      walkSpeed: 'Gehtempo',
      runSpeed: 'Lauftempo',
      rideSprintSpeed: 'Reit-Sprint',
      transportSpeed: 'Transporttempo',
      swimSpeed: 'Schwimmtempo',
      predator: 'Prädator',
      expRatio: 'EP-Multiplikator',
    },
  },
  'es-ES': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Cargando…',
    notFound: 'No se encontró ningún Pal para "{{id}}".',
    backToList: 'Volver a la Paldex',
    viewInEncyclopedia: 'Ver en la Paldex →',
    viewOnMap: 'Ver en el mapa completo',
    noSpawns: 'Este Pal no tiene ubicaciones de aparición conocidas.',
    breedingOnly: 'No aparece en la naturaleza; se obtiene mediante crianza.',
    summonOnly: 'No aparece en la naturaleza; se obtiene por invocación.',
    summonMaterials: 'Materiales de invocación',
    spawnWild: 'Salvaje',
    spawnBoss: 'Jefe',
    nightOnly: 'Nocturno',
    nightOnlyNote: 'Solo aparece de noche.',
    lv: 'Nv',
    skill: 'Habilidad',
    power: 'Poder',
    cooldown: 'Enfriamiento',
    range: 'Alcance',
    type: 'Tipo',
    melee: 'Cuerpo a cuerpo',
    ranged: 'A distancia',
    genderless: 'Sin género',
    rankScaling: 'Escala por rango',
    effectTime: 'Duración',
    cost: 'Coste de activación',
    toggle: 'Habilidad conmutable',
    condensation: 'Se desbloquea y refuerza mediante condensación (Nv.1–5).',
    unlockItem: 'Objeto de desbloqueo',
    bredFrom: 'Criado a partir de',
    openBreeding: 'Abrir calculadora de crianza →',
    noBreeding: 'Ninguna combinación de crianza produce este Pal.',
    workBestCaption: '★ Mejor aptitud de trabajo: las estrellas de la Cápsula de concentrado Pal la mejoran primero.',
    condenseTitle: 'Mejoras de la Cápsula de concentrado Pal',
    friendshipNote: '— aumento de estadísticas por rango de confianza, hasta el rango 10.',
    summonLevel: 'Jefe Nv{{n}}',
    summonEggPool: 'Grupo de recompensas',
    firstDefeatReward: 'Recompensa por primera victoria',
    unlocksTechNote: 'Capturar este Pal desbloquea:',
    enemyScalingNote: 'Multiplicadores aplicados a la forma alfa/jefe salvaje.',
    dmgTaken: 'Daño recibido',
    dmgDealt: 'Daño infligido',
    habitatLabel: 'Hábitat de la Paldex',
    habitatDay: 'Día',
    habitatNight: 'Noche',
    yes: 'Sí',
    section: {
      description: 'Descripción',
      stats: 'Estadísticas base',
      details: 'Detalles',
      work: 'Aptitud laboral',
      partnerSkill: 'Habilidad de compañero',
      activeSkills: 'Habilidades activas',
      passives: 'Habilidades pasivas',
      drops: 'Botín',
      bossDrops: 'Botín de jefe',
      spawns: 'Ubicaciones de aparición',
      breeding: 'Crianza',
      dungeons: 'Aparece en mazmorras',
      fishing: 'Se obtiene pescando',
      unlocksTech: 'Desbloquea tecnología',
      enemyScaling: 'Escalado de enemigos',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Ataque cuerpo a cuerpo',
      shotAttack: 'Ataque',
      defense: 'Defensa',
      support: 'Apoyo',
      craftSpeed: 'Velocidad de trabajo',
      stamina: 'Aguante',
      foodAmount: 'Comida',
      maxFullStomach: 'Saciedad máx.',
      captureRate: 'Índice de captura',
      price: 'Oro',
      size: 'Tamaño',
      rarity: 'Rareza',
      egg: 'Huevo',
      gender: 'Género',
      slowWalkSpeed: 'Vel. al andar',
      walkSpeed: 'Vel. al caminar',
      runSpeed: 'Vel. al correr',
      rideSprintSpeed: 'Vel. montura',
      transportSpeed: 'Vel. transporte',
      swimSpeed: 'Vel. al nadar',
      predator: 'Depredador',
      expRatio: 'Multiplicador de EXP',
    },
  },
  'es-MX': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Cargando…',
    notFound: 'No se encontró ningún Pal para "{{id}}".',
    backToList: 'Volver a la Paldex',
    viewInEncyclopedia: 'Ver en la Paldex →',
    viewOnMap: 'Ver en el mapa completo',
    noSpawns: 'Este Pal no tiene ubicaciones de aparición conocidas.',
    breedingOnly: 'No aparece en la naturaleza; se obtiene mediante crianza.',
    summonOnly: 'No aparece en la naturaleza; se obtiene por invocación.',
    summonMaterials: 'Materiales de invocación',
    spawnWild: 'Salvaje',
    spawnBoss: 'Jefe',
    nightOnly: 'Nocturno',
    nightOnlyNote: 'Solo aparece de noche.',
    lv: 'Nv',
    skill: 'Habilidad',
    power: 'Poder',
    cooldown: 'Enfriamiento',
    range: 'Alcance',
    type: 'Tipo',
    melee: 'Cuerpo a cuerpo',
    ranged: 'A distancia',
    genderless: 'Sin género',
    rankScaling: 'Escala por rango',
    effectTime: 'Duración',
    cost: 'Coste de activación',
    toggle: 'Habilidad conmutable',
    condensation: 'Se desbloquea y refuerza mediante condensación (Nv.1–5).',
    unlockItem: 'Objeto de desbloqueo',
    bredFrom: 'Criado a partir de',
    openBreeding: 'Abrir calculadora de crianza →',
    noBreeding: 'Ninguna combinación de crianza produce este Pal.',
    workBestCaption: '★ Mejor aptitud de trabajo: las estrellas de la Cápsula de concentrado Pal la mejoran primero.',
    condenseTitle: 'Mejoras de la Cápsula de concentrado Pal',
    friendshipNote: '— aumento de estadísticas por rango de confianza, hasta el rango 10.',
    summonLevel: 'Jefe Nv{{n}}',
    summonEggPool: 'Grupo de recompensas',
    firstDefeatReward: 'Recompensa por primera victoria',
    unlocksTechNote: 'Capturar este Pal desbloquea:',
    enemyScalingNote: 'Multiplicadores aplicados a la forma alfa/jefe salvaje.',
    dmgTaken: 'Daño recibido',
    dmgDealt: 'Daño infligido',
    habitatLabel: 'Hábitat de la Paldex',
    habitatDay: 'Día',
    habitatNight: 'Noche',
    yes: 'Sí',
    section: {
      description: 'Descripción',
      stats: 'Estadísticas base',
      details: 'Detalles',
      work: 'Aptitud laboral',
      partnerSkill: 'Habilidad de compañero',
      activeSkills: 'Habilidades activas',
      passives: 'Habilidades pasivas',
      drops: 'Botín',
      bossDrops: 'Botín de jefe',
      spawns: 'Ubicaciones de aparición',
      breeding: 'Crianza',
      dungeons: 'Aparece en mazmorras',
      fishing: 'Se obtiene pescando',
      unlocksTech: 'Desbloquea tecnología',
      enemyScaling: 'Escalado de enemigos',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Ataque cuerpo a cuerpo',
      shotAttack: 'Ataque',
      defense: 'Defensa',
      support: 'Apoyo',
      craftSpeed: 'Velocidad de trabajo',
      stamina: 'Aguante',
      foodAmount: 'Comida',
      maxFullStomach: 'Saciedad máx.',
      captureRate: 'Índice de captura',
      price: 'Oro',
      size: 'Tamaño',
      rarity: 'Rareza',
      egg: 'Huevo',
      gender: 'Género',
      slowWalkSpeed: 'Vel. al andar',
      walkSpeed: 'Vel. al caminar',
      runSpeed: 'Vel. al correr',
      rideSprintSpeed: 'Vel. montura',
      transportSpeed: 'Vel. transporte',
      swimSpeed: 'Vel. al nadar',
      predator: 'Depredador',
      expRatio: 'Multiplicador de EXP',
    },
  },
  'fr-FR': {
    title: 'Paldex',
    searchPlaceholder: 'Rechercher des Pals…',
    count: '{{count}} Pals',
    loading: 'Chargement…',
    notFound: 'Aucun Pal trouvé pour « {{id}} ».',
    backToList: 'Retour à la Paldex',
    viewInEncyclopedia: 'Voir dans la Paldex →',
    viewOnMap: 'Voir sur la carte complète',
    noSpawns: "Ce Pal n'a aucun lieu d'apparition connu.",
    breedingOnly: "Absent à l'état sauvage — à obtenir par élevage.",
    summonOnly: "Absent à l'état sauvage — à obtenir par invocation.",
    summonMaterials: "Matériaux d'invocation",
    spawnWild: 'Sauvage',
    spawnBoss: 'Boss',
    nightOnly: 'Nuit',
    nightOnlyNote: 'N’apparaît que la nuit.',
    lv: 'Niv',
    skill: 'Compétence',
    power: 'Puissance',
    cooldown: 'Recharge',
    range: 'Portée',
    type: 'Type',
    melee: 'Mêlée',
    ranged: 'À distance',
    genderless: 'Asexué',
    rankScaling: 'Progression par rang',
    effectTime: 'Durée',
    cost: "Coût d'activation",
    toggle: 'Compétence à activer',
    condensation: 'Débloqué et renforcé par condensation (Niv.1–5).',
    unlockItem: 'Objet de déblocage',
    bredFrom: 'Issu de',
    openBreeding: "Ouvrir le calculateur d'élevage →",
    noBreeding: 'Aucune combinaison ne produit ce Pal.',
    workBestCaption: '★ Meilleure aptitude au travail — les étoiles de la Capsule d’essence de Pal l’améliorent en premier.',
    condenseTitle: 'Améliorations de la Capsule d’essence de Pal',
    friendshipNote: '— gain de statistiques par rang de confiance, jusqu’au rang 10.',
    summonLevel: 'Boss Niv{{n}}',
    summonEggPool: 'Récompenses possibles',
    firstDefeatReward: 'Récompense de première victoire',
    unlocksTechNote: 'Capturer ce Pal débloque :',
    enemyScalingNote: 'Multiplicateurs appliqués à la forme alpha/boss sauvage.',
    dmgTaken: 'Dégâts subis',
    dmgDealt: 'Dégâts infligés',
    habitatLabel: 'Habitat du Paldex',
    habitatDay: 'Jour',
    habitatNight: 'Nuit',
    yes: 'Oui',
    section: {
      description: 'Description',
      stats: 'Statistiques de base',
      details: 'Détails',
      work: 'Aptitude au travail',
      partnerSkill: 'Compétence de partenaire',
      activeSkills: 'Compétences actives',
      passives: 'Compétences passives',
      drops: 'Butin',
      bossDrops: 'Butin de boss',
      spawns: "Lieux d'apparition",
      breeding: 'Élevage',
      dungeons: 'Présent dans les donjons',
      fishing: 'Obtenu à la pêche',
      unlocksTech: 'Débloque une technologie',
      enemyScaling: 'Multiplicateurs de boss',
    },
    stat: {
      hp: 'PV',
      meleeAttack: 'Attaque de mêlée',
      shotAttack: 'Attaque',
      defense: 'Défense',
      support: 'Soutien',
      craftSpeed: 'Vitesse de travail',
      stamina: 'Endurance',
      foodAmount: 'Nourriture',
      maxFullStomach: 'Satiété max.',
      captureRate: 'Taux de capture',
      price: 'Or',
      size: 'Taille',
      rarity: 'Rareté',
      egg: 'Œuf',
      gender: 'Sexe',
      slowWalkSpeed: 'Vit. marche lente',
      walkSpeed: 'Vit. de marche',
      runSpeed: 'Vit. de course',
      rideSprintSpeed: 'Vit. en monture',
      transportSpeed: 'Vit. de transport',
      swimSpeed: 'Vit. de nage',
      predator: 'Prédateur',
      expRatio: 'Multiplicateur d’XP',
    },
  },
  'id-ID': {
    title: 'Paldex',
    searchPlaceholder: 'Cari Pal…',
    count: '{{count}} Pal',
    loading: 'Memuat…',
    notFound: 'Tidak ada Pal untuk "{{id}}".',
    backToList: 'Kembali ke Paldex',
    viewInEncyclopedia: 'Lihat di Paldex →',
    viewOnMap: 'Lihat di peta penuh',
    noSpawns: 'Pal ini tidak memiliki lokasi kemunculan yang diketahui.',
    breedingOnly: 'Tidak ditemukan di alam liar — diperoleh melalui perkembangbiakan.',
    summonOnly: 'Tidak ditemukan di alam liar — diperoleh melalui pemanggilan.',
    summonMaterials: 'Bahan pemanggilan',
    spawnWild: 'Liar',
    spawnBoss: 'Bos',
    nightOnly: 'Malam',
    nightOnlyNote: 'Hanya muncul di malam hari.',
    lv: 'Lv',
    skill: 'Skill',
    power: 'Kekuatan',
    cooldown: 'Waktu jeda',
    range: 'Jangkauan',
    type: 'Tipe',
    melee: 'Jarak dekat',
    ranged: 'Jarak jauh',
    genderless: 'Tanpa kelamin',
    rankScaling: 'Skala peringkat',
    effectTime: 'Durasi',
    cost: 'Biaya aktivasi',
    toggle: 'Skill sakelar',
    condensation: 'Dibuka dan diperkuat melalui kondensasi (Lv.1–5).',
    unlockItem: 'Item Pembuka',
    bredFrom: 'Diternak dari',
    openBreeding: 'Buka kalkulator ternak →',
    noBreeding: 'Tidak ada kombinasi ternak yang menghasilkan Pal ini.',
    workBestCaption: '★ Kecocokan kerja terbaik — bintang Tabung Ekstraktor Pal meningkatkannya lebih dulu.',
    condenseTitle: 'Peningkatan Tabung Ekstraktor Pal',
    friendshipNote: '— kenaikan statistik per peringkat kepercayaan, hingga peringkat 10.',
    summonLevel: 'Bos Lv{{n}}',
    summonEggPool: 'Kumpulan hadiah',
    firstDefeatReward: 'Hadiah kemenangan pertama',
    unlocksTechNote: 'Menangkap Pal ini membuka:',
    enemyScalingNote: 'Pengali yang diterapkan pada wujud alfa/bos liar.',
    dmgTaken: 'Damage diterima',
    dmgDealt: 'Damage diberikan',
    habitatLabel: 'Habitat Paldex',
    habitatDay: 'Siang',
    habitatNight: 'Malam',
    yes: 'Ya',
    section: {
      description: 'Deskripsi',
      stats: 'Statistik Dasar',
      details: 'Detail',
      work: 'Kecocokan Kerja',
      partnerSkill: 'Skill Pasangan',
      activeSkills: 'Skill Aktif',
      passives: 'Skill Pasif',
      drops: 'Jarahan',
      bossDrops: 'Jarahan Bos',
      spawns: 'Lokasi Kemunculan',
      breeding: 'Ternak',
      dungeons: 'Ditemukan di Dungeon',
      fishing: 'Didapat dari Memancing',
      unlocksTech: 'Membuka Teknologi',
      enemyScaling: 'Skala Musuh',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Serangan Jarak Dekat',
      shotAttack: 'Serangan',
      defense: 'Pertahanan',
      support: 'Dukungan',
      craftSpeed: 'Kecepatan Kerja',
      stamina: 'Stamina',
      foodAmount: 'Makanan',
      maxFullStomach: 'Tingkat Kenyang Maks.',
      captureRate: 'Tingkat Tangkap',
      price: 'Emas',
      size: 'Ukuran',
      rarity: 'Kelangkaan',
      egg: 'Telur',
      gender: 'Kelamin',
      slowWalkSpeed: 'Kec. jalan pelan',
      walkSpeed: 'Kec. jalan',
      runSpeed: 'Kec. lari',
      rideSprintSpeed: 'Kec. tunggangan',
      transportSpeed: 'Kec. angkut',
      swimSpeed: 'Kec. renang',
      predator: 'Predator',
      expRatio: 'Pengali EXP',
    },
  },
  'it-IT': {
    title: 'Paldex',
    searchPlaceholder: 'Cerca Pal…',
    count: '{{count}} Pal',
    loading: 'Caricamento…',
    notFound: 'Nessun Pal trovato per "{{id}}".',
    backToList: 'Torna alla Paldex',
    viewInEncyclopedia: 'Vedi nella Paldex →',
    viewOnMap: 'Vedi sulla mappa completa',
    noSpawns: 'Questo Pal non ha luoghi di comparsa noti.',
    breedingOnly: 'Non presente in natura: si ottiene tramite allevamento.',
    summonOnly: 'Non presente in natura: si ottiene tramite evocazione.',
    summonMaterials: 'Materiali di evocazione',
    spawnWild: 'Selvatico',
    spawnBoss: 'Boss',
    nightOnly: 'Notte',
    nightOnlyNote: 'Appare solo di notte.',
    lv: 'Lv',
    skill: 'Abilità',
    power: 'Potenza',
    cooldown: 'Ricarica',
    range: 'Gittata',
    type: 'Tipo',
    melee: 'Mischia',
    ranged: 'A distanza',
    genderless: 'Senza sesso',
    rankScaling: 'Scala per grado',
    effectTime: 'Durata',
    cost: 'Costo di attivazione',
    toggle: 'Abilità commutabile',
    condensation: 'Sbloccato e potenziato tramite condensazione (Lv.1–5).',
    unlockItem: 'Oggetto di sblocco',
    bredFrom: 'Generato da',
    openBreeding: 'Apri il calcolatore di allevamento →',
    noBreeding: 'Nessuna combinazione di allevamento produce questo Pal.',
    workBestCaption: '★ Migliore attitudine al lavoro: le stelle della Capsula di potenziamento Pal la migliorano per prima.',
    condenseTitle: 'Miglioramenti della Capsula di potenziamento Pal',
    friendshipNote: '— aumento di statistiche per grado di fiducia, fino al grado 10.',
    summonLevel: 'Boss Lv{{n}}',
    summonEggPool: 'Pool di ricompense',
    firstDefeatReward: 'Ricompensa per la prima vittoria',
    unlocksTechNote: 'Catturare questo Pal sblocca:',
    enemyScalingNote: 'Moltiplicatori applicati alla forma alfa/boss selvatica.',
    dmgTaken: 'Danni subiti',
    dmgDealt: 'Danni inflitti',
    habitatLabel: 'Habitat del Paldex',
    habitatDay: 'Giorno',
    habitatNight: 'Notte',
    yes: 'Sì',
    section: {
      description: 'Descrizione',
      stats: 'Statistiche base',
      details: 'Dettagli',
      work: 'Idoneità al lavoro',
      partnerSkill: 'Abilità del compagno',
      activeSkills: 'Abilità attive',
      passives: 'Abilità passive',
      drops: 'Bottino',
      bossDrops: 'Bottino del boss',
      spawns: 'Luoghi di comparsa',
      breeding: 'Allevamento',
      dungeons: 'Presente nei dungeon',
      fishing: 'Ottenibile pescando',
      unlocksTech: 'Sblocca tecnologia',
      enemyScaling: 'Potenziamento nemico',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Attacco in mischia',
      shotAttack: 'Attacco',
      defense: 'Difesa',
      support: 'Supporto',
      craftSpeed: 'Velocità di lavoro',
      stamina: 'Vigore',
      foodAmount: 'Cibo',
      maxFullStomach: 'Sazietà max.',
      captureRate: 'Tasso di cattura',
      price: 'Oro',
      size: 'Taglia',
      rarity: 'Rarità',
      egg: 'Uovo',
      gender: 'Sesso',
      slowWalkSpeed: 'Vel. camminata lenta',
      walkSpeed: 'Vel. camminata',
      runSpeed: 'Vel. corsa',
      rideSprintSpeed: 'Vel. cavalcatura',
      transportSpeed: 'Vel. trasporto',
      swimSpeed: 'Vel. nuoto',
      predator: 'Predatore',
      expRatio: 'Moltiplicatore EXP',
    },
  },
  'ja-JP': {
    title: 'パルズかんせいずかん',
    searchPlaceholder: 'パルを検索…',
    count: '{{count}} 体',
    loading: '読み込み中…',
    notFound: '「{{id}}」のパルが見つかりません。',
    backToList: '図鑑に戻る',
    viewInEncyclopedia: '図鑑で見る →',
    viewOnMap: '全体マップで見る',
    noSpawns: 'このパルの出現場所は不明です。',
    breedingOnly: '野生では出現しません。交配で入手できます。',
    summonOnly: '野生では出現しません。召喚で入手できます。',
    summonMaterials: '召喚素材',
    spawnWild: '野生',
    spawnBoss: 'ボス',
    nightOnly: '夜間',
    nightOnlyNote: '夜間のみ出現。',
    lv: 'Lv',
    skill: 'スキル',
    power: '威力',
    cooldown: 'クールタイム',
    range: '射程',
    type: 'タイプ',
    melee: '近接',
    ranged: '遠隔',
    genderless: '性別なし',
    rankScaling: 'ランク倍率',
    effectTime: '効果時間',
    cost: '発動コスト',
    toggle: '切り替え式',
    condensation: '凝縮で解放・強化されます（Lv.1〜5）。',
    unlockItem: '解放アイテム',
    bredFrom: '交配元',
    openBreeding: '交配計算機を開く →',
    noBreeding: 'このパルを生む交配の組み合わせはありません。',
    workBestCaption: '★ 最も得意な作業適性 — パル濃縮ポッドの星で優先的に強化されます。',
    condenseTitle: 'パル濃縮ポッドによる強化',
    friendshipNote: '— 信頼度ランクごとのステータス上昇量（最大ランク10）。',
    summonLevel: 'ボス Lv{{n}}',
    summonEggPool: '報酬プール',
    firstDefeatReward: '初回討伐報酬',
    unlocksTechNote: 'このパルを捕獲すると解放:',
    enemyScalingNote: '野生のボス個体に適用される倍率。',
    dmgTaken: '被ダメージ',
    dmgDealt: '与ダメージ',
    habitatLabel: '図鑑の生息域',
    habitatDay: '昼',
    habitatNight: '夜',
    yes: 'はい',
    section: {
      description: '説明',
      stats: '基礎ステータス',
      details: '詳細',
      work: '仕事適性',
      partnerSkill: 'パートナースキル',
      activeSkills: 'アクティブスキル',
      passives: 'パッシブスキル',
      drops: 'ドロップ',
      bossDrops: 'ボスドロップ',
      spawns: '出現場所',
      breeding: '交配',
      dungeons: '出現するダンジョン',
      fishing: '釣りで入手',
      unlocksTech: '解放されるテクノロジー',
      enemyScaling: '敵個体の倍率',
    },
    stat: {
      hp: 'HP',
      meleeAttack: '近接攻撃',
      shotAttack: '攻撃',
      defense: '防御',
      support: 'サポート',
      craftSpeed: '作業速度',
      stamina: 'スタミナ',
      foodAmount: '食事量',
      maxFullStomach: '最大満腹度',
      captureRate: '捕獲率',
      price: 'ゴールド',
      size: 'サイズ',
      rarity: 'レア度',
      egg: 'タマゴ',
      gender: '性別',
      slowWalkSpeed: '低速歩行速度',
      walkSpeed: '歩行速度',
      runSpeed: '走行速度',
      rideSprintSpeed: '騎乗ダッシュ速度',
      transportSpeed: '運搬速度',
      swimSpeed: '遊泳速度',
      predator: 'プレデター',
      expRatio: '経験値倍率',
    },
  },
  'ko-KR': {
    title: '팰 도감',
    searchPlaceholder: '팰 검색…',
    count: '{{count}}마리',
    loading: '불러오는 중…',
    notFound: '"{{id}}"에 해당하는 팰을 찾을 수 없습니다.',
    backToList: '도감으로 돌아가기',
    viewInEncyclopedia: '도감에서 보기 →',
    viewOnMap: '전체 지도에서 보기',
    noSpawns: '이 팰의 출현 위치가 없습니다.',
    breedingOnly: '야생에서 출현하지 않습니다. 교배로 얻을 수 있습니다.',
    summonOnly: '야생에서 출현하지 않습니다. 소환으로 얻을 수 있습니다.',
    summonMaterials: '소환 재료',
    spawnWild: '야생',
    spawnBoss: '보스',
    nightOnly: '밤',
    nightOnlyNote: '밤에만 출현합니다.',
    lv: 'Lv',
    skill: '스킬',
    power: '위력',
    cooldown: '쿨타임',
    range: '사거리',
    type: '유형',
    melee: '근접',
    ranged: '원거리',
    genderless: '성별 없음',
    rankScaling: '랭크 배율',
    effectTime: '지속 시간',
    cost: '발동 비용',
    toggle: '전환형 스킬',
    condensation: '응축으로 해금·강화됩니다 (Lv.1~5).',
    unlockItem: '해금 아이템',
    bredFrom: '교배 재료',
    openBreeding: '교배 계산기 열기 →',
    noBreeding: '이 팰을 만드는 교배 조합이 없습니다.',
    workBestCaption: '★ 가장 뛰어난 작업 적성 — 팰 농축 포드의 별이 우선적으로 강화합니다.',
    condenseTitle: '팰 농축 포드 강화',
    friendshipNote: '— 신뢰도 랭크당 능력치 증가량 (최대 10랭크).',
    summonLevel: '보스 Lv{{n}}',
    summonEggPool: '보상 풀',
    firstDefeatReward: '최초 처치 보상',
    unlocksTechNote: '이 팰을 포획하면 해금:',
    enemyScalingNote: '야생 보스 개체에 적용되는 배율입니다.',
    dmgTaken: '받는 피해',
    dmgDealt: '주는 피해',
    habitatLabel: '도감 서식지',
    habitatDay: '낮',
    habitatNight: '밤',
    yes: '예',
    section: {
      description: '설명',
      stats: '기본 능력치',
      details: '세부 정보',
      work: '작업 적성',
      partnerSkill: '파트너 스킬',
      activeSkills: '액티브 스킬',
      passives: '패시브 스킬',
      drops: '드롭',
      bossDrops: '보스 드롭',
      spawns: '출현 위치',
      breeding: '교배',
      dungeons: '등장 던전',
      fishing: '낚시로 획득',
      unlocksTech: '해금되는 기술',
      enemyScaling: '적 개체 배율',
    },
    stat: {
      hp: 'HP',
      meleeAttack: '근접 공격',
      shotAttack: '공격',
      defense: '방어',
      support: '서포트',
      craftSpeed: '작업 속도',
      stamina: '스태미나',
      foodAmount: '식사량',
      maxFullStomach: '최대 포만도',
      captureRate: '포획률',
      price: '골드',
      size: '크기',
      rarity: '희귀도',
      egg: '알',
      gender: '성별',
      slowWalkSpeed: '느린 걷기 속도',
      walkSpeed: '걷기 속도',
      runSpeed: '달리기 속도',
      rideSprintSpeed: '탑승 질주 속도',
      transportSpeed: '운반 속도',
      swimSpeed: '수영 속도',
      predator: '프레데터',
      expRatio: '경험치 배율',
    },
  },
  'pl-PL': {
    title: 'Paldex',
    searchPlaceholder: 'Szukaj Pali…',
    count: 'Pale: {{count}}',
    loading: 'Wczytywanie…',
    notFound: 'Nie znaleziono Pala dla „{{id}}".',
    backToList: 'Powrót do Paldeksu',
    viewInEncyclopedia: 'Zobacz w Paldeksie →',
    viewOnMap: 'Zobacz na pełnej mapie',
    noSpawns: 'Ten Pal nie ma znanych miejsc występowania.',
    breedingOnly: 'Nie występuje na wolności — zdobywany przez hodowlę.',
    summonOnly: 'Nie występuje na wolności — zdobywany przez przyzwanie.',
    summonMaterials: 'Materiały do przyzwania',
    spawnWild: 'Dziki',
    spawnBoss: 'Boss',
    nightOnly: 'Noc',
    nightOnlyNote: 'Pojawia się tylko w nocy.',
    lv: 'Poz',
    skill: 'Umiejętność',
    power: 'Moc',
    cooldown: 'Odnowienie',
    range: 'Zasięg',
    type: 'Typ',
    melee: 'Zwarcie',
    ranged: 'Dystans',
    genderless: 'Bezpłciowy',
    rankScaling: 'Skalowanie rangi',
    effectTime: 'Czas trwania',
    cost: 'Koszt aktywacji',
    toggle: 'Umiejętność przełączana',
    condensation: 'Odblokowywany i wzmacniany przez kondensację (Poz.1–5).',
    unlockItem: 'Przedmiot odblokowujący',
    bredFrom: 'Wyhodowany z',
    openBreeding: 'Otwórz kalkulator hodowli →',
    noBreeding: 'Żadna kombinacja hodowli nie tworzy tego Pala.',
    workBestCaption: '★ Najlepsze predyspozycje do pracy — gwiazdki Kondensatora Esencji Pali ulepszają je w pierwszej kolejności.',
    condenseTitle: 'Ulepszenia Kondensatora Esencji Pali',
    friendshipNote: '— przyrost statystyk za każdą rangę zaufania, do rangi 10.',
    summonLevel: 'Boss poz. {{n}}',
    summonEggPool: 'Pula nagród',
    firstDefeatReward: 'Nagroda za pierwsze zwycięstwo',
    unlocksTechNote: 'Schwytanie tego Pala odblokowuje:',
    enemyScalingNote: 'Mnożniki stosowane do dzikiej formy alfa/bossa.',
    dmgTaken: 'Otrzymywane obrażenia',
    dmgDealt: 'Zadawane obrażenia',
    habitatLabel: 'Siedlisko z Paldeksu',
    habitatDay: 'Dzień',
    habitatNight: 'Noc',
    yes: 'Tak',
    section: {
      description: 'Opis',
      stats: 'Statystyki podstawowe',
      details: 'Szczegóły',
      work: 'Przydatność do pracy',
      partnerSkill: 'Umiejętność partnera',
      activeSkills: 'Umiejętności aktywne',
      passives: 'Umiejętności pasywne',
      drops: 'Łup',
      bossDrops: 'Łup z bossa',
      spawns: 'Miejsca występowania',
      breeding: 'Hodowla',
      dungeons: 'Występuje w lochach',
      fishing: 'Do złowienia na wędkę',
      unlocksTech: 'Odblokowuje technologię',
      enemyScaling: 'Skalowanie przeciwnika',
    },
    stat: {
      hp: 'PŻ',
      meleeAttack: 'Atak wręcz',
      shotAttack: 'Atak',
      defense: 'Obrona',
      support: 'Wsparcie',
      craftSpeed: 'Tempo pracy',
      stamina: 'Wytrzymałość',
      foodAmount: 'Jedzenie',
      maxFullStomach: 'Maks. sytość',
      captureRate: 'Wskaźnik schwytania',
      price: 'Złoto',
      size: 'Rozmiar',
      rarity: 'Rzadkość',
      egg: 'Jajo',
      gender: 'Płeć',
      slowWalkSpeed: 'Prędkość powolnego chodu',
      walkSpeed: 'Prędkość chodu',
      runSpeed: 'Prędkość biegu',
      rideSprintSpeed: 'Prędkość wierzchowca',
      transportSpeed: 'Prędkość transportu',
      swimSpeed: 'Prędkość pływania',
      predator: 'Drapieżnik',
      expRatio: 'Mnożnik PD',
    },
  },
  'pt-BR': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Carregando…',
    notFound: 'Nenhum Pal encontrado para "{{id}}".',
    backToList: 'Voltar à Paldex',
    viewInEncyclopedia: 'Ver na Paldex →',
    viewOnMap: 'Ver no mapa completo',
    noSpawns: 'Este Pal não tem locais de surgimento conhecidos.',
    breedingOnly: 'Não aparece na natureza — obtido por reprodução.',
    summonOnly: 'Não aparece na natureza — obtido por invocação.',
    summonMaterials: 'Materiais de invocação',
    spawnWild: 'Selvagem',
    spawnBoss: 'Chefe',
    nightOnly: 'Noite',
    nightOnlyNote: 'Aparece apenas à noite.',
    lv: 'Nv',
    skill: 'Habilidade',
    power: 'Poder',
    cooldown: 'Recarga',
    range: 'Alcance',
    type: 'Tipo',
    melee: 'Corpo a corpo',
    ranged: 'À distância',
    genderless: 'Sem gênero',
    rankScaling: 'Escala por classe',
    effectTime: 'Duração',
    cost: 'Custo de ativação',
    toggle: 'Habilidade alternável',
    condensation: 'Desbloqueado e reforçado por condensação (Nv.1–5).',
    unlockItem: 'Item de desbloqueio',
    bredFrom: 'Gerado a partir de',
    openBreeding: 'Abrir calculadora de reprodução →',
    noBreeding: 'Nenhuma combinação de reprodução gera este Pal.',
    workBestCaption: '★ Melhor aptidão de trabalho — as estrelas do Casulo de Condensação de Pal a aprimoram primeiro.',
    condenseTitle: 'Melhorias do Casulo de Condensação de Pal',
    friendshipNote: '— ganho de atributos por nível de Confiança, até o nível 10.',
    summonLevel: 'Chefe Nv{{n}}',
    summonEggPool: 'Conjunto de recompensas',
    firstDefeatReward: 'Recompensa da primeira vitória',
    unlocksTechNote: 'Capturar este Pal desbloqueia:',
    enemyScalingNote: 'Multiplicadores aplicados à forma alfa/chefe selvagem.',
    dmgTaken: 'Dano recebido',
    dmgDealt: 'Dano causado',
    habitatLabel: 'Habitat da Paldex',
    habitatDay: 'Dia',
    habitatNight: 'Noite',
    yes: 'Sim',
    section: {
      description: 'Descrição',
      stats: 'Atributos base',
      details: 'Detalhes',
      work: 'Aptidão de trabalho',
      partnerSkill: 'Habilidade de parceiro',
      activeSkills: 'Habilidades ativas',
      passives: 'Habilidades passivas',
      drops: 'Itens',
      bossDrops: 'Itens de chefe',
      spawns: 'Locais de surgimento',
      breeding: 'Reprodução',
      dungeons: 'Encontrado em masmorras',
      fishing: 'Obtido pescando',
      unlocksTech: 'Desbloqueia tecnologia',
      enemyScaling: 'Escalonamento inimigo',
    },
    stat: {
      hp: 'PV',
      meleeAttack: 'Ataque corpo a corpo',
      shotAttack: 'Ataque',
      defense: 'Defesa',
      support: 'Suporte',
      craftSpeed: 'Velocidade de trabalho',
      stamina: 'Vigor',
      foodAmount: 'Comida',
      maxFullStomach: 'Fartura máx.',
      captureRate: 'Taxa de captura',
      price: 'Ouro',
      size: 'Tamanho',
      rarity: 'Raridade',
      egg: 'Ovo',
      gender: 'Gênero',
      slowWalkSpeed: 'Vel. de caminhada lenta',
      walkSpeed: 'Vel. de caminhada',
      runSpeed: 'Vel. de corrida',
      rideSprintSpeed: 'Vel. montado',
      transportSpeed: 'Vel. de transporte',
      swimSpeed: 'Vel. de natação',
      predator: 'Predador',
      expRatio: 'Multiplicador de EXP',
    },
  },
  'ru-RU': {
    title: 'Палдекс',
    searchPlaceholder: 'Поиск палов…',
    count: 'Палов: {{count}}',
    loading: 'Загрузка…',
    notFound: 'Пал по запросу «{{id}}» не найден.',
    backToList: 'Назад в Палдекс',
    viewInEncyclopedia: 'Открыть в Палдексе →',
    viewOnMap: 'Показать на полной карте',
    noSpawns: 'У этого пала нет известных мест появления.',
    breedingOnly: 'Не встречается в дикой природе — получается разведением.',
    summonOnly: 'Не встречается в дикой природе — получается призывом.',
    summonMaterials: 'Материалы для призыва',
    spawnWild: 'Дикий',
    spawnBoss: 'Босс',
    nightOnly: 'Ночь',
    nightOnlyNote: 'Появляется только ночью.',
    lv: 'Ур',
    skill: 'Навык',
    power: 'Сила',
    cooldown: 'Перезарядка',
    range: 'Дальность',
    type: 'Тип',
    melee: 'Ближний бой',
    ranged: 'Дальний бой',
    genderless: 'Бесполый',
    rankScaling: 'Масштаб по рангу',
    effectTime: 'Длительность',
    cost: 'Стоимость активации',
    toggle: 'Переключаемый навык',
    condensation: 'Открывается и усиливается конденсацией (Ур.1–5).',
    unlockItem: 'Предмет разблокировки',
    bredFrom: 'Выведен из',
    openBreeding: 'Открыть калькулятор разведения →',
    noBreeding: 'Ни одна комбинация разведения не даёт этого пала.',
    workBestCaption: '★ Лучшая рабочая специализация — звёзды Конденсатора Палов улучшают её в первую очередь.',
    condenseTitle: 'Улучшения Конденсатора Палов',
    friendshipNote: '— прирост характеристик за каждый ранг доверия, до 10-го ранга.',
    summonLevel: 'Босс ур. {{n}}',
    summonEggPool: 'Пул наград',
    firstDefeatReward: 'Награда за первую победу',
    unlocksTechNote: 'Поимка этого пала открывает:',
    enemyScalingNote: 'Множители для дикой альфа-/босс-формы.',
    dmgTaken: 'Получаемый урон',
    dmgDealt: 'Наносимый урон',
    habitatLabel: 'Ареал из Палдекса',
    habitatDay: 'День',
    habitatNight: 'Ночь',
    yes: 'Да',
    section: {
      description: 'Описание',
      stats: 'Базовые характеристики',
      details: 'Подробности',
      work: 'Пригодность к работе',
      partnerSkill: 'Навык напарника',
      activeSkills: 'Активные навыки',
      passives: 'Пассивные навыки',
      drops: 'Добыча',
      bossDrops: 'Добыча с босса',
      spawns: 'Места появления',
      breeding: 'Разведение',
      dungeons: 'Встречается в подземельях',
      fishing: 'Ловится на рыбалке',
      unlocksTech: 'Открывает технологию',
      enemyScaling: 'Усиление босс-формы',
    },
    stat: {
      hp: 'ОЗ',
      meleeAttack: 'Ближняя атака',
      shotAttack: 'Атака',
      defense: 'Защита',
      support: 'Поддержка',
      craftSpeed: 'Скорость работы',
      stamina: 'Выносливость',
      foodAmount: 'Еда',
      maxFullStomach: 'Макс. уровень сытости',
      captureRate: 'Шанс поимки',
      price: 'Золото',
      size: 'Размер',
      rarity: 'Редкость',
      egg: 'Яйцо',
      gender: 'Пол',
      slowWalkSpeed: 'Скор. медленной ходьбы',
      walkSpeed: 'Скор. ходьбы',
      runSpeed: 'Скор. бега',
      rideSprintSpeed: 'Скор. верхом',
      transportSpeed: 'Скор. переноски',
      swimSpeed: 'Скор. плавания',
      predator: 'Хищник',
      expRatio: 'Множитель опыта',
    },
  },
  'th-TH': {
    title: 'สารานุกรม Pal',
    searchPlaceholder: 'ค้นหา Pal…',
    count: '{{count}} ตัว',
    loading: 'กำลังโหลด…',
    notFound: 'ไม่พบ Pal สำหรับ "{{id}}"',
    backToList: 'กลับไปที่สารานุกรม',
    viewInEncyclopedia: 'ดูในสารานุกรม →',
    viewOnMap: 'ดูบนแผนที่เต็ม',
    noSpawns: 'Pal ตัวนี้ไม่มีตำแหน่งการปรากฏที่ทราบ',
    breedingOnly: 'ไม่พบในป่า — ได้รับจากการผสมพันธุ์',
    summonOnly: 'ไม่พบในป่า — ได้รับจากการอัญเชิญ',
    summonMaterials: 'วัตถุดิบอัญเชิญ',
    spawnWild: 'ป่า',
    spawnBoss: 'บอส',
    nightOnly: 'กลางคืน',
    nightOnlyNote: 'ปรากฏเฉพาะตอนกลางคืน',
    lv: 'Lv',
    skill: 'สกิล',
    power: 'พลัง',
    cooldown: 'คูลดาวน์',
    range: 'ระยะโจมตี',
    type: 'ประเภท',
    melee: 'ระยะประชิด',
    ranged: 'ระยะไกล',
    genderless: 'ไม่มีเพศ',
    rankScaling: 'การปรับตามระดับ',
    effectTime: 'ระยะเวลา',
    cost: 'ค่าเปิดใช้งาน',
    toggle: 'สกิลสลับเปิดปิด',
    condensation: 'ปลดล็อกและเสริมพลังผ่านการควบแน่น (Lv.1–5)',
    unlockItem: 'ไอเทมปลดล็อก',
    bredFrom: 'ผสมพันธุ์จาก',
    openBreeding: 'เปิดเครื่องคำนวณการผสมพันธุ์ →',
    noBreeding: 'ไม่มีการผสมพันธุ์ใดที่ให้ Pal ตัวนี้',
    workBestCaption: '★ ความถนัดงานที่ดีที่สุด — ดาวจากแคปซูลควบแน่นพาลจะอัปเกรดให้ก่อน',
    condenseTitle: 'อัปเกรดจากแคปซูลควบแน่นพาล',
    friendshipNote: '— ค่าสถานะที่เพิ่มขึ้นต่อระดับความเชื่อใจ สูงสุดระดับ 10',
    summonLevel: 'บอส Lv{{n}}',
    summonEggPool: 'กลุ่มรางวัล',
    firstDefeatReward: 'รางวัลชนะครั้งแรก',
    unlocksTechNote: 'จับพัลตัวนี้เพื่อปลดล็อก:',
    enemyScalingNote: 'ตัวคูณที่ใช้กับร่างอัลฟ่า/บอสในป่า',
    dmgTaken: 'ดาเมจที่ได้รับ',
    dmgDealt: 'ดาเมจที่สร้าง',
    habitatLabel: 'ถิ่นอาศัยตามสารานุกรม',
    habitatDay: 'กลางวัน',
    habitatNight: 'กลางคืน',
    yes: 'ใช่',
    section: {
      description: 'คำอธิบาย',
      stats: 'ค่าพื้นฐาน',
      details: 'รายละเอียด',
      work: 'ความถนัดงาน',
      partnerSkill: 'สกิลคู่หู',
      activeSkills: 'สกิลโจมตี',
      passives: 'สกิลติดตัว',
      drops: 'ไอเทมที่ดรอป',
      bossDrops: 'ไอเทมดรอปจากบอส',
      spawns: 'ตำแหน่งที่เกิด',
      breeding: 'การผสมพันธุ์',
      dungeons: 'พบในดันเจี้ยน',
      fishing: 'ได้จากการตกปลา',
      unlocksTech: 'ปลดล็อกเทคโนโลยี',
      enemyScaling: 'ตัวคูณของบอส',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'โจมตีระยะประชิด',
      shotAttack: 'โจมตี',
      defense: 'ป้องกัน',
      support: 'สนับสนุน',
      craftSpeed: 'ความเร็วในการทำงาน',
      stamina: 'สตามินา',
      foodAmount: 'อาหาร',
      maxFullStomach: 'ระดับความอิ่มสูงสุด',
      captureRate: 'อัตราการจับ',
      price: 'ทอง',
      size: 'ขนาด',
      rarity: 'ความหายาก',
      egg: 'ไข่',
      gender: 'เพศ',
      slowWalkSpeed: 'ความเร็วเดินช้า',
      walkSpeed: 'ความเร็วเดิน',
      runSpeed: 'ความเร็ววิ่ง',
      rideSprintSpeed: 'ความเร็วขี่',
      transportSpeed: 'ความเร็วขนส่ง',
      swimSpeed: 'ความเร็วว่ายน้ำ',
      predator: 'นักล่า',
      expRatio: 'ตัวคูณ EXP',
    },
  },
  'tr-TR': {
    title: 'Paldex',
    searchPlaceholder: 'Pal ara…',
    count: '{{count}} Pal',
    loading: 'Yükleniyor…',
    notFound: '"{{id}}" için Pal bulunamadı.',
    backToList: "Paldex'e dön",
    viewInEncyclopedia: "Paldex'te görüntüle →",
    viewOnMap: 'Tam haritada görüntüle',
    noSpawns: 'Bu Palın bilinen bir çıkış konumu yok.',
    breedingOnly: 'Vahşi doğada bulunmaz — üretimle elde edilir.',
    summonOnly: 'Vahşi doğada bulunmaz — çağırarak elde edilir.',
    summonMaterials: 'Çağırma malzemeleri',
    spawnWild: 'Vahşi',
    spawnBoss: 'Boss',
    nightOnly: 'Gece',
    nightOnlyNote: 'Sadece geceleri belirir.',
    lv: 'Sv',
    skill: 'Yetenek',
    power: 'Güç',
    cooldown: 'Bekleme süresi',
    range: 'Menzil',
    type: 'Tür',
    melee: 'Yakın dövüş',
    ranged: 'Menzilli',
    genderless: 'Cinsiyetsiz',
    rankScaling: 'Rütbe ölçeği',
    effectTime: 'Süre',
    cost: 'Etkinleştirme maliyeti',
    toggle: 'Aç/kapa yeteneği',
    condensation: 'Yoğunlaştırma ile açılır ve güçlenir (Sv.1–5).',
    unlockItem: 'Kilit Açma Eşyası',
    bredFrom: 'Şundan üretildi',
    openBreeding: 'Üretme hesaplayıcıyı aç →',
    noBreeding: 'Hiçbir üretme kombinasyonu bu Palı üretmez.',
    workBestCaption: '★ En iyi iş uygunluğu — Pal Özü Yoğunlaştırıcı yıldızları önce onu geliştirir.',
    condenseTitle: 'Pal Özü Yoğunlaştırıcı geliştirmeleri',
    friendshipNote: '— güven seviyesi başına değer artışı, en fazla seviye 10.',
    summonLevel: 'Boss Sv{{n}}',
    summonEggPool: 'Ödül havuzu',
    firstDefeatReward: 'İlk galibiyet ödülü',
    unlocksTechNote: 'Bu Palı yakalamak şunları açar:',
    enemyScalingNote: 'Vahşi alfa/boss formuna uygulanan çarpanlar.',
    dmgTaken: 'Alınan hasar',
    dmgDealt: 'Verilen hasar',
    habitatLabel: 'Paldex yaşam alanı',
    habitatDay: 'Gündüz',
    habitatNight: 'Gece',
    yes: 'Evet',
    section: {
      description: 'Açıklama',
      stats: 'Temel Değerler',
      details: 'Ayrıntılar',
      work: 'İş Uygunluğu',
      partnerSkill: 'Partner Yeteneği',
      activeSkills: 'Aktif Yetenekler',
      passives: 'Pasif Yetenekler',
      drops: 'Düşen Eşyalar',
      bossDrops: 'Bosstan Düşen Eşyalar',
      spawns: 'Doğma Noktaları',
      breeding: 'Üretme',
      dungeons: 'Zindanlarda bulunur',
      fishing: 'Balık tutarak elde edilir',
      unlocksTech: 'Teknoloji açar',
      enemyScaling: 'Boss Çarpanları',
    },
    stat: {
      hp: 'CP',
      meleeAttack: 'Yakın Dövüş Saldırısı',
      shotAttack: 'Saldırı',
      defense: 'Savunma',
      support: 'Destek',
      craftSpeed: 'İş Hızı',
      stamina: 'Dayanıklılık',
      foodAmount: 'Yiyecek',
      maxFullStomach: 'Maks. Açlık',
      captureRate: 'Yakalama Oranı',
      price: 'Altın',
      size: 'Boyut',
      rarity: 'Nadirlik',
      egg: 'Yumurta',
      gender: 'Cinsiyet',
      slowWalkSpeed: 'Yavaş yürüme hızı',
      walkSpeed: 'Yürüme hızı',
      runSpeed: 'Koşma hızı',
      rideSprintSpeed: 'Binek hızı',
      transportSpeed: 'Taşıma hızı',
      swimSpeed: 'Yüzme hızı',
      predator: 'Yırtıcı',
      expRatio: 'Tecrübe çarpanı',
    },
  },
  'vi-VN': {
    title: 'Paldex',
    searchPlaceholder: 'Tìm Pal…',
    count: '{{count}} Pal',
    loading: 'Đang tải…',
    notFound: 'Không tìm thấy Pal cho "{{id}}".',
    backToList: 'Quay lại Paldex',
    viewInEncyclopedia: 'Xem trong Paldex →',
    viewOnMap: 'Xem trên bản đồ đầy đủ',
    noSpawns: 'Pal này không có địa điểm xuất hiện nào được biết đến.',
    breedingOnly: 'Không xuất hiện ngoài hoang dã — có được qua nhân giống.',
    summonOnly: 'Không xuất hiện ngoài hoang dã — có được qua triệu hồi.',
    summonMaterials: 'Nguyên liệu triệu hồi',
    spawnWild: 'Hoang dã',
    spawnBoss: 'Boss',
    nightOnly: 'Ban đêm',
    nightOnlyNote: 'Chỉ xuất hiện vào ban đêm.',
    lv: 'Cấp',
    skill: 'Kỹ năng',
    power: 'Sức mạnh',
    cooldown: 'Thời gian hồi',
    range: 'Tầm bắn',
    type: 'Loại',
    melee: 'Cận chiến',
    ranged: 'Tầm xa',
    genderless: 'Không giới tính',
    rankScaling: 'Tỷ lệ theo bậc',
    effectTime: 'Thời lượng',
    cost: 'Chi phí kích hoạt',
    toggle: 'Kỹ năng bật/tắt',
    condensation: 'Mở khóa và tăng cường qua ngưng tụ (Cấp 1–5).',
    unlockItem: 'Vật phẩm mở khóa',
    bredFrom: 'Nhân giống từ',
    openBreeding: 'Mở công cụ tính nhân giống →',
    noBreeding: 'Không có tổ hợp nhân giống nào tạo ra Pal này.',
    workBestCaption: '★ Năng khiếu làm việc tốt nhất — sao của Máy Tinh Luyện Pal sẽ nâng cấp nó trước tiên.',
    condenseTitle: 'Nâng cấp Máy Tinh Luyện Pal',
    friendshipNote: '— chỉ số tăng thêm mỗi cấp Độ Tin Cậy, tối đa cấp 10.',
    summonLevel: 'Boss cấp {{n}}',
    summonEggPool: 'Nhóm phần thưởng',
    firstDefeatReward: 'Phần thưởng hạ gục lần đầu',
    unlocksTechNote: 'Bắt Pal này sẽ mở khóa:',
    enemyScalingNote: 'Hệ số nhân áp dụng cho dạng alpha/boss hoang dã.',
    dmgTaken: 'Sát thương nhận vào',
    dmgDealt: 'Sát thương gây ra',
    habitatLabel: 'Môi trường sống theo Paldex',
    habitatDay: 'Ban ngày',
    habitatNight: 'Ban đêm',
    yes: 'Có',
    section: {
      description: 'Mô tả',
      stats: 'Chỉ số cơ bản',
      details: 'Chi tiết',
      work: 'Độ phù hợp công việc',
      partnerSkill: 'Kỹ năng đồng hành',
      activeSkills: 'Kỹ năng chủ động',
      passives: 'Kỹ năng bị động',
      drops: 'Vật phẩm rơi',
      bossDrops: 'Vật phẩm rơi từ Boss',
      spawns: 'Vị trí xuất hiện',
      breeding: 'Nhân giống',
      dungeons: 'Xuất hiện trong hầm ngục',
      fishing: 'Bắt được khi câu cá',
      unlocksTech: 'Mở khóa công nghệ',
      enemyScaling: 'Hệ số boss',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Tấn công cận chiến',
      shotAttack: 'Tấn công',
      defense: 'Phòng thủ',
      support: 'Hỗ trợ',
      craftSpeed: 'Tốc độ làm việc',
      stamina: 'Thể lực',
      foodAmount: 'Thức ăn',
      maxFullStomach: 'Mức độ no tối đa',
      captureRate: 'Tỷ lệ bắt',
      price: 'Vàng',
      size: 'Kích thước',
      rarity: 'Độ hiếm',
      egg: 'Trứng',
      gender: 'Giới tính',
      slowWalkSpeed: 'Tốc độ đi chậm',
      walkSpeed: 'Tốc độ đi',
      runSpeed: 'Tốc độ chạy',
      rideSprintSpeed: 'Tốc độ cưỡi',
      transportSpeed: 'Tốc độ vận chuyển',
      swimSpeed: 'Tốc độ bơi',
      predator: 'Hung Bạo',
      expRatio: 'Hệ số EXP',
    },
  },
  'zh-CN': {
    title: '帕鲁图鉴',
    searchPlaceholder: '搜索帕鲁…',
    count: '{{count}} 只帕鲁',
    loading: '加载中…',
    notFound: '未找到帕鲁「{{id}}」。',
    backToList: '返回图鉴',
    viewInEncyclopedia: '在图鉴中查看 →',
    viewOnMap: '在完整地图中查看',
    noSpawns: '该帕鲁没有已知的出现地点。',
    breedingOnly: '不会在野外出现，可通过配种获得。',
    summonOnly: '不会在野外出现，可通过召唤获得。',
    summonMaterials: '召唤材料',
    spawnWild: '野生',
    spawnBoss: '头目',
    nightOnly: '夜间',
    nightOnlyNote: '仅在夜间出现。',
    lv: '等级',
    skill: '技能',
    power: '威力',
    cooldown: '冷却',
    range: '射程',
    type: '类型',
    melee: '近战',
    ranged: '远程',
    genderless: '无性别',
    rankScaling: '等级加成',
    effectTime: '持续时间',
    cost: '发动消耗',
    toggle: '可切换技能',
    condensation: '通过浓缩解锁并强化（等级 1–5）。',
    unlockItem: '解锁道具',
    bredFrom: '配种来源',
    openBreeding: '打开配种计算器 →',
    noBreeding: '没有可产出该帕鲁的配种组合。',
    workBestCaption: '★ 最擅长的工作适性 — 帕鲁浓缩机的星级会优先强化它。',
    condenseTitle: '帕鲁浓缩机强化',
    friendshipNote: '— 每级信赖度提升的属性值（最高10级）。',
    summonLevel: '头目 Lv{{n}}',
    summonEggPool: '奖励池',
    firstDefeatReward: '首次击败奖励',
    unlocksTechNote: '捕获该帕鲁可解锁：',
    enemyScalingNote: '野外头目形态所应用的倍率。',
    dmgTaken: '受到伤害',
    dmgDealt: '造成伤害',
    habitatLabel: '图鉴栖息地',
    habitatDay: '白天',
    habitatNight: '夜晚',
    yes: '是',
    section: {
      description: '描述',
      stats: '基础属性',
      details: '详细信息',
      work: '工作适性',
      partnerSkill: '伙伴技能',
      activeSkills: '主动技能',
      passives: '被动技能',
      drops: '掉落',
      bossDrops: 'BOSS掉落',
      spawns: '出现地点',
      breeding: '配种',
      dungeons: '出现的地下城',
      fishing: '钓鱼获得',
      unlocksTech: '解锁科技',
      enemyScaling: '头目形态倍率',
    },
    stat: {
      hp: '生命值',
      meleeAttack: '近战攻击',
      shotAttack: '攻击',
      defense: '防御',
      support: '支援',
      craftSpeed: '工作速度',
      stamina: '耐力',
      foodAmount: '食量',
      maxFullStomach: '最大饱腹度',
      captureRate: '捕获率',
      price: '金币',
      size: '体型',
      rarity: '稀有度',
      egg: '蛋',
      gender: '性别',
      slowWalkSpeed: '慢走速度',
      walkSpeed: '步行速度',
      runSpeed: '奔跑速度',
      rideSprintSpeed: '骑乘冲刺速度',
      transportSpeed: '搬运速度',
      swimSpeed: '游泳速度',
      predator: '捕食者',
      expRatio: '经验值倍率',
    },
  },
  'zh-TW': {
    title: '帕魯圖鑑',
    searchPlaceholder: '搜尋帕魯…',
    count: '{{count}} 隻帕魯',
    loading: '載入中…',
    notFound: '未找到帕魯「{{id}}」。',
    backToList: '返回圖鑑',
    viewInEncyclopedia: '在圖鑑中查看 →',
    viewOnMap: '在完整地圖中查看',
    noSpawns: '該帕魯沒有已知的出現地點。',
    breedingOnly: '不會在野外出現，可透過配種獲得。',
    summonOnly: '不會在野外出現，可透過召喚獲得。',
    summonMaterials: '召喚材料',
    spawnWild: '野生',
    spawnBoss: '頭目',
    nightOnly: '夜間',
    nightOnlyNote: '僅在夜間出現。',
    lv: '等級',
    skill: '技能',
    power: '威力',
    cooldown: '冷卻',
    range: '射程',
    type: '類型',
    melee: '近戰',
    ranged: '遠程',
    genderless: '無性別',
    rankScaling: '等級加成',
    effectTime: '持續時間',
    cost: '發動消耗',
    toggle: '可切換技能',
    condensation: '透過濃縮解鎖並強化（等級 1–5）。',
    unlockItem: '解鎖道具',
    bredFrom: '配種來源',
    openBreeding: '開啟配種計算器 →',
    noBreeding: '沒有可產出該帕魯的配種組合。',
    workBestCaption: '★ 最擅長的工作適性 — 帕魯濃縮機的星級會優先強化它。',
    condenseTitle: '帕魯濃縮機強化',
    friendshipNote: '— 每級信賴度提升的屬性值（最高10級）。',
    summonLevel: '頭目 Lv{{n}}',
    summonEggPool: '獎勵池',
    firstDefeatReward: '首次擊敗獎勵',
    unlocksTechNote: '捕獲該帕魯可解鎖：',
    enemyScalingNote: '野外頭目形態所應用的倍率。',
    dmgTaken: '受到傷害',
    dmgDealt: '造成傷害',
    habitatLabel: '圖鑑棲息地',
    habitatDay: '白天',
    habitatNight: '夜晚',
    yes: '是',
    section: {
      description: '描述',
      stats: '基礎屬性',
      details: '詳細資訊',
      work: '工作適性',
      partnerSkill: '夥伴技能',
      activeSkills: '主動技能',
      passives: '被動技能',
      drops: '掉落',
      bossDrops: 'BOSS掉落',
      spawns: '出現地點',
      breeding: '配種',
      dungeons: '出現的地下城',
      fishing: '釣魚獲得',
      unlocksTech: '解鎖科技',
      enemyScaling: '頭目形態倍率',
    },
    stat: {
      hp: '生命值',
      meleeAttack: '近戰攻擊',
      shotAttack: '攻擊',
      defense: '防禦',
      support: '支援',
      craftSpeed: '工作速度',
      stamina: '耐力',
      foodAmount: '食量',
      maxFullStomach: '最大飽足度',
      captureRate: '捕獲率',
      price: '金幣',
      size: '體型',
      rarity: '稀有度',
      egg: '蛋',
      gender: '性別',
      slowWalkSpeed: '慢走速度',
      walkSpeed: '步行速度',
      runSpeed: '奔跑速度',
      rideSprintSpeed: '騎乘衝刺速度',
      transportSpeed: '搬運速度',
      swimSpeed: '游泳速度',
      predator: '捕食者',
      expRatio: '經驗值倍率',
    },
  },
}
