import type { Language } from './i18n'

// Research Lab page UI chrome, merged into the `translation` namespace under
// the `research` key (see i18n.ts). Project names come from the locale data
// files (locales/{lng}/research.json); this table only holds the page's own
// labels plus a display name per EffectType enum value.
export interface ResearchStrings {
  title: string
  caption: string
  /** bIsEssential badge on a project node. */
  essential: string
  /** Lab work amount label. */
  work: string
  /** "Unlocks: <tech>" link on gate projects. */
  unlocksTech: string
  /** EffectType enum value → short display name. */
  effect: Record<string, string>
}

export const RESEARCH_STRINGS: Record<Language, ResearchStrings> = {
  'en-US': {
    title: 'Research',
    caption:
      'Research Lab projects: pick a work category tab and follow the in-game prerequisite tree — effect, material cost, and lab work per project.',
    essential: 'Essential',
    work: 'Work',
    unlocksTech: 'Unlocks',
    effect: {
      CraftSpeed: 'Crafting speed',
      LabResearchSpeed: 'Research speed',
      ConsumeEnergyRate: 'Power consumption',
      EnergyStorageRate: 'Power storage',
      AttackRateBaseCampWorker: 'Base worker attack',
      DefenseRateBaseCampWorker: 'Base worker defense',
      ExpeditionRewardRate: 'Expedition rewards',
      ExpeditionTimeCostRate: 'Expedition time',
      FarmCropGrowupSpeed: 'Crop growth speed',
      FarmCropHarvestNumRate: 'Harvest yield',
      ItemCorruptionSpeedRate: 'Spoilage speed',
      OilExtractionSpeedRate: 'Oil extraction speed',
      PalEggHatchingSpeed: 'Egg incubation speed',
      ProductExtraItemProbability: 'Bonus product chance',
      ProductItemConsumeMaterialNumRate: 'Material consumption',
    },
  },
  'de-DE': {
    title: 'Forschung',
    caption:
      'Forschungslabor-Projekte: Arbeitskategorie wählen und dem Voraussetzungsbaum aus dem Spiel folgen — Effekt, Materialkosten und Laborarbeit je Projekt.',
    essential: 'Essenziell',
    work: 'Arbeit',
    unlocksTech: 'Schaltet frei',
    effect: {
      CraftSpeed: 'Fertigungsgeschwindigkeit',
      LabResearchSpeed: 'Forschungsgeschwindigkeit',
      ConsumeEnergyRate: 'Stromverbrauch',
      EnergyStorageRate: 'Stromspeicher',
      AttackRateBaseCampWorker: 'Angriff der Basis-Arbeiter',
      DefenseRateBaseCampWorker: 'Verteidigung der Basis-Arbeiter',
      ExpeditionRewardRate: 'Expeditionsbelohnungen',
      ExpeditionTimeCostRate: 'Expeditionsdauer',
      FarmCropGrowupSpeed: 'Pflanzenwachstum',
      FarmCropHarvestNumRate: 'Ernteertrag',
      ItemCorruptionSpeedRate: 'Verderbtempo',
      OilExtractionSpeedRate: 'Ölfördergeschwindigkeit',
      PalEggHatchingSpeed: 'Ei-Brutgeschwindigkeit',
      ProductExtraItemProbability: 'Bonusprodukt-Chance',
      ProductItemConsumeMaterialNumRate: 'Materialverbrauch',
    },
  },
  'es-ES': {
    title: 'Investigación',
    caption:
      'Proyectos del laboratorio de investigación: elige una categoría de trabajo y sigue el árbol de requisitos del juego — efecto, coste de materiales y trabajo de laboratorio por proyecto.',
    essential: 'Esencial',
    work: 'Trabajo',
    unlocksTech: 'Desbloquea',
    effect: {
      CraftSpeed: 'Velocidad de fabricación',
      LabResearchSpeed: 'Velocidad de investigación',
      ConsumeEnergyRate: 'Consumo de energía',
      EnergyStorageRate: 'Almacenamiento de energía',
      AttackRateBaseCampWorker: 'Ataque de trabajadores de la base',
      DefenseRateBaseCampWorker: 'Defensa de trabajadores de la base',
      ExpeditionRewardRate: 'Recompensas de expedición',
      ExpeditionTimeCostRate: 'Duración de expedición',
      FarmCropGrowupSpeed: 'Crecimiento de cultivos',
      FarmCropHarvestNumRate: 'Rendimiento de cosecha',
      ItemCorruptionSpeedRate: 'Velocidad de deterioro',
      OilExtractionSpeedRate: 'Velocidad de extracción de petróleo',
      PalEggHatchingSpeed: 'Velocidad de incubación',
      ProductExtraItemProbability: 'Probabilidad de producto extra',
      ProductItemConsumeMaterialNumRate: 'Consumo de materiales',
    },
  },
  'es-MX': {
    title: 'Investigación',
    caption:
      'Proyectos del laboratorio de investigación: elige una categoría de trabajo y sigue el árbol de requisitos del juego — efecto, costo de materiales y trabajo de laboratorio por proyecto.',
    essential: 'Esencial',
    work: 'Trabajo',
    unlocksTech: 'Desbloquea',
    effect: {
      CraftSpeed: 'Velocidad de fabricación',
      LabResearchSpeed: 'Velocidad de investigación',
      ConsumeEnergyRate: 'Consumo de energía',
      EnergyStorageRate: 'Almacenamiento de energía',
      AttackRateBaseCampWorker: 'Ataque de trabajadores de la base',
      DefenseRateBaseCampWorker: 'Defensa de trabajadores de la base',
      ExpeditionRewardRate: 'Recompensas de expedición',
      ExpeditionTimeCostRate: 'Duración de expedición',
      FarmCropGrowupSpeed: 'Crecimiento de cultivos',
      FarmCropHarvestNumRate: 'Rendimiento de cosecha',
      ItemCorruptionSpeedRate: 'Velocidad de deterioro',
      OilExtractionSpeedRate: 'Velocidad de extracción de petróleo',
      PalEggHatchingSpeed: 'Velocidad de incubación',
      ProductExtraItemProbability: 'Probabilidad de producto extra',
      ProductItemConsumeMaterialNumRate: 'Consumo de materiales',
    },
  },
  'fr-FR': {
    title: 'Recherche',
    caption:
      'Projets du laboratoire de recherche : choisissez une catégorie de travail et suivez l’arbre des prérequis du jeu — effet, coût en matériaux et travail de laboratoire par projet.',
    essential: 'Essentiel',
    work: 'Travail',
    unlocksTech: 'Débloque',
    effect: {
      CraftSpeed: 'Vitesse de fabrication',
      LabResearchSpeed: 'Vitesse de recherche',
      ConsumeEnergyRate: 'Consommation d’énergie',
      EnergyStorageRate: 'Stockage d’énergie',
      AttackRateBaseCampWorker: 'Attaque des travailleurs de la base',
      DefenseRateBaseCampWorker: 'Défense des travailleurs de la base',
      ExpeditionRewardRate: 'Récompenses d’expédition',
      ExpeditionTimeCostRate: 'Durée d’expédition',
      FarmCropGrowupSpeed: 'Croissance des cultures',
      FarmCropHarvestNumRate: 'Rendement des récoltes',
      ItemCorruptionSpeedRate: 'Vitesse de péremption',
      OilExtractionSpeedRate: 'Vitesse d’extraction du pétrole',
      PalEggHatchingSpeed: 'Vitesse d’incubation des œufs',
      ProductExtraItemProbability: 'Chance de produit bonus',
      ProductItemConsumeMaterialNumRate: 'Consommation de matériaux',
    },
  },
  'id-ID': {
    title: 'Riset',
    caption:
      'Proyek Lab Riset: pilih tab kategori kerja dan ikuti pohon prasyarat seperti di dalam game — efek, biaya material, dan kerja lab per proyek.',
    essential: 'Esensial',
    work: 'Kerja',
    unlocksTech: 'Membuka',
    effect: {
      CraftSpeed: 'Kecepatan kerajinan',
      LabResearchSpeed: 'Kecepatan riset',
      ConsumeEnergyRate: 'Konsumsi listrik',
      EnergyStorageRate: 'Penyimpanan listrik',
      AttackRateBaseCampWorker: 'Serangan pekerja markas',
      DefenseRateBaseCampWorker: 'Pertahanan pekerja markas',
      ExpeditionRewardRate: 'Hadiah ekspedisi',
      ExpeditionTimeCostRate: 'Waktu ekspedisi',
      FarmCropGrowupSpeed: 'Kecepatan tumbuh tanaman',
      FarmCropHarvestNumRate: 'Hasil panen',
      ItemCorruptionSpeedRate: 'Kecepatan pembusukan',
      OilExtractionSpeedRate: 'Kecepatan ekstraksi minyak',
      PalEggHatchingSpeed: 'Kecepatan penetasan telur',
      ProductExtraItemProbability: 'Peluang produk bonus',
      ProductItemConsumeMaterialNumRate: 'Konsumsi material',
    },
  },
  'it-IT': {
    title: 'Ricerca',
    caption:
      'Progetti del laboratorio di ricerca: scegli una categoria di lavoro e segui l’albero dei prerequisiti del gioco — effetto, costo dei materiali e lavoro di laboratorio per progetto.',
    essential: 'Essenziale',
    work: 'Lavoro',
    unlocksTech: 'Sblocca',
    effect: {
      CraftSpeed: 'Velocità di fabbricazione',
      LabResearchSpeed: 'Velocità di ricerca',
      ConsumeEnergyRate: 'Consumo di energia',
      EnergyStorageRate: 'Accumulo di energia',
      AttackRateBaseCampWorker: 'Attacco dei lavoratori della base',
      DefenseRateBaseCampWorker: 'Difesa dei lavoratori della base',
      ExpeditionRewardRate: 'Ricompense di spedizione',
      ExpeditionTimeCostRate: 'Durata delle spedizioni',
      FarmCropGrowupSpeed: 'Crescita delle colture',
      FarmCropHarvestNumRate: 'Resa del raccolto',
      ItemCorruptionSpeedRate: 'Velocità di deterioramento',
      OilExtractionSpeedRate: 'Velocità di estrazione del petrolio',
      PalEggHatchingSpeed: 'Velocità di incubazione delle uova',
      ProductExtraItemProbability: 'Probabilità di prodotto bonus',
      ProductItemConsumeMaterialNumRate: 'Consumo di materiali',
    },
  },
  'ja-JP': {
    title: '研究',
    caption:
      '研究ラボのプロジェクト:作業カテゴリのタブを選んで、ゲーム内と同じ前提ツリーをたどれます。各プロジェクトの効果・素材コスト・研究作業量を表示。',
    essential: '重要',
    work: '作業量',
    unlocksTech: '解放',
    effect: {
      CraftSpeed: '製作速度',
      LabResearchSpeed: '研究速度',
      ConsumeEnergyRate: '電力消費',
      EnergyStorageRate: '蓄電量',
      AttackRateBaseCampWorker: '拠点パルの攻撃力',
      DefenseRateBaseCampWorker: '拠点パルの防御力',
      ExpeditionRewardRate: '探検の報酬',
      ExpeditionTimeCostRate: '探検の所要時間',
      FarmCropGrowupSpeed: '作物の成長速度',
      FarmCropHarvestNumRate: '収穫量',
      ItemCorruptionSpeedRate: '食品の腐敗速度',
      OilExtractionSpeedRate: '原油の採掘速度',
      PalEggHatchingSpeed: '卵の孵化速度',
      ProductExtraItemProbability: '追加生産の確率',
      ProductItemConsumeMaterialNumRate: '素材の消費量',
    },
  },
  'ko-KR': {
    title: '연구',
    caption:
      '연구 실험실 프로젝트: 작업 카테고리 탭을 선택해 게임과 같은 선행 트리를 따라가세요 — 프로젝트별 효과, 재료 비용, 연구 작업량.',
    essential: '필수',
    work: '작업량',
    unlocksTech: '해금',
    effect: {
      CraftSpeed: '제작 속도',
      LabResearchSpeed: '연구 속도',
      ConsumeEnergyRate: '전력 소비',
      EnergyStorageRate: '전력 저장량',
      AttackRateBaseCampWorker: '거점 팰 공격력',
      DefenseRateBaseCampWorker: '거점 팰 방어력',
      ExpeditionRewardRate: '탐험 보상',
      ExpeditionTimeCostRate: '탐험 소요 시간',
      FarmCropGrowupSpeed: '작물 성장 속도',
      FarmCropHarvestNumRate: '수확량',
      ItemCorruptionSpeedRate: '음식 부패 속도',
      OilExtractionSpeedRate: '원유 채굴 속도',
      PalEggHatchingSpeed: '알 부화 속도',
      ProductExtraItemProbability: '추가 생산 확률',
      ProductItemConsumeMaterialNumRate: '재료 소비량',
    },
  },
  'pl-PL': {
    title: 'Badania',
    caption:
      'Projekty laboratorium badawczego: wybierz kategorię pracy i podążaj za drzewem wymagań jak w grze — efekt, koszt materiałów i praca laboratoryjna dla każdego projektu.',
    essential: 'Kluczowe',
    work: 'Praca',
    unlocksTech: 'Odblokowuje',
    effect: {
      CraftSpeed: 'Szybkość wytwarzania',
      LabResearchSpeed: 'Szybkość badań',
      ConsumeEnergyRate: 'Zużycie energii',
      EnergyStorageRate: 'Magazynowanie energii',
      AttackRateBaseCampWorker: 'Atak pracowników bazy',
      DefenseRateBaseCampWorker: 'Obrona pracowników bazy',
      ExpeditionRewardRate: 'Nagrody z ekspedycji',
      ExpeditionTimeCostRate: 'Czas ekspedycji',
      FarmCropGrowupSpeed: 'Wzrost upraw',
      FarmCropHarvestNumRate: 'Plon zbiorów',
      ItemCorruptionSpeedRate: 'Szybkość psucia się',
      OilExtractionSpeedRate: 'Szybkość wydobycia ropy',
      PalEggHatchingSpeed: 'Szybkość wylęgania jaj',
      ProductExtraItemProbability: 'Szansa na dodatkowy produkt',
      ProductItemConsumeMaterialNumRate: 'Zużycie materiałów',
    },
  },
  'pt-BR': {
    title: 'Pesquisa',
    caption:
      'Projetos do laboratório de pesquisa: escolha uma categoria de trabalho e siga a árvore de pré-requisitos do jogo — efeito, custo de materiais e trabalho de laboratório por projeto.',
    essential: 'Essencial',
    work: 'Trabalho',
    unlocksTech: 'Desbloqueia',
    effect: {
      CraftSpeed: 'Velocidade de fabricação',
      LabResearchSpeed: 'Velocidade de pesquisa',
      ConsumeEnergyRate: 'Consumo de energia',
      EnergyStorageRate: 'Armazenamento de energia',
      AttackRateBaseCampWorker: 'Ataque dos trabalhadores da base',
      DefenseRateBaseCampWorker: 'Defesa dos trabalhadores da base',
      ExpeditionRewardRate: 'Recompensas de expedição',
      ExpeditionTimeCostRate: 'Tempo de expedição',
      FarmCropGrowupSpeed: 'Crescimento das plantações',
      FarmCropHarvestNumRate: 'Rendimento da colheita',
      ItemCorruptionSpeedRate: 'Velocidade de deterioração',
      OilExtractionSpeedRate: 'Velocidade de extração de petróleo',
      PalEggHatchingSpeed: 'Velocidade de incubação de ovos',
      ProductExtraItemProbability: 'Chance de produto bônus',
      ProductItemConsumeMaterialNumRate: 'Consumo de materiais',
    },
  },
  'ru-RU': {
    title: 'Исследования',
    caption:
      'Проекты исследовательской лаборатории: выберите категорию работы и следуйте дереву требований, как в игре — эффект, стоимость материалов и лабораторная работа для каждого проекта.',
    essential: 'Важное',
    work: 'Работа',
    unlocksTech: 'Открывает',
    effect: {
      CraftSpeed: 'Скорость изготовления',
      LabResearchSpeed: 'Скорость исследований',
      ConsumeEnergyRate: 'Потребление энергии',
      EnergyStorageRate: 'Запас энергии',
      AttackRateBaseCampWorker: 'Атака работников базы',
      DefenseRateBaseCampWorker: 'Защита работников базы',
      ExpeditionRewardRate: 'Награды экспедиций',
      ExpeditionTimeCostRate: 'Время экспедиций',
      FarmCropGrowupSpeed: 'Рост урожая',
      FarmCropHarvestNumRate: 'Объём урожая',
      ItemCorruptionSpeedRate: 'Скорость порчи еды',
      OilExtractionSpeedRate: 'Скорость добычи нефти',
      PalEggHatchingSpeed: 'Скорость инкубации яиц',
      ProductExtraItemProbability: 'Шанс дополнительной продукции',
      ProductItemConsumeMaterialNumRate: 'Расход материалов',
    },
  },
  'th-TH': {
    title: 'การวิจัย',
    caption:
      'โปรเจกต์ห้องแล็บวิจัย: เลือกแท็บหมวดงานแล้วดูแผนผังเงื่อนไขแบบเดียวกับในเกม — เอฟเฟกต์ ต้นทุนวัสดุ และงานวิจัยของแต่ละโปรเจกต์',
    essential: 'จำเป็น',
    work: 'งาน',
    unlocksTech: 'ปลดล็อก',
    effect: {
      CraftSpeed: 'ความเร็วในการผลิต',
      LabResearchSpeed: 'ความเร็วในการวิจัย',
      ConsumeEnergyRate: 'การใช้พลังงานไฟฟ้า',
      EnergyStorageRate: 'ความจุไฟฟ้าสำรอง',
      AttackRateBaseCampWorker: 'พลังโจมตีของพัลในฐาน',
      DefenseRateBaseCampWorker: 'พลังป้องกันของพัลในฐาน',
      ExpeditionRewardRate: 'รางวัลการสำรวจ',
      ExpeditionTimeCostRate: 'เวลาการสำรวจ',
      FarmCropGrowupSpeed: 'ความเร็วการเติบโตของพืช',
      FarmCropHarvestNumRate: 'ปริมาณผลผลิต',
      ItemCorruptionSpeedRate: 'ความเร็วการเน่าเสียของอาหาร',
      OilExtractionSpeedRate: 'ความเร็วการสกัดน้ำมัน',
      PalEggHatchingSpeed: 'ความเร็วการฟักไข่',
      ProductExtraItemProbability: 'โอกาสได้ผลผลิตพิเศษ',
      ProductItemConsumeMaterialNumRate: 'ปริมาณการใช้วัสดุ',
    },
  },
  'tr-TR': {
    title: 'Araştırma',
    caption:
      'Araştırma Laboratuvarı projeleri: bir iş kategorisi sekmesi seçin ve oyundaki ön koşul ağacını izleyin — proje başına etki, malzeme maliyeti ve laboratuvar işi.',
    essential: 'Temel',
    work: 'İş',
    unlocksTech: 'Açar',
    effect: {
      CraftSpeed: 'Üretim hızı',
      LabResearchSpeed: 'Araştırma hızı',
      ConsumeEnergyRate: 'Güç tüketimi',
      EnergyStorageRate: 'Güç depolama',
      AttackRateBaseCampWorker: 'Üs işçisi saldırısı',
      DefenseRateBaseCampWorker: 'Üs işçisi savunması',
      ExpeditionRewardRate: 'Keşif ödülleri',
      ExpeditionTimeCostRate: 'Keşif süresi',
      FarmCropGrowupSpeed: 'Ekin büyüme hızı',
      FarmCropHarvestNumRate: 'Hasat verimi',
      ItemCorruptionSpeedRate: 'Bozulma hızı',
      OilExtractionSpeedRate: 'Petrol çıkarma hızı',
      PalEggHatchingSpeed: 'Yumurta kuluçka hızı',
      ProductExtraItemProbability: 'Bonus ürün şansı',
      ProductItemConsumeMaterialNumRate: 'Malzeme tüketimi',
    },
  },
  'vi-VN': {
    title: 'Nghiên cứu',
    caption:
      'Dự án Phòng Nghiên cứu: chọn thẻ nhóm công việc và theo cây điều kiện như trong game — hiệu ứng, chi phí nguyên liệu và công việc nghiên cứu của từng dự án.',
    essential: 'Thiết yếu',
    work: 'Công việc',
    unlocksTech: 'Mở khóa',
    effect: {
      CraftSpeed: 'Tốc độ chế tạo',
      LabResearchSpeed: 'Tốc độ nghiên cứu',
      ConsumeEnergyRate: 'Tiêu thụ điện',
      EnergyStorageRate: 'Trữ điện',
      AttackRateBaseCampWorker: 'Sức tấn công Pal tại căn cứ',
      DefenseRateBaseCampWorker: 'Phòng thủ Pal tại căn cứ',
      ExpeditionRewardRate: 'Phần thưởng thám hiểm',
      ExpeditionTimeCostRate: 'Thời gian thám hiểm',
      FarmCropGrowupSpeed: 'Tốc độ cây trồng phát triển',
      FarmCropHarvestNumRate: 'Sản lượng thu hoạch',
      ItemCorruptionSpeedRate: 'Tốc độ hư hỏng thức ăn',
      OilExtractionSpeedRate: 'Tốc độ khai thác dầu',
      PalEggHatchingSpeed: 'Tốc độ ấp trứng',
      ProductExtraItemProbability: 'Tỷ lệ sản phẩm thêm',
      ProductItemConsumeMaterialNumRate: 'Tiêu hao nguyên liệu',
    },
  },
  'zh-CN': {
    title: '研究',
    caption:
      '研究实验室项目：选择工作类别标签，按游戏内的前置树查看——每个项目的效果、材料消耗与研究工作量。',
    essential: '重要',
    work: '工作量',
    unlocksTech: '解锁',
    effect: {
      CraftSpeed: '制作速度',
      LabResearchSpeed: '研究速度',
      ConsumeEnergyRate: '电力消耗',
      EnergyStorageRate: '电力储存',
      AttackRateBaseCampWorker: '据点帕鲁攻击力',
      DefenseRateBaseCampWorker: '据点帕鲁防御力',
      ExpeditionRewardRate: '探险奖励',
      ExpeditionTimeCostRate: '探险耗时',
      FarmCropGrowupSpeed: '作物生长速度',
      FarmCropHarvestNumRate: '收获数量',
      ItemCorruptionSpeedRate: '食物腐坏速度',
      OilExtractionSpeedRate: '原油开采速度',
      PalEggHatchingSpeed: '孵蛋速度',
      ProductExtraItemProbability: '额外产物概率',
      ProductItemConsumeMaterialNumRate: '材料消耗',
    },
  },
  'zh-TW': {
    title: '研究',
    caption:
      '研究實驗室項目：選擇工作類別分頁，依遊戲內的前置樹查看——每個項目的效果、材料消耗與研究工作量。',
    essential: '重要',
    work: '工作量',
    unlocksTech: '解鎖',
    effect: {
      CraftSpeed: '製作速度',
      LabResearchSpeed: '研究速度',
      ConsumeEnergyRate: '電力消耗',
      EnergyStorageRate: '電力儲存',
      AttackRateBaseCampWorker: '據點帕魯攻擊力',
      DefenseRateBaseCampWorker: '據點帕魯防禦力',
      ExpeditionRewardRate: '探險獎勵',
      ExpeditionTimeCostRate: '探險耗時',
      FarmCropGrowupSpeed: '作物生長速度',
      FarmCropHarvestNumRate: '收穫數量',
      ItemCorruptionSpeedRate: '食物腐壞速度',
      OilExtractionSpeedRate: '原油開採速度',
      PalEggHatchingSpeed: '孵蛋速度',
      ProductExtraItemProbability: '額外產物機率',
      ProductItemConsumeMaterialNumRate: '材料消耗',
    },
  },
}
