import type { Language } from './i18n'

// Stat-simulator strings, merged into the `translation` namespace under a
// `sim` key (see i18n.ts). Game-derived terms follow the game's own text
// tables via the data-repo locales: Statue of Power (BuildableGoddessStatue),
// souls (PalUpgradeStone items), awakening (PalAwakening_* crystals), the
// condenser (CharacterRankUp) and trust ranks (pal.friendshipNote terms).
// The Attack row label reuses `pal.stat.shotAttack` directly. Delta-cell
// formula tooltips are built numerically in the page and need no strings.
export interface SimStrings {
  title: string
  caption: string
  pickPal: string
  /** Prefix of the species base-value line shown next to the picker. */
  base: string
  level: string
  /** Condenser star rank 0–4 (input label). */
  stars: string
  /** Trust (friendship) rank 0–10 (input label). */
  bond: string
  /** Doubles as the input label and (with a "+" prefix) the column header. */
  awakening: string
  /** Statue-of-Power soul ranks group title. */
  souls: string
  /** IV sliders group title. */
  ivs: string
  /** Results-table column headers. */
  stat: string
  /** Base value scaled to the chosen level. */
  colBase: string
  colTrust: string
  colIv: string
  colStars: string
  colSouls: string
  stageFinal: string
  /** Editable last column: the stat as displayed in game. */
  colInGame: string
  stageNote: string
  /** How the editable in-game column behaves. */
  editNote: string
  /** In-game cell tooltip: IVs matching the shown value ({{range}}). */
  ivMatch: string
  /** In-game cell warning: no IV 0–100 reproduces the entered stat. */
  noMatch: string
  /** Work speed has no IV — its in-game cell can only mismatch via settings. */
  craftNoIv: string
  /** Formula-tooltip legend labels, rendered as `number — label` lines under
   *  the numeric derivation. Trust-rank / IV / star / soul COUNTS reuse the
   *  bond / colIv / colStars / colSouls labels; `level` labels the level. */
  fBase: string
  /** Flat +10 folded into every pal's HP before level scaling. */
  fBonus: string
  fCoeff: string
  fConst: string
  /** ×1.1, applies to the species base only. */
  fAwakenMul: string
  /** Friendship_* per-trust-rank base gain. */
  fGrowth: string
  /** 0.003 → +0.3% per IV point. */
  fIvCoeff: string
  /** 0.05 per star (0.1 for work speed). */
  fStarRate: string
  /** 0.03 per soul rank. */
  fSoulRate: string
  /** ×0.7 species multiplier on work speed. */
  fTribe: string
  /** Result of the previous stage that a multiplier stage starts from. */
  fPrev: string
  /** Working base in the IV tooltip once awakening/trust are folded in. */
  fBaseEnh: string
}

export const SIM_STRINGS: Record<Language, SimStrings> = {
  'en-US': {
    title: 'Stat Simulator',
    caption:
      'Compute the exact in-game stats of any pal from its enhancements — or enter the displayed stats to reveal the hidden IVs (talents).',
    pickPal: 'Select a pal…',
    base: 'base',
    level: 'Level',
    stars: 'Condense stars',
    bond: 'Trust rank',
    awakening: 'Awakening',
    souls: 'Soul ranks (Statue of Power)',
    ivs: 'IVs (hidden talents)',
    stat: 'Stat',
    colBase: 'Base',
    colTrust: 'Trust',
    colIv: 'IV',
    colStars: 'Stars',
    colSouls: 'Souls',
    stageFinal: 'Final',
    colInGame: 'In-game',
    stageNote:
      'Each stage is truncated before the next multiplier, exactly as the game computes it. Work speed ignores level and IVs.',
    editNote:
      'Edit the last column to solve the matching IV automatically — red means no IV (0–100) produces that value.',
    ivMatch: 'Matching IV: {{range}}',
    noMatch: 'No IV (0–100) produces this value — check level, stars, souls, trust rank and awakening.',
    craftNoIv: 'Work speed has no IV — if the in-game value differs, one of the other settings is off.',
    fBase: 'species base value',
    fBonus: 'flat bonus (every pal)',
    fCoeff: 'per-level coefficient',
    fConst: 'flat constant',
    fAwakenMul: 'awakening multiplier (species base only)',
    fGrowth: 'gain per trust rank',
    fIvCoeff: 'bonus per IV point',
    fStarRate: 'bonus per star',
    fSoulRate: 'bonus per soul rank',
    fTribe: 'work-speed species multiplier',
    fPrev: 'previous subtotal',
    fBaseEnh: 'species base incl. awakening & trust',
  },
  'de-DE': {
    title: 'Werte-Simulator',
    caption:
      'Berechne die exakten Spielwerte eines Pals aus seinen Verstärkungen – oder gib die angezeigten Werte ein, um die versteckten IVs (Talente) zu ermitteln.',
    pickPal: 'Pal auswählen…',
    base: 'Basis',
    level: 'Stufe',
    stars: 'Entsafter-Sterne',
    bond: 'Zutraulichkeits-Rang',
    awakening: 'Erweckung',
    souls: 'Seelen-Ränge (Statue der Kraft)',
    ivs: 'IVs (versteckte Talente)',
    stat: 'Wert',
    colBase: 'Basis',
    colTrust: 'Zutraulichkeit',
    colIv: 'IV',
    colStars: 'Sterne',
    colSouls: 'Seelen',
    stageFinal: 'Endwert',
    colInGame: 'Im Spiel',
    stageNote:
      'Jede Stufe wird vor dem nächsten Multiplikator abgerundet, genau wie im Spiel. Das Arbeitstempo ignoriert Stufe und IVs.',
    editNote:
      'Bearbeite die letzte Spalte, um das passende IV automatisch zu bestimmen – rot bedeutet, dass kein IV (0–100) diesen Wert ergibt.',
    ivMatch: 'Passendes IV: {{range}}',
    noMatch: 'Kein IV (0–100) ergibt diesen Wert – prüfe Stufe, Sterne, Seelen, Zutraulichkeits-Rang und Erweckung.',
    craftNoIv: 'Das Arbeitstempo hat kein IV – weicht der Wert im Spiel ab, stimmt eine der anderen Einstellungen nicht.',
    fBase: 'Spezies-Basiswert',
    fBonus: 'fester Bonus (jedes Pal)',
    fCoeff: 'Koeffizient pro Stufe',
    fConst: 'feste Konstante',
    fAwakenMul: 'Erweckungs-Multiplikator (nur Spezies-Basis)',
    fGrowth: 'Zuwachs pro Zutraulichkeits-Rang',
    fIvCoeff: 'Bonus pro IV-Punkt',
    fStarRate: 'Bonus pro Stern',
    fSoulRate: 'Bonus pro Seelen-Rang',
    fTribe: 'Speziesfaktor des Arbeitstempos',
    fPrev: 'vorherige Zwischensumme',
    fBaseEnh: 'Spezies-Basis inkl. Erweckung & Zutraulichkeit',
  },
  'es-ES': {
    title: 'Simulador de estadísticas',
    caption:
      'Calcula las estadísticas exactas de cualquier pal en el juego a partir de sus mejoras, o introduce las estadísticas mostradas para revelar los IVs ocultos (talentos).',
    pickPal: 'Selecciona un pal…',
    base: 'base',
    level: 'Nivel',
    stars: 'Estrellas de concentrado',
    bond: 'Rango de confianza',
    awakening: 'Despertar',
    souls: 'Rangos de espíritu (Estatua de Poder)',
    ivs: 'IVs (talentos ocultos)',
    stat: 'Estadística',
    colBase: 'Base',
    colTrust: 'Confianza',
    colIv: 'IV',
    colStars: 'Estrellas',
    colSouls: 'Espíritus',
    stageFinal: 'Final',
    colInGame: 'En el juego',
    stageNote:
      'Cada etapa se trunca antes del siguiente multiplicador, exactamente como lo calcula el juego. La velocidad de trabajo ignora el nivel y los IVs.',
    editNote:
      'Edita la última columna para calcular automáticamente el IV correspondiente; en rojo significa que ningún IV (0–100) produce ese valor.',
    ivMatch: 'IV correspondiente: {{range}}',
    noMatch: 'Ningún IV (0–100) produce este valor: revisa nivel, estrellas, espíritus, rango de confianza y despertar.',
    craftNoIv: 'La velocidad de trabajo no tiene IV: si el valor del juego difiere, alguno de los otros ajustes está mal.',
    fBase: 'valor base de la especie',
    fBonus: 'bono fijo (todos los pals)',
    fCoeff: 'coeficiente por nivel',
    fConst: 'constante fija',
    fAwakenMul: 'multiplicador de despertar (solo base de especie)',
    fGrowth: 'ganancia por rango de confianza',
    fIvCoeff: 'bono por punto de IV',
    fStarRate: 'bono por estrella',
    fSoulRate: 'bono por rango de espíritu',
    fTribe: 'multiplicador de especie (velocidad de trabajo)',
    fPrev: 'subtotal anterior',
    fBaseEnh: 'base de especie con despertar y confianza',
  },
  'es-MX': {
    title: 'Simulador de estadísticas',
    caption:
      'Calcula las estadísticas exactas de cualquier pal en el juego a partir de sus mejoras, o ingresa las estadísticas mostradas para revelar los IVs ocultos (talentos).',
    pickPal: 'Selecciona un pal…',
    base: 'base',
    level: 'Nivel',
    stars: 'Estrellas de concentrado',
    bond: 'Rango de confianza',
    awakening: 'Despertar',
    souls: 'Rangos de alma (Estatua de Poder)',
    ivs: 'IVs (talentos ocultos)',
    stat: 'Estadística',
    colBase: 'Base',
    colTrust: 'Confianza',
    colIv: 'IV',
    colStars: 'Estrellas',
    colSouls: 'Almas',
    stageFinal: 'Final',
    colInGame: 'En el juego',
    stageNote:
      'Cada etapa se trunca antes del siguiente multiplicador, exactamente como lo calcula el juego. La velocidad de trabajo ignora el nivel y los IVs.',
    editNote:
      'Edita la última columna para calcular automáticamente el IV correspondiente; en rojo significa que ningún IV (0–100) produce ese valor.',
    ivMatch: 'IV correspondiente: {{range}}',
    noMatch: 'Ningún IV (0–100) produce este valor: revisa nivel, estrellas, almas, rango de confianza y despertar.',
    craftNoIv: 'La velocidad de trabajo no tiene IV: si el valor del juego difiere, alguno de los otros ajustes está mal.',
    fBase: 'valor base de la especie',
    fBonus: 'bono fijo (todos los pals)',
    fCoeff: 'coeficiente por nivel',
    fConst: 'constante fija',
    fAwakenMul: 'multiplicador de despertar (solo base de especie)',
    fGrowth: 'ganancia por rango de confianza',
    fIvCoeff: 'bono por punto de IV',
    fStarRate: 'bono por estrella',
    fSoulRate: 'bono por rango de alma',
    fTribe: 'multiplicador de especie (velocidad de trabajo)',
    fPrev: 'subtotal anterior',
    fBaseEnh: 'base de especie con despertar y confianza',
  },
  'fr-FR': {
    title: 'Simulateur de statistiques',
    caption:
      'Calculez les statistiques exactes en jeu de n’importe quel pal à partir de ses améliorations — ou saisissez les statistiques affichées pour révéler les IV cachés (talents).',
    pickPal: 'Sélectionner un pal…',
    base: 'base',
    level: 'Niveau',
    stars: 'Étoiles de condensation',
    bond: 'Rang de confiance',
    awakening: 'Éveil',
    souls: 'Rangs d’âme (Statue de puissance)',
    ivs: 'IV (talents cachés)',
    stat: 'Statistique',
    colBase: 'Base',
    colTrust: 'Confiance',
    colIv: 'IV',
    colStars: 'Étoiles',
    colSouls: 'Âmes',
    stageFinal: 'Final',
    colInGame: 'En jeu',
    stageNote:
      'Chaque étape est tronquée avant le multiplicateur suivant, exactement comme dans le jeu. La vitesse de travail ignore le niveau et les IV.',
    editNote:
      'Modifiez la dernière colonne pour déterminer automatiquement l’IV correspondant — en rouge, aucun IV (0–100) ne produit cette valeur.',
    ivMatch: 'IV correspondant : {{range}}',
    noMatch: 'Aucun IV (0–100) ne produit cette valeur — vérifiez le niveau, les étoiles, les âmes, le rang de confiance et l’éveil.',
    craftNoIv: 'La vitesse de travail n’a pas d’IV — si la valeur en jeu diffère, un des autres réglages est incorrect.',
    fBase: 'valeur de base de l’espèce',
    fBonus: 'bonus fixe (tous les pals)',
    fCoeff: 'coefficient par niveau',
    fConst: 'constante fixe',
    fAwakenMul: 'multiplicateur d’éveil (base d’espèce uniquement)',
    fGrowth: 'gain par rang de confiance',
    fIvCoeff: 'bonus par point d’IV',
    fStarRate: 'bonus par étoile',
    fSoulRate: 'bonus par rang d’âme',
    fTribe: 'multiplicateur d’espèce (vitesse de travail)',
    fPrev: 'sous-total précédent',
    fBaseEnh: 'base d’espèce avec éveil et confiance',
  },
  'id-ID': {
    title: 'Simulator Statistik',
    caption:
      'Hitung statistik persis dalam game untuk pal mana pun dari peningkatannya — atau masukkan statistik yang ditampilkan untuk mengungkap IV tersembunyi (bakat).',
    pickPal: 'Pilih pal…',
    base: 'dasar',
    level: 'Level',
    stars: 'Bintang ekstraksi',
    bond: 'Peringkat kepercayaan',
    awakening: 'Pelatihan Elemen',
    souls: 'Peringkat Batu Pal (Patung Kekuatan)',
    ivs: 'IV (bakat tersembunyi)',
    stat: 'Statistik',
    colBase: 'Dasar',
    colTrust: 'Kepercayaan',
    colIv: 'IV',
    colStars: 'Bintang',
    colSouls: 'Batu Pal',
    stageFinal: 'Akhir',
    colInGame: 'Dalam game',
    stageNote:
      'Setiap tahap dibulatkan ke bawah sebelum pengali berikutnya, persis seperti perhitungan game. Kecepatan Kerja mengabaikan level dan IV.',
    editNote:
      'Ubah kolom terakhir untuk menghitung IV yang cocok secara otomatis — merah berarti tidak ada IV (0–100) yang menghasilkan nilai itu.',
    ivMatch: 'IV yang cocok: {{range}}',
    noMatch:
      'Tidak ada IV (0–100) yang menghasilkan nilai ini — periksa level, bintang, Batu Pal, peringkat kepercayaan, dan Pelatihan Elemen.',
    craftNoIv: 'Kecepatan Kerja tidak punya IV — jika nilai dalam game berbeda, salah satu pengaturan lain keliru.',
    fBase: 'nilai dasar spesies',
    fBonus: 'bonus tetap (semua pal)',
    fCoeff: 'koefisien per level',
    fConst: 'konstanta tetap',
    fAwakenMul: 'pengali Pelatihan Elemen (hanya dasar spesies)',
    fGrowth: 'kenaikan per peringkat kepercayaan',
    fIvCoeff: 'bonus per poin IV',
    fStarRate: 'bonus per bintang',
    fSoulRate: 'bonus per peringkat Batu Pal',
    fTribe: 'pengali spesies (Kecepatan Kerja)',
    fPrev: 'subtotal sebelumnya',
    fBaseEnh: 'dasar spesies termasuk Pelatihan Elemen & kepercayaan',
  },
  'it-IT': {
    title: 'Simulatore di statistiche',
    caption:
      'Calcola le statistiche esatte in gioco di qualsiasi pal a partire dai suoi potenziamenti — oppure inserisci le statistiche mostrate per scoprire gli IV nascosti (talenti).',
    pickPal: 'Seleziona un pal…',
    base: 'base',
    level: 'Livello',
    stars: 'Stelle di potenziamento',
    bond: 'Grado di fiducia',
    awakening: 'Risveglio',
    souls: 'Gradi anima (Statua del potere)',
    ivs: 'IV (talenti nascosti)',
    stat: 'Statistica',
    colBase: 'Base',
    colTrust: 'Fiducia',
    colIv: 'IV',
    colStars: 'Stelle',
    colSouls: 'Anime',
    stageFinal: 'Finale',
    colInGame: 'In gioco',
    stageNote:
      'Ogni fase viene troncata prima del moltiplicatore successivo, esattamente come calcola il gioco. La velocità di lavoro ignora livello e IV.',
    editNote:
      'Modifica l’ultima colonna per ricavare automaticamente l’IV corrispondente — in rosso significa che nessun IV (0–100) produce quel valore.',
    ivMatch: 'IV corrispondente: {{range}}',
    noMatch: 'Nessun IV (0–100) produce questo valore — controlla livello, stelle, anime, grado di fiducia e risveglio.',
    craftNoIv: 'La velocità di lavoro non ha IV — se il valore in gioco è diverso, una delle altre impostazioni è sbagliata.',
    fBase: 'valore base della specie',
    fBonus: 'bonus fisso (tutti i pal)',
    fCoeff: 'coefficiente per livello',
    fConst: 'costante fissa',
    fAwakenMul: 'moltiplicatore del risveglio (solo base di specie)',
    fGrowth: 'guadagno per grado di fiducia',
    fIvCoeff: 'bonus per punto IV',
    fStarRate: 'bonus per stella',
    fSoulRate: 'bonus per grado anima',
    fTribe: 'moltiplicatore di specie (velocità di lavoro)',
    fPrev: 'subtotale precedente',
    fBaseEnh: 'base di specie con risveglio e fiducia',
  },
  'ja-JP': {
    title: 'ステータスシミュレーター',
    caption:
      '強化状態からパルのゲーム内ステータスを正確に計算できます。表示ステータスを入力すれば、隠しステータスの個体値も逆算できます。',
    pickPal: 'パルを選択…',
    base: '基礎値',
    level: 'レベル',
    stars: '濃縮ランク（星）',
    bond: '信頼度ランク',
    awakening: '覚醒',
    souls: 'ソウル強化（力の石像）',
    ivs: '個体値（隠しステータス）',
    stat: 'ステータス',
    colBase: '基礎値',
    colTrust: '信頼度',
    colIv: '個体値',
    colStars: '星',
    colSouls: 'ソウル',
    stageFinal: '最終値',
    colInGame: 'ゲーム内値',
    stageNote:
      '各段階はゲームと同じく、次の倍率を掛ける前に端数を切り捨てます。作業速度はレベルと個体値の影響を受けません。',
    editNote:
      '最後の列を編集すると、対応する個体値を自動で逆算します。赤色は、どの個体値（0〜100）でもその値にならないことを示します。',
    ivMatch: '一致する個体値: {{range}}',
    noMatch: 'どの個体値（0〜100）でもこの値になりません。レベル・星・ソウル・信頼度ランク・覚醒を確認してください。',
    craftNoIv: '作業速度に個体値はありません。ゲーム内の値と異なる場合は、他の設定のいずれかが違っています。',
    fBase: '種族基礎値',
    fBonus: '固定ボーナス（全パル共通）',
    fCoeff: 'レベル係数',
    fConst: '固定定数',
    fAwakenMul: '覚醒倍率（種族基礎値のみに適用）',
    fGrowth: '信頼度ランクごとの上昇量',
    fIvCoeff: '個体値1あたりのボーナス',
    fStarRate: '星1つあたりのボーナス',
    fSoulRate: 'ソウル1ランクあたりのボーナス',
    fTribe: '作業速度の種族倍率',
    fPrev: '前段階の値',
    fBaseEnh: '覚醒・信頼度込みの種族基礎値',
  },
  'ko-KR': {
    title: '스탯 시뮬레이터',
    caption:
      '강화 상태로부터 팰의 게임 내 스탯을 정확히 계산하거나, 표시된 스탯을 입력해 숨겨진 개체값을 역산할 수 있습니다.',
    pickPal: '팰 선택…',
    base: '기본값',
    level: '레벨',
    stars: '농축 랭크(별)',
    bond: '신뢰도 랭크',
    awakening: '각성',
    souls: '영혼 강화 (힘의 석상)',
    ivs: '개체값 (숨겨진 능력치)',
    stat: '스탯',
    colBase: '기본값',
    colTrust: '신뢰도',
    colIv: '개체값',
    colStars: '별',
    colSouls: '영혼',
    stageFinal: '최종',
    colInGame: '게임 내 값',
    stageNote:
      '각 단계는 게임과 동일하게 다음 배율을 곱하기 전에 소수점을 버립니다. 작업 속도는 레벨과 개체값의 영향을 받지 않습니다.',
    editNote:
      '마지막 열을 수정하면 해당하는 개체값을 자동으로 역산합니다. 빨간색은 어떤 개체값(0–100)으로도 그 값이 나올 수 없다는 뜻입니다.',
    ivMatch: '일치하는 개체값: {{range}}',
    noMatch: '어떤 개체값(0–100)으로도 이 값이 나오지 않습니다. 레벨·별·영혼·신뢰도 랭크·각성을 확인하세요.',
    craftNoIv: '작업 속도에는 개체값이 없습니다. 게임 내 값과 다르면 다른 설정 중 하나가 틀린 것입니다.',
    fBase: '종족 기본값',
    fBonus: '고정 보너스 (모든 팰 공통)',
    fCoeff: '레벨 계수',
    fConst: '고정 상수',
    fAwakenMul: '각성 배율 (종족 기본값에만 적용)',
    fGrowth: '신뢰도 랭크당 증가량',
    fIvCoeff: '개체값 1당 보너스',
    fStarRate: '별 1개당 보너스',
    fSoulRate: '영혼 1랭크당 보너스',
    fTribe: '작업 속도 종족 배율',
    fPrev: '이전 단계 값',
    fBaseEnh: '각성·신뢰도 반영 종족 기본값',
  },
  'pl-PL': {
    title: 'Symulator statystyk',
    caption:
      'Oblicz dokładne statystyki dowolnego Pala w grze na podstawie jego ulepszeń — albo wpisz wyświetlane statystyki, aby poznać ukryte IV (talenty).',
    pickPal: 'Wybierz Pala…',
    base: 'baza',
    level: 'Poziom',
    stars: 'Gwiazdki kondensacji',
    bond: 'Ranga zaufania',
    awakening: 'Przebudzenie',
    souls: 'Rangi dusz (Posąg Mocy)',
    ivs: 'IV (ukryte talenty)',
    stat: 'Statystyka',
    colBase: 'Baza',
    colTrust: 'Zaufanie',
    colIv: 'IV',
    colStars: 'Gwiazdki',
    colSouls: 'Dusze',
    stageFinal: 'Ostateczna',
    colInGame: 'W grze',
    stageNote:
      'Każdy etap jest zaokrąglany w dół przed kolejnym mnożnikiem, dokładnie tak jak liczy to gra. Tempo pracy ignoruje poziom i IV.',
    editNote:
      'Edytuj ostatnią kolumnę, aby automatycznie wyznaczyć pasujące IV — czerwień oznacza, że żadne IV (0–100) nie daje tej wartości.',
    ivMatch: 'Pasujące IV: {{range}}',
    noMatch: 'Żadne IV (0–100) nie daje tej wartości — sprawdź poziom, gwiazdki, dusze, rangę zaufania i przebudzenie.',
    craftNoIv: 'Tempo pracy nie ma IV — jeśli wartość w grze się różni, któreś z pozostałych ustawień jest błędne.',
    fBase: 'wartość bazowa gatunku',
    fBonus: 'stały bonus (każdy Pal)',
    fCoeff: 'współczynnik na poziom',
    fConst: 'stała wartość',
    fAwakenMul: 'mnożnik przebudzenia (tylko baza gatunku)',
    fGrowth: 'przyrost na rangę zaufania',
    fIvCoeff: 'bonus za punkt IV',
    fStarRate: 'bonus za gwiazdkę',
    fSoulRate: 'bonus za rangę duszy',
    fTribe: 'mnożnik gatunkowy (tempo pracy)',
    fPrev: 'poprzednia suma częściowa',
    fBaseEnh: 'baza gatunku z przebudzeniem i zaufaniem',
  },
  'pt-BR': {
    title: 'Simulador de atributos',
    caption:
      'Calcule os atributos exatos de qualquer Pal no jogo a partir dos seus aprimoramentos — ou insira os atributos exibidos para revelar os IVs ocultos (talentos).',
    pickPal: 'Selecione um pal…',
    base: 'base',
    level: 'Nível',
    stars: 'Estrelas de condensação',
    bond: 'Nível de Confiança',
    awakening: 'Despertar',
    souls: 'Níveis de alma (Estátua da Força)',
    ivs: 'IVs (talentos ocultos)',
    stat: 'Atributo',
    colBase: 'Base',
    colTrust: 'Confiança',
    colIv: 'IV',
    colStars: 'Estrelas',
    colSouls: 'Almas',
    stageFinal: 'Final',
    colInGame: 'No jogo',
    stageNote:
      'Cada etapa é truncada antes do próximo multiplicador, exatamente como o jogo calcula. A velocidade de trabalho ignora nível e IVs.',
    editNote:
      'Edite a última coluna para calcular automaticamente o IV correspondente — vermelho significa que nenhum IV (0–100) produz esse valor.',
    ivMatch: 'IV correspondente: {{range}}',
    noMatch: 'Nenhum IV (0–100) produz este valor — verifique nível, estrelas, almas, nível de Confiança e despertar.',
    craftNoIv: 'A velocidade de trabalho não tem IV — se o valor no jogo for diferente, uma das outras configurações está errada.',
    fBase: 'valor base da espécie',
    fBonus: 'bônus fixo (todos os pals)',
    fCoeff: 'coeficiente por nível',
    fConst: 'constante fixa',
    fAwakenMul: 'multiplicador do despertar (só a base da espécie)',
    fGrowth: 'ganho por nível de Confiança',
    fIvCoeff: 'bônus por ponto de IV',
    fStarRate: 'bônus por estrela',
    fSoulRate: 'bônus por nível de alma',
    fTribe: 'multiplicador de espécie (velocidade de trabalho)',
    fPrev: 'subtotal anterior',
    fBaseEnh: 'base da espécie com despertar e Confiança',
  },
  'ru-RU': {
    title: 'Симулятор характеристик',
    caption:
      'Рассчитайте точные игровые характеристики любого пала по его усилениям — или введите отображаемые характеристики, чтобы узнать скрытые IV (таланты).',
    pickPal: 'Выберите пала…',
    base: 'база',
    level: 'Уровень',
    stars: 'Звёзды конденсации',
    bond: 'Ранг доверия',
    awakening: 'Пробуждение',
    souls: 'Ранги душ (Монумент Силы)',
    ivs: 'IV (скрытые таланты)',
    stat: 'Характеристика',
    colBase: 'База',
    colTrust: 'Доверие',
    colIv: 'IV',
    colStars: 'Звёзды',
    colSouls: 'Души',
    stageFinal: 'Итог',
    colInGame: 'В игре',
    stageNote:
      'Каждый этап округляется вниз перед следующим множителем — ровно так же считает игра. Скорость работы не зависит от уровня и IV.',
    editNote:
      'Измените последний столбец, чтобы автоматически подобрать подходящий IV — красный цвет означает, что ни один IV (0–100) не даёт это значение.',
    ivMatch: 'Подходящий IV: {{range}}',
    noMatch: 'Ни один IV (0–100) не даёт это значение — проверьте уровень, звёзды, души, ранг доверия и пробуждение.',
    craftNoIv: 'У скорости работы нет IV — если значение в игре отличается, одна из остальных настроек неверна.',
    fBase: 'базовое значение вида',
    fBonus: 'фиксированный бонус (у всех палов)',
    fCoeff: 'коэффициент за уровень',
    fConst: 'фиксированная константа',
    fAwakenMul: 'множитель пробуждения (только к базе вида)',
    fGrowth: 'прирост за ранг доверия',
    fIvCoeff: 'бонус за очко IV',
    fStarRate: 'бонус за звезду',
    fSoulRate: 'бонус за ранг души',
    fTribe: 'видовой множитель скорости работы',
    fPrev: 'предыдущий промежуточный итог',
    fBaseEnh: 'база вида с пробуждением и доверием',
  },
  'th-TH': {
    title: 'เครื่องคำนวณค่าสถานะ',
    caption:
      'คำนวณค่าสถานะในเกมที่แม่นยำของพัลตัวใดก็ได้จากการเสริมพลังของมัน — หรือกรอกค่าสถานะที่แสดงเพื่อหาค่า IV ที่ซ่อนอยู่ (พรสวรรค์)',
    pickPal: 'เลือกพัล…',
    base: 'ค่าพื้นฐาน',
    level: 'เลเวล',
    stars: 'ดาวควบแน่น',
    bond: 'ระดับความเชื่อใจ',
    awakening: 'ความตื่นรู้',
    souls: 'ระดับโซล (รูปปั้นหินแห่งพลัง)',
    ivs: 'IV (พรสวรรค์ที่ซ่อนอยู่)',
    stat: 'ค่าสถานะ',
    colBase: 'พื้นฐาน',
    colTrust: 'ความเชื่อใจ',
    colIv: 'IV',
    colStars: 'ดาว',
    colSouls: 'โซล',
    stageFinal: 'สุดท้าย',
    colInGame: 'ในเกม',
    stageNote:
      'แต่ละขั้นจะถูกปัดเศษลงก่อนคูณตัวคูณถัดไป เหมือนที่เกมคำนวณทุกประการ ความเร็วในการทำงานไม่ขึ้นกับเลเวลและ IV',
    editNote:
      'แก้ไขคอลัมน์สุดท้ายเพื่อคำนวณ IV ที่ตรงกันโดยอัตโนมัติ — สีแดงหมายความว่าไม่มี IV (0–100) ใดให้ค่านั้นได้',
    ivMatch: 'IV ที่ตรงกัน: {{range}}',
    noMatch: 'ไม่มี IV (0–100) ใดให้ค่านี้ได้ — ตรวจสอบเลเวล ดาว โซล ระดับความเชื่อใจ และความตื่นรู้',
    craftNoIv: 'ความเร็วในการทำงานไม่มี IV — หากค่าในเกมต่างออกไป แสดงว่าการตั้งค่าอื่นบางอย่างไม่ถูกต้อง',
    fBase: 'ค่าพื้นฐานของสายพันธุ์',
    fBonus: 'โบนัสคงที่ (พัลทุกตัว)',
    fCoeff: 'สัมประสิทธิ์ต่อเลเวล',
    fConst: 'ค่าคงที่',
    fAwakenMul: 'ตัวคูณความตื่นรู้ (เฉพาะค่าพื้นฐานสายพันธุ์)',
    fGrowth: 'ค่าที่เพิ่มต่อระดับความเชื่อใจ',
    fIvCoeff: 'โบนัสต่อแต้ม IV',
    fStarRate: 'โบนัสต่อดาว',
    fSoulRate: 'โบนัสต่อระดับโซล',
    fTribe: 'ตัวคูณสายพันธุ์ของความเร็วในการทำงาน',
    fPrev: 'ผลลัพธ์ขั้นก่อนหน้า',
    fBaseEnh: 'ค่าพื้นฐานสายพันธุ์รวมความตื่นรู้และความเชื่อใจ',
  },
  'tr-TR': {
    title: 'Değer Simülatörü',
    caption:
      'Herhangi bir Pal’in oyun içi değerlerini güçlendirmelerinden tam olarak hesaplayın — ya da gösterilen değerleri girerek gizli IV’leri (yetenekleri) ortaya çıkarın.',
    pickPal: 'Bir pal seçin…',
    base: 'taban',
    level: 'Seviye',
    stars: 'Yoğunlaştırma yıldızları',
    bond: 'Güven seviyesi',
    awakening: 'Uyandırış',
    souls: 'Ruh seviyeleri (Güç Heykeli)',
    ivs: 'IV’ler (gizli yetenekler)',
    stat: 'Değer',
    colBase: 'Taban',
    colTrust: 'Güven',
    colIv: 'IV',
    colStars: 'Yıldızlar',
    colSouls: 'Ruhlar',
    stageFinal: 'Son',
    colInGame: 'Oyunda',
    stageNote:
      'Her aşama, oyunun hesapladığı gibi bir sonraki çarpandan önce aşağı yuvarlanır. İş Hızı seviye ve IV’leri yok sayar.',
    editNote:
      'Eşleşen IV’yi otomatik bulmak için son sütunu düzenleyin — kırmızı, hiçbir IV’nin (0–100) bu değeri veremediği anlamına gelir.',
    ivMatch: 'Eşleşen IV: {{range}}',
    noMatch: 'Hiçbir IV (0–100) bu değeri vermiyor — seviyeyi, yıldızları, ruhları, güven seviyesini ve uyandırışı kontrol edin.',
    craftNoIv: 'İş Hızının IV’si yoktur — oyundaki değer farklıysa diğer ayarlardan biri yanlıştır.',
    fBase: 'tür taban değeri',
    fBonus: 'sabit bonus (her Pal)',
    fCoeff: 'seviye başına katsayı',
    fConst: 'sabit değer',
    fAwakenMul: 'uyandırış çarpanı (yalnızca tür tabanı)',
    fGrowth: 'güven seviyesi başına kazanç',
    fIvCoeff: 'IV puanı başına bonus',
    fStarRate: 'yıldız başına bonus',
    fSoulRate: 'ruh seviyesi başına bonus',
    fTribe: 'İş Hızı tür çarpanı',
    fPrev: 'önceki ara toplam',
    fBaseEnh: 'uyandırış ve güven dahil tür tabanı',
  },
  'vi-VN': {
    title: 'Trình mô phỏng chỉ số',
    caption:
      'Tính chính xác chỉ số trong game của bất kỳ Pal nào từ các nâng cấp của nó — hoặc nhập chỉ số hiển thị để tìm ra IV ẩn (tiềm năng).',
    pickPal: 'Chọn một pal…',
    base: 'cơ bản',
    level: 'Cấp',
    stars: 'Sao tinh luyện',
    bond: 'Cấp Độ Tin Cậy',
    awakening: 'Thức Tỉnh',
    souls: 'Cấp linh hồn (Tượng Đá Sức Mạnh)',
    ivs: 'IV (tiềm năng ẩn)',
    stat: 'Chỉ số',
    colBase: 'Gốc',
    colTrust: 'Tin Cậy',
    colIv: 'IV',
    colStars: 'Sao',
    colSouls: 'Linh hồn',
    stageFinal: 'Cuối cùng',
    colInGame: 'Trong game',
    stageNote:
      'Mỗi giai đoạn được làm tròn xuống trước khi nhân hệ số tiếp theo, đúng như cách game tính. Tốc độ làm việc không phụ thuộc cấp và IV.',
    editNote:
      'Sửa cột cuối để tự động giải ra IV tương ứng — màu đỏ nghĩa là không IV nào (0–100) cho ra giá trị đó.',
    ivMatch: 'IV khớp: {{range}}',
    noMatch: 'Không IV nào (0–100) cho ra giá trị này — kiểm tra cấp, sao, linh hồn, cấp Độ Tin Cậy và Thức Tỉnh.',
    craftNoIv: 'Tốc độ làm việc không có IV — nếu giá trị trong game khác, một trong các thiết lập còn lại chưa đúng.',
    fBase: 'chỉ số gốc của loài',
    fBonus: 'cộng cố định (mọi Pal)',
    fCoeff: 'hệ số mỗi cấp',
    fConst: 'hằng số cố định',
    fAwakenMul: 'hệ số Thức Tỉnh (chỉ áp dụng chỉ số gốc loài)',
    fGrowth: 'tăng mỗi cấp Độ Tin Cậy',
    fIvCoeff: 'cộng thêm mỗi điểm IV',
    fStarRate: 'cộng thêm mỗi sao',
    fSoulRate: 'cộng thêm mỗi cấp linh hồn',
    fTribe: 'hệ số loài của tốc độ làm việc',
    fPrev: 'kết quả bước trước',
    fBaseEnh: 'chỉ số gốc loài gồm Thức Tỉnh và Tin Cậy',
  },
  'zh-CN': {
    title: '属性模拟器',
    caption:
      '根据强化状态精确计算任意帕鲁的游戏内属性，也可以输入游戏中显示的属性，反推隐藏的个体值（天赋）。',
    pickPal: '选择帕鲁…',
    base: '基础值',
    level: '等级',
    stars: '浓缩星级',
    bond: '信赖度等级',
    awakening: '觉醒',
    souls: '魂强化（力量石像）',
    ivs: '个体值（隐藏天赋）',
    stat: '属性',
    colBase: '基础值',
    colTrust: '信赖度',
    colIv: '个体值',
    colStars: '星级',
    colSouls: '魂',
    stageFinal: '最终值',
    colInGame: '游戏内',
    stageNote: '每一步都会先向下取整再乘下一个倍率，与游戏内部计算完全一致。工作速度不受等级和个体值影响。',
    editNote: '编辑最后一列可自动反推对应的个体值；显示红色表示任何个体值（0–100）都无法得到该数值。',
    ivMatch: '匹配的个体值：{{range}}',
    noMatch: '任何个体值（0–100）都无法得到该数值，请检查等级、星级、魂强化、信赖度等级和觉醒。',
    craftNoIv: '工作速度没有个体值；如果游戏内数值不同，说明其他某项设置有误。',
    fBase: '种族基础值',
    fBonus: '固定加成（所有帕鲁相同）',
    fCoeff: '每级成长系数',
    fConst: '固定常数',
    fAwakenMul: '觉醒倍率（仅作用于种族基础值）',
    fGrowth: '每级信赖度成长',
    fIvCoeff: '每点个体值加成',
    fStarRate: '每星加成',
    fSoulRate: '每级魂强化加成',
    fTribe: '工作速度种族倍率',
    fPrev: '上一步结果',
    fBaseEnh: '含觉醒与信赖度的种族基础值',
  },
  'zh-TW': {
    title: '屬性模擬器',
    caption:
      '根據強化狀態精確計算任意帕魯的遊戲內屬性，也可以輸入遊戲中顯示的屬性，反推隱藏的個體值（天賦）。',
    pickPal: '選擇帕魯…',
    base: '基礎值',
    level: '等級',
    stars: '濃縮星級',
    bond: '信賴度等級',
    awakening: '覺醒',
    souls: '魂強化（力量之像）',
    ivs: '個體值（隱藏天賦）',
    stat: '屬性',
    colBase: '基礎值',
    colTrust: '信賴度',
    colIv: '個體值',
    colStars: '星級',
    colSouls: '魂',
    stageFinal: '最終值',
    colInGame: '遊戲內',
    stageNote: '每一步都會先無條件捨去再乘上下一個倍率，與遊戲內部計算完全一致。工作速度不受等級與個體值影響。',
    editNote: '編輯最後一欄可自動反推對應的個體值；顯示紅色表示任何個體值（0–100）都無法得到該數值。',
    ivMatch: '匹配的個體值：{{range}}',
    noMatch: '任何個體值（0–100）都無法得到該數值，請檢查等級、星級、魂強化、信賴度等級與覺醒。',
    craftNoIv: '工作速度沒有個體值；若遊戲內數值不同，代表其他某項設定有誤。',
    fBase: '種族基礎值',
    fBonus: '固定加成（所有帕魯相同）',
    fCoeff: '每級成長係數',
    fConst: '固定常數',
    fAwakenMul: '覺醒倍率（僅作用於種族基礎值）',
    fGrowth: '每級信賴度成長',
    fIvCoeff: '每點個體值加成',
    fStarRate: '每星加成',
    fSoulRate: '每級魂強化加成',
    fTribe: '工作速度種族倍率',
    fPrev: '上一步結果',
    fBaseEnh: '含覺醒與信賴度的種族基礎值',
  },
}
