import { useEffect, useMemo, useState } from 'react'
import { IconInfoCircle, IconRefresh, IconTrash } from '@tabler/icons-react'
import { Button, Input } from '@gamemap/ui'
import { useTranslation } from 'react-i18next'
import { ContentPage } from '@/components/ContentPage'
import { calculateScenario, DEFAULT_GUILDS, DEFAULT_RULES, enumerateScenarios, isValidRoster, type LeagueGuild, type LeagueGroup, type LeagueRules, type LeagueScenario, type WeekNumber } from './league'

const ranks = [1, 2, 3, 4]
const numberValue = (value: string) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0 }

function WeekRankSelect({ guild, week, t, points, onChange }: { guild: LeagueGuild; week: WeekNumber; points: number[]; t: (key: string, options?: Record<string, unknown>) => string; onChange: (rank: number | null, group?: LeagueGroup | null) => void }) {
  const groupAware = week === 2 || week === 4
  const value = groupAware && guild.weeks[week].rank !== null && guild.weeks[week].group ? `${guild.weeks[week].group}:${guild.weeks[week].rank}` : guild.weeks[week].rank ?? ''
  return <span className="inline-flex items-center gap-1"><select aria-label={`${guild.name} ${t('league.weekShort', { week })}`} value={value} onChange={(event) => { if (!event.target.value) { onChange(null, groupAware ? null : undefined); return }; if (groupAware) { const [group, rank] = event.target.value.split(':'); onChange(Number(rank), group as LeagueGroup) } else onChange(Number(event.target.value)) }} className={groupAware ? 'h-9 w-44 rounded-md border border-border bg-background px-1 text-sm' : 'h-9 w-16 rounded-md border border-border bg-background px-1 text-sm'}>
    <option value="">—</option>
    {groupAware ? <><optgroup label={t('league.winner')}>{ranks.map((rank) => <option key={`winner:${rank}`} value={`winner:${rank}`}>{t('league.winner')} {rank}</option>)}</optgroup><optgroup label={t('league.loser')}>{ranks.map((rank) => <option key={`loser:${rank}`} value={`loser:${rank}`}>{t('league.loser')} {rank}</option>)}</optgroup></> : ranks.map((rank) => <option key={rank} value={rank}>{rank}</option>)}
  </select>{guild.weeks[week].rank !== null ? <span className="whitespace-nowrap text-xs font-medium text-emerald-700 dark:text-emerald-300">+{points[guild.weeks[week].rank - 1] ?? 0}</span> : null}</span>
}

function ScenarioLine({ scenario, targetId, t }: { scenario: LeagueScenario; targetId: string; t: (key: string, options?: Record<string, unknown>) => string }) {
  const target = scenario.results.find((result) => result.id === targetId)
  if (!target) return null
  return <div className="rounded-md border border-border bg-background p-3 text-sm"><div className="flex flex-wrap items-center gap-2 font-medium"><span className={target.finalRank <= 4 ? 'text-emerald-700 dark:text-emerald-300' : 'text-rose-700 dark:text-rose-300'}>{t('league.rankValue', { rank: target.finalRank })}</span><span>{target.name}</span><span className="text-muted-foreground">{target.finalPoints} {t('league.points')}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{t('league.weekPath')}: {([1, 2, 3, 4] as WeekNumber[]).map((week) => `${t('league.weekShort', { week })}#${scenario.assignments[targetId]?.[week] ?? '—'}`).join(' · ')}</p></div>
}

export default function LeaguePointsPage() {
  const { t } = useTranslation()
  const [guilds, setGuilds] = useState<LeagueGuild[]>(DEFAULT_GUILDS.map((guild) => ({ ...guild, weeks: { ...guild.weeks } })))
  const [rules, setRules] = useState<LeagueRules>({ ...DEFAULT_RULES, matchPoints: [...DEFAULT_RULES.matchPoints], round1Bonuses: [...DEFAULT_RULES.round1Bonuses], round2Bonuses: [...DEFAULT_RULES.round2Bonuses] })
  const [targetId, setTargetId] = useState(DEFAULT_GUILDS[0].id)
  useEffect(() => { document.title = `${t('league.title')} - ${t('siteTitle')}` }, [t])
  const valid = isValidRoster(guilds)
  const enumeration = useMemo(() => valid ? enumerateScenarios(guilds, rules, 7) : { scenarios: [], truncated: false }, [guilds, rules, valid])
  const fixed = guilds.every((guild) => ([1, 2, 3, 4] as WeekNumber[]).every((week) => guild.weeks[week].rank !== null))
  const current = fixed && valid ? calculateScenario(guilds, rules) : null
  const targetTotal = guilds.find((guild) => guild.id === targetId)?.targetTotal
  const matching = targetTotal === null || targetTotal === undefined ? enumeration.scenarios : enumeration.scenarios.filter((scenario) => scenario.results.find((result) => result.id === targetId)?.finalPoints === targetTotal)
  const targetRanks = [...new Set(enumeration.scenarios.map((scenario) => scenario.results.find((result) => result.id === targetId)?.finalRank).filter((rank): rank is number => Boolean(rank)))].sort((a, b) => a - b)
  const updateGuild = (id: string, patch: Partial<LeagueGuild>) => setGuilds((items) => items.map((guild) => guild.id === id ? { ...guild, ...patch } : guild))
  const updateWeek = (id: string, week: WeekNumber, patch: Partial<LeagueGuild['weeks'][WeekNumber]>) => setGuilds((items) => items.map((guild) => guild.id === id ? { ...guild, weeks: { ...guild.weeks, [week]: { ...guild.weeks[week], ...patch } } } : guild))
  const updateRule = (key: 'matchPoints' | 'round1Bonuses' | 'round2Bonuses', index: number, value: string) => setRules((currentRules) => ({ ...currentRules, [key]: currentRules[key].map((item, itemIndex) => itemIndex === index ? numberValue(value) : item) }))
  const reset = () => { setGuilds(DEFAULT_GUILDS.map((guild) => ({ ...guild, weeks: { ...guild.weeks } }))); setRules({ ...DEFAULT_RULES, matchPoints: [...DEFAULT_RULES.matchPoints], round1Bonuses: [...DEFAULT_RULES.round1Bonuses], round2Bonuses: [...DEFAULT_RULES.round2Bonuses] }); setTargetId(DEFAULT_GUILDS[0].id) }

  return <ContentPage active="/tools/league-points" title={t('league.title')} wide><div className="space-y-5" data-testid="league-points-page">
    <header className="border-b border-border pb-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">{t('league.eyebrow')}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{t('league.title')}</h1><p className="mt-1 max-w-4xl text-sm leading-6 text-muted-foreground">{t('league.description')}</p></header>
    <section className="rounded-lg border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{t('league.rulesTitle')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('league.rulesHint')}</p></div><Button variant="ghost" size="sm" onClick={reset}><IconRefresh size={16} />{t('league.reset')}</Button></div><div className="mt-4 grid gap-4 xl:grid-cols-3"><RuleInputs title={t('league.matchPoints')} values={rules.matchPoints} onChange={(index, value) => updateRule('matchPoints', index, value)} t={t} /><RuleInputs title={t('league.round1Bonuses')} values={rules.round1Bonuses} onChange={(index, value) => updateRule('round1Bonuses', index, value)} t={t} /><RuleInputs title={t('league.round2Bonuses')} values={rules.round2Bonuses} onChange={(index, value) => updateRule('round2Bonuses', index, value)} t={t} /></div></section>
    <section className="rounded-lg border border-border bg-card p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{t('league.rosterTitle')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('league.rosterHint')}</p></div><label className="flex items-center gap-2 text-sm"><span>{t('league.target')}</span><select value={targetId} onChange={(event) => setTargetId(event.target.value)} className="h-9 rounded-md border border-border bg-background px-2">{guilds.map((guild) => <option key={guild.id} value={guild.id}>{guild.name}</option>)}</select></label></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[960px] text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="px-2 py-2">{t('league.guild')}</th>{([1, 2, 3, 4] as WeekNumber[]).map((week) => <th key={week} className="px-2 py-2">{t('league.weekShort', { week })}</th>)}<th className="px-2 py-2">{t('league.targetTotal')}</th><th className="px-2 py-2" /></tr></thead><tbody>{guilds.map((guild) => <tr key={guild.id} className="border-b border-border/60 last:border-0"><td className="px-2 py-2"><Input aria-label={t('league.guild')} value={guild.name} onChange={(event) => updateGuild(guild.id, { name: event.target.value })} className="h-9 min-w-40" /></td>{([1, 2, 3, 4] as WeekNumber[]).map((week) => <td key={week} className="px-2 py-2"><WeekRankSelect guild={guild} week={week} points={rules.matchPoints} t={t} onChange={(rank, group) => updateWeek(guild.id, week, { rank, ...(group !== undefined ? { group } : {}) })} /></td>)}<td className="px-2 py-2"><Input aria-label={t('league.targetTotal')} type="number" min={0} placeholder="—" value={guild.targetTotal ?? ''} onChange={(event) => updateGuild(guild.id, { targetTotal: event.target.value === '' ? null : numberValue(event.target.value) })} className="h-9 w-24" /></td><td className="px-2 py-2 text-right"><button type="button" disabled={guilds.length <= 8} aria-label={t('league.remove')} className="rounded p-2 text-muted-foreground enabled:hover:bg-muted enabled:hover:text-foreground disabled:opacity-30" onClick={() => setGuilds((items) => items.length > 8 ? items.filter((item) => item.id !== guild.id) : items)}><IconTrash size={16} /></button></td></tr>)}</tbody></table></div>
      <div className="mt-3 flex flex-wrap items-center gap-3">{!valid ? <span className="text-xs text-amber-700 dark:text-amber-300"><IconInfoCircle size={14} className="mr-1 inline" />{t('league.rosterInvalid')}</span> : <span className="text-xs text-muted-foreground">{t('league.inputHint')}</span>}</div>
    </section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-border bg-card p-4 shadow-sm"><h2 className="font-semibold">{t('league.summaryTitle')}</h2>{!valid ? <p className="mt-3 text-sm text-muted-foreground">{t('league.completeRoster')}</p> : enumeration.truncated ? <p className="mt-3 rounded-md border border-amber-300/60 bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/20 dark:text-amber-200"><IconInfoCircle size={16} className="mr-1 inline" />{t('league.tooMany', { limit: 6 })}</p> : <><p className="mt-3 text-xs text-muted-foreground">{t('league.possibleRanks')}</p><p className="mt-1 text-2xl font-semibold">{targetRanks.length ? targetRanks.map((rank) => t('league.rankValue', { rank })).join('、') : '—'}</p><p className="mt-1 text-xs text-muted-foreground">{t('league.scenarioCount', { count: matching.length })}</p>{matching.length ? <p className="mt-3 rounded-md border border-emerald-300/60 bg-emerald-50 p-3 text-sm text-emerald-800 dark:bg-emerald-950/20 dark:text-emerald-200">{t('league.qualifyCount', { count: matching.filter((scenario) => (scenario.results.find((result) => result.id === targetId)?.finalRank ?? 99) <= rules.qualificationCount).length })}</p> : <p className="mt-3 rounded-md border border-rose-300/60 bg-rose-50 p-3 text-sm text-rose-800 dark:bg-rose-950/20 dark:text-rose-200">{t('league.noMatch')}</p>}</>}</div><div className="rounded-lg border border-border bg-card p-4 shadow-sm"><h2 className="font-semibold">{t('league.pathsTitle')}</h2>{!valid ? <p className="mt-3 text-sm text-muted-foreground">{t('league.completeRoster')}</p> : enumeration.truncated ? <p className="mt-3 text-sm text-muted-foreground">{t('league.tooMany', { limit: 6 })}</p> : matching.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">{t('league.noPath')}</p> : <div className="mt-3 space-y-2">{matching.slice(0, 6).map((scenario, index) => <ScenarioLine key={index} scenario={scenario} targetId={targetId} t={t} />)}</div>}</div></section>
    {current ? <section className="rounded-lg border border-border bg-card p-4 shadow-sm"><h2 className="font-semibold">{t('league.currentTitle')}</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="px-2 py-2">{t('league.guild')}</th>{([1, 2, 3, 4] as WeekNumber[]).map((week) => <th key={week} className="px-2 py-2">{t('league.weekShort', { week })}</th>)}<th className="px-2 py-2">{t('league.round1Total')}</th><th className="px-2 py-2">{t('league.round2Total')}</th><th className="px-2 py-2">{t('league.finalTotal')}</th><th className="px-2 py-2">{t('league.finalRank')}</th></tr></thead><tbody>{current.results.map((result) => <tr key={result.id} className="border-b border-border/60 last:border-0"><td className="px-2 py-2 font-medium">{result.name}</td>{result.weekPoints.map((points, index) => <td key={index} className="px-2 py-2">{points}</td>)}<td className="px-2 py-2">{result.round1Total}</td><td className="px-2 py-2">{result.round2Total}</td><td className="px-2 py-2 font-semibold">{result.finalPoints}</td><td className="px-2 py-2">#{result.finalRank}</td></tr>)}</tbody></table></div></section> : null}
  </div></ContentPage>
}

function RuleInputs({ title, values, onChange, t }: { title: string; values: number[]; onChange: (index: number, value: string) => void; t: (key: string, options?: Record<string, unknown>) => string }) { return <div><h3 className="text-sm font-medium">{title}</h3><div className="mt-2 grid grid-cols-4 gap-2">{values.map((value, index) => <label key={index} className="min-w-0 text-xs text-muted-foreground"><span className="block truncate">{t('league.place', { rank: index + 1 })}</span><Input type="number" min={0} value={value} onChange={(event) => onChange(index, event.target.value)} className="mt-1 h-9 w-full min-w-0" /></label>)}</div></div> }
