version: '3.5'
services:
  celery:
    image: tcimba/aion2-backend
    restart: always
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
        PYPI_MIRROR: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    networks:
      - aion2-network
    environment:
      - REDIS_HOST=172.16.24.23
      - REDIS_PORT=16379
    command: >
      poetry run celery
      -A aion2.backend.app.celery:celery_app
      worker
      --loglevel=info
      --concurrency=4
networks:
  aion2-network:
