from enum import Enum


class ErrorCode(str, Enum):
    ABYSSARTIFACTADMINNOTFOUNDERROR = "AbyssArtifactAdminNotFoundError"
    ABYSSARTIFACTNOTFOUNDERROR = "AbyssArtifactNotFoundError"
    ABYSSARTIFACTSTATENOTFOUNDERROR = "AbyssArtifactStateNotFoundError"
    ALTCHACHALLENGEERROR = "AltchaChallengeError"
    APINOTIMPLEMENTEDERROR = "ApiNotImplementedError"
    BITSETTOOLONGERROR = "BitSetTooLongError"
    CATEGORYNOTFOUNDERROR = "CategoryNotFoundError"
    COMMENTNOTFOUNDERROR = "CommentNotFoundError"
    ERROR = "Error"
    ILLEGALFIELDERROR = "IllegalFieldError"
    IMAGEERROR = "ImageError"
    INTEGRITYERROR = "IntegrityError"
    INTERNALSERVERERROR = "InternalServerError"
    INVALIDTOKENERROR = "InvalidTokenError"
    LANGUAGENOTFOUNDERROR = "LanguageNotFoundError"
    MAPNOTFOUNDERROR = "MapNotFoundError"
    MARKERFEEDBACKNOTEDITABLEERROR = "MarkerFeedbackNotEditableError"
    MARKERFEEDBACKNOTFOUNDERROR = "MarkerFeedbackNotFoundError"
    MARKERIMAGENOTFOUNDERROR = "MarkerImageNotFoundError"
    MARKERNOTFOUNDERROR = "MarkerNotFoundError"
    PERMISSIONERROR = "PermissionError"
    RATELIMITEXCEEDEDERROR = "RateLimitExceededError"
    REGIONNOTFOUNDERROR = "RegionNotFoundError"
    S3CONFIGERROR = "S3ConfigError"
    S3UPLOADERROR = "S3UploadError"
    SEASONNOTFOUNDERROR = "SeasonNotFoundError"
    SERVERMATCHINGNOTFOUNDERROR = "ServerMatchingNotFoundError"
    SERVERNOTFOUNDERROR = "ServerNotFoundError"
    SUBTYPENOTFOUNDERROR = "SubTypeNotFoundError"
    SUCCESS = "Success"
    UNAUTHORIZEDERROR = "UnauthorizedError"
    UNKNOWNFIELDERROR = "UnknownFieldError"
    USERALREADYEXISTSERROR = "UserAlreadyExistsError"
    USERALREADYVERIFIEDERROR = "UserAlreadyVerifiedError"
    USEREMAILALREADYEXISTSERROR = "UserEmailAlreadyExistsError"
    USERINACTIVEERROR = "UserInactiveError"
    USERINVALIDPASSWORDERROR = "UserInvalidPasswordError"
    USERMANAGERERROR = "UserManagerError"
    USERNOTFOUNDERROR = "UserNotFoundError"
    USERNOTUPDATABLEERROR = "UserNotUpdatableError"
    VALIDATIONERROR = "ValidationError"

    def __str__(self) -> str:
        return str(self.value)
