import type { Language } from './i18n'

// Pal-encyclopedia strings, merged into the `translation` namespace under a
// `pal` key (see i18n.ts). Data-driven labels (element / work / skill / item /
// pal names) come from the locale data files, not here — this table only holds
// the encyclopedia's own UI chrome.
export interface PalStrings {
  title: string
  searchPlaceholder: string
  count: string
  loading: string
  notFound: string
  backToList: string
  viewInEncyclopedia: string
  viewOnMap: string
  noSpawns: string
  lv: string
  skill: string
  power: string
  cooldown: string
  rankScaling: string
  condensation: string
  unlockItem: string
  bredFrom: string
  openBreeding: string
  noBreeding: string
  section: {
    description: string
    stats: string
    work: string
    partnerSkill: string
    activeSkills: string
    passives: string
    drops: string
    spawns: string
    breeding: string
  }
  stat: {
    hp: string
    meleeAttack: string
    shotAttack: string
    defense: string
    craftSpeed: string
    stamina: string
    foodAmount: string
    captureRate: string
    price: string
  }
}

export const PAL_STRINGS: Record<Language, PalStrings> = {
  'en-US': {
    title: 'Paldeck',
    searchPlaceholder: 'Search Pals…',
    count: '{{count}} Pals',
    loading: 'Loading…',
    notFound: 'No Pal found for "{{id}}".',
    backToList: 'Back to Paldeck',
    viewInEncyclopedia: 'View in Paldeck →',
    viewOnMap: 'View on full map',
    noSpawns: 'This Pal has no known wild spawns.',
    lv: 'Lv',
    skill: 'Skill',
    power: 'Power',
    cooldown: 'Cooldown',
    rankScaling: 'Rank scaling',
    condensation: 'Unlocked and strengthened via condensation (Lv.1–5).',
    unlockItem: 'Unlock Item',
    bredFrom: 'Bred from',
    openBreeding: 'Open breeding calculator →',
    noBreeding: 'No breeding combinations produce this Pal.',
    section: {
      description: 'Description',
      stats: 'Base Stats',
      work: 'Work Suitability',
      partnerSkill: 'Partner Skill',
      activeSkills: 'Active Skills',
      passives: 'Passive Skills',
      drops: 'Drops',
      spawns: 'Spawn Locations',
      breeding: 'Breeding',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Melee Attack',
      shotAttack: 'Ranged Attack',
      defense: 'Defense',
      craftSpeed: 'Work Speed',
      stamina: 'Stamina',
      foodAmount: 'Food',
      captureRate: 'Capture Rate',
      price: 'Gold',
    },
  },
  'de-DE': {
    title: 'Paldex',
    searchPlaceholder: 'Pals suchen…',
    count: '{{count}} Pals',
    loading: 'Wird geladen…',
    notFound: 'Kein Pal für „{{id}}" gefunden.',
    backToList: 'Zurück zur Paldex',
    viewInEncyclopedia: 'In der Paldex ansehen →',
    viewOnMap: 'Auf voller Karte ansehen',
    noSpawns: 'Für dieses Pal sind keine wilden Spawns bekannt.',
    lv: 'Stufe',
    skill: 'Fähigkeit',
    power: 'Stärke',
    cooldown: 'Abklingzeit',
    rankScaling: 'Rang-Skalierung',
    condensation: 'Durch Verdichtung freigeschaltet und verstärkt (Stufe 1–5).',
    unlockItem: 'Freischaltobjekt',
    bredFrom: 'Gezüchtet aus',
    openBreeding: 'Zucht-Rechner öffnen →',
    noBreeding: 'Keine Zuchtkombination erzeugt dieses Pal.',
    section: {
      description: 'Beschreibung',
      stats: 'Basiswerte',
      work: 'Arbeitseignung',
      partnerSkill: 'Partner-Fähigkeit',
      activeSkills: 'Aktive Fähigkeiten',
      passives: 'Passive Fähigkeiten',
      drops: 'Beute',
      spawns: 'Fundorte',
      breeding: 'Zucht',
    },
    stat: {
      hp: 'LP',
      meleeAttack: 'Nahkampfangriff',
      shotAttack: 'Fernkampfangriff',
      defense: 'Verteidigung',
      craftSpeed: 'Arbeitstempo',
      stamina: 'Ausdauer',
      foodAmount: 'Nahrung',
      captureRate: 'Fangrate',
      price: 'Gold',
    },
  },
  'es-ES': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Cargando…',
    notFound: 'No se encontró ningún Pal para "{{id}}".',
    backToList: 'Volver a la Paldex',
    viewInEncyclopedia: 'Ver en la Paldex →',
    viewOnMap: 'Ver en el mapa completo',
    noSpawns: 'Este Pal no tiene apariciones salvajes conocidas.',
    lv: 'Nv',
    skill: 'Habilidad',
    power: 'Poder',
    cooldown: 'Enfriamiento',
    rankScaling: 'Escala por rango',
    condensation: 'Se desbloquea y refuerza mediante condensación (Nv.1–5).',
    unlockItem: 'Objeto de desbloqueo',
    bredFrom: 'Criado a partir de',
    openBreeding: 'Abrir calculadora de crianza →',
    noBreeding: 'Ninguna combinación de crianza produce este Pal.',
    section: {
      description: 'Descripción',
      stats: 'Estadísticas base',
      work: 'Aptitud laboral',
      partnerSkill: 'Habilidad de compañero',
      activeSkills: 'Habilidades activas',
      passives: 'Habilidades pasivas',
      drops: 'Botín',
      spawns: 'Ubicaciones de aparición',
      breeding: 'Crianza',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Ataque cuerpo a cuerpo',
      shotAttack: 'Ataque a distancia',
      defense: 'Defensa',
      craftSpeed: 'Velocidad de trabajo',
      stamina: 'Aguante',
      foodAmount: 'Comida',
      captureRate: 'Índice de captura',
      price: 'Oro',
    },
  },
  'es-MX': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Cargando…',
    notFound: 'No se encontró ningún Pal para "{{id}}".',
    backToList: 'Volver a la Paldex',
    viewInEncyclopedia: 'Ver en la Paldex →',
    viewOnMap: 'Ver en el mapa completo',
    noSpawns: 'Este Pal no tiene apariciones salvajes conocidas.',
    lv: 'Nv',
    skill: 'Habilidad',
    power: 'Poder',
    cooldown: 'Enfriamiento',
    rankScaling: 'Escala por rango',
    condensation: 'Se desbloquea y refuerza mediante condensación (Nv.1–5).',
    unlockItem: 'Objeto de desbloqueo',
    bredFrom: 'Criado a partir de',
    openBreeding: 'Abrir calculadora de crianza →',
    noBreeding: 'Ninguna combinación de crianza produce este Pal.',
    section: {
      description: 'Descripción',
      stats: 'Estadísticas base',
      work: 'Aptitud laboral',
      partnerSkill: 'Habilidad de compañero',
      activeSkills: 'Habilidades activas',
      passives: 'Habilidades pasivas',
      drops: 'Botín',
      spawns: 'Ubicaciones de aparición',
      breeding: 'Crianza',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Ataque cuerpo a cuerpo',
      shotAttack: 'Ataque a distancia',
      defense: 'Defensa',
      craftSpeed: 'Velocidad de trabajo',
      stamina: 'Aguante',
      foodAmount: 'Comida',
      captureRate: 'Índice de captura',
      price: 'Oro',
    },
  },
  'fr-FR': {
    title: 'Paldex',
    searchPlaceholder: 'Rechercher des Pals…',
    count: '{{count}} Pals',
    loading: 'Chargement…',
    notFound: 'Aucun Pal trouvé pour « {{id}} ».',
    backToList: 'Retour à la Paldex',
    viewInEncyclopedia: 'Voir dans la Paldex →',
    viewOnMap: 'Voir sur la carte complète',
    noSpawns: "Ce Pal n'a aucune apparition sauvage connue.",
    lv: 'Niv',
    skill: 'Compétence',
    power: 'Puissance',
    cooldown: 'Recharge',
    rankScaling: 'Progression par rang',
    condensation: 'Débloqué et renforcé par condensation (Niv.1–5).',
    unlockItem: 'Objet de déblocage',
    bredFrom: 'Issu de',
    openBreeding: "Ouvrir le calculateur d'élevage →",
    noBreeding: 'Aucune combinaison ne produit ce Pal.',
    section: {
      description: 'Description',
      stats: 'Statistiques de base',
      work: 'Aptitude au travail',
      partnerSkill: 'Compétence de partenaire',
      activeSkills: 'Compétences actives',
      passives: 'Compétences passives',
      drops: 'Butin',
      spawns: "Lieux d'apparition",
      breeding: 'Élevage',
    },
    stat: {
      hp: 'PV',
      meleeAttack: 'Attaque de mêlée',
      shotAttack: 'Attaque à distance',
      defense: 'Défense',
      craftSpeed: 'Vitesse de travail',
      stamina: 'Endurance',
      foodAmount: 'Nourriture',
      captureRate: 'Taux de capture',
      price: 'Or',
    },
  },
  'id-ID': {
    title: 'Paldex',
    searchPlaceholder: 'Cari Pal…',
    count: '{{count}} Pal',
    loading: 'Memuat…',
    notFound: 'Tidak ada Pal untuk "{{id}}".',
    backToList: 'Kembali ke Paldex',
    viewInEncyclopedia: 'Lihat di Paldex →',
    viewOnMap: 'Lihat di peta penuh',
    noSpawns: 'Pal ini tidak memiliki kemunculan liar yang diketahui.',
    lv: 'Lv',
    skill: 'Skill',
    power: 'Kekuatan',
    cooldown: 'Waktu jeda',
    rankScaling: 'Skala peringkat',
    condensation: 'Dibuka dan diperkuat melalui kondensasi (Lv.1–5).',
    unlockItem: 'Item Pembuka',
    bredFrom: 'Diternak dari',
    openBreeding: 'Buka kalkulator ternak →',
    noBreeding: 'Tidak ada kombinasi ternak yang menghasilkan Pal ini.',
    section: {
      description: 'Deskripsi',
      stats: 'Statistik Dasar',
      work: 'Kecocokan Kerja',
      partnerSkill: 'Skill Pasangan',
      activeSkills: 'Skill Aktif',
      passives: 'Skill Pasif',
      drops: 'Jarahan',
      spawns: 'Lokasi Kemunculan',
      breeding: 'Ternak',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Serangan Jarak Dekat',
      shotAttack: 'Serangan Jarak Jauh',
      defense: 'Pertahanan',
      craftSpeed: 'Kecepatan Kerja',
      stamina: 'Stamina',
      foodAmount: 'Makanan',
      captureRate: 'Tingkat Tangkap',
      price: 'Emas',
    },
  },
  'it-IT': {
    title: 'Paldex',
    searchPlaceholder: 'Cerca Pal…',
    count: '{{count}} Pal',
    loading: 'Caricamento…',
    notFound: 'Nessun Pal trovato per "{{id}}".',
    backToList: 'Torna alla Paldex',
    viewInEncyclopedia: 'Vedi nella Paldex →',
    viewOnMap: 'Vedi sulla mappa completa',
    noSpawns: 'Questo Pal non ha comparse selvatiche note.',
    lv: 'Lv',
    skill: 'Abilità',
    power: 'Potenza',
    cooldown: 'Ricarica',
    rankScaling: 'Scala per grado',
    condensation: 'Sbloccato e potenziato tramite condensazione (Lv.1–5).',
    unlockItem: 'Oggetto di sblocco',
    bredFrom: 'Generato da',
    openBreeding: 'Apri il calcolatore di allevamento →',
    noBreeding: 'Nessuna combinazione di allevamento produce questo Pal.',
    section: {
      description: 'Descrizione',
      stats: 'Statistiche base',
      work: 'Idoneità al lavoro',
      partnerSkill: 'Abilità del compagno',
      activeSkills: 'Abilità attive',
      passives: 'Abilità passive',
      drops: 'Bottino',
      spawns: 'Luoghi di comparsa',
      breeding: 'Allevamento',
    },
    stat: {
      hp: 'PS',
      meleeAttack: 'Attacco in mischia',
      shotAttack: 'Attacco a distanza',
      defense: 'Difesa',
      craftSpeed: 'Velocità di lavoro',
      stamina: 'Vigore',
      foodAmount: 'Cibo',
      captureRate: 'Tasso di cattura',
      price: 'Oro',
    },
  },
  'ja-JP': {
    title: 'パルズかんせいずかん',
    searchPlaceholder: 'パルを検索…',
    count: '{{count}} 体',
    loading: '読み込み中…',
    notFound: '「{{id}}」のパルが見つかりません。',
    backToList: '図鑑に戻る',
    viewInEncyclopedia: '図鑑で見る →',
    viewOnMap: '全体マップで見る',
    noSpawns: 'このパルの野生出現地点は不明です。',
    lv: 'Lv',
    skill: 'スキル',
    power: '威力',
    cooldown: 'クールタイム',
    rankScaling: 'ランク倍率',
    condensation: '凝縮で解放・強化されます（Lv.1〜5）。',
    unlockItem: '解放アイテム',
    bredFrom: '交配元',
    openBreeding: '交配計算機を開く →',
    noBreeding: 'このパルを生む交配の組み合わせはありません。',
    section: {
      description: '説明',
      stats: '基礎ステータス',
      work: '仕事適性',
      partnerSkill: 'パートナースキル',
      activeSkills: 'アクティブスキル',
      passives: 'パッシブスキル',
      drops: 'ドロップ',
      spawns: '出現場所',
      breeding: '交配',
    },
    stat: {
      hp: 'HP',
      meleeAttack: '近接攻撃',
      shotAttack: '遠隔攻撃',
      defense: '防御',
      craftSpeed: '作業速度',
      stamina: 'スタミナ',
      foodAmount: '食事量',
      captureRate: '捕獲率',
      price: 'ゴールド',
    },
  },
  'ko-KR': {
    title: '팰 도감',
    searchPlaceholder: '팰 검색…',
    count: '{{count}}마리',
    loading: '불러오는 중…',
    notFound: '"{{id}}"에 해당하는 팰을 찾을 수 없습니다.',
    backToList: '도감으로 돌아가기',
    viewInEncyclopedia: '도감에서 보기 →',
    viewOnMap: '전체 지도에서 보기',
    noSpawns: '이 팰의 야생 출현 지점이 없습니다.',
    lv: 'Lv',
    skill: '스킬',
    power: '위력',
    cooldown: '쿨타임',
    rankScaling: '랭크 배율',
    condensation: '응축으로 해금·강화됩니다 (Lv.1~5).',
    unlockItem: '해금 아이템',
    bredFrom: '교배 재료',
    openBreeding: '교배 계산기 열기 →',
    noBreeding: '이 팰을 만드는 교배 조합이 없습니다.',
    section: {
      description: '설명',
      stats: '기본 능력치',
      work: '작업 적성',
      partnerSkill: '파트너 스킬',
      activeSkills: '액티브 스킬',
      passives: '패시브 스킬',
      drops: '드롭',
      spawns: '출현 위치',
      breeding: '교배',
    },
    stat: {
      hp: 'HP',
      meleeAttack: '근접 공격',
      shotAttack: '원거리 공격',
      defense: '방어',
      craftSpeed: '작업 속도',
      stamina: '스태미나',
      foodAmount: '식사량',
      captureRate: '포획률',
      price: '골드',
    },
  },
  'pl-PL': {
    title: 'Paldex',
    searchPlaceholder: 'Szukaj Pali…',
    count: 'Pale: {{count}}',
    loading: 'Wczytywanie…',
    notFound: 'Nie znaleziono Pala dla „{{id}}".',
    backToList: 'Powrót do Paldeksu',
    viewInEncyclopedia: 'Zobacz w Paldeksie →',
    viewOnMap: 'Zobacz na pełnej mapie',
    noSpawns: 'Ten Pal nie ma znanych dzikich miejsc odrodzenia.',
    lv: 'Poz',
    skill: 'Umiejętność',
    power: 'Moc',
    cooldown: 'Odnowienie',
    rankScaling: 'Skalowanie rangi',
    condensation: 'Odblokowywany i wzmacniany przez kondensację (Poz.1–5).',
    unlockItem: 'Przedmiot odblokowujący',
    bredFrom: 'Wyhodowany z',
    openBreeding: 'Otwórz kalkulator hodowli →',
    noBreeding: 'Żadna kombinacja hodowli nie tworzy tego Pala.',
    section: {
      description: 'Opis',
      stats: 'Statystyki podstawowe',
      work: 'Przydatność do pracy',
      partnerSkill: 'Umiejętność partnera',
      activeSkills: 'Umiejętności aktywne',
      passives: 'Umiejętności pasywne',
      drops: 'Łup',
      spawns: 'Miejsca występowania',
      breeding: 'Hodowla',
    },
    stat: {
      hp: 'PŻ',
      meleeAttack: 'Atak wręcz',
      shotAttack: 'Atak dystansowy',
      defense: 'Obrona',
      craftSpeed: 'Tempo pracy',
      stamina: 'Wytrzymałość',
      foodAmount: 'Jedzenie',
      captureRate: 'Wskaźnik schwytania',
      price: 'Złoto',
    },
  },
  'pt-BR': {
    title: 'Paldex',
    searchPlaceholder: 'Buscar Pals…',
    count: '{{count}} Pals',
    loading: 'Carregando…',
    notFound: 'Nenhum Pal encontrado para "{{id}}".',
    backToList: 'Voltar à Paldex',
    viewInEncyclopedia: 'Ver na Paldex →',
    viewOnMap: 'Ver no mapa completo',
    noSpawns: 'Este Pal não tem surgimentos selvagens conhecidos.',
    lv: 'Nv',
    skill: 'Habilidade',
    power: 'Poder',
    cooldown: 'Recarga',
    rankScaling: 'Escala por classe',
    condensation: 'Desbloqueado e reforçado por condensação (Nv.1–5).',
    unlockItem: 'Item de desbloqueio',
    bredFrom: 'Gerado a partir de',
    openBreeding: 'Abrir calculadora de reprodução →',
    noBreeding: 'Nenhuma combinação de reprodução gera este Pal.',
    section: {
      description: 'Descrição',
      stats: 'Atributos base',
      work: 'Aptidão de trabalho',
      partnerSkill: 'Habilidade de parceiro',
      activeSkills: 'Habilidades ativas',
      passives: 'Habilidades passivas',
      drops: 'Itens',
      spawns: 'Locais de surgimento',
      breeding: 'Reprodução',
    },
    stat: {
      hp: 'PV',
      meleeAttack: 'Ataque corpo a corpo',
      shotAttack: 'Ataque à distância',
      defense: 'Defesa',
      craftSpeed: 'Velocidade de trabalho',
      stamina: 'Vigor',
      foodAmount: 'Comida',
      captureRate: 'Taxa de captura',
      price: 'Ouro',
    },
  },
  'ru-RU': {
    title: 'Палдекс',
    searchPlaceholder: 'Поиск палов…',
    count: 'Палов: {{count}}',
    loading: 'Загрузка…',
    notFound: 'Пал по запросу «{{id}}» не найден.',
    backToList: 'Назад в Палдекс',
    viewInEncyclopedia: 'Открыть в Палдексе →',
    viewOnMap: 'Показать на полной карте',
    noSpawns: 'У этого пала нет известных мест появления в дикой природе.',
    lv: 'Ур',
    skill: 'Навык',
    power: 'Сила',
    cooldown: 'Перезарядка',
    rankScaling: 'Масштаб по рангу',
    condensation: 'Открывается и усиливается конденсацией (Ур.1–5).',
    unlockItem: 'Предмет разблокировки',
    bredFrom: 'Выведен из',
    openBreeding: 'Открыть калькулятор разведения →',
    noBreeding: 'Ни одна комбинация разведения не даёт этого пала.',
    section: {
      description: 'Описание',
      stats: 'Базовые характеристики',
      work: 'Пригодность к работе',
      partnerSkill: 'Навык напарника',
      activeSkills: 'Активные навыки',
      passives: 'Пассивные навыки',
      drops: 'Добыча',
      spawns: 'Места появления',
      breeding: 'Разведение',
    },
    stat: {
      hp: 'ОЗ',
      meleeAttack: 'Ближняя атака',
      shotAttack: 'Дальняя атака',
      defense: 'Защита',
      craftSpeed: 'Скорость работы',
      stamina: 'Выносливость',
      foodAmount: 'Еда',
      captureRate: 'Шанс поимки',
      price: 'Золото',
    },
  },
  'th-TH': {
    title: 'สารานุกรม Pal',
    searchPlaceholder: 'ค้นหา Pal…',
    count: '{{count}} ตัว',
    loading: 'กำลังโหลด…',
    notFound: 'ไม่พบ Pal สำหรับ "{{id}}"',
    backToList: 'กลับไปที่สารานุกรม',
    viewInEncyclopedia: 'ดูในสารานุกรม →',
    viewOnMap: 'ดูบนแผนที่เต็ม',
    noSpawns: 'Pal ตัวนี้ไม่มีจุดเกิดในป่าที่ทราบ',
    lv: 'Lv',
    skill: 'สกิล',
    power: 'พลัง',
    cooldown: 'คูลดาวน์',
    rankScaling: 'การปรับตามระดับ',
    condensation: 'ปลดล็อกและเสริมพลังผ่านการควบแน่น (Lv.1–5)',
    unlockItem: 'ไอเทมปลดล็อก',
    bredFrom: 'ผสมพันธุ์จาก',
    openBreeding: 'เปิดเครื่องคำนวณการผสมพันธุ์ →',
    noBreeding: 'ไม่มีการผสมพันธุ์ใดที่ให้ Pal ตัวนี้',
    section: {
      description: 'คำอธิบาย',
      stats: 'ค่าพื้นฐาน',
      work: 'ความถนัดงาน',
      partnerSkill: 'สกิลคู่หู',
      activeSkills: 'สกิลโจมตี',
      passives: 'สกิลติดตัว',
      drops: 'ไอเทมที่ดรอป',
      spawns: 'ตำแหน่งที่เกิด',
      breeding: 'การผสมพันธุ์',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'โจมตีระยะประชิด',
      shotAttack: 'โจมตีระยะไกล',
      defense: 'ป้องกัน',
      craftSpeed: 'ความเร็วในการทำงาน',
      stamina: 'สตามินา',
      foodAmount: 'อาหาร',
      captureRate: 'อัตราการจับ',
      price: 'ทอง',
    },
  },
  'tr-TR': {
    title: 'Paldex',
    searchPlaceholder: 'Pal ara…',
    count: '{{count}} Pal',
    loading: 'Yükleniyor…',
    notFound: '"{{id}}" için Pal bulunamadı.',
    backToList: "Paldex'e dön",
    viewInEncyclopedia: "Paldex'te görüntüle →",
    viewOnMap: 'Tam haritada görüntüle',
    noSpawns: 'Bu Palın bilinen vahşi doğma noktası yok.',
    lv: 'Sv',
    skill: 'Yetenek',
    power: 'Güç',
    cooldown: 'Bekleme süresi',
    rankScaling: 'Rütbe ölçeği',
    condensation: 'Yoğunlaştırma ile açılır ve güçlenir (Sv.1–5).',
    unlockItem: 'Kilit Açma Eşyası',
    bredFrom: 'Şundan üretildi',
    openBreeding: 'Üretme hesaplayıcıyı aç →',
    noBreeding: 'Hiçbir üretme kombinasyonu bu Palı üretmez.',
    section: {
      description: 'Açıklama',
      stats: 'Temel Değerler',
      work: 'İş Uygunluğu',
      partnerSkill: 'Partner Yeteneği',
      activeSkills: 'Aktif Yetenekler',
      passives: 'Pasif Yetenekler',
      drops: 'Düşen Eşyalar',
      spawns: 'Doğma Noktaları',
      breeding: 'Üretme',
    },
    stat: {
      hp: 'CP',
      meleeAttack: 'Yakın Dövüş Saldırısı',
      shotAttack: 'Menzilli Saldırı',
      defense: 'Savunma',
      craftSpeed: 'İş Hızı',
      stamina: 'Dayanıklılık',
      foodAmount: 'Yiyecek',
      captureRate: 'Yakalama Oranı',
      price: 'Altın',
    },
  },
  'vi-VN': {
    title: 'Paldex',
    searchPlaceholder: 'Tìm Pal…',
    count: '{{count}} Pal',
    loading: 'Đang tải…',
    notFound: 'Không tìm thấy Pal cho "{{id}}".',
    backToList: 'Quay lại Paldex',
    viewInEncyclopedia: 'Xem trong Paldex →',
    viewOnMap: 'Xem trên bản đồ đầy đủ',
    noSpawns: 'Pal này không có điểm xuất hiện hoang dã nào được biết đến.',
    lv: 'Cấp',
    skill: 'Kỹ năng',
    power: 'Sức mạnh',
    cooldown: 'Thời gian hồi',
    rankScaling: 'Tỷ lệ theo bậc',
    condensation: 'Mở khóa và tăng cường qua ngưng tụ (Cấp 1–5).',
    unlockItem: 'Vật phẩm mở khóa',
    bredFrom: 'Nhân giống từ',
    openBreeding: 'Mở công cụ tính nhân giống →',
    noBreeding: 'Không có tổ hợp nhân giống nào tạo ra Pal này.',
    section: {
      description: 'Mô tả',
      stats: 'Chỉ số cơ bản',
      work: 'Độ phù hợp công việc',
      partnerSkill: 'Kỹ năng đồng hành',
      activeSkills: 'Kỹ năng chủ động',
      passives: 'Kỹ năng bị động',
      drops: 'Vật phẩm rơi',
      spawns: 'Vị trí xuất hiện',
      breeding: 'Nhân giống',
    },
    stat: {
      hp: 'HP',
      meleeAttack: 'Tấn công cận chiến',
      shotAttack: 'Tấn công tầm xa',
      defense: 'Phòng thủ',
      craftSpeed: 'Tốc độ làm việc',
      stamina: 'Thể lực',
      foodAmount: 'Thức ăn',
      captureRate: 'Tỷ lệ bắt',
      price: 'Vàng',
    },
  },
  'zh-CN': {
    title: '帕鲁图鉴',
    searchPlaceholder: '搜索帕鲁…',
    count: '{{count}} 只帕鲁',
    loading: '加载中…',
    notFound: '未找到帕鲁「{{id}}」。',
    backToList: '返回图鉴',
    viewInEncyclopedia: '在图鉴中查看 →',
    viewOnMap: '在完整地图中查看',
    noSpawns: '该帕鲁没有已知的野外刷新点。',
    lv: '等级',
    skill: '技能',
    power: '威力',
    cooldown: '冷却',
    rankScaling: '等级加成',
    condensation: '通过浓缩解锁并强化（等级 1–5）。',
    unlockItem: '解锁道具',
    bredFrom: '配种来源',
    openBreeding: '打开配种计算器 →',
    noBreeding: '没有可产出该帕鲁的配种组合。',
    section: {
      description: '描述',
      stats: '基础属性',
      work: '工作适性',
      partnerSkill: '伙伴技能',
      activeSkills: '主动技能',
      passives: '被动技能',
      drops: '掉落',
      spawns: '出现地点',
      breeding: '配种',
    },
    stat: {
      hp: '生命值',
      meleeAttack: '近战攻击',
      shotAttack: '远程攻击',
      defense: '防御',
      craftSpeed: '工作速度',
      stamina: '耐力',
      foodAmount: '食量',
      captureRate: '捕获率',
      price: '金币',
    },
  },
  'zh-TW': {
    title: '帕魯圖鑑',
    searchPlaceholder: '搜尋帕魯…',
    count: '{{count}} 隻帕魯',
    loading: '載入中…',
    notFound: '未找到帕魯「{{id}}」。',
    backToList: '返回圖鑑',
    viewInEncyclopedia: '在圖鑑中查看 →',
    viewOnMap: '在完整地圖中查看',
    noSpawns: '該帕魯沒有已知的野外刷新點。',
    lv: '等級',
    skill: '技能',
    power: '威力',
    cooldown: '冷卻',
    rankScaling: '等級加成',
    condensation: '透過濃縮解鎖並強化（等級 1–5）。',
    unlockItem: '解鎖道具',
    bredFrom: '配種來源',
    openBreeding: '開啟配種計算器 →',
    noBreeding: '沒有可產出該帕魯的配種組合。',
    section: {
      description: '描述',
      stats: '基礎屬性',
      work: '工作適性',
      partnerSkill: '夥伴技能',
      activeSkills: '主動技能',
      passives: '被動技能',
      drops: '掉落',
      spawns: '出現地點',
      breeding: '配種',
    },
    stat: {
      hp: '生命值',
      meleeAttack: '近戰攻擊',
      shotAttack: '遠程攻擊',
      defense: '防禦',
      craftSpeed: '工作速度',
      stamina: '耐力',
      foodAmount: '食量',
      captureRate: '捕獲率',
      price: '金幣',
    },
  },
}
