// GENERATED by scripts/extract-fansite.mjs — do not edit by hand.
//
// SOURCE: https://lostark-cn.pages.dev — NOT the game client.
//
// Every coefficient here is the fan site's reverse-engineering, kept only
// for systems the extracted client does not expose in a decodable form:
// the engraving and affix-line text tables.
//
// Anything the game DOES expose lives in data-lostark and wins over this.
// If a future decode finds one of these in the client, delete it from here.







export const dpsLineOptions = [
  "对敌人造成的伤害+0.55%",
  "对敌人造成的伤害+1.20%",
  "对敌人造成的伤害+2.00%",
  "额外伤害+0.70%",
  "额外伤害+1.60%",
  "额外伤害+2.60%",
  "攻击力+80",
  "攻击力+195",
  "攻击力+390",
  "武器攻击力+195",
  "武器攻击力+480",
  "武器攻击力+960",
  "其它",
  "攻击力+0.40%",
  "攻击力+0.95%",
  "攻击力+1.55%",
  "武器攻击力+0.80%",
  "武器攻击力+1.80%",
  "武器攻击力+3.00%",
  "暴击率+0.40%",
  "暴击率+0.95%",
  "暴击率+1.55%",
  "暴击伤害+1.10%",
  "暴击伤害+2.40%",
  "暴击伤害+4.00%"
];

export const supportLineOptions = [
  "烙印力+2.15%",
  "烙印力+4.80%",
  "烙印力+8.00%",
  "增加小夜曲、信仰、和谐能量获得量+1.60%",
  "增加小夜曲、信仰、和谐能量获得量+3.60%",
  "增加小夜曲、信仰、和谐能量获得量+6.00%",
  "武器攻击力+195",
  "武器攻击力+480",
  "武器攻击力+960",
  "最大生命值+1300",
  "最大生命值+3250",
  "最大生命值+6500",
  "其它",
  "武器攻击力+0.80%",
  "武器攻击力+1.80%",
  "武器攻击力+3.00%",
  "队友恢复效果+0.95%",
  "队友恢复效果+2.10%",
  "队友恢复效果+3.50%",
  "队友护盾效果+0.95%",
  "队友护盾效果+2.10%",
  "队友护盾效果+3.50%",
  "我军伤害量强化效果+2.00%",
  "我军伤害量强化效果+4.50%",
  "我军伤害量强化效果+7.50%",
  "我军攻击力强化效果+1.35%",
  "我军攻击力强化效果+3.00%",
  "我军攻击力强化效果+5.50%"
];

export const dpsLineEffects = {
  "对敌人造成的伤害+0.55%": {
    "battle": 0.0055,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "对敌人造成的伤害+1.20%": {
    "battle": 0.012,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "对敌人造成的伤害+2.00%": {
    "battle": 0.02,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+0.70%": {
    "battle": 0.00538461538461539,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+1.60%": {
    "battle": 0.0123072,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+2.60%": {
    "battle": 0.0199992,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+80": {
    "battle": 0.00056,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+195": {
    "battle": 0.001365,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+390": {
    "battle": 0.00273,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "武器攻击力+195": {
    "battle": 0,
    "weaponFlat": 195,
    "weaponPct": 0
  },
  "武器攻击力+480": {
    "battle": 0,
    "weaponFlat": 480,
    "weaponPct": 0
  },
  "武器攻击力+960": {
    "battle": 0,
    "weaponFlat": 960,
    "weaponPct": 0
  },
  "其它": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+0.40%": {
    "battle": 0.004,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+0.95%": {
    "battle": 0.0095,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+1.55%": {
    "battle": 0.0155,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "武器攻击力+0.80%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.008
  },
  "武器攻击力+1.80%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.018
  },
  "武器攻击力+3.00%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.03
  },
  "暴击率+0.40%": {
    "battle": 0.0030968,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击率+0.95%": {
    "battle": 0.0073549,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击率+1.55%": {
    "battle": 0.0120001,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+1.10%": {
    "battle": 0.0033,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+2.40%": {
    "battle": 0.0072,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+4.00%": {
    "battle": 0.012,
    "weaponFlat": 0,
    "weaponPct": 0
  }
};

export const supportLineEffects = {
  "烙印力+2.15%": {
    "support": 0.0129,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "烙印力+4.80%": {
    "support": 0.0288,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "烙印力+8.00%": {
    "support": 0.048,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+1.60%": {
    "support": 0.008,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+3.60%": {
    "support": 0.018,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+6.00%": {
    "support": 0.03,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+195": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 195,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+480": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 480,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+960": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 960,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "最大生命值+1300": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 1300
  },
  "最大生命值+3250": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 3250
  },
  "最大生命值+6500": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 6500
  },
  "其它": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+0.80%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.008,
    "maxHpFlat": 0
  },
  "武器攻击力+1.80%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.018,
    "maxHpFlat": 0
  },
  "武器攻击力+3.00%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.03,
    "maxHpFlat": 0
  },
  "队友恢复效果+0.95%": {
    "support": 0,
    "heal": 0.00665,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友恢复效果+2.10%": {
    "support": 0,
    "heal": 0.0147,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友恢复效果+3.50%": {
    "support": 0,
    "heal": 0.0245,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+0.95%": {
    "support": 0,
    "heal": 0.00665,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+2.10%": {
    "support": 0,
    "heal": 0.0147,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+3.50%": {
    "support": 0,
    "heal": 0.0245,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+2.00%": {
    "support": 0.01,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+4.50%": {
    "support": 0.0225,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+7.50%": {
    "support": 0.0375,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+1.35%": {
    "support": 0.010125,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+3.00%": {
    "support": 0.0225,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+5.50%": {
    "support": 0.0375,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  }
};

export const dpsBraceletLines = [
  {
    "id": "dps-0",
    "side": "左",
    "text": "暴击率增加3.4%。攻击触发暴击时，对敌人造成的伤害增加1.5%。",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-1",
    "side": "左",
    "text": "暴击率增加4.2%。攻击触发暴击时，对敌人造成的伤害增加1.5%。",
    "value": 0.04,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-2",
    "side": "左",
    "text": "暴击率增加5.0%。攻击触发暴击时，对敌人造成的伤害增加1.5%。",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-3",
    "side": "左",
    "text": "暴击伤害增加6.8%。攻击触发暴击时,对敌人造成的伤害增加1.5%。",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-4",
    "side": "左",
    "text": "暴击伤害增加8.4%。攻击触发暴击时,对敌人造成的伤害增加1.5%。",
    "value": 0.04,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-5",
    "side": "左",
    "text": "暴击伤害增加10%。攻击触发暴击时,对敌人造成的伤害增加1.5%。",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-6",
    "side": "左",
    "text": "额外伤害增加2.5%。恶魔与大恶魔系伤害量增加2.5%。",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-7",
    "side": "左",
    "text": "额外伤害增加3.0%。恶魔与大恶魔系伤害量增加2.5%。",
    "value": 0.04,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-8",
    "side": "左",
    "text": "额外伤害增加3.5%。恶魔与大恶魔系伤害量增加2.5%。",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-9",
    "side": "左",
    "text": "技能的冷却时间增加2%，但对敌人造成的伤害增加4.5%。",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-10",
    "side": "左",
    "text": "技能的冷却时间增加2%，但对敌人造成的伤害增加5.0%。",
    "value": 0.04,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-11",
    "side": "左",
    "text": "技能的冷却时间增加2%，但对敌人造成的伤害增加5.5%。",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-12",
    "side": "左",
    "text": "对敌人造成的伤害增加2%,对处于瘫痪状态的敌人造成的伤害增加4%。",
    "value": 0.028,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-13",
    "side": "左",
    "text": "对敌人造成的伤害增加2.5%,对处于瘫痪状态的敌人造成的伤害增加4.5%。",
    "value": 0.034,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-14",
    "side": "左",
    "text": "对敌人造成的伤害增加3%,对处于瘫痪状态的乱人造成的伤害增加5%。",
    "value": 0.04,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-15",
    "side": "左",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1160，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.0188,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-16",
    "side": "左",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1320，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.0214,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-17",
    "side": "左",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1480，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.024,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-18",
    "side": "左",
    "text": "武器攻击力增加7200。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2000。",
    "value": 0.0054,
    "heal": 0,
    "flatAttack": 7200
  },
  {
    "id": "dps-19",
    "side": "左",
    "text": "武器攻击力增加8100。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2200。",
    "value": 0.0059,
    "heal": 0,
    "flatAttack": 8100
  },
  {
    "id": "dps-20",
    "side": "左",
    "text": "武器攻击力增加9000。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2400。",
    "value": 0.0065,
    "heal": 0,
    "flatAttack": 9000
  },
  {
    "id": "dps-21",
    "side": "左",
    "text": "武器攻击力增加6900。攻击命中时，在120秒内每30秒武器攻击力增加130。（最多30叠加)",
    "value": 0.0105,
    "heal": 0,
    "flatAttack": 6900
  },
  {
    "id": "dps-22",
    "side": "左",
    "text": "武器攻击力增加7800。攻击命中时，在120秒内每30秒武器攻击力增加140。（最多30叠加)",
    "value": 0.0113,
    "heal": 0,
    "flatAttack": 7800
  },
  {
    "id": "dps-23",
    "side": "左",
    "text": "武器攻击力增加8700。攻击命中时，在120秒内每30秒武器攻击力增加150。（最多30叠加)",
    "value": 0.0121,
    "heal": 0,
    "flatAttack": 8700
  },
  {
    "id": "dps-24",
    "side": "左",
    "text": "武器攻击力+7200",
    "value": 0,
    "heal": 0,
    "flatAttack": 7200
  },
  {
    "id": "dps-25",
    "side": "左",
    "text": "武器攻击力+8100",
    "value": 0,
    "heal": 0,
    "flatAttack": 8100
  },
  {
    "id": "dps-26",
    "side": "左",
    "text": "武器攻击力+9000",
    "value": 0,
    "heal": 0,
    "flatAttack": 9000
  },
  {
    "id": "dps-27",
    "side": "右",
    "text": "对敌人造成的伤害增加2.0%。",
    "value": 0.02,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-28",
    "side": "右",
    "text": "对敌人造成的伤害增加2.5%。",
    "value": 0.025,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-29",
    "side": "右",
    "text": "对敌人造成的伤害增加3.0%。",
    "value": 0.03,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-30",
    "side": "右",
    "text": "额外伤害 +3.00%",
    "value": 0.023076,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-31",
    "side": "右",
    "text": "额外伤害 +3.50%",
    "value": 0.026922,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-32",
    "side": "右",
    "text": "额外伤害 +4.00%",
    "value": 0.030768,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-33",
    "side": "右",
    "text": "头部/背后攻击技能对敌人造成的伤害增加2.5%。",
    "value": 0.0175,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-34",
    "side": "右",
    "text": "头部/背后攻击技能对敌人造成的伤害增加3%。",
    "value": 0.021,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-35",
    "side": "右",
    "text": "头部/背后攻击技能对敌人造成的伤害增加3.5%。",
    "value": 0.0245,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-36",
    "side": "右",
    "text": "非头背型攻击技能对敌人造成的伤害增加2.5%。不适用于觉醒技能。",
    "value": 0.025,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-37",
    "side": "右",
    "text": "非头背型攻击技能对敌人造成的伤害增加3%。不适用于觉醒技能。",
    "value": 0.03,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-38",
    "side": "右",
    "text": "非头背型攻击技能对敌人造成的伤害增加3.5%。不适用于觉醒技能。",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-39",
    "side": "右",
    "text": "暴击率 +3.40%",
    "value": 0.0238,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-40",
    "side": "右",
    "text": "暴击率 +4.20%",
    "value": 0.0294,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-41",
    "side": "右",
    "text": "暴击率 +5.00%",
    "value": 0.035,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-42",
    "side": "右",
    "text": "暴击伤害 +6.80%",
    "value": 0.0226644,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-43",
    "side": "右",
    "text": "暴击伤害 +8.40%",
    "value": 0.0279972,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-44",
    "side": "右",
    "text": "暴击伤害 +10.00%",
    "value": 0.03333,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-45",
    "side": "右",
    "text": "命中时，目标暴击抗性-1.8%。我军攻击力强化效果+2%",
    "value": 0.0126,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-46",
    "side": "右",
    "text": "命中时，目标暴击抗性-2.1%。我军攻击力强化效果+2.5%",
    "value": 0.0147,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-47",
    "side": "右",
    "text": "命中时，目标暴击抗性-2.5%。我军攻击力强化效果+2.5%",
    "value": 0.0175,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-48",
    "side": "右",
    "text": "命中时，目标暴击伤害抗性减少3.6%。我军攻击力强化效果+2%",
    "value": 0.0126,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-49",
    "side": "右",
    "text": "命中时，目标暴击伤害抗性减少4.2%。我军攻击力强化效果+2.5%",
    "value": 0.0147,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-50",
    "side": "右",
    "text": "命中时，目标暴击伤害抗性减少4.8%。我军攻击力强化效果+3%",
    "value": 0.0175,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-51",
    "side": "右",
    "text": "命中时，目标防御力-1.8%。我军攻击力强化效果+2%",
    "value": 0.0126,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-52",
    "side": "右",
    "text": "命中时，目标防御力-2.1%。我军攻击力强化效果+2.5%",
    "value": 0.0147,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "dps-53",
    "side": "右",
    "text": "命中时，目标防御力-2.5%。我军攻击力强化效果+3.0%",
    "value": 0.0175,
    "heal": 0,
    "flatAttack": 0
  }
];

export const supportBraceletLines = [
  {
    "id": "support-0",
    "side": "",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1160，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.0188,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-1",
    "side": "",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1320，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.0214,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-2",
    "side": "",
    "text": "攻击命中时，10秒内每秒武器攻击力增加1480，攻击与移动速度提升1%。(最多6叠加)",
    "value": 0.024,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-3",
    "side": "",
    "text": "武器攻击力增加7200。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2000。",
    "value": 0.0054,
    "heal": 0,
    "flatAttack": 7200
  },
  {
    "id": "support-4",
    "side": "",
    "text": "武器攻击力增加8100。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2200。",
    "value": 0.0059,
    "heal": 0,
    "flatAttack": 8100
  },
  {
    "id": "support-5",
    "side": "",
    "text": "武器攻击力增加9000。自身生命值高于50%的情况下，攻击命中敌人时在5秒内武器攻击力增加2400。",
    "value": 0.0065,
    "heal": 0,
    "flatAttack": 9000
  },
  {
    "id": "support-6",
    "side": "",
    "text": "武器攻击力增加6900。攻击命中时，在120秒内每30秒武器攻击力增加130。（最多30叠加)",
    "value": 0.0105,
    "heal": 0,
    "flatAttack": 6900
  },
  {
    "id": "support-7",
    "side": "",
    "text": "武器攻击力增加7800。攻击命中时，在120秒内每30秒武器攻击力增加140。（最多30叠加)",
    "value": 0.0113,
    "heal": 0,
    "flatAttack": 7800
  },
  {
    "id": "support-8",
    "side": "",
    "text": "武器攻击力增加8700。攻击命中时，在120秒内每30秒武器攻击力增加150。（最多30叠加)",
    "value": 0.0121,
    "heal": 0,
    "flatAttack": 8700
  },
  {
    "id": "support-9",
    "side": "",
    "text": "我军攻击力强化效果+4%",
    "value": 0.03,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-10",
    "side": "",
    "text": "我军攻击力强化效果+5%",
    "value": 0.0375,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-11",
    "side": "",
    "text": "我军攻击力强化效果+6%",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-12",
    "side": "",
    "text": "我军伤害量强化效果+6%",
    "value": 0.03,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-13",
    "side": "",
    "text": "我军伤害量强化效果+7.5%",
    "value": 0.0375,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-14",
    "side": "",
    "text": "我军伤害量强化效果+9%",
    "value": 0.045,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-15",
    "side": "",
    "text": "命中时，目标防御力-1.8%。我军攻击力强化效果+2%",
    "value": 0.0906,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-16",
    "side": "",
    "text": "命中时，目标防御力-2.1%。我军攻击力强化效果+2.5%",
    "value": 0.107,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-17",
    "side": "",
    "text": "命中时，目标防御力-2.5%。我军攻击力强化效果+3.0%",
    "value": 0.1275,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-18",
    "side": "",
    "text": "命中时，目标暴击抗性-1.8%。我军攻击力强化效果+2%",
    "value": 0.0906,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-19",
    "side": "",
    "text": "命中时，目标暴击抗性-2.1%。我军攻击力强化效果+2.5%",
    "value": 0.107,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-20",
    "side": "",
    "text": "命中时，目标暴击抗性-2.5%。我军攻击力强化效果+2.5%",
    "value": 0.1275,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-21",
    "side": "",
    "text": "命中时，目标暴击伤害抗性减少3.6%。我军攻击力强化效果+2%",
    "value": 0.0906,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-22",
    "side": "",
    "text": "命中时，目标暴击伤害抗性减少4.2%。我军攻击力强化效果+2.5%",
    "value": 0.107,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-23",
    "side": "",
    "text": "命中时，目标暴击伤害抗性减少4.8%。我军攻击力强化效果+3%",
    "value": 0.1275,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-24",
    "side": "",
    "text": "获得保护型组队效果的对象在5秒内伤害提升0.9%，攻击力强化效果提升2%",
    "value": 0.0906,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-25",
    "side": "",
    "text": "获得保护型组队效果的对象在5秒内伤害提升1.1%，攻击力强化效果提升2.5%",
    "value": 0.107,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-26",
    "side": "",
    "text": "获得保护型组队效果的对象在5秒内伤害提升1.3%，攻击力强化效果提升3%",
    "value": 0.1275,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-27",
    "side": "",
    "text": "队友保护及恢复效果增加2.5%",
    "value": 0,
    "heal": 0.017,
    "flatAttack": 0
  },
  {
    "id": "support-28",
    "side": "",
    "text": "队友保护及恢复效果增加3.0%",
    "value": 0,
    "heal": 0.021,
    "flatAttack": 0
  },
  {
    "id": "support-29",
    "side": "",
    "text": "队友保护及恢复效果增加3.5%",
    "value": 0,
    "heal": 0.0245,
    "flatAttack": 0
  },
  {
    "id": "support-30",
    "side": "",
    "text": "最大生命值 +11200",
    "value": 0,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-31",
    "side": "",
    "text": "最大生命值 +14000",
    "value": 0,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-32",
    "side": "",
    "text": "最大生命值 +16800",
    "value": 0,
    "heal": 0,
    "flatAttack": 0
  },
  {
    "id": "support-33",
    "side": "",
    "text": "武器攻击力+7200",
    "value": 0,
    "heal": 0,
    "flatAttack": 7200
  },
  {
    "id": "support-34",
    "side": "",
    "text": "武器攻击力+8100",
    "value": 0,
    "heal": 0,
    "flatAttack": 8100
  },
  {
    "id": "support-35",
    "side": "",
    "text": "武器攻击力+9000",
    "value": 0,
    "heal": 0,
    "flatAttack": 9000
  }
];

/**
 * @deprecated SUPERSEDED by `avatars/options.json` — delete with the engine patch.
 *
 * The client carries these very three numbers on the avatar item itself
 * (`ItemGradeOptionStatic`, `AddonType00 = 2` on stat 7/8/9 = Str%/Agi%/Int%,
 * `AddonValue00` 50/100/200 at the 1e4 divisor). Kept for one commit only, because
 * `engine.ts` is owned elsewhere and still imports it. `scripts/extract-fansite.mjs`
 * no longer emits it.
 */

/**
 * @deprecated SUPERSEDED by `RoleCoefficients.combat_stat_rates` — delete with the
 * engine patch.
 *
 * Both rates are BattlePoint Type 26 (`battlestat`) exactly, and its per-role stat
 * split is the client's too. `base` is the one part that is NOT in the client: every
 * Type 26 row leaves `ValueC` at zero, so the game reads real trait totals and this
 * 2160 is a fan-site convenience. `scripts/extract-fansite.mjs` no longer emits it.
 */

/** Ability-stone basic-attack bonus once total stone levels reach 5. */
export const STONE_BASIC = { threshold: 5, amp: 0.015 };
