// GENERATED by scripts/extract-fansite.mjs — do not edit by hand.
//
// SOURCE: https://lostark-cn.pages.dev — NOT the game client.
//
// Every coefficient here is the fan site's reverse-engineering, kept only
// for systems the extracted client does not expose in a decodable form:
// engravings (no BattlePoint Type is keyed by AbilityEngrave ids), bracelet
// lines, avatars (no Type carries {0.005, 0.01, 0.02} at any scaling) and
// roster combat stats.
//
// Anything the game DOES expose lives in data-lostark and wins over this.
// If a future decode finds one of these in the client, delete it from here.

export const dpsEngravingBase = {
  "怨恨": 0.18,
  "肾上腺素": 0.152,
  "迅捷利刃": 0.16,
  "重量强化": 0.16,
  "尖刺重锤": 0.1439,
  "咒术人偶": 0.14,
  "强力侧击": 0.14,
  "法力爆发": 0.13,
  "破釜沉舟": 0.14,
  "护盾猛攻": 0.14,
  "精力充沛": 0.14,
  "锐利眼神": 0.075,
  "速战速决": 0.144,
  "以太充能": 0.126,
  "头击/背击": 0.153,
  "蓄力强化": 0.144,
  "精密短刀": 0.106
};

export const dpsEngravingBooks = {
  "怨恨": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "肾上腺素": [
    0,
    0.0105,
    0.021,
    0.0315,
    0.042
  ],
  "迅捷利刃": [
    0,
    0.008,
    0.016,
    0.024,
    0.032
  ],
  "重量强化": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "尖刺重锤": [
    0,
    0.0074,
    0.0149,
    0.0223,
    0.0297
  ],
  "咒术人偶": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "强力侧击": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "法力爆发": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "破釜沉舟": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "护盾猛攻": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "精力充沛": [
    0,
    0.0075,
    0.015,
    0.0225,
    0.03
  ],
  "锐利眼神": [
    0,
    0.0038,
    0.0075,
    0.0113,
    0.015
  ],
  "速战速决": [
    0,
    0.006,
    0.012,
    0.018,
    0.024
  ],
  "以太充能": [
    0,
    0.009,
    0.018,
    0.027,
    0.036
  ],
  "头击/背击": [
    0,
    0.007,
    0.014,
    0.021,
    0.028
  ],
  "蓄力强化": [
    0,
    0.006,
    0.012,
    0.018,
    0.024
  ],
  "精密短刀": [
    0,
    0.0053,
    0.0106,
    0.0159,
    0.0212
  ]
};

export const dpsEngravingStones = {
  "怨恨": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "肾上腺素": [
    0,
    0.0288,
    0.036,
    0.0498,
    0.057
  ],
  "迅捷利刃": [
    0,
    0.03,
    0.0376,
    0.0528,
    0.06
  ],
  "重量强化": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "尖刺重锤": [
    0,
    0.0279,
    0.035,
    0.0492,
    0.0559
  ],
  "咒术人偶": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "强力侧击": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "法力爆发": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "破釜沉舟": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "护盾猛攻": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "精力充沛": [
    0,
    0.03,
    0.0375,
    0.0525,
    0.06
  ],
  "锐利眼神": [
    0,
    0.012,
    0.015,
    0.021,
    0.024
  ],
  "速战速决": [
    0,
    0.024,
    0.03,
    0.042,
    0.048
  ],
  "以太充能": [
    0,
    0.03,
    0.04,
    0.054,
    0.06
  ],
  "头击/背击": [
    0,
    0.027,
    0.034,
    0.047,
    0.054
  ],
  "蓄力强化": [
    0,
    0.024,
    0.03,
    0.042,
    0.048
  ],
  "精密短刀": [
    0,
    0.021,
    0.0263,
    0.0368,
    0.042
  ]
};

export const supportEngravingBase = {
  "妙手回春": {
    "support": 0,
    "heal": 0.392
  },
  "觉醒": {
    "support": 0.27,
    "heal": 0
  },
  "法力环绕": {
    "support": 0.14,
    "heal": 0
  },
  "以太生成": {
    "support": 0.24,
    "heal": 0
  },
  "反制冲击": {
    "support": 0.024,
    "heal": 0
  },
  "其他": {
    "support": 0,
    "heal": 0
  }
};

export const supportEngravingBooks = {
  "妙手回春": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0.014,
      0.028,
      0.042,
      0.056
    ]
  },
  "觉醒": {
    "support": [
      0,
      0.0075,
      0.015,
      0.0225,
      0.03
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "法力环绕": {
    "support": [
      0,
      0.015,
      0.03,
      0.045,
      0.06
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "以太生成": {
    "support": [
      0,
      0.0096,
      0.0192,
      0.0288,
      0.0384
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "反制冲击": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "其他": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  }
};

export const supportEngravingStones = {
  "妙手回春": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0.028,
      0.035,
      0.049,
      0.056
    ]
  },
  "觉醒": {
    "support": [
      0,
      0.03,
      0.0375,
      0.0525,
      0.06
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "法力环绕": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "以太生成": {
    "support": [
      0,
      0.0288,
      0.036,
      0.0504,
      0.0576
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "反制冲击": {
    "support": [
      0,
      0.009,
      0.0113,
      0.0158,
      0.018
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  "其他": {
    "support": [
      0,
      0,
      0,
      0,
      0
    ],
    "heal": [
      0,
      0,
      0,
      0,
      0
    ]
  }
};

export const dpsLineOptions = [
  "对敌人造成的伤害+0.55%",
  "对敌人造成的伤害+1.20%",
  "对敌人造成的伤害+2.00%",
  "额外伤害+0.70%",
  "额外伤害+1.60%",
  "额外伤害+2.60%",
  "攻击力+80",
  "攻击力+195",
  "攻击力+390",
  "武器攻击力+195",
  "武器攻击力+480",
  "武器攻击力+960",
  "其它",
  "攻击力+0.40%",
  "攻击力+0.95%",
  "攻击力+1.55%",
  "武器攻击力+0.80%",
  "武器攻击力+1.80%",
  "武器攻击力+3.00%",
  "暴击率+0.40%",
  "暴击率+0.95%",
  "暴击率+1.55%",
  "暴击伤害+1.10%",
  "暴击伤害+2.40%",
  "暴击伤害+4.00%"
];

export const supportLineOptions = [
  "烙印力+2.15%",
  "烙印力+4.80%",
  "烙印力+8.00%",
  "增加小夜曲、信仰、和谐能量获得量+1.60%",
  "增加小夜曲、信仰、和谐能量获得量+3.60%",
  "增加小夜曲、信仰、和谐能量获得量+6.00%",
  "武器攻击力+195",
  "武器攻击力+480",
  "武器攻击力+960",
  "最大生命值+1300",
  "最大生命值+3250",
  "最大生命值+6500",
  "其它",
  "武器攻击力+0.80%",
  "武器攻击力+1.80%",
  "武器攻击力+3.00%",
  "队友恢复效果+0.95%",
  "队友恢复效果+2.10%",
  "队友恢复效果+3.50%",
  "队友护盾效果+0.95%",
  "队友护盾效果+2.10%",
  "队友护盾效果+3.50%",
  "我军伤害量强化效果+2.00%",
  "我军伤害量强化效果+4.50%",
  "我军伤害量强化效果+7.50%",
  "我军攻击力强化效果+1.35%",
  "我军攻击力强化效果+3.00%",
  "我军攻击力强化效果+5.50%"
];

export const dpsLineEffects = {
  "对敌人造成的伤害+0.55%": {
    "battle": 0.0055,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "对敌人造成的伤害+1.20%": {
    "battle": 0.012,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "对敌人造成的伤害+2.00%": {
    "battle": 0.02,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+0.70%": {
    "battle": 0.00538461538461539,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+1.60%": {
    "battle": 0.0123072,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "额外伤害+2.60%": {
    "battle": 0.0199992,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+80": {
    "battle": 0.00056,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+195": {
    "battle": 0.001365,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+390": {
    "battle": 0.00273,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "武器攻击力+195": {
    "battle": 0,
    "weaponFlat": 195,
    "weaponPct": 0
  },
  "武器攻击力+480": {
    "battle": 0,
    "weaponFlat": 480,
    "weaponPct": 0
  },
  "武器攻击力+960": {
    "battle": 0,
    "weaponFlat": 960,
    "weaponPct": 0
  },
  "其它": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+0.40%": {
    "battle": 0.004,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+0.95%": {
    "battle": 0.0095,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "攻击力+1.55%": {
    "battle": 0.0155,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "武器攻击力+0.80%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.008
  },
  "武器攻击力+1.80%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.018
  },
  "武器攻击力+3.00%": {
    "battle": 0,
    "weaponFlat": 0,
    "weaponPct": 0.03
  },
  "暴击率+0.40%": {
    "battle": 0.0030968,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击率+0.95%": {
    "battle": 0.0073549,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击率+1.55%": {
    "battle": 0.0120001,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+1.10%": {
    "battle": 0.0033,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+2.40%": {
    "battle": 0.0072,
    "weaponFlat": 0,
    "weaponPct": 0
  },
  "暴击伤害+4.00%": {
    "battle": 0.012,
    "weaponFlat": 0,
    "weaponPct": 0
  }
};

export const supportLineEffects = {
  "烙印力+2.15%": {
    "support": 0.0129,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "烙印力+4.80%": {
    "support": 0.0288,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "烙印力+8.00%": {
    "support": 0.048,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+1.60%": {
    "support": 0.008,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+3.60%": {
    "support": 0.018,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "增加小夜曲、信仰、和谐能量获得量+6.00%": {
    "support": 0.03,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+195": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 195,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+480": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 480,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+960": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 960,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "最大生命值+1300": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 1300
  },
  "最大生命值+3250": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 3250
  },
  "最大生命值+6500": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 6500
  },
  "其它": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "武器攻击力+0.80%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.008,
    "maxHpFlat": 0
  },
  "武器攻击力+1.80%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.018,
    "maxHpFlat": 0
  },
  "武器攻击力+3.00%": {
    "support": 0,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0.03,
    "maxHpFlat": 0
  },
  "队友恢复效果+0.95%": {
    "support": 0,
    "heal": 0.00665,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友恢复效果+2.10%": {
    "support": 0,
    "heal": 0.0147,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友恢复效果+3.50%": {
    "support": 0,
    "heal": 0.0245,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+0.95%": {
    "support": 0,
    "heal": 0.00665,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+2.10%": {
    "support": 0,
    "heal": 0.0147,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "队友护盾效果+3.50%": {
    "support": 0,
    "heal": 0.0245,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+2.00%": {
    "support": 0.01,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+4.50%": {
    "support": 0.0225,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军伤害量强化效果+7.50%": {
    "support": 0.0375,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+1.35%": {
    "support": 0.010125,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+3.00%": {
    "support": 0.0225,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  },
  "我军攻击力强化效果+5.50%": {
    "support": 0.0375,
    "heal": 0,
    "weaponFlat": 0,
    "weaponPct": 0,
    "maxHpFlat": 0
  }
};

/** Avatar (时装) tier -> amp. Fan-site avatarAmp(). */
export const avatarAmp: Record<string, number> = {
  传说: 0.02,
  英雄: 0.01,
  稀有: 0.005,
  无: 0,
};

/** Combat-stat base and per-point rates. Fan-site calcDps/calcSupport. */
export const COMBAT_STAT = {
  /** Base 战斗特性 before roster bonuses. */
  base: 2160,
  /** Damage dealers convert crit+spec+swift at this rate. */
  dpsRate: 0.0003,
  /** Supports convert spec+swift only, at this rate. */
  supportRate: 0.0004,
};

/** Ability-stone basic-attack bonus once total stone levels reach 5. */
export const STONE_BASIC = { threshold: 5, amp: 0.015 };
