import type { MarkerDetailLabels } from "./MarkerDetailDrawer"

type MarkerDetailLabelText = Omit<MarkerDetailLabels, "collapseSection" | "expandSection" | "commentCount" | "viewReplies"> & {
  collapseSection: string
  expandSection: string
  commentCount: string
  viewReplies: string
}

const en: MarkerDetailLabelText = {
  close: "Close marker details",
  position: "Position",
  copyPosition: "Copy position",
  copied: "Copied",
  copyFailed: "Copy failed",
  details: "Details",
  comments: "Comments",
  scrollArea: "Marker content, scrollable",
  collapseSection: "Collapse {{title}}",
  expandSection: "Show all {{title}}",
  description: "Marker description",
  gallery: "Player images",
  galleryDescription: "Help other players identify this location",
  uploadImage: "Add image",
  galleryReviewNote: "Images become public after community review. Up to 3 images.",
  commentCount: "{{count}} comments",
  popular: "Popular",
  latest: "Latest",
  like: "Like",
  reply: "Reply",
  viewReplies: "View {{count}} replies",
  commentPlaceholder: "Share useful information about this marker",
  attachImages: "Attach images",
  attachmentLimit: "Up to 3 images",
  publish: "Publish",
  emptyDetails: "No additional details yet. Add an image or leave a useful comment.",
  emptyComments: "No comments yet. Start the conversation.",
  guestAuthor: "Guest",
  justNow: "Just now",
  awaitingReview: "Awaiting review",
}

const texts: Record<string, MarkerDetailLabelText> = {
  "en-US": en,
  "zh-CN": {
    ...en,
    close: "关闭点位详情",
    position: "坐标",
    copyPosition: "复制坐标",
    copied: "已复制",
    copyFailed: "复制失败",
    details: "详情",
    comments: "留言",
    scrollArea: "点位内容，可滚动",
    collapseSection: "收起{{title}}",
    expandSection: "展示全部{{title}}",
    description: "点位说明",
    gallery: "玩家图片",
    galleryDescription: "帮助其他玩家确认这个位置",
    uploadImage: "添加图片",
    galleryReviewNote: "图片经社区审核后公开，最多上传 3 张。",
    commentCount: "{{count}} 条留言",
    popular: "热门",
    latest: "最新",
    like: "点赞",
    reply: "回复",
    viewReplies: "查看 {{count}} 条回复",
    commentPlaceholder: "分享这个点位的实用信息",
    attachImages: "添加图片",
    attachmentLimit: "最多 3 张",
    publish: "发布",
    emptyDetails: "暂时没有更多详情。你可以添加图片或留下实用信息。",
    emptyComments: "暂时没有留言，来发布第一条吧。",
    guestAuthor: "访客",
    justNow: "刚刚",
    awaitingReview: "等待审核",
  },
  "zh-TW": {
    ...en,
    close: "關閉點位詳情",
    position: "座標",
    copyPosition: "複製座標",
    copied: "已複製",
    copyFailed: "複製失敗",
    details: "詳情",
    comments: "留言",
    scrollArea: "點位內容，可捲動",
    collapseSection: "收起{{title}}",
    expandSection: "顯示全部{{title}}",
    description: "點位說明",
    gallery: "玩家圖片",
    galleryDescription: "幫助其他玩家確認這個位置",
    uploadImage: "加入圖片",
    galleryReviewNote: "圖片經社群審核後公開，最多上傳 3 張。",
    commentCount: "{{count}} 則留言",
    popular: "熱門",
    latest: "最新",
    like: "讚",
    reply: "回覆",
    viewReplies: "查看 {{count}} 則回覆",
    commentPlaceholder: "分享這個點位的實用資訊",
    attachImages: "加入圖片",
    attachmentLimit: "最多 3 張",
    publish: "發佈",
    emptyDetails: "暫時沒有更多詳情。你可以加入圖片或留下實用資訊。",
    emptyComments: "暫時沒有留言，來發佈第一則吧。",
    guestAuthor: "訪客",
    justNow: "剛剛",
    awaitingReview: "等待審核",
  },
  "ko-KR": {
    ...en,
    close: "마커 상세 닫기",
    position: "좌표",
    copyPosition: "좌표 복사",
    copied: "복사됨",
    copyFailed: "복사 실패",
    details: "상세",
    comments: "댓글",
    scrollArea: "스크롤 가능한 마커 내용",
    collapseSection: "{{title}} 접기",
    expandSection: "{{title}} 모두 보기",
    description: "마커 설명",
    gallery: "플레이어 이미지",
    galleryDescription: "다른 플레이어가 위치를 확인하도록 도와주세요",
    uploadImage: "이미지 추가",
    galleryReviewNote: "이미지는 커뮤니티 검토 후 공개됩니다. 최대 3장.",
    commentCount: "댓글 {{count}}개",
    popular: "인기",
    latest: "최신",
    like: "좋아요",
    reply: "답글",
    viewReplies: "답글 {{count}}개 보기",
    commentPlaceholder: "이 마커에 유용한 정보를 공유하세요",
    attachImages: "이미지 첨부",
    attachmentLimit: "최대 3장",
    publish: "게시",
  },
}

function interpolate(template: string, name: string, value: string | number): string {
  return template.replace(`{{${name}}}`, String(value))
}

export function markerDetailLabelsFor(language: string): MarkerDetailLabels {
  const text = texts[language] ?? texts[language.split("-")[0] === "zh" ? "zh-CN" : "en-US"] ?? en
  return {
    ...text,
    collapseSection: (title) => interpolate(text.collapseSection, "title", title),
    expandSection: (title) => interpolate(text.expandSection, "title", title),
    commentCount: (count) => interpolate(text.commentCount, "count", count),
    viewReplies: (count) => interpolate(text.viewReplies, "count", count),
  }
}
