"""add abyss artifact order

Revision ID: 09b4c2ed3c59
Revises: 331a7af2d297
Create Date: 2026-01-22 19:38:27.138736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b4c2ed3c59'
down_revision: Union[str, Sequence[str], None] = '331a7af2d297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abyss_artifacts', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('abyss_artifacts_map_id_fkey'), 'abyss_artifacts', type_='foreignkey')
    op.drop_column('abyss_artifacts', 'map_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abyss_artifacts', sa.Column('map_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('abyss_artifacts_map_id_fkey'), 'abyss_artifacts', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    op.drop_column('abyss_artifacts', 'order')
    # ### end Alembic commands ###
