"""add index_in_subtype

Revision ID: 0c3674211db3
Revises: 375b71105e4a
Create Date: 2025-11-30 14:23:17.434754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0c3674211db3'
down_revision: Union[str, Sequence[str], None] = '375b71105e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('index_in_subtype', sa.Integer(), nullable=True))

    op.execute("""
               WITH ranked AS (SELECT id,
                                      ROW_NUMBER() OVER (
                        PARTITION BY map_id, subtype_id
                        ORDER BY id
                    ) - 1 AS idx
                               FROM markers
                               WHERE subtype_id IS NOT NULL)
               UPDATE markers AS m
               SET index_in_subtype = r.idx FROM ranked AS r
               WHERE m.id = r.id;
               """)

    op.create_unique_constraint('uq_marker_map_subtype_index', 'markers', ['map_id', 'subtype_id', 'index_in_subtype'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_marker_map_subtype_index', 'markers', type_='unique')
    op.drop_column('markers', 'index_in_subtype')
    # ### end Alembic commands ###
