"""add abyss artifact map state

Revision ID: 10872b686a2a
Revises: f10bd85ec4ea
Create Date: 2026-01-25 21:28:19.720107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10872b686a2a'
down_revision: Union[str, Sequence[str], None] = 'f10bd85ec4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abyss_artifact_map_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_matching_id', sa.UUID(), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_matching_id'], ['server_matchings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_matching_id', name='_abyss_artifact_map_server_matching_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abyss_artifact_map_states')
    # ### end Alembic commands ###
