"""add type to map

Revision ID: 12ada5145648
Revises: d3434c43b4a5
Create Date: 2025-11-19 14:55:29.909346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ada5145648'
down_revision: Union[str, Sequence[str], None] = 'd3434c43b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('type', sa.String(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'type')
    # ### end Alembic commands ###
