"""add type in marker

Revision ID: 15e8acb1c571
Revises: 36fcaeea636d
Create Date: 2026-01-04 17:18:36.158578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e8acb1c571'
down_revision: Union[str, Sequence[str], None] = '36fcaeea636d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'type')
    # ### end Alembic commands ###
