"""add map_id to abyss_artifact_map_states

Revision ID: 17e1f705feae
Revises: c85c54c5ec93
Create Date: 2026-01-26 16:31:45.342409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e1f705feae'
down_revision: Union[str, Sequence[str], None] = 'c85c54c5ec93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add map_id as nullable first
    op.add_column('abyss_artifact_map_states', sa.Column('map_id', sa.UUID(), nullable=True))
    
    # Try to populate map_id from existing data
    # AbyssArtifactMapState.states is a JSON list of {abyss_artifact_id: UUID, state: int}
    # We can take the first abyss_artifact_id from the states list and find its map_id
    # via abyss_artifacts -> markers -> maps
    
    op.execute("""
        UPDATE abyss_artifact_map_states
        SET map_id = (
            SELECT m.map_id 
            FROM markers m
            JOIN abyss_artifacts aa ON aa.marker_id = m.id
            WHERE aa.id = (states->0->>'abyss_artifact_id')::uuid
            LIMIT 1
        )
        WHERE states IS NOT NULL AND jsonb_array_length(states::jsonb) > 0
    """)

    # For any remaining nulls (if any), or if we want to be safe, 
    # we might need a default or just delete them if they are invalid.
    # Given it's dev, let's just delete records that couldn't be mapped if any.
    op.execute("DELETE FROM abyss_artifact_map_states WHERE map_id IS NULL")

    # Now set it to NOT NULL
    op.alter_column('abyss_artifact_map_states', 'map_id', nullable=False)
    
    op.create_foreign_key(None, 'abyss_artifact_map_states', 'maps', ['map_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abyss_artifact_map_states', type_='foreignkey')
    op.drop_column('abyss_artifact_map_states', 'map_id')
    # ### end Alembic commands ###
