"""rename abyss artifact map states and add votes

Revision ID: 1ed601ea3315
Revises: 17e1f705feae
Create Date: 2026-01-27 16:50:27.162594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed601ea3315'
down_revision: Union[str, Sequence[str], None] = '17e1f705feae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abyss_artifact_states')
    op.rename_table('abyss_artifact_map_states', 'abyss_artifact_states')
    
    op.add_column('abyss_artifact_states', sa.Column('contributor_id', sa.UUID(), nullable=True))
    op.add_column('abyss_artifact_states', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    
    op.create_foreign_key(op.f('abyss_artifact_states_contributor_id_fkey'), 'abyss_artifact_states', 'users', ['contributor_id'], ['id'], ondelete='SET NULL')
    
    op.create_table('abyss_artifact_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abyss_artifact_state_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abyss_artifact_state_id'], ['abyss_artifact_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abyss_artifact_votes')
    
    op.drop_constraint(op.f('abyss_artifact_states_contributor_id_fkey'), 'abyss_artifact_states', type_='foreignkey')
    op.drop_column('abyss_artifact_states', 'is_verified')
    op.drop_column('abyss_artifact_states', 'contributor_id')
    
    op.rename_table('abyss_artifact_states', 'abyss_artifact_map_states')
    
    op.create_table('abyss_artifact_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('abyss_artifact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('server_matching_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['abyss_artifact_id'], ['abyss_artifacts.id'], name='abyss_artifact_states_abyss_artifact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_matching_id'], ['server_matchings.id'], name='abyss_artifact_states_server_matching_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='abyss_artifact_states_pkey'),
    sa.UniqueConstraint('abyss_artifact_id', 'server_matching_id', 'record_time', name='_abyss_artifact_server_matching_record_time_uc')
    )
    # ### end Alembic commands ###
