"""marker subtype index constraint

Revision ID: 210056fb77d4
Revises: 85ba443accd8
Create Date: 2025-12-05 04:40:24.702363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210056fb77d4'
down_revision: Union[str, Sequence[str], None] = '85ba443accd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_marker_map_subtype_index'), 'markers', type_='unique')
    op.create_index('idx_marker_map_subtype_index', 'markers', ['map_id', 'subtype_id', 'index_in_subtype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_marker_map_subtype_index', table_name='markers')
    op.create_unique_constraint(op.f('uq_marker_map_subtype_index'), 'markers', ['map_id', 'subtype_id', 'index_in_subtype'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
