"""Add user_id and relationship to AbyssArtifactVote

Revision ID: 31f837b47eb8
Revises: 9a4be225d192
Create Date: 2026-01-27 23:45:19.848956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f837b47eb8'
down_revision: Union[str, Sequence[str], None] = '9a4be225d192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abyss_artifact_votes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'abyss_artifact_votes', ['abyss_artifact_state_id', 'user_id'])
    op.create_foreign_key(None, 'abyss_artifact_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abyss_artifact_votes', type_='foreignkey')
    op.drop_constraint(None, 'abyss_artifact_votes', type_='unique')
    op.drop_column('abyss_artifact_votes', 'user_id')
    # ### end Alembic commands ###
