"""add abyss artifact

Revision ID: 331a7af2d297
Revises: f7524e5cf4eb
Create Date: 2026-01-22 16:55:28.455539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331a7af2d297'
down_revision: Union[str, Sequence[str], None] = 'f7524e5cf4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abyss_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('marker_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marker_id'], ['markers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marker_id')
    )
    op.create_table('abyss_artifact_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abyss_artifact_id', sa.UUID(), nullable=False),
    sa.Column('server_matching_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abyss_artifact_id'], ['abyss_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_matching_id'], ['server_matchings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abyss_artifact_id', 'server_matching_id', name='_abyss_artifact_server_matching_uc')
    )
    op.create_unique_constraint('_server_region_server_id_uc', 'servers', ['server_region', 'server_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_server_region_server_id_uc', 'servers', type_='unique')
    op.drop_table('abyss_artifact_states')
    op.drop_table('abyss_artifacts')
    # ### end Alembic commands ###
