"""add image_id in feedback

Revision ID: 35c0a8fadc42
Revises: 576f8846cfb8
Create Date: 2025-12-08 14:16:20.210105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c0a8fadc42'
down_revision: Union[str, Sequence[str], None] = '576f8846cfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker_feedbacks', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'marker_feedbacks', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker_feedbacks', type_='foreignkey')
    op.drop_column('marker_feedbacks', 'image_id')
    # ### end Alembic commands ###
