"""add timestamp in marker feedback

Revision ID: 36fcaeea636d
Revises: cf911848d34e
Create Date: 2025-12-11 19:04:27.937071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fcaeea636d'
down_revision: Union[str, Sequence[str], None] = 'cf911848d34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker_feedbacks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('marker_feedbacks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marker_feedbacks', 'updated_at')
    op.drop_column('marker_feedbacks', 'created_at')
    # ### end Alembic commands ###
