"""add icon_scale

Revision ID: 39c8d7dee620
Revises: d8c2780234ca
Create Date: 2025-11-21 19:57:25.104744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c8d7dee620'
down_revision: Union[str, Sequence[str], None] = 'd8c2780234ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtypes', sa.Column('icon_scale', sa.Double(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtypes', 'icon_scale')
    # ### end Alembic commands ###
