"""add subtype hide_tooltip

Revision ID: 45df5528af97
Revises: 39c8d7dee620
Create Date: 2025-11-21 21:19:47.505721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45df5528af97'
down_revision: Union[str, Sequence[str], None] = '39c8d7dee620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtypes', sa.Column('hide_tooltip', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtypes', 'hide_tooltip')
    # ### end Alembic commands ###
