"""add subtype_id in feedback

Revision ID: 576f8846cfb8
Revises: 790bc53091d0
Create Date: 2025-12-07 18:40:36.145436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576f8846cfb8'
down_revision: Union[str, Sequence[str], None] = '790bc53091d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker_feedbacks', sa.Column('subtype_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'marker_feedbacks', 'subtypes', ['subtype_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker_feedbacks', type_='foreignkey')
    op.drop_column('marker_feedbacks', 'subtype_id')
    # ### end Alembic commands ###
