"""update season unique constraint to include matching_number

Revision ID: 6378f1ba7e6d
Revises: e986c82c2319
Create Date: 2026-02-25 04:36:35.491631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6378f1ba7e6d'
down_revision: Union[str, Sequence[str], None] = 'e986c82c2319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_number_server_region_uc'), 'seasons', type_='unique')
    op.create_unique_constraint('_number_matching_server_region_uc', 'seasons', ['number', 'matching_number', 'server_region'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_number_matching_server_region_uc', 'seasons', type_='unique')
    op.create_unique_constraint(op.f('_number_server_region_uc'), 'seasons', ['number', 'server_region'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
