"""add abyss artifact order

Revision ID: 788c256bc4ea
Revises: 09b4c2ed3c59
Create Date: 2026-01-23 03:04:37.721718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788c256bc4ea'
down_revision: Union[str, Sequence[str], None] = '09b4c2ed3c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_abyss_artifact_server_matching_uc'), 'abyss_artifact_states', type_='unique')
    op.create_unique_constraint('_abyss_artifact_server_matching_date_uc', 'abyss_artifact_states', ['abyss_artifact_id', 'server_matching_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_abyss_artifact_server_matching_date_uc', 'abyss_artifact_states', type_='unique')
    op.create_unique_constraint(op.f('_abyss_artifact_server_matching_uc'), 'abyss_artifact_states', ['abyss_artifact_id', 'server_matching_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
