"""add map_id in feedback

Revision ID: 790bc53091d0
Revises: e8fca66f703b
Create Date: 2025-12-07 13:59:40.147041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790bc53091d0'
down_revision: Union[str, Sequence[str], None] = 'e8fca66f703b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker_feedbacks', sa.Column('map_id', sa.UUID(), nullable=False))
    op.alter_column('marker_feedbacks', 'marker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('marker_feedbacks_marker_id_fkey'), 'marker_feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'marker_feedbacks', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'marker_feedbacks', 'markers', ['marker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker_feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'marker_feedbacks', type_='foreignkey')
    op.create_foreign_key(op.f('marker_feedbacks_marker_id_fkey'), 'marker_feedbacks', 'markers', ['marker_id'], ['id'], ondelete='CASCADE')
    op.alter_column('marker_feedbacks', 'marker_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('marker_feedbacks', 'map_id')
    # ### end Alembic commands ###
