"""change season to date

Revision ID: 7adc02ad4684
Revises: 9ce7a556992b
Create Date: 2026-01-21 04:06:27.253352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adc02ad4684'
down_revision: Union[str, Sequence[str], None] = '9ce7a556992b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('server_region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'server_region')
    # ### end Alembic commands ###
