"""add marker feedback

Revision ID: 85ba443accd8
Revises: 786d3deb4834
Create Date: 2025-12-03 18:18:00.721404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ba443accd8'
down_revision: Union[str, Sequence[str], None] = '786d3deb4834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marker_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marker_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREATE', 'UPDATE', name='feedback_type'), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'REVISION', 'PENDING', name='feedback_status'), nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['markers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marker_feedbacks')
    # ### end Alembic commands ###
