"""add user marker progress

Revision ID: 97ddc17b3822
Revises: 0c3674211db3
Create Date: 2025-11-30 16:51:47.848490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ddc17b3822'
down_revision: Union[str, Sequence[str], None] = '0c3674211db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_marker_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('subtype_id', sa.UUID(), nullable=False),
    sa.Column('bitset', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtype_id'], ['subtypes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'map_id', 'subtype_id', name='uq_user_marker_progress_user_map_subtype')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_marker_progress')
    # ### end Alembic commands ###
