"""remove contributor_id from abyss_artifact_states and add abyss_artifact_contributors

Revision ID: 9a4be225d192
Revises: 1ed601ea3315
Create Date: 2026-01-27 18:02:28.600421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4be225d192'
down_revision: Union[str, Sequence[str], None] = '1ed601ea3315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abyss_artifact_contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abyss_artifact_state_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abyss_artifact_state_id'], ['abyss_artifact_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abyss_artifact_state_id', 'user_id')
    )
    op.drop_constraint(op.f('abyss_artifact_states_contributor_id_fkey'), 'abyss_artifact_states', type_='foreignkey')
    op.drop_column('abyss_artifact_states', 'contributor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abyss_artifact_states', sa.Column('contributor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('abyss_artifact_states_contributor_id_fkey'), 'abyss_artifact_states', 'users', ['contributor_id'], ['id'], ondelete='SET NULL')
    op.drop_table('abyss_artifact_contributors')
    # ### end Alembic commands ###
