"""add icon in marker

Revision ID: c00b2d06277e
Revises: 35c0a8fadc42
Create Date: 2025-12-09 12:01:18.515315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00b2d06277e'
down_revision: Union[str, Sequence[str], None] = '35c0a8fadc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'icon')
    # ### end Alembic commands ###
