"""Remove unique constraint on abyss_artifact_map_states server_matching_id

Revision ID: c85c54c5ec93
Revises: 10872b686a2a
Create Date: 2026-01-25 21:44:04.814993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85c54c5ec93'
down_revision: Union[str, Sequence[str], None] = '10872b686a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_abyss_artifact_map_server_matching_uc'), 'abyss_artifact_map_states', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('_abyss_artifact_map_server_matching_uc'), 'abyss_artifact_map_states', ['server_matching_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
