"""add deleted in marker feedback

Revision ID: cf911848d34e
Revises: c00b2d06277e
Create Date: 2025-12-10 17:00:04.740949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf911848d34e'
down_revision: Union[str, Sequence[str], None] = 'c00b2d06277e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE feedback_status ADD VALUE 'DELETED';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
