"""add region_id to marker

Revision ID: d8c2780234ca
Revises: 5aec73d7e8ac
Create Date: 2025-11-20 23:23:40.519518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c2780234ca'
down_revision: Union[str, Sequence[str], None] = '5aec73d7e8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('region_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'markers', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.drop_column('markers', 'region_id')
    # ### end Alembic commands ###
