"""add matching_number to season

Revision ID: e986c82c2319
Revises: ba1c3dba228d
Create Date: 2026-02-24 20:48:57.761645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e986c82c2319'
down_revision: Union[str, Sequence[str], None] = 'ba1c3dba228d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('matching_number', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'matching_number')
    # ### end Alembic commands ###
