"""rename date to record_time in AbyssArtifactState

Revision ID: f10bd85ec4ea
Revises: 788c256bc4ea
Create Date: 2026-01-23 16:23:06.616067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10bd85ec4ea'
down_revision: Union[str, Sequence[str], None] = '788c256bc4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abyss_artifact_states', 'date', new_column_name='record_time', type_=sa.DateTime(timezone=True), postgresql_using='date::timestamp with time zone')
    op.drop_constraint(op.f('_abyss_artifact_server_matching_date_uc'), 'abyss_artifact_states', type_='unique')
    op.create_unique_constraint('_abyss_artifact_server_matching_record_time_uc', 'abyss_artifact_states', ['abyss_artifact_id', 'server_matching_id', 'record_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abyss_artifact_states', 'record_time', new_column_name='date', type_=sa.Date(), postgresql_using='record_time::date')
    op.drop_constraint('_abyss_artifact_server_matching_record_time_uc', 'abyss_artifact_states', type_='unique')
    op.create_unique_constraint(op.f('_abyss_artifact_server_matching_date_uc'), 'abyss_artifact_states', ['abyss_artifact_id', 'server_matching_id', 'date'])
    # ### end Alembic commands ###
