"""change season unique key

Revision ID: f7524e5cf4eb
Revises: 7adc02ad4684
Create Date: 2026-01-21 04:24:20.514895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7524e5cf4eb'
down_revision: Union[str, Sequence[str], None] = '7adc02ad4684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('seasons_number_key'), 'seasons', type_='unique')
    op.create_unique_constraint('_number_server_region_uc', 'seasons', ['number', 'server_region'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_number_server_region_uc', 'seasons', type_='unique')
    op.create_unique_constraint(op.f('seasons_number_key'), 'seasons', ['number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
