"""add order field to server_matchings

Revision ID: fde12bf31351
Revises: 6378f1ba7e6d
Create Date: 2026-03-01 21:08:39.263266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde12bf31351'
down_revision: Union[str, Sequence[str], None] = '6378f1ba7e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_matchings', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_matchings', 'order')
    # ### end Alembic commands ###
