#!/usr/bin/env node
/**
 * Generate src/calc/fansite.generated.ts from the reference fan site's
 * calculator.js.
 *
 * These are the systems the extracted game client does NOT expose in a form we
 * could decode. Everything the game *does* expose comes from data-lostark
 * instead and takes precedence; this file exists only to reach parity with the
 * reference on the fan site's engraving and affix-line text tables.
 *
 * Three helpers this script used to emit are gone, because the client turned out
 * to carry all three: the avatar main-stat amp (ItemGradeOptionStatic, stat 7/8/9
 * -- {0.005, 0.01, 0.02} exactly), the combat-trait rates (BattlePoint Type 26,
 * 0.0003 and 0.0004 exactly) and the Esther weapon names (a four-table join off
 * BattlePoint Type 23's ValueB). Do not re-add them: data-lostark wins.
 *
 * Usage: node scripts/extract-fansite.mjs [path-to-calculator.js]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(process.argv[2] ?? resolve(HERE, '../../../../_lostark_ref/calculator.js'))
const OUT = resolve(HERE, '../src/calc')

const source = readFileSync(SRC, 'utf8')

const NAMES = [
  'dpsEngravingBase', 'dpsEngravingBooks', 'dpsEngravingStones',
  'supportEngravingBase', 'supportEngravingBooks', 'supportEngravingStones',
  'dpsLineOptions', 'supportLineOptions',
  'dpsLineEffects', 'supportLineEffects',
]

/** Extract the object/array literal assigned to `const NAME =`. */
function extractLiteral(name) {
  const m = new RegExp(`const\\s+${name}\\s*=\\s*`).exec(source)
  if (!m) throw new Error(`not found: ${name}`)
  let i = m.index + m[0].length
  if (source.startsWith('Object.freeze(', i)) i += 'Object.freeze('.length
  const open = source[i]
  if (open !== '{' && open !== '[') throw new Error(`${name} is not a literal`)
  const close = open === '{' ? '}' : ']'
  let depth = 0, inStr = null, out = ''
  for (; i < source.length; i++) {
    const ch = source[i]
    out += ch
    if (inStr) { if (ch === inStr && source[i - 1] !== '\\') inStr = null; continue }
    if (ch === '"' || ch === "'" || ch === '`') { inStr = ch; continue }
    if (ch === open) depth++
    else if (ch === close) { depth--; if (depth === 0) break }
  }
  if (depth !== 0) throw new Error(`unbalanced: ${name}`)
  return out
}

const parts = [
  '// GENERATED by scripts/extract-fansite.mjs — do not edit by hand.',
  '//',
  '// SOURCE: https://lostark-cn.pages.dev — NOT the game client.',
  '//',
  '// Every coefficient here is the fan site\'s reverse-engineering, kept only',
  '// for systems the extracted client does not expose in a decodable form:',
  '// the engraving and affix-line text tables.',
  '//',
  '// Anything the game DOES expose lives in data-lostark and wins over this.',
  '// If a future decode finds one of these in the client, delete it from here.',
  '',
]

for (const name of NAMES) {
  const value = new Function(`return (${extractLiteral(name)});`)()
  parts.push(`export const ${name} = ${JSON.stringify(value, null, 2)};`, '')
}

// Bracelet lines live inside the defaults object rather than a named const.
const BACKSLASH = String.fromCharCode(92)
function extractBraceletLines(role) {
  const anchor = role === 'dps' ? 'const dpsDefaults = {' : 'const supportDefaults = {'
  const start = source.indexOf(anchor)
  const key = source.indexOf('braceletLines: [', start)
  let i = source.indexOf('[', key)
  let depth = 0, inStr = null, out = ''
  for (; i < source.length; i++) {
    const ch = source[i]
    out += ch
    if (inStr) { if (ch === inStr && source[i - 1] !== BACKSLASH) inStr = null; continue }
    if (ch === '"' || ch === "'" || ch === '`') { inStr = ch; continue }
    if (ch === '[') depth++
    else if (ch === ']') { depth--; if (depth === 0) break }
  }
  return new Function(`return (${out});`)()
}

for (const role of ['dps', 'support']) {
  // The two roles store different fields: dps uses `value`, support uses
  // `support` (plus `heal` and `flatAttack`). Normalise to one shape so the
  // engine does not need to branch on it.
  const lines = extractBraceletLines(role).map((l, i) => ({
    id: `${role}-${i}`,
    side: l.side ?? '',
    text: l.text,
    value: role === 'support' ? (l.support ?? 0) : (l.value ?? 0),
    heal: l.heal ?? 0,
    flatAttack: l.flatAttack ?? 0,
  }))
  parts.push(`export const ${role}BraceletLines = ${JSON.stringify(lines, null, 2)};`, '')
}

// The one helper still not in the client. The ability-stone threshold of 5 IS
// (AbilityStoneBase.LevelStage00, uniform across all 58 stones), but the amp it
// grants is not: the option is a flat stat 150 add and no BattlePoint Type is keyed
// to that stat.
parts.push(`/** Ability-stone basic-attack bonus once total stone levels reach 5. */
export const STONE_BASIC = { threshold: 5, amp: 0.015 };
`)

mkdirSync(OUT, { recursive: true })
writeFileSync(resolve(OUT, 'fansite.generated.ts'), parts.join('\n'), 'utf8')
console.log(`wrote fansite.generated.ts (${NAMES.length} tables + 1 helper)`)
