#!/usr/bin/env node
/**
 * Generate src/calc/fansite.generated.ts from the reference fan site's
 * calculator.js.
 *
 * These are the systems the extracted game client does NOT expose in a form we
 * could decode. Everything the game *does* expose comes from data-lostark
 * instead and takes precedence; this file exists only to reach parity with the
 * reference on engravings, bracelet lines, avatars and roster stats.
 *
 * Usage: node scripts/extract-fansite.mjs [path-to-calculator.js]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(process.argv[2] ?? resolve(HERE, '../../../../_lostark_ref/calculator.js'))
const OUT = resolve(HERE, '../src/calc')

const source = readFileSync(SRC, 'utf8')

const NAMES = [
  'dpsEngravingBase', 'dpsEngravingBooks', 'dpsEngravingStones',
  'supportEngravingBase', 'supportEngravingBooks', 'supportEngravingStones',
  'dpsLineOptions', 'supportLineOptions',
  'dpsLineEffects', 'supportLineEffects',
]

/** Extract the object/array literal assigned to `const NAME =`. */
function extractLiteral(name) {
  const m = new RegExp(`const\\s+${name}\\s*=\\s*`).exec(source)
  if (!m) throw new Error(`not found: ${name}`)
  let i = m.index + m[0].length
  if (source.startsWith('Object.freeze(', i)) i += 'Object.freeze('.length
  const open = source[i]
  if (open !== '{' && open !== '[') throw new Error(`${name} is not a literal`)
  const close = open === '{' ? '}' : ']'
  let depth = 0, inStr = null, out = ''
  for (; i < source.length; i++) {
    const ch = source[i]
    out += ch
    if (inStr) { if (ch === inStr && source[i - 1] !== '\\') inStr = null; continue }
    if (ch === '"' || ch === "'" || ch === '`') { inStr = ch; continue }
    if (ch === open) depth++
    else if (ch === close) { depth--; if (depth === 0) break }
  }
  if (depth !== 0) throw new Error(`unbalanced: ${name}`)
  return out
}

const parts = [
  '// GENERATED by scripts/extract-fansite.mjs — do not edit by hand.',
  '//',
  '// SOURCE: https://lostark-cn.pages.dev — NOT the game client.',
  '//',
  '// Every coefficient here is the fan site\'s reverse-engineering, kept only',
  '// for systems the extracted client does not expose in a decodable form:',
  '// engravings (no BattlePoint Type is keyed by AbilityEngrave ids), bracelet',
  '// lines, avatars (no Type carries {0.005, 0.01, 0.02} at any scaling) and',
  '// roster combat stats.',
  '//',
  '// Anything the game DOES expose lives in data-lostark and wins over this.',
  '// If a future decode finds one of these in the client, delete it from here.',
  '',
]

for (const name of NAMES) {
  const value = new Function(`return (${extractLiteral(name)});`)()
  parts.push(`export const ${name} = ${JSON.stringify(value, null, 2)};`, '')
}

// Small helpers the fan site expresses as functions rather than tables.
parts.push(`/** Avatar (时装) tier -> amp. Fan-site avatarAmp(). */
export const avatarAmp: Record<string, number> = {
  传说: 0.02,
  英雄: 0.01,
  稀有: 0.005,
  无: 0,
};

/** Combat-stat base and per-point rates. Fan-site calcDps/calcSupport. */
export const COMBAT_STAT = {
  /** Base 战斗特性 before roster bonuses. */
  base: 2160,
  /** Damage dealers convert crit+spec+swift at this rate. */
  dpsRate: 0.0003,
  /** Supports convert spec+swift only, at this rate. */
  supportRate: 0.0004,
};

/** Ability-stone basic-attack bonus once total stone levels reach 5. */
export const STONE_BASIC = { threshold: 5, amp: 0.015 };
`)

mkdirSync(OUT, { recursive: true })
writeFileSync(resolve(OUT, 'fansite.generated.ts'), parts.join('\n'), 'utf8')
console.log(`wrote fansite.generated.ts (${NAMES.length} tables + 3 helpers)`)
