/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteRouteImport } from './routes/wiki/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as WikiTypeIndexRouteImport } from './routes/wiki/$type/index'
import { Route as WikiTypeSlugRouteImport } from './routes/wiki/$type/$slug'

const WikiRouteRoute = WikiRouteRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiTypeIndexRoute = WikiTypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiTypeSlugRoute = WikiTypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => WikiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type/': typeof WikiTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type': typeof WikiTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type/': typeof WikiTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wiki' | '/wiki/' | '/wiki/$type/$slug' | '/wiki/$type/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wiki' | '/wiki/$type/$slug' | '/wiki/$type'
  id:
    '__root__' | '/' | '/wiki' | '/wiki/' | '/wiki/$type/$slug' | '/wiki/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WikiRouteRoute: typeof WikiRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/$type/': {
      id: '/wiki/$type/'
      path: '/$type'
      fullPath: '/wiki/$type/'
      preLoaderRoute: typeof WikiTypeIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/$type/$slug': {
      id: '/wiki/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/wiki/$type/$slug'
      preLoaderRoute: typeof WikiTypeSlugRouteImport
      parentRoute: typeof WikiRouteRoute
    }
  }
}

interface WikiRouteRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
  WikiTypeSlugRoute: typeof WikiTypeSlugRoute
  WikiTypeIndexRoute: typeof WikiTypeIndexRoute
}

const WikiRouteRouteChildren: WikiRouteRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
  WikiTypeSlugRoute: WikiTypeSlugRoute,
  WikiTypeIndexRoute: WikiTypeIndexRoute,
}

const WikiRouteRouteWithChildren = WikiRouteRoute._addFileChildren(
  WikiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WikiRouteRoute: WikiRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
