/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as WikiRouteRouteImport } from './routes/wiki/route'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as WikiTraintradeRouteImport } from './routes/wiki/traintrade'
import { Route as WikiUtopianTheaterRouteImport } from './routes/wiki/utopian-theater'
import { Route as WikiTypeIndexRouteImport } from './routes/wiki/$type/index'
import { Route as WikiTypeSlugRouteImport } from './routes/wiki/$type/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRouteRoute = WikiRouteRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiTraintradeRoute = WikiTraintradeRouteImport.update({
  id: '/traintrade',
  path: '/traintrade',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiUtopianTheaterRoute = WikiUtopianTheaterRouteImport.update({
  id: '/utopian-theater',
  path: '/utopian-theater',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiTypeIndexRoute = WikiTypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const WikiTypeSlugRoute = WikiTypeSlugRouteImport.update({
  id: '/$type/$slug',
  path: '/$type/$slug',
  getParentRoute: () => WikiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/wiki/traintrade': typeof WikiTraintradeRoute
  '/wiki/utopian-theater': typeof WikiUtopianTheaterRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type/': typeof WikiTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/wiki/traintrade': typeof WikiTraintradeRoute
  '/wiki/utopian-theater': typeof WikiUtopianTheaterRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type': typeof WikiTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/wiki/traintrade': typeof WikiTraintradeRoute
  '/wiki/utopian-theater': typeof WikiUtopianTheaterRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$type/$slug': typeof WikiTypeSlugRoute
  '/wiki/$type/': typeof WikiTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wiki'
    | '/changelog'
    | '/wiki/traintrade'
    | '/wiki/utopian-theater'
    | '/wiki/'
    | '/wiki/$type/$slug'
    | '/wiki/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/wiki/traintrade'
    | '/wiki/utopian-theater'
    | '/wiki'
    | '/wiki/$type/$slug'
    | '/wiki/$type'
  id:
    | '__root__'
    | '/'
    | '/wiki'
    | '/changelog'
    | '/wiki/traintrade'
    | '/wiki/utopian-theater'
    | '/wiki/'
    | '/wiki/$type/$slug'
    | '/wiki/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WikiRouteRoute: typeof WikiRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/traintrade': {
      id: '/wiki/traintrade'
      path: '/traintrade'
      fullPath: '/wiki/traintrade'
      preLoaderRoute: typeof WikiTraintradeRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/utopian-theater': {
      id: '/wiki/utopian-theater'
      path: '/utopian-theater'
      fullPath: '/wiki/utopian-theater'
      preLoaderRoute: typeof WikiUtopianTheaterRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/$type/': {
      id: '/wiki/$type/'
      path: '/$type'
      fullPath: '/wiki/$type/'
      preLoaderRoute: typeof WikiTypeIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/wiki/$type/$slug': {
      id: '/wiki/$type/$slug'
      path: '/$type/$slug'
      fullPath: '/wiki/$type/$slug'
      preLoaderRoute: typeof WikiTypeSlugRouteImport
      parentRoute: typeof WikiRouteRoute
    }
  }
}

interface WikiRouteRouteChildren {
  WikiTraintradeRoute: typeof WikiTraintradeRoute
  WikiUtopianTheaterRoute: typeof WikiUtopianTheaterRoute
  WikiIndexRoute: typeof WikiIndexRoute
  WikiTypeSlugRoute: typeof WikiTypeSlugRoute
  WikiTypeIndexRoute: typeof WikiTypeIndexRoute
}

const WikiRouteRouteChildren: WikiRouteRouteChildren = {
  WikiTraintradeRoute: WikiTraintradeRoute,
  WikiUtopianTheaterRoute: WikiUtopianTheaterRoute,
  WikiIndexRoute: WikiIndexRoute,
  WikiTypeSlugRoute: WikiTypeSlugRoute,
  WikiTypeIndexRoute: WikiTypeIndexRoute,
}

const WikiRouteRouteWithChildren = WikiRouteRoute._addFileChildren(
  WikiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WikiRouteRoute: WikiRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
